### ISSUE TITLE
Mangopay terms pdfs fail

### ISSUE THREAD

**Issue by cweiske** [liberapay/liberapay.com#1009]
The PDFs for DE and EN linked on https://liberapay.com/about/legal#mangopay-terms are empty:

- <https://liberapay.com/assets/mangopay/Mangopay_Terms-EN.pdf?etag=.Em2Q-LF68iIlY23Lk8hFSA~~>
- <https://liberapay.com/assets/mangopay/Mangopay_Terms-DE.pdf?etag=.00zzI57qDD_8kH1XfMxieg~~>

**Comment by Changaco** [comment]
No, they're not empty.

![screenshot_20180313_094626](https://user-images.githubusercontent.com/1581590/37331148-66ed1bc8-26a3-11e8-8131-345b6f006862.png)
