### ISSUE TITLE
Tor and rate limiting

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#1015]
For rate limiting purposes we should treat Tor exit nodes as a single origin network. Context: <https://github.com/liberapay/salon/issues/192#issuecomment-373928421>.

If I remember correctly Cloudflare tags requests coming from Tor with a specific "country" code, so we should be able to use that.

**Comment by EdOverflow** [comment]
> If I remember correctly Cloudflare tags requests coming from Tor with a specific "country" code, so we should be able to use that.

Yep, that is the case.

> Since late February 2016, Cloudflare treats Tor exit nodes as a "country" of their own. There's no geography associated with these IPs, but this approach lets Cloudflare customers override the default Cloudflare threat score to define the experience for their Tor visitors. [[1]](https://support.cloudflare.com/hc/en-us/articles/203306930-Does-Cloudflare-block-Tor-)
