### ISSUE TITLE
Control clicking project name opens link in current and new tab

### ISSUE THREAD

**Issue by gaul** [liberapay/liberapay.com#1018]
When control clicking a project name on https://liberapay.com/explore/teams I expect the browser to open the link in only a new tab, yet it opens in both a new tab and the current tab.  When I right click and select open in new tab, the browser only opens a new tab.  Tested on Firefox 61 nightly.

**Comment by jorgesumle** [comment]
Using Tor Browser 7.5.2 (based on Mozilla Firefox 52.7.2), I don't have this issue. Anyway, there is nothing weird about the links, I can say from looking at the code. Any particular project that causes that problem?

**Comment by Changaco** [comment]
The culprit is this simplistic piece of code: https://github.com/liberapay/liberapay.com/blob/276/js/10-base.js#L42-L44

**Comment by hpr** [comment]
I submitted a PR for this: https://github.com/liberapay/liberapay.com/pull/1041

**Comment by jorgesumle** [comment]
I realize that I didn't have this issue because I browse with JavaScript disabled. Thanks a lot for the fix @hpr
