### ISSUE TITLE
Major American bank detects Liberapay.com as fradulent

### ISSUE THREAD

**Issue by braderhart** [liberapay/liberapay.com#1022]
This is now second time I have to call my bank to add money to my Liberapay wallet, as my bank keeps detecting you as fraud. I realize that isn't the case, but it makes me uneasy to use your service if I have to call my bank everytime. Why do they keep detecting you as fraud and what steps are you taking to help prevent these types of issues?

**Comment by trebmuh** [comment]
@braderhart : when on the phone with your bank, did you asked them why do **they do** detect liberapay as fraudulent?

**Comment by Changaco** [comment]
> Why do they keep detecting you as fraud

I don't know. In fact they're probably the only ones who know that.

> what steps are you taking to help prevent these types of issues?

The only thing we can do at this point is implement #994, which should help increase the success rate of card payments from the US, UK, and Australia.

**Comment by braderhart** [comment]
@Changaco Any progress on this? My bank is flagging me every week with your payment system. I can't keep calling in every week. Until this is fixed I will be unable to recommend or use your service.

**Comment by revi** [comment]
>>Why do they keep detecting you as fraud
>
>I don't know. In fact they're probably the only ones who know that.

What does your bank say about Liberapay?

**Comment by braderhart** [comment]
@revi That the payment vendor raises an alert in their system as a high risk, and that is all the information they can provide.

**Comment by Changaco** [comment]
@braderhart Can you try a new payment with freshly-input card details? If the payment works it would mean that the problem is the missing CVV when using a saved card number.

**Comment by braderhart** [comment]
@Changaco My payments are getting flagged for high risk activity, not for wrong CVV. Whenever I call my bank then they have to authorize the charge before I can try again, and then a week later I have to do the same thing. I realize this is also a problem with the banks, however I am signed up for "Verified by Visa" and I believe your suggestion to implement #994 will likely fix the issue (or should help improve the scoring system).

**Comment by Changaco** [comment]
Okay, thanks for the additional details. I've started working on #994.

**Comment by Changaco** [comment]
@braderhart It's now possible to add a billing address when paying by card, please [try it](https://liberapay.com/braderhart/wallet/payin/card/?currency=USD) and let me know if it works.

**Comment by Changaco** [comment]
@braderhart No luck, eh?

**Comment by braderhart** [comment]
No, not the first time. I will trying logging out and see if it helps. It briefly mentions Verified by Visa, which I think is their additional authorization platform. Please check the following and let me know if you have it enabled?

https://docs.mangopay.com/guide/3d-secure

**Comment by Changaco** [comment]
We do support 3DS. In fact mangopay doesn't allow disabling it and uses it automatically for any payment worth more than 50 euros.

**Comment by braderhart** [comment]
It still isn't working. I will call my bank again this time. Thanks for your help and efforts.

**Comment by braderhart** [comment]
I've let my bank know multiple times now that I want them to accept this vendor, but they keep blocking them. Maybe I really just need to find a new financial institution.

**Comment by Changaco** [comment]
Maybe, but we still need to find a solution that doesn't involve doing that, because most donors won't.

It's possible that the following change which mangopay is reportedly working on will solve the problem:

> ### Activate automatic retry with a second acquirer
>
> For many reasons, some transactions can be accepted by acquirer banks and refused by others. In order to improve your success rate on payins, we will automatically retry the transactions with a second acquirer. 

Source: https://trello.com/b/y3UFMThq/mangopay-public-roadmap

**Comment by Changaco** [comment]
We now process payments through Stripe or PayPal instead of Mangopay, so this issue should be solved.
