### ISSUE TITLE
Theme the site

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#103]
The site looks too generic right now, it needs a visual identity, even if it's only a simple one.

**Comment by Changaco** [comment]
A blocker here is that I haven't been able to decide on a color palette. Any ideas?

**Comment by Calinou** [comment]
I have opened a broader issue about this: #183 with more detailed information.

**Comment by Changaco** [comment]
Closing in favor of #183. I would have preferred keeping this issue though, I think #183 is too broad.
