### ISSUE TITLE
404 error with slash at the end of donate url

### ISSUE THREAD

**Issue by TobiGr** [liberapay/liberapay.com#1031]
First of all, thanks for your awesome service!

When I visit https://liberapay.com/TeamNewPipe/donate I get to the donate page. But when I add a `/` at the end of the URL, the link causes a 404 error:
https://liberapay.com/TeamNewPipe/donate/
I can only reproduce this with the `donate/` pages.

**Comment by Changaco** [comment]
Hmm, I think I see the cause. A quick fix would be to move `www/%username/%action.spt` ([this file](https://github.com/liberapay/liberapay.com/blob/277/www/%25username/%25action.spt)) to a subdirectory, e.g. `www/%username/letters/%action.spt`.

**Comment by ibjib** [comment]
> I can only reproduce this with the donate/ pages.

I'm able to reproduce with `tip/` . It seems like this is a bug with Panda or the configuration of the engine, or maybe a routing regex. I'm looking it up now, but maybe someone can save me some time: Does someone know where the routing regex is?
