### ISSUE TITLE
Link to Liberapay in Romanian is broken

### ISSUE THREAD

**Issue by dasj19** [liberapay/liberapay.com#1038]
Hello, the subdomain https://ro.liberapay.com/ is not available yet. But it is linked to it from the language chooser next to the profile button.

**Comment by jorgesumle** [comment]
It works locally in commit 3623f813134bd1d72ecbb1630697dd150daaf882

Maybe it's a deployment issue.

![bildschirmfoto vom 2018-03-30 23-53-35](https://user-images.githubusercontent.com/14212780/38155031-a9ab2fd8-3475-11e8-9ca4-95a121a5fd14.png)

**Comment by jorgesumle** [comment]
It's working now
