### ISSUE TITLE
Print button does not work

### ISSUE THREAD

**Issue by dasj19** [liberapay/liberapay.com#1039]
The print button show on top of a receipt does not work.
In the JavaScript console it fails with the following message:

TypeError: 'print' called on an object that does not implement interface Window.

**Comment by Changaco** [comment]
Which browser gave you that error?

**Comment by dasj19** [comment]
I tested first on Firefox 52.7.2 (the ESR version)
But I now confirm that Chromium 65 gives a similar error:

Uncaught TypeError: Illegal invocation 4321:1
