### ISSUE TITLE
Libravatar is shutting down

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#1044]
[Libravatar.org is shutting down on 2018-09-01](https://blog.libravatar.org/posts/Libravatar.org_is_shutting_down_on_2018-09-01/)

[Looking back on starting Libravatar](https://feeding.cloud.geek.nz/posts/looking-back-on-starting-libravatar/)

**Comment by rugk** [comment]
Can't you also just provide a simple upload service, so it does not have to be loaded from third-party sites. E.g. Twitter is regularly blocked in browsers there, because they just track users.

**Comment by tibbi** [comment]
yeah, uploading a simple image should definitely be an option. I just cannot currently set an avatar for my project...

**Comment by Changaco** [comment]
Closing since Libravatar is no longer shutting down. #1278 is the new issue for direct avatar upload.
