### ISSUE TITLE
Change the default avatar image

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#105]
@Zatalyz pointed out in IRC yesterday that we're still using Gratipay's logo, I'm so used to it I hadn't even noticed. :D

**Comment by Changaco** [comment]
By the way, our new default avatar:
![default-avatar.png](https://github.com/liberapay/liberapay.com/blob/7ce5bed776adbc6cd84598fb063e11f6c8e26351/www/assets/avatar-default.png?raw=true)

**Comment by Zatalyz** [comment]
Very elegant :D

**Comment by Changaco** [comment]
It came out nice, didn't it? I started with the simple idea of using a question mark, but it looked a little weird, then I thought "what if I flip it?", and voilà! :-)
