### ISSUE TITLE
Calculation of number of weeks funded by added money seems wrong

### ISSUE THREAD

**Issue by jibe-b** [liberapay/liberapay.com#1065]
When adding money ![image](https://user-images.githubusercontent.com/6146483/38662377-60465098-3e34-11e8-9d27-ebc65a1124b2.png)

The values calculated by the formula `amount_added/donation_per_week` seem wrong:
![image](https://user-images.githubusercontent.com/6146483/38662270-0cc83288-3e34-11e8-8d54-c241616ba88f.png)

when my `donation_per_week` amount is 
![image](https://user-images.githubusercontent.com/6146483/38662279-1675b7ec-3e34-11e8-839c-4822b183e144.png)

**Comment by Changaco** [comment]
It looks like both donations and pledges are counted in this formula.
