### ISSUE TITLE
comma handling by payment system: French vs English notation

### ISSUE THREAD

**Issue by jibe-b** [liberapay/liberapay.com#1066]
The French notation of decimals uses comma while the global notation uses dots.

At the time of adding money, this may lead to issues (and big payments!)

I wrote

![image](https://user-images.githubusercontent.com/6146483/38663250-9d549830-3e36-11e8-8237-45a3b69bbb86.png)

meaning 40.23

and indeed, it was interepreted as 10<sup>3</sup> higher

![image](https://user-images.githubusercontent.com/6146483/38663163-5fda69f8-3e36-11e8-8895-8a6754062604.png)

**Comment by Changaco** [comment]
The screenshots show that you're browsing Liberapay in English, so you have to use the English number format. If you switch to French then inputting `40,23` should work as expected.

**Comment by jibe-b** [comment]
That seems to be a regular behaviour.

But as some users do not fit into the regular schema, maybe should be add a warning?

Or parse the value and when it is not of the form `x,xxx` but `x,xx` or `x,x` ask if the user really meant `x,00x`.

 Like: when I type "40,23" a warning indicating: "did you mean `4,023`"?

**Comment by Changaco** [comment]
A German user appears to have been affected by this issue, the amount of a direct debit was interpreted as €1500 instead of €15.

**Comment by Changaco** [comment]
It would be possible to modify the `parse_decimal_or_400` function to raise a new `AmbiguousAmount` exception. It could either show a simple error message or use the `html_template` and `form-repost` mechanisms to allow the user to confirm or correct the number directly.

**Comment by Changaco** [comment]
I've opened an issue upstream: <https://github.com/python-babel/babel/issues/589>.

**Comment by Changaco** [comment]
A fix has been merged upstream: <https://github.com/python-babel/babel/pull/590>.
