### ISSUE TITLE
Adding money: "Best for small payements" -> "payments <100€"

### ISSUE THREAD

**Issue by jibe-b** [liberapay/liberapay.com#1067]
If I make no mistake, 

Direct Debit is has lower fees than Bank Wire below 100€ (0,59€ vs 0,59%). So maybe instead of "small amounts"

![image](https://user-images.githubusercontent.com/6146483/38663949-941d5f3e-3e38-11e8-977e-466dbf2036ba.png)

indicate "payments below 100€"?

**Comment by Changaco** [comment]
Closing as obsolete since we no longer support donating by bank transfer.
