### ISSUE TITLE
Pending payins aren't visible on the Wallet page

### ISSUE THREAD

**Issue by jibe-b** [liberapay/liberapay.com#1068]
One can manage a "money addition attempt" right after having made it:

![image](https://user-images.githubusercontent.com/6146483/38664633-72fe4122-3e3a-11e8-9b39-d1ec608571e0.png)

but when the page is lost, the "money addition attempt" cannot be managed (basically cancelled).

Maybe could they be recorded in the wallet to allow to cancel them later?

**Comment by Changaco** [comment]
Pending payins are shown in <https://liberapay.com/about/me/wallet/payin>, but you're correct that we should also display them at the top of the Wallet page.

**Comment by jibe-b** [comment]
I didn't know.

Maybe should we add the date the "pending bank wire" was made?

**Comment by jibe-b** [comment]
What happens if the "pending bank wire" is cancelled and the payment is done?

**Comment by Changaco** [comment]
Cancelling a bank wire only disables the failure notification, the money can still be received.

**Comment by jibe-b** [comment]
Well done!

**Comment by Changaco** [comment]
Closing as irrelevant since bank wires are no longer supported and the Wallet page is going away.
