### ISSUE TITLE
[HACKcessibility] make the language coverage clickable and point to a translation platform

### ISSUE THREAD

**Issue by jibe-b** [liberapay/liberapay.com#1070]
Displaying the translation coverage is really nice and incitative.

Making the percentage clickable and pointing to the place where translation can be improved may ease the path to contribution.

Todo list:
- [x] check where translation occurs: https://hosted.weblate.org/engage/liberapay/?utm_source=liberapay-navbar
- [x] find the dom elements of the language menu: https://github.com/liberapay/liberapay.com/blob/master/templates/navbar-common.html#L15
- [x] add a link

**Comment by jibe-b** [comment]
Indeed, the link at the bottom of the menu is already very good.

![image](https://user-images.githubusercontent.com/6146483/38759094-6a6cda10-3f74-11e8-813b-4c6acb41544b.png)

**Comment by jorgesumle** [comment]
It's a cool idea, but I believe most people just want to pick a language. Your idea could make end-users redirect to Weblate by mistake.

**Comment by jibe-b** [comment]
@jorgesumle You're right. How about having the percentage and hence the link in a smaller font (say 75% of the regular size) and aligned to the right?

**Comment by jibe-b** [comment]
I let it here, maybe can it be helpful. (and I go advertise the indication of the translation coverage to another project who will like the idea ;) )

**Comment by jorgesumle** [comment]
You gave me an idea. Maybe we can remove the 100% from the completed translations? Or show the percentage in a smaller size, I think would allow reading the language more easily (now, when you move look down you see a percentage, that's not a good user experience). Maybe you can redesign the dropdown to make it nicer.

There is an open work-in-progress [pull request about the design](https://github.com/liberapay/liberapay.com/pull/935).

**Comment by jorgesumle** [comment]
> "89% -> help translate!"

That's more characters. "89% complete" is OK for me. I still think that linking to Weblate in each language option is a bad idea that will confuse some people; the "Help us translate Liberapay" is already quite effective. I'm only for a change in the design.
