### ISSUE TITLE
AWS

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#1075]
Our estimated AWS bill for April is $53.91, almost entirely composed of EC2 (webapp) and RDS (database) costs. We can decrease the bill by ~35% next month if we pay upfront to reserve one year of what we currently use, however if we need to change anything or migrate off AWS in the next 8 months then we'll have lost money by paying upfront.

If you have any thoughts on what we could/should do feel free to share them here.

(The alternatives to AWS are still the same as a year ago, see <https://github.com/liberapay/liberapay.com/issues/177#issuecomment-285297316>.)

**Comment by jorgesumle** [comment]
Don't have a good answer now, but I prefer setting up our own infrastructure. However, it will be more complicated and I currently don't have the time to help with that. If we haven't had any problem with AWS yet and nobody offers a better solution, just stick with it.

**Comment by comradekingu** [comment]
I dislike AWS. Smaller and more "libre" providers are a bit more expensive, but I would chip in to see a change away from AWS to that effect.

**Comment by Changaco** [comment]
Everyone dislikes AWS, yet nobody seems to have a realistic alternative to propose.

**Comment by jorgesumle** [comment]
> Everyone dislikes AWS, yet nobody seems to have a realistic alternative to propose.

Yes, so the best option is to keep using it until someone comes up with a replacement. Just saying we prefer small libre providers isn't enough, we must offer a proposal. I clarify it in case my opinion was misunderstood.

**Comment by lutzhorn** [comment]
Unless some numbers about the necessary resources (CPU, memory, HD) and software are presented, it is hard to suggest an alternative.

**Comment by comradekingu** [comment]
@Changaco https://greenhost.net/ is rolling out a system that looks to be the best of both worlds.

**Comment by Siesh1oo** [comment]
Have a look on https://www.hetzner.de (depending on load/storage dedicated or cloud might be more efficient, both seem much better bang-for-buck than aws), and maybe directly contact https://www.vikings.net

**Comment by tuxayo** [comment]
> Everyone dislikes AWS, yet nobody seems to have a realistic alternative to propose.

When there will be enough donations, would a switch be possible?

What should be the new goal on https://eo.liberapay.com/LiberapayOrg/ ?

**Comment by Changaco** [comment]
Traditional hosting providers aren't equivalent to AWS, they only provide machines with an OS preinstalled, whereas AWS is an entire ecosystem of services that make it easier to build a real web app, including databases (RDS), file storage (S3) and email delivery (SES). Running a web app outside of a cloud ecosystem like AWS means installing and maintaining auxiliary services yourself, which can cost a lot of time. Some traditional hosting providers have realized this and are starting to offer their own sets of services based on [OpenStack](https://en.wikipedia.org/wiki/OpenStack), but they're a long way from being on par with AWS.

**Comment by Changaco** [comment]
Note: there are AWS competitors that I didn't know about when I first migrated Liberapay, for example [IBM Cloud](https://www.ibm.com/cloud/) and [Alibaba Cloud](https://en.wikipedia.org/wiki/Alibaba_Cloud), however I'm not sure they have significant advantages.

**Comment by Changaco** [comment]
Our monthly AWS bill is usually below or around €50, but the one for last month jumped to €72.19 ($79.11), mostly because of data transfer charges, for 355GB!

![Screenshot of AWS bandwidth billing for March 2020](https://user-images.githubusercontent.com/1581590/78645278-93aa9600-78b7-11ea-85f2-a58d92978bed.png)

![Screenshot of the Cloudflare bandwidth graph for liberapay.com from March 8 to today: 64.68 GB uncached bandwidth](https://user-images.githubusercontent.com/1581590/78643128-0ca7ee80-78b4-11ea-836d-4684432f5ae6.png)

**Comment by Changaco** [comment]
I've opened a new issue: #1727.
