### ISSUE TITLE
Clarify website about debit cards vs credit cards

### ISSUE THREAD

**Issue by arunisaac** [liberapay/liberapay.com#1076]
I was able to add money to my Liberapay wallet using a MasterCard debit card. However, the liberapay website only mentions credit cards as an accepted mode of payment. I almost made an expensive bank wire transfer because I don't have a credit card and thought only credit cards are accepted. Perhaps, the website should be clearer about this.

**Comment by Changaco** [comment]
As far as I know the only difference between the two card types is that the core payment processing fee is a little higher for credit cards than for debit cards. At our level the two types are indistinguishable and the fee is the same.

**Comment by trebmuh** [comment]
@arunisaac : which page did you refer when you write:
> he liberapay website only mentions credit cards as an accepted mode of payment
?

**Comment by arunisaac** [comment]
I was referring to the /%username/wallet/payin page. I believe it corresponds to this source file: https://github.com/liberapay/liberapay.com/blob/1db0e6c08607e2b9bd7f0f2b114ef93ef264d00f/www/%25username/wallet/payin/%25back_to.spt

**Comment by trebmuh** [comment]
@Changaco see #1078

**Comment by Changaco** [comment]
@arunisaac Would you prefer "Credit/Debit Card", or just "Card"?

**Comment by bearbin** [comment]
I think there exist debit cards that don't use the same processing system as credit cards (maybe in Germany?) so probably just "Card" is better.

**Comment by trebmuh** [comment]
Change updated to just "Card". Fine to change it again to get the best consensus. Waiting for @arunisaac 's comment.

**Comment by Changaco** [comment]
The risk with just "Card" is translator confusion and possibly translation mistakes, although in the context of Liberapay I'm not sure there are other kinds of cards we could be referring to.

**Comment by trebmuh** [comment]
> although in the context of Liberapay I'm not sure there are other kinds of cards we could be referring to.

I think so too.

**Comment by arunisaac** [comment]
I prefer "Credit/Debit Card". Just "Card" is a little too vague.

**Comment by Changaco** [comment]
Settled on "Credit/Debit Card" because "Card" could also refer to an ID card.

**Comment by trebmuh** [comment]
Fair enough.
