### ISSUE TITLE
License discussion

### ISSUE THREAD

**Issue by lusy** [liberapay/liberapay.com#1088]
Hey, maybe this decision has a long discussion behind it and it was a very conscious choice (in this case just ignore the issue), however, as far as I'm concerned, it's not recommended to use CC licenses for code. 
Creative Commons are written with creative media (pictures, videos, texts,... ) in mind. This website gives an overview over software licenses and the rights they grant:[https://choosealicense.com/licenses/]( https://choosealicense.com/licenses/)
Maybe you're looking for something like the Unlicense?
Cheers

**Comment by bearbin** [comment]
Please see #564.

CC0 is an acceptable license for code.

**Comment by lusy** [comment]
Ah, sorry, I could've searched through old issues before opening this^^
