### ISSUE TITLE
Goal page is not accessible once connected

### ISSUE THREAD

**Issue by SimonSarazin** [liberapay/liberapay.com#109]
"405 Method Not Allowed"
on this page 
https://liberapay.com/unisson/goal.html when i want to change my goal
I'm connected on my account.

**Comment by Changaco** [comment]
I'm confused as to how you ended up in this situation @SimonSarazin, changing a team's goal works fine.

**Comment by Changaco** [comment]
I've made a change that may prevent this, reopen if it ever happens again.

**Comment by Changaco** [comment]
Looks like I misunderstood the problem, @Zatalyz is reporting the same issue.

**Comment by Zatalyz** [comment]
The same, but with 403 error. I can't modify goal.

**Comment by Changaco** [comment]
Okay, I've found the problem, and why I wasn't able to see it, so now I can really fix it.

**Comment by Changaco** [comment]
@SimonSarazin @Zatalyz Fix deployed, you should be able to set goals for your teams now.
