### ISSUE TITLE
Cloudflare can be bypassed too easily

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#1093]
A solution to this is to use [Cloudflare's Argo Tunnel](https://www.cloudflare.com/products/argo-tunnel/) instead of directly listening for HTTP traffic from the Internet, however ~~it costs $5/month + $0.10 per GB (after the first GB), and~~ it would be a problem if we ever have to stop using Cloudflare.

**Comment by Changaco** [comment]
ping @EdOverflow

**Comment by EdOverflow** [comment]
Yep, it is currently fairly trivial to find the origin IPs.

```
5.135.***.***
52.17.***.**
52.212.***.**
```

**Comment by Changaco** [comment]
[A Boring Announcement: Free Tunnels for Everyone](https://blog.cloudflare.com/tunnel-for-everyone/)
