### ISSUE TITLE
Canceling authorization prevents future registration

### ISSUE THREAD

**Issue by droidmonkey** [liberapay/liberapay.com#1098]
When registering a team the GitHub authorization process kicks in. In my organization (keepassxreboot) we do not allow apps to auto-register so they must be explicitly authorized. I was not ready to make that commitment and canceled the authorization process. However, now the KeePassXC team is in a half-registered state and I cannot link it with my actual account anymore (https://liberapay.com/keepassxc/).

1. Request the KeePassXC team be reset

2. This bug needs to be fixed or some alternate way to claim a team.

**Comment by Changaco** [comment]
I don't understand the problem. As of now the GitHub organization "keepassxreboot" is connected to the "keepassxc" Liberapay account, which seems to be what you wanted.

**Comment by droidmonkey** [comment]
I realized that the authorization emails for the account all went to the spam folder. Good to go on registration.

However, how do i add team members? The UI is not very easy to work around.

**Comment by mattbk** [comment]
Is there an explanation of what the point of organizations is?

**Comment by Changaco** [comment]
Organization accounts are for businesses and nonprofits. In the future they will be able to have members, reimburse expenses (#505), and act as fiscal sponsors for teams.

**Comment by droidmonkey** [comment]
The whole process is wanting for some clarity. Having never used your platform before, it would seem I royally messed everything up and doesn't look like I can fix it.

**Comment by Changaco** [comment]
@droidmonkey I have transformed https://liberapay.com/keepassxc into a team. To invite others to join log in to your personal account then go to <https://liberapay.com/keepassxc/edit/members>.

**Comment by droidmonkey** [comment]
Thank you works perfectly
