### ISSUE TITLE
Facebook connect on our profile is not working

### ISSUE THREAD

**Issue by SimonSarazin** [liberapay/liberapay.com#110]

**Comment by Changaco** [comment]
What I'm seeing [in Sentry](https://sentry.changaco.oy.lc/sentry/liberapaycom/issues/6/) is: `error_code=4201`, `error_message=User canceled the Dialog flow`, which is not very helpful.

**Comment by Changaco** [comment]
I can't reproduce this, connecting my Facebook account works fine. I've improved OAuth error handling, so if it happens again you should see an error message.

**Comment by Changaco** [comment]
I've figured this out, the app wasn't "live" on Facebook, it was only usable by developers.
