### ISSUE TITLE
Add logo to badge at shields.io

### ISSUE THREAD

**Issue by mattbk** [liberapay/liberapay.com#1103]
Currently:
![image](https://user-images.githubusercontent.com/3729038/40065563-b5ee18de-5827-11e8-9133-0d791a3dfc45.png)

Suggestion from https://twitter.com/l33tname/status/996052539014598656:
> I found that but they look confusing and don't include the logo or the color

**Comment by fliiiix** [comment]
Thanks for opening a ticket my main problem with these buttons is that it's not clear that they are for Liberapay. They way they look they could be basically for many different platforms. So it would be cool if the looked more like this: ![Donate](https://liberapay.com/assets/widgets/donate.svg)

**Comment by mattbk** [comment]
This looks pretty simple based on https://github.com/badges/shields/pull/1413 and then adding e.g. `?logo=liberapay` to the path.

Logos go here: https://github.com/badges/shields/tree/gh-pages/logo.

**Comment by mattbk** [comment]
Some ideas. I may drop the background yellow on the logo.

![image](https://user-images.githubusercontent.com/3729038/40136266-0311521c-590d-11e8-8be0-e1c3af38acf7.png)

**Comment by mattbk** [comment]
Feedback from @fliiiix on Twitter:
> Can not login on github at the moment but I personaly prefere the first ones:
https://user-images.githubusercontent.com/3729038/40136266-0311521c-590d-11e8-8be0-e1c3af38acf7.png https://twitter.com/l33tname/status/996872045089697794

> text black on white but the logo in color I think making the entire badge yellow is a bit too much https://twitter.com/l33tname/status/996872311482568705

**Comment by mattbk** [comment]
I'll roll with the white/yellow logo on black and we can change in the future.

**Comment by mattbk** [comment]
The PR has been committed, we're just waiting on deployment (which does not happen very often.)

**Comment by fliiiix** [comment]
Yay, it looks like it's deployed but it seems that now it always shows invalid.

![2018-06-03--1528026784_3840x1080](https://user-images.githubusercontent.com/1682954/40886312-a820c14e-6735-11e8-8927-724e8ffc6aad.png)

**Comment by Changaco** [comment]
@fliiiix That was due to the requests from Shields being blocked because we're currently in "Under Attack" mode, I've adjusted the settings to correct the problem.

**Comment by Changaco** [comment]
I believe this issue can be closed now. Good work @mattbk! :slightly_smiling_face:

**Comment by fliiiix** [comment]
:tada: Amazing :tada: thank you @mattbk & @Changaco :heart:
