### ISSUE TITLE
Connect Github-Organization

### ISSUE THREAD

**Issue by jerger** [liberapay/liberapay.com#1142]
Hi, 
I've many organizations on GitHub, but I want only connect one of them to librepay & add organization repos. Is there a way?

BR, jerger

**Comment by jorgesumle** [comment]
> I've many organizations on GitHub, but I want only connect one of them to librepay & add organization repos. Is there a way?

Write the following URL `https://liberapay.com/on/github/organization` (replace *organization* with your organization name). Scroll to the bottom, you'll see the team members and a button to connect that team account (**Connect team account**).

**Comment by Changaco** [comment]
@jerger You have to [create a team](https://liberapay.com/about/teams), then attach the GitHub organization from the team's profile settings.

Related issue: #1104.

**Comment by jerger** [comment]
works thank u :-)
