### ISSUE TITLE
Misaligned list under "giving"

### ISSUE THREAD

**Issue by eldelacajita** [liberapay/liberapay.com#1145]
In the "Giving" section of my personal profile, I've noticed that one of the donations (the last one on the list) seems misaligned with the rest, and has a slightly different background color under the currency symbol. 

![imagen](https://user-images.githubusercontent.com/2880679/41407154-df204f56-6fce-11e8-900c-02ac777e8b4c.png)

**Comment by Changaco** [comment]
This issue is a duplicate of #1025.

**Comment by eldelacajita** [comment]
Sorry! I was searching for "align" related words and that one didn't show up.
