### ISSUE TITLE
The FAQ about processing fees is unclear

### ISSUE THREAD

**Issue by doniks** [liberapay/liberapay.com#1147]
I think this whole answer needs more elaboration. It tries to squeeze a lot of complex information 

It says "Withdrawing euros to a SEPA bank account is free" 

I don't get it. Should this say *from* instead of *to*? Is this referring to direct debit? Or is this a fourth payment option? 

", transfers to other countries cost €2.93 each."

Again, I'm lost. This seems to be taking about fees based on the recipient, while everything else is talking about fees based on the mode of payment. Please make it at least two separate sentences and make them both clearer.

"Withdrawing US dollar"

I guess this is now in addition to the table above?! Only applies to direct debit? No, not supported ... do you then maybe mean bank wire? Why is it not in the table then?

It's just all not clear.

**Comment by doniks** [comment]
I'm happy to draft formulations/representation to make it clearer, but first I would need answers to how it works, then I can help with how to communicate it.

**Comment by mattbk** [comment]
The table contains information on fees when you are transferring money _into_ your Liberapay wallet.

![image](https://user-images.githubusercontent.com/3729038/41556350-246b4636-7300-11e8-8747-688c874f65d9.png)

The paragraph below the table is information on fees when you are transferring money _out of_ your Liberapay wallet.

> Withdrawing euros to a SEPA bank account is free, transfers to other countries cost €2.93 each. Withdrawing US dollars costs $3.51 per transfer regardless of the destination country.

**Comment by mattbk** [comment]
The withdrawal information could be in a table as well. People might see it more readily that way.

```
              | Euro      | US Dollar
--------------------------------
SEPA          |   free    | not supported
non-SEPA      | €2.93     | $3.51
```

**Comment by doniks** [comment]
I thought about it, but one might also get the impression that you cannot withdraw USD into a SEPA account

**Comment by mattbk** [comment]
If that's possible, then "not supported" could be replaced by "$3.51" and be clear, correct?

I actually don't know whether it's possible or not from reading the page.

**Comment by doniks** [comment]
oh, yeah. another 3.51 would make it clear. and that way I would also agree that the table is better than the bullet list

**Comment by Changaco** [comment]
Closing as obsolete. The FAQ now longer contains a list of fees, because there are way too many different cases now.
