### ISSUE TITLE
using github is indirectly supporting fascism

### ISSUE THREAD

**Issue by PaulFree14** [liberapay/liberapay.com#1150]
As many of you propably know, github got bought by microsoft.
Yet there is many to say about microsoft, but I believe it's important to have current events in mind, and how the struggle for free software can be linked with those of others.

That's how resisting becomes more powerfull, when the opressed give visability to each others struggle and take action of solidary.

Microsoft is currently supporting ICE.
Take on that matter also a look at this:
https://boingboing.net/2018/06/20/godwins-law-suspended.html
(myself haven't really made any research on that sybject)

This is a call for directAction in solidarity with anyone being effected by the fascist activities conducted by the US agency ICE.

Since being here on github, we can start to use this proprietary plattform instead of sharing code, colaborating on code and being constructive about coding to use it to exclusivly share informations about microsoft supporting fascism, what it has to do with ones own use of this plattform and deconstructing fascist ideology.

Also start writing issues about this into any other software projects you empathise with
and encourage people to do the same.

Thought their is potential of making a trend out of this, that could damage the trademark github and microsoft and raises more awareness about ICE within the coder scene.

Maybe someone could come up with a much better writing then this one, incl. some more research and possibilities that can be taken to resist ICE in specific or racism in general.

**Comment by jorgesumle** [comment]
We plan to do that (see #46). I got stuck in the process, so maybe someone can help me with GitLab-CI, see ongoing efforts from #1143

**Comment by PaulFree14** [comment]
That's great! Thank you. 
But in the linked issues I could rather see technical or software related reasoning but nothing about ICE. 

there is some great outrage right now on this matter that can be used to damage microsofts 7.5 billion $ investemt, demonstrating that support of #fascism has its costs and even push people towards non-propriertary plattforms as best free software. 

It will help to create more awarness about both struggle, closed software and closed society without it's being much effort.

**Comment by jorgesumle** [comment]
> But in the linked issues I could rather see technical or software related reasoning but nothing about ICE.

Well, we have the [salon](https://github.com/liberapay/salon) for non-technical issues:

>  Liberapay's salon, where the discussions that don't belong elsewhere take place
