### ISSUE TITLE
[feature] Pledge on Mastodon account

### ISSUE THREAD

**Issue by tuxayo** [liberapay/liberapay.com#1155]
As of now, one can only pledge to accounts on Twitter, GitHub and Bitbucket.

After searching in the issues. Several mention Mastodon but none is about the pledge feature.

**Comment by tuxayo** [comment]
Is there a technical reason that blocks this? Or this is only because more hot stuff is in the list?
Thus, is the feature valuable and would a patch be accepted?

**Comment by trebmuh** [comment]
FWIW, I'd see this as a great improvement.

**Comment by mattbk** [comment]
> Thus, is the feature valuable and would a patch be accepted?

Seeing how @Changaco tagged this the way he did, I think a PR would be accepted.

**Comment by mattbk** [comment]
I wonder if it could be generalized to any ActivityPub account.

**Comment by Changaco** [comment]
I just remembered that this is actually an upstream issue: <https://github.com/tootsuite/mastodon/issues/4588>.

**Comment by Changaco** [comment]
The upstream issue has been fixed. The documentation for the new API endpoint is at https://docs.joinmastodon.org/methods/accounts/#lookup
