### ISSUE TITLE
Payment processing is down

### ISSUE THREAD

**Issue by LiamDawe** [liberapay/liberapay.com#1160]
Just tried to view how much my account has available to withdraw and...oh

> 500
> Internal Server Error
> 
> Looks like you've found a bug! Sorry for the inconvenience, we'll get it fixed ASAP!
> The details of this error have been recorded. If you decide to contact us please include the following  error identification code in your message: bb79c1225a6c416baa920b039684c86f.

**Comment by Changaco** [comment]
We're having serious problems with our payment processor today, I was about to launch this week's payday when they deactivated our account! See https://github.com/liberapay/salon/issues/242 for details.

**Comment by LiamDawe** [comment]
Ouch any idea where the requests came from? Sounds like something needs locking down...

**Comment by Changaco** [comment]
What needs to be locked down is Mangopay's own SDK: <https://github.com/Mangopay/mangopay2-python-sdk/issues/165>.

**Comment by BaptisteGelez** [comment]
Can't we check the data user is sending before giving it to Mangopay, until they patch their SDK?
