### ISSUE TITLE
Quarantine prevents emptying wallet

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#1173]
From @LiamDawe in <https://github.com/liberapay/salon/issues/232#issuecomment-404689291>:

> Will you turn off the quarantine then, so us creators can get our funds right away? Don't like the idea of losing some of it if they do abruptly cut you off.

**Comment by Changaco** [comment]
We could turn off the quarantine but we need to disable payins first.

**Comment by LiamDawe** [comment]
Okay well you apparently only have a few weeks left anyway right? Doesnt make sense to allow anyone to add new funds (emptying wallet still allowed to creators of course) since any brand new funds wouldn't hit the quarantine time.

**Comment by Changaco** [comment]
Yes, I guess we have no choice but to disable all payins at this point. It would have been much nicer to have at least one new payment processor set up before turning off payments through mangopay, even if it was only a simple paypal integration, but mangopay's haste doesn't help provide a smooth transition.

**Comment by LiamDawe** [comment]
Indeed, real shame it got here, but absolutely no point allowing further new pay-ins since they won't hit your quarantine threshold in time.

**Comment by Changaco** [comment]
Actually they might if mangopay extends the deadline, but since mangopay has only said that they *could* extend the deadline and not that they *will* we can't count on it.

**Comment by LiamDawe** [comment]
That's a pretty big *if* and at this point, is it worth causing hassle for anyone? The ideal solution would be to prevent any such issues I think :)

**Comment by WhatsThePlan** [comment]
hi any news bout this or in progress? is kind of important indeed or money will be lost

**Comment by LiamDawe** [comment]
I've managed to withdraw a lot of it, but I am also still worried some will be lost as there's only ~10 days left until the date they said they will terminate.

**Comment by SirCmpwn** [comment]
I'm also concerned about this. I have fair bit of money which is going to be quaranteed until after the deadline.

**Comment by Changaco** [comment]
The quarantine is now disabled. Sorry about the delay.

**Comment by a3nm** [comment]
Worked for me, thanks!
