### ISSUE TITLE
2.0 suggestions (what seems to have kept away donations for us)

### ISSUE THREAD

**Issue by dtugend** [liberapay/liberapay.com#1174]
I am not sure if this is the right place to comment (sorry if not),
but maybe it's possible to take these into account for Liberapay 2.0:

What mostly kept donations away for us according to the opinion of my team and a few potential donors was:
- **Lacking support of PayPal** (#424 - not sure if fixable, due to the way PayPal works and behaves (likes to suspend accounts etc))
- **Donations appeared to donors as reoccurring** (#415 has the same problem, but the fixes still make _people believe it is reoccurring_)

I myself didn't like the donations being virtually reoccurring and would have preferred to donate from time to time instead, until I (not very likely) decide to make it reoccurring. I know it's technically the same at the moment, but most people don't think of it that way.

Thank you for your efforts in the past and good luck with the future.

**Comment by Calinou** [comment]
> **Donations appeared to donors as reoccurring**

See [the FAQ](https://liberapay.com/about/faq#one-time-gift):

> **Can I make a one-time donation?**
> Liberapay is designed for long-term stable funding and only supports recurring gifts.

**Comment by dtugend** [comment]
Okay, understood, feature not wanted.
Thank you nevertheless.
