### ISSUE TITLE
/edit/goal

### ISSUE THREAD

**Issue by haheute** [liberapay/liberapay.com#1177]
Hello.

When I want to set my role/goal on liberapay.com, I get an error:

```
<input type="radio" name="goal" id="goal-0" value="0.00">

Bad Request
"0.00" is not a properly formatted number. Perhaps you meant 0 oder 0?
```

Just wanted to report it.

**Comment by jorgesumle** [comment]
What is the language you were using when you got that error? If you were browsing in German or other languages which use commas to separate decimal numbers, that's the correct behaviour.

What we can improve is the error message for 0, both suggestions are the same.

**Comment by Changaco** [comment]
@haheute Thanks for this report, I can indeed replicate the problem by switching my browser to German.

@jorgesumle It's not the correct behavior, we're using the wrong function to parse the number.
