### ISSUE TITLE
PayPal integration

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#1187]
In #1181 I implemented connecting a Stripe account, it should be possible to do the same for PayPal.

**Comment by Gert-dev** [comment]
Minor question about this that I can't seem to find any info about yet: how will this work with respect to donors? If a receiver sets up only a Stripe account for receiving, will he be able to receive from donors using PayPal? Similarly, can a receiver with only PayPal also receive from users paying through Stripe? 

Previously everything ended up on the Mangopay account, but seeing as there is no intermediary account anymore now (I think?), I'm not sure how it works.

**Comment by Changaco** [comment]
Yes, it will be recommended to set up both PayPal and Stripe to maximize convenience for donors. There won't be a "bridge" between the two systems, we can't transfer money between PayPal and Stripe accounts.

**Comment by mattbk** [comment]
Won't credit cards work to give to both PayPal and Stripe?

**Comment by LiamDawe** [comment]
> PayPal
> Not available in United Kingdom.

Erm, yes it is ;)

**Comment by Aicaya** [comment]
>PayPal
>Not available in Puerto Rico.

Puerto Rico counts as part of the United States, so Paypal is also available. Same with Stripe, which shows the same alert.

**Comment by bernd-wechner** [comment]
What does it matter I wonder where it's not available? Adding any payment means as an option for those who prefer it increases the net likely contributor base, end of story, I don't care if the payment means is not available to everyone, it's that it is available to and preferred by a significant demography that make it well worth supporting.

An age old principle is that the easier you make it to contribute, the more you can expect will be contributed. End of story. 

Adding PayPal or any payment option does not oblige or constrain anyone to use it.
