### ISSUE TITLE
Payouts are messed up

### ISSUE THREAD

**Issue by LiamDawe** [liberapay/liberapay.com#1188]
Got an email saying:

> €28.45 was given to you personally.

Only 4.31 has ended up in my wallet? 

Also had a [report](https://twitter.com/HerrMuskat/status/1021804807408037890) that a user was unable to empty their remaining funds to me.

My receiving page says:

> You receive €28.20 per week.
> You can't receive money until you've configured a payment account.

I'm assuming something has messed up, with the move away from Mangopay.

**Comment by Changaco** [comment]
The numbers are accurate but the wording is no longer appropriate now that donations are transferred in advance. Hopefully it'll be fixed next week.

Your income this week is €28.45, but you've already received and withdrawn most of it in advance last week.

**Comment by LiamDawe** [comment]
Yeah that wording then makes zero sense.
