### ISSUE TITLE
"Payment" in the menu is not translatable

### ISSUE THREAD

**Issue by tuxayo** [liberapay/liberapay.com#1189]
![screenshot_2018-07-27_17-35-05](https://user-images.githubusercontent.com/2678215/43330443-82ae1e30-91c3-11e8-841b-f86495dbcfb2.png)
![screenshot_2018-07-27_17-35-19](https://user-images.githubusercontent.com/2678215/43330444-84b581f0-91c3-11e8-8784-8092d0840690.png)
![screenshot_2018-07-27_17-35-40](https://user-images.githubusercontent.com/2678215/43330447-868e8706-91c3-11e8-8ccb-f295a6198972.png)

**Comment by Changaco** [comment]
It is translatable, but only the Finnish translation has been deployed so far:

![screenshot_20180731_114731](https://user-images.githubusercontent.com/1581590/43452347-82b4eda4-94b7-11e8-963d-d366ef9ca2ba.png)
