### ISSUE TITLE
Receiving page information are confusing

### ISSUE THREAD

**Issue by trebmuh** [liberapay/liberapay.com#1197]
Related to: https://mastodon.xyz/@Liberapay/100520158923864989
Translation for the non-French readers:
> @Liberapay and otherwise, clarifying this mess would be possible???
> You need a stripe account to receive but not to give on one side, on another side it tells me that I'm still receiving????
> and from another side I can't give?
> and that, in fact, according to the logs, that... works?

***

On [my account](https://liberapay.com/me/receiving/), I've got this:

![liberapay-flou](https://user-images.githubusercontent.com/8705846/43909225-183b3448-9bfa-11e8-854d-77b25e8df6e2.png)

First line says that I'm receiving some money, second line says I can't receive money. It is confusing and needs to be clarified.

I'm trying a shot in the dark since I'm not totally sure how LP works nowadays (I'm still catching up  after 4 weeks of-the-web with what changed in LP):
- **First line**: You're receiving €XX.XX from donors per week.
- **Second line**: You can't transfer the money from your LiberaPay account to your bank account until you've configured a payment account.

@Changaco can you please confirm/infirm that my shot in the dark is right/wrong?

**Comment by trebmuh** [comment]
( ping @liberapay/media-managers )

**Comment by trebmuh** [comment]
(maybe) related to https://github.com/liberapay/liberapay.com/issues/1188

**Comment by mattbk** [comment]
More accurately, it might be

- Donors want to give you $XX.XX per week.
- You can't receive money until you've connected an account to receive

(I think "payment account" in the context of receiving is confusing.)

No money is held in Liberapay; it goes straight from the donors' credit cards into the Stripe account.

**Comment by trebmuh** [comment]
Thanks for the clarification @mattbk 
Trying #1198 to fix this, pending @Changaco approval.
