### ISSUE TITLE
Confusing language on giving page

### ISSUE THREAD

**Issue by mattbk** [liberapay/liberapay.com#1201]
At https://liberapay.com/about/me/giving/ I see:

![image](https://user-images.githubusercontent.com/3729038/43963437-f2cabbf8-9c7f-11e8-8e85-c96840c9fa79.png)

First it says I have to renew donations, then it says my donations are funded by my income. I'm guessing the latter is no longer correct?

**Comment by Changaco** [comment]
This was fixed in #1254.
