### ISSUE TITLE
Error when installing dev env with docker

### ISSUE THREAD

**Issue by MartinDelille** [liberapay/liberapay.com#1204]
I have an error at the second step:

```
$ docker-compose run web bash recreate-schema.sh                                        ✔  2994  11:25:13
Creating network "liberapaycom_default" with the default driver
Creating liberapaycom_db_1 ... done
==============================================================================
Applying sql/recreate-schema.sql ...

psql: could not connect to server: Connection refused
	Is the server running on host "db" (172.24.0.2) and accepting
	TCP/IP connections on port 5432?
```

**Comment by MartinDelille** [comment]
@EliotBerriot @diogoosorio @Changaco I see you contribute to the docker configuration. Any idea on what is going on?

**Comment by Changaco** [comment]
I don't use Docker, any contribution I may have made to its configuration was simple maintenance.

**Comment by MartinDelille** [comment]
Ok I will wait if other contributor can help me fix it (because I don't use docker so much too). I find the official development setup quite complicated.

**Comment by mattbk** [comment]
I've gotten the non-Docker instructions to work before (although it's been a while). Which part do you need help with?

**Comment by jorgesumle** [comment]
> Ok I will wait if other contributor can help me fix it (because I don't use docker so much too). I find the official development setup quite complicated.

The Dockerfile is outdated. The failure you got might be related to the fact that Debian 8 uses the version 9.4 of postgresql, while Liberapay requires 9.6 or greater. I guess it could be solved updating the Dockerfile to use Debian 9, which has the 9.6 version of postgresql.
