### ISSUE TITLE
Not receiving one-time login email

### ISSUE THREAD

**Issue by jelkner** [liberapay/liberapay.com#1214]
I created an account but am now locked out since I am not receiving the one-time login emails to login to the site.  I've tried this several times, been locked out for a day, and tried again the next day, but still no luck.

**Comment by jorgesumle** [comment]
Did you look receive the confirmation email? Did you look in the spam folder?

**Comment by jelkner** [comment]
I looked *carefully* in the spam folder each time and did not see a confirmation email there.

**Comment by jelkner** [comment]
I emailed support from the email that I used to register to confirm its validity.

**Comment by Changaco** [comment]
@jelkner Our emails are now being sent via a different route, let me know if you still don't receive them.
