### ISSUE TITLE
SEPA Direct Debits

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#1233]
Stripe has enabled SEPA Direct Debits on our account, we need to finish the implementation on our side.

**Comment by Changaco** [comment]
I've sent a message to our bank (Crédit Mutuel) asking if they can get us a SEPA creditor identifier.

**Comment by MathiasRenner** [comment]
@Changaco Do you plan working on a SEPA debit method without Stripe? Is there a need to use stripe instead of pure SEPA processes? To me, I don't know why I need stripe since SEPA works for itself, doesn't it? Thanks for your comments!

**Comment by Changaco** [comment]
Stripe is very much needed, Liberapay is way too small to interface directly with low-level payment systems like the ones that process SEPA Direct Debits, and Stripe does much more than those.

**Comment by Changaco** [comment]
Regarding my previous comment: the conversation with the bank went nowhere, they want me to go see them at their office and they don't care that I'm 300km away from it at the moment. I'll be back in that region in two weeks.

**Comment by Kaligule** [comment]
@Changaco Thanks for keeping us updated. Sepa is the only viable option of money transfer for me, so I am watching this very carefully.

**Comment by Changaco** [comment]
Sorry it's taking so long, I know SEPA Direct Debits are particularly important to German users because many of them simply don't own a card.

**Comment by Kaligule** [comment]
@Changaco Nothing to be sorry about, thank you for your great work.

**Comment by MathiasRenner** [comment]
I openened a new issue for following the discussion about Stripe and privacy concerns: https://github.com/liberapay/liberapay.com/issues/1268

**Comment by Changaco** [comment]
I've just returned from an appointment at the bank. I have to send them some documents via email so that they can forward our request to the central bank. After that we have to wait for a response, which could take a few weeks.

**Comment by Changaco** [comment]
Just received an email from the bank: we finally have our SEPA creditor identifier! :man_dancing: :tada: 

I'll get to work on finishing the technical implementation as soon as possible.

**Comment by trebmuh** [comment]
Nice!

**Comment by Changaco** [comment]
After some back and forth with Stripe's support we're now finally able to process SEPA Direct Debits!

![Screenshot of the Stripe Dashboard showing "SEPA Direct Debit" as "Live"](https://user-images.githubusercontent.com/1581590/48717311-6c4b1e80-ec19-11e8-817e-164b72a6ac0e.png)

Final step: merge and deploy #1337.

**Comment by trebmuh** [comment]
\o/

**Comment by Changaco** [comment]
SEPA Direct Debits should be operational now.

**Comment by trebmuh** [comment]
Would that be related to the fact that I received today an email from stripe asking for a scan or photograph of a government-issued photo ID?

**Comment by IzzySoft** [comment]
And does this still need a Stripe account (on the receiving end)?

**Comment by mattbk** [comment]
@IzzySoft, yes: https://github.com/liberapay/liberapay.com/blob/09fa92915f4c5c4bf1e44d2d8ab450f3d6c850fd/www/%25username/giving/pay/%25payment_id.spt#L113.

**Comment by IzzySoft** [comment]
@mattbk thanks, I was afraid so. I need to think that over. Still don't understand why withdrawing needs a "man in the middle" for SEPA, especially as that's no micro-payment anymore (at least not if you'd set a limit for this). But then, it's not my area of proficiency.

**Comment by davidak** [comment]
>Stripe is very much needed, Liberapay is way too small to interface directly with low-level payment systems like the ones that process SEPA Direct Debits, and Stripe does much more than those.

@Changaco what would be needed to solve this?

For example [mein-grundeinkommen.de](https://www.mein-grundeinkommen.de/) started quiet small and is now quiet big. I setup recurring direct debit (SEPA) in my profile and can change the amount at any time. I think they don't use a special payment provider, just a bank. I could ask how they do that technically.

Also, would it help to ask other organizations like FSF, FSFE, Software Freedom Conservancy, The Document Foundation, that have experience with collecting donations for help?

**Comment by Changaco** [comment]
@davidak The organizations you mentioned all collect money for themselves, they're not payment processors like Liberapay and consequently they don't have to follow financial regulations.

**Comment by davidak** [comment]
mein-grundeinkommen.de works like a lottery and choose a random person that receives a universal basic income for one year. But i think that's also a different case than donations. But it shows that the technical side can be done, even by a small team.

@Changaco Is the main problem the regulation? Do you have an idea how big we must become that it makes sense to support SEPA directly? Do you plan doing it then?

The mentioned organizations have a big network and contact to lawyers. They might be able to help find a solution.

**Comment by mattbk** [comment]
Somewhere a number of a few hundred thousand EUR was tossed around as what would be needed to get a money transmission license in order to act more like a bank.

**Comment by Changaco** [comment]
Those of you who don't understand why we need Stripe may want to read this: [PSD2: Implications for marketplaces and platforms](https://stripe.com/connect/eu-guide).
