### ISSUE TITLE
500 error when renewing payment (with Stripe at least)

### ISSUE THREAD

**Issue by tuxayo** [liberapay/liberapay.com#1240]
I wanted to renew a payment.
It was a 0.24/week so 1€/month
So I wanted to pay 12€ upfront as usual (not the first renewal) to keep the fees not too high but no to pay too much in advance.

So I input 12, clicked on "Initiate payment" and boom

id:
ec6b835dbf7c4c0c8faa879629256a7f

**Comment by tuxayo** [comment]
And I can reproduce at will
ae2eeb104abe4f55b6f03b255628e810

**Comment by tuxayo** [comment]
I might not try again until future notice, the payment might get triggered ^^"
From the info that I see from my bank, the payment didn't happen. So I'm not worrying about that.

**Comment by Changaco** [comment]
Fixed in #1241.

**Comment by tuxayo** [comment]
Confirmed by renewing 3 donations with Stripe, thanks a lot :D
