### ISSUE TITLE
The username change warning isn't clear enough

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#1242]
<https://mastodonten.de/@scroom/100724362756380264>:

> [@Liberapay](https://mastodon.xyz/@Liberapay) I have a question about existing links to donation accounts: I changed my name and then I got a hint that I had to change the donation links. So far the old link still works. Will it be turned off at some point?
>
> https://liberapay.com/~32819/donate

**Comment by trebmuh** [comment]
@Changaco : while translating this new text, I've thought the following: wouldn't it be safer to have a delay before someone can reclame an old username? Something like 2 months maybe?

**Comment by Changaco** [comment]
@trebmuh Yes, but that's a separate issue: #1712.
