### ISSUE TITLE
500 error when renewing payment with Paypal

### ISSUE THREAD

**Issue by tuxayo** [liberapay/liberapay.com#1244]
I wanted to renew a payment.
It was a 0.24/week so 1€/month
So I wanted to pay 12€ upfront as usual (not the first renewal with PayPal, it already worked for other donations) to keep the fees not too high but not to pay too much in advance.

So I input 12, clicked on "Initiate payment" and boom

b57e12b4473f4dbb84195917a3706c28
c1f75c51ac2c42d1888557719a76a854

**Comment by tuxayo** [comment]
I feel like I got some sort of curse, it's exactly like #1240 😂😂😂

**Comment by Changaco** [comment]
It looks the same as #1240 but it's a different problem. The payment is being rejected by PayPal:

```json
{
    "name":"PAYEE_ACCOUNT_RESTRICTED",
    "message":"Refused - payee account is restricted",
    "information_link":"https://developer.paypal.com/docs/api/payments/#errors",
    "debug_id":"d7030f8bc093c"
}
```

https://sentry.io/share/issue/86912c7e0dc94c2ebe2242bc363498d2/

**Comment by tuxayo** [comment]
Should this error be caught to inform the sender?

**Comment by Changaco** [comment]
Yes, we need to show a proper error message to the payer.

**Comment by tuxayo** [comment]
Confirmed thanks :)
