### ISSUE TITLE
Donations via PayPal only? 

### ISSUE THREAD

**Issue by SGallay** [liberapay/liberapay.com#1258]
It's a question but also, possibly, an issue: I once renewed donations using PayPal and now all my donations renewals go through PayPal.

Is this "the new normal" or is there an option missing, somewhere, to change the source of donations (for example to Stripe instead of PayPal)?

**Comment by mattbk** [comment]
Whether payments are made by PayPal or Stripe (credit card) is set by the receiver. If it looks like you are only able to give via PayPal, this means that either the receiver has only PayPal set to receive or there is a bug where you are only seeing a PayPal option even if Stripe is also available.

**Comment by SGallay** [comment]
I have both Stripe and PayPal set up, but I don’t see the option to switch back to Stripe now that I have PayPal activated.

Am I looking at the wrong place?

—
Stéphane « Alias » Gallay – stephane.gallay@me.com (mailto:stephane.gallay@me.com)
https://alias.erdorin.org – Ceci n’est pas une signature

**Comment by mattbk** [comment]
Are you trying to donate or are you trying to receive donations?

**Comment by mattbk** [comment]
If you are trying to donate, the payment method used (Stripe or PayPal for the moment) depends on what the receiver has set up.
