### ISSUE TITLE
Notify donors earlier when an account cannot receive payments

### ISSUE THREAD

**Issue by mattbk** [liberapay/liberapay.com#1262]
For example at https://liberapay.com/davidrevoy/ I click "Donate:"

![image](https://user-images.githubusercontent.com/3729038/46430861-dc582080-c70f-11e8-9916-598310caba81.png)

It brings me to the "how much" screen:

![image](https://user-images.githubusercontent.com/3729038/46430882-ec700000-c70f-11e8-93fe-0e4ecc8e48ba.png)

And then bumps me to my /giving page, where I see that I actually can't send any money:

![image](https://user-images.githubusercontent.com/3729038/46430923-0a3d6500-c710-11e8-8195-617c3c830ce5.png)

Now obviously we want to encourage people to set up donations even if the recipient doesn't have a payment method yet, but we also don't want to frustrate new users. Is there a way to identify such a donation as "pending payment method" before the third step in the process? It's almost the same thing as a pledge.

(Additionally, showing that a recipient "Receives $X" and then saying that you can't send them money is confusing.)

**Comment by mattbk** [comment]
Perhaps adding which payment methods are accepted near the "Donate" button would help as well.

Something like a credit card and PayPal icon. If more payment methods were added, this particular example wouldn't work. I don't think the Stripe logo would be meaningful to donors--it's just a credit card to them.

![image](https://user-images.githubusercontent.com/3729038/46542381-e3a03b00-c883-11e8-8111-185cc2579037.png)

**Comment by mattbk** [comment]
I think this falls under this ticket as well: https://twitter.com/krtfflslt/status/1072170622506147840

**Comment by silberzwiebel** [comment]
Hi @mattbk, thanks for linking my tweet here and pointing me to this issue. As I'd like to avoid paypal, it would be nice to see whether I can donate to the receiver using SEPA. 
Especially, it would be good to see this information already in the overview page. In this example, dino only uses paypal, while f-droid accepts SEPA. But I have to click on the buttons to find this out.
![bildschirmfoto-20181213112948-996x245](https://user-images.githubusercontent.com/4533862/49932972-c1055080-feca-11e8-8315-ade654f9bb68.png)

**Comment by mattbk** [comment]
If we can do this, adding a filter to #1275 would be helpful as well.

**Comment by mattbk** [comment]
> In general I don't think it's a good idea to show the available payment methods in profile boxes. (https://github.com/liberapay/liberapay.com/pull/1366#issuecomment-447559587) 

Why not?

**Comment by trebmuh** [comment]
I'm asking myself the same question. There are several messages in Mastodon asking around this question which leads me to be under the impression that it would help donors (and potential donors) to feel they understand better what's going on and what will happen.

**Comment by Changaco** [comment]
(Should have been closed by #1366.)
