### ISSUE TITLE
Miscalculation on display

### ISSUE THREAD

**Issue by trebmuh** [liberapay/liberapay.com#1265]
If I'm looking at [my personal account](https://liberapay.com/trebmuh/), it says that I'm receiving 4.94€ from 7 donors. If I'm looking at [the LibraZiK project](https://liberapay.com/LibraZiK/) (which I'm the only one in the team), it says that it receives 2.01€ from 3 donors.

But if I'm looking at the notification from this week which says that I received 6,95€ this week from 4 (personal) + 3 (from the LibraZiK team) donors, it sounds that the numbers should be:
- personal donations: 4,94€ from 4 donors,
- LibraZiK donations: 2,01€ from 3 donors.

It then looks like that, on [my personal account](https://liberapay.com/trebmuh/), it should says either:
- 6.95€ from 7 donors,
- or 4.94€ from 4 donors.

_With the old (mangopay) system, it was the first one if I remember correctly._

I don't know if I'm the only one affected or if this affects all LP users.

**Comment by Changaco** [comment]
The code that computes the actual takes of team members is broken, you can see in https://liberapay.com/LibraZiK/income/ that your computed take is zero instead of €2.01.

```sql
select id, username, receiving, taking, npatrons, nteampatrons from participants where username = 'trebmuh';
  id  | username | receiving  |   taking   | npatrons | nteampatrons 
------+----------+------------+------------+----------+--------------
 4696 | trebmuh  | (4.94,EUR) | (0.00,EUR) |        4 |            3
(1 row)
```

**Comment by trebmuh** [comment]
Thanks for this clear explanation. :+1:

**Comment by mattbk** [comment]
I assume this explains my question at https://github.com/liberapay/liberapay.com/issues/1222#issuecomment-424381568.

**Comment by Changaco** [comment]
This is fixed. \o/
