### ISSUE TITLE
Show payment processing fees in About pages

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#128]
We don't actually show them anywhere on the site!

**Comment by Changaco** [comment]
This issue was reported by a user in the first ever email to the support address. :-)

**Comment by MartinDelille** [comment]
This should be displayed in the FAQ right? 

Are [these fees](https://www.mangopay.com/fr/nos-tarifs/) correct?

**Comment by Changaco** [comment]
Yes, but we want to use the `FEE_*` constants from `liberapay/billing/exchanges.py`. We should move them to `liberapay/constants.py`, that way they'll be automatically available in simplates as `constants.FEE_*` without having to import them.

**Comment by Changaco** [comment]
In addition to putting the info in the FAQ, we should mention the fees in the Introduction page and link to the new FAQ entry for details.

**Comment by Changaco** [comment]
We should also tell/remind users about fees when they're about to pay them, so on the `/wallet/pay{in,out}` pages.
