### ISSUE TITLE
Add rupee support

### ISSUE THREAD

**Issue by MartinDelille** [liberapay/liberapay.com#1282]
This follows a thread on [discourse meta forum](https://meta.discourse.org/t/liberapay-integration/99267) regarding rupee support. Rupee is already mentionned [here](https://github.com/liberapay/liberapay.com/issues/1081) and is supported by Stripe.

There is also a more generic issue about adding more currency here: #833

**Comment by pratiksinhacs** [comment]
I am interested

**Comment by Changaco** [comment]
The INR is in the list of 31 currencies that will be added soon as part of #833.

**Comment by Changaco** [comment]
Current status:

![Screenshot of an INR donation amount selector](https://user-images.githubusercontent.com/1581590/47086156-0da91400-d219-11e8-92f3-12d24894269e.png)

(The amounts are computed automatically from the ones in EUR, so they may seem weird. Feel free to propose different amounts.)

**Comment by MartinDelille** [comment]
@pratiksinhacs What amount would you propose for rupee? In euros, it goes from one cent to 100€ (which is the maximum transferable amount per month).

**Comment by pratiksinhacs** [comment]
Ok leave it like that

Symbolic should be Rs 50/month

**Comment by MartinDelille** [comment]
@pratiksinhacs it's more than 10 times the euros symbolic donation which seems to be a lot. This is a microdonation system. I would round it 1 rupee per week.

**Comment by pratiksinhacs** [comment]
Ok 
Add a feature for one time payment also

**Comment by MartinDelille** [comment]
Sorry but this is a recurring microdonation system. Although the current system looks very like a one time payement in the end. More info on the website: https://liberapay.com/

**Comment by Changaco** [comment]
Done in #1286.
