### ISSUE TITLE
Wrond mécène number

### ISSUE THREAD

**Issue by MartinDelille** [liberapay/liberapay.com#1284]
I give to a user but the "mécène" count is still zero:
<img width="801" alt="screenshot 2018-10-20 11 31 03" src="https://user-images.githubusercontent.com/879889/47254009-c363a500-d45b-11e8-9ff1-27f6d7a370a0.png">

Here is the donatee page: https://liberapay.com/zaquestion/

**Comment by Changaco** [comment]
The number of patrons isn't wrong, zaquestion doesn't actually receive any donations.
