### ISSUE TITLE
Profile doesn't redirect to set language

### ISSUE THREAD

**Issue by jelv** [liberapay/liberapay.com#1306]
The [link](https://liberapay.com/SFTtech/) to the profile on [this ](https://nl.liberapay.com/Jelv/giving/pay/paypal/?beneficiary=34338) giving page went to the English version. I expected it to stay in Dutch.

**Comment by Changaco** [comment]
I can see how that could be annoying/disorienting. Fortunately this issue is easy to fix.

**Comment by jelv** [comment]
Also the redirection from PayPal back to Liberapay set it back to English also.
