### ISSUE TITLE
Bug during payment modification

### ISSUE THREAD

**Issue by MartinDelille** [liberapay/liberapay.com#1313]
I try to donate to this account: https://liberapay.com/lowtechlab/ after a previous promise on the twitter account.

lowtechlab created its account on the plateform but if I see that I donate to it, the actual number of mecene is still 0.

I tried to change the amount since I know that with the new system we need to do a payment in advance but I had a 500 error with the following error code: `fc677c3e6c54434ba77bcf1eac628a18`

**Comment by MartinDelille** [comment]
Thanks @Changaco ! Is it deployed? The bug seams to be fixed.

Unfortunately the user cannot receive my donation. I checked with him and his paypal account is connected.

**Comment by Changaco** [comment]
Yes, it's deployed.

The user has connected a PayPal account but he hasn't confirmed the email address. The verification code has expired by now, so the user will have to go to https://liberapay.com/about/me/emails/ and click the "Resend email" button.

**Comment by MartinDelille** [comment]
Ok maybe some clarification would be needed there. Shall I reopen this issue or create another one?
