### ISSUE TITLE
Raising amount possible bug?

### ISSUE THREAD

**Issue by trebmuh** [liberapay/liberapay.com#1323]
My actual take on the LP team is 5€ a week.

The following is displayed on liberapay.com when I'm logged in:

![bug2-lp](https://user-images.githubusercontent.com/8705846/48136092-14b6c580-e29f-11e8-8ada-9cf29c3f0683.png)

According to https://liberapay.com/about/teams#throttling , I shouldn't be able to ask for more than a 10€ take for next week if the "Regulation of take amounts" functionality is activated on the LP team. If this functionality isn't activated on the LP team, then I don't know where the _26,50€_ amount calculation comes from since (at the time of writing), the LP team leftover is _5,00 € and 2,93 $US_ which would make the following calculation for the maximum amount I could ask for: 5€ (week take) + 5€ + 2.93$ which equals to roughly a bit less than half of the _26,50€_ mentioned above.

It doesn't looks clear to me what's going on, and I might be totally/partially wrong with how the system works, but something sounds fishy here.

**Comment by Changaco** [comment]
€26.50 is indeed a weird limit given the current situation. Looking at the code I see a bug that might be responsible.

**Comment by Changaco** [comment]
After fixing that bug I'm getting €21.65, which is €5.00 + a leftover of €16.65.

**Comment by trebmuh** [comment]
Does that corresponds to the actual leftover of the team? _(I guess you're trying that on a home-made installation of LP which might not be on the same state than the production one)_

**Comment by trebmuh** [comment]
OK

**Comment by trebmuh** [comment]
Going further, how does a team can enable the take throttling?

**Comment by Changaco** [comment]
Adding or removing take throttling requires sending an email to support. I remember this happening at least once.

**Comment by Changaco** [comment]
The remaining TODO before closing this issue is to figure out why the team's estimated income is fluctuating between ~€160 and ~€190, thus resulting in a different leftover and different take limits.

**Comment by trebmuh** [comment]
> Adding or removing take throttling requires sending an email to support. I remember this happening at least once.

I've made a PR to add this knowledge to the https://liberapay.com/about/teams page. See #1330 .

**Comment by trebmuh** [comment]
(up)

Looking at https://liberapay.com/me/receiving/ , I'm receiving 10€/week, there is ~61,59 € leftover for the team, and the page tells me that I can take up to €119.99 this week:

![lp-upto](https://user-images.githubusercontent.com/8705846/103940614-e73f5e00-512d-11eb-9e1e-9950a0b03833.png)

**Comment by Changaco** [comment]
There's a disagreement on the amount of the leftover. The simplistic part of the code estimates it at ~€110, which added to your €10 take results in the €120 limit, whereas the more complicated part of the code returns a lower estimate.

**Comment by Changaco** [comment]
The discrepancies arise from fraud. Donations from suspended accounts are counted in some parts of the code and excluded in others.

**Comment by trebmuh** [comment]
Thanks for the precisions.
