### ISSUE TITLE
"organizations" question

### ISSUE THREAD

**Issue by trebmuh** [liberapay/liberapay.com#1333]
I was looking at the [Debian organisation page](https://liberapay.com/for/Debian/).
I can see the 18 last subscribed members on the page.
Reading from the beginning of the same page, it looks like there are 41 members subscribed.

How can I see a list of those 41 members?

Another related question, looking at the [organization exploration](https://liberapay.com/explore/organizations), I can't find the Debian one. How so?

**Comment by Changaco** [comment]
You confused organizations and communities. https://liberapay.com/for/Debian/ is a community so it's listed in <https://liberapay.com/explore/communities>, not in <https://liberapay.com/explore/organizations>.

It's not possible to see all the members of a community yet, pagination hasn't been implemented.

**Comment by trebmuh** [comment]
I didn't confused both but didn't clearly indicate it in my first message. Thanks for the disambiguation.

About the pagination not implemented, ok, I see now that my question was a duplicate of #511 .

thanks @Changaco
