### ISSUE TITLE
Accounts looking strange to me

### ISSUE THREAD

**Issue by trebmuh** [liberapay/liberapay.com#1342]
I was doing some researches about groups/people I might start to donate to sometime.

I've encountered some pretty strangish accounts such as:

- https://liberapay.com/mastodon./ (which looks a fake one trying to fish up people)
- https://liberapay.com/for/admin/ and https://liberapay.com/haha/ which looks to have been automated from some script maybe
- https://liberapay.com/openstreetmap/ which looks to hook up the well known "open street map" project name (and the linked "communities" also look to have been automated from a dysfunctional script)

@Changaco how to best deal with that?

**Comment by Changaco** [comment]
Those accounts all appear to have been created by security researchers coming from [HackerOne](https://hackerone.com/liberapay). I have put them in isolation so that they don't show up in search results.
