### ISSUE TITLE
Liberapay should supply ownership information.

### ISSUE THREAD

**Issue by NazcaLine** [liberapay/liberapay.com#1352]
Liberapay should supply ownership information.

**Comment by trebmuh** [comment]
@NazcaLine it's not clear to me what you are referring to. Could you please be more precise?

**Comment by adrelanos** [comment]
Who owns Liberapay? Who are the shareholders of Liberapay?

Well, it's a French nonprofit so it doesn't have shareholders. I guess it has a council and the councilors control Liberapay as per the foundation charter document.

More information about all of this would be interesting.

**Comment by hugoroger** [comment]
It has a great lead architect  but indeed no shareholders.

Em dom, 13 de jan de 2019 às 08:57, Patrick Schleizer <
notifications@github.com> escreveu:

**Comment by Changaco** [comment]
We already have links to https://github.com/liberapay/liberapay.org in [the homepage](https://liberapay.com/), [the about page](https://liberapay.com/about/) and [the feeds page](https://liberapay.com/about/feeds).
