### ISSUE TITLE
SEPA Direct Debit "The payment has been initiated."-page

### ISSUE THREAD

**Issue by jelv** [liberapay/liberapay.com#1358]
Problem: After starting a donation with SEPA Direct Debit you go to the "The payment has been initiated."-page. On this page you get the details to start donating with credit card, see screenshot. The Initiate the payment button is weird to see when you just started donating with SEPA Direct Debit.

Expected behaviour: Only get the confirmation and thank you message for donation.

!["The payment has been initiated."-page](https://user-images.githubusercontent.com/7106279/49143443-531e2e00-f2fb-11e8-897c-05186a99ceba.jpg)

**Comment by mattbk** [comment]
Same issue for PayPal:

![image](https://user-images.githubusercontent.com/3729038/49452764-61f75b80-f7a7-11e8-8e01-202e3e88e698.png)
