### ISSUE TITLE
Redundancy in strings

### ISSUE THREAD

**Issue by tuxayo** [liberapay/liberapay.com#1365]
These two strings are suspicious :)

https://github.com/liberapay/liberapay.com/blob/9f7d86b9a666b5ddacb578305b7420d72a28618a/emails/payin_sdd_created.spt

>  "This operation is being carried out based on {link_start}the mandate {mandate_id}{link_end} that you signed on {acceptance_date}, authorizing Liberapay (SEPA creditor {creditor_identifier}) to send instructions to **your bank to debit your account** and **your bank to debit your account** in accordance with those instructions.",

https://github.com/liberapay/liberapay.com/blob/e1f8f36aad2f4bb7e8005e018e599227ae6f07ac/www/%25username/giving/pay/stripe/%25payin_id.spt

>  "to **your bank to debit your account** and **your bank to debit your account** in "

**Comment by Changaco** [comment]
There's nothing wrong with these strings, they're just slightly verbose legal wording.

**Comment by tuxayo** [comment]
Oh, I see now it's two separate parts about what is authorized. Liberapay sending instructions and the bank to execute them.

Thanks :)
