### ISSUE TITLE
Federated libravatar should be supported

### ISSUE THREAD

**Issue by tastytea** [liberapay/liberapay.com#1367]
The key feature of libravatar is federation. Please add support for it. The necessary steps are roughly described in https://wiki.libravatar.org/api/ and the available libraries are listed in https://wiki.libravatar.org/libraries/.

**Comment by Changaco** [comment]
There is already an open PR for this: #1043.

**Comment by criztovyl** [comment]
I think this can be re-opened as a Feature Request now I closed my PR.
