### ISSUE TITLE
Add Ethereum Support

### ISSUE THREAD

**Issue by gjhklfdsa** [liberapay/liberapay.com#1375]
**Feature**: Add Ethereum Support
**How**? I would recommend utilizing [KyberNetwork](https://kyber.network/) for the transaction and exchange for fiat via [Bitpay](https://bitpay.com/), [CoinBase](https://commerce.coinbase.com/), or one one many alternatives.

Another, low-fee alternative would be to convert coins to [USDT](https://www.wikipedia.org/wiki/Tether_(cryptocurrency)) and allow withdraws for owner accounts. This leaves liquidation up to the account owner.

**Comment by MarionMoseby** [comment]
Doesnt give much confidence that the first line on wikipedias tether says: controversial

**Comment by lullis** [comment]
Is this being worked on? I am working on a [open source payment gateway solution for ethereum tokens](https://docs.hub20.io) and I would be very interested in contributing to this story.

**Comment by Changaco** [comment]
Closing in favor of #1994.
