### ISSUE TITLE
What is default admin username and password?

### ISSUE THREAD

**Issue by yocorn** [liberapay/liberapay.com#1380]
What is default admin username and password?

I created the new dev instance of Liberapay! I can't log in as admin!

**Comment by Changaco** [comment]
There isn't one, you have to create a normal account like you would do on the real website, then give it the admin privilege by modifying the database directly (`psql liberapay -c "update participants set privileges = 1 where username = 'your-admin-username'"`).

**Comment by yocorn** [comment]
Yeah Thanks, It's working!
