### ISSUE TITLE
Anti-freespeech or censorship resistant platform?

### ISSUE THREAD

**Issue by onpars** [liberapay/liberapay.com#1383]
I am wondering if it is worth to start contributing to and using your platform or if I am soon be part The Big Purge.

Are you more like SJW or more like gab.ai?

"Every organization that is not explicitly right wing will become left wing over time."

Can new people join your team, is your leadership elected by democratic vote? Is there a risk that the leadership is replaced by the censorship happy SJW?

Will you bow down to public SJW pressure and ban people they target lest they boycott you, or will you stand for freedom of speech?

What if mastercard, stripe, paypal or any other payment processor asks you to kick anyone from your platform?

Yes, this really happens. Patreon kicked someone because mastercard demanded it.

https://twitter.com/Patreon/status/1029551216886341634

Will you comply and kick the person? Or will you be censorship resistant, kick only people demanded by court order? Will you try to fight such cases of undue influence by payment processors in court?

What if I post in public something that nowadays is politically incorrect and considered worthy of deplatforming such as "trump is ok", "it's ok to be right wing", "it's ok to be white", "build the wall", "transsexuality is mental illness, gender dysphoria", "holocaust revisionism" or whatever ends up next on the list of forbidden speech? Will you use any such quotes as excuses to kick people from the platform?

**Comment by Changaco** [comment]
Liberapay cannot protect anyone from the decisions of underlying payment processors, [not even itself](https://medium.com/liberapay-blog/liberapay-is-in-trouble-b58b40714d82).

**Comment by nagybarnabas** [comment]
We understand that, but what we are asking is whether you will actively track our social media what we post like Patreon does?

**Comment by jorgesumle** [comment]
> what we are asking is whether you will actively track our social media what we post like Patreon does?

We don't have resources to follow every user, we just comply to the laws of the European Union. See [the legal page](https://en.liberapay.com/about/legal):

> Liberapay complies with the laws of the European Union. With the help of our partners we monitor transactions for possible fraud, money laundering, and terrorism financing. 

If by "free speech" you mean using Liberapay to finance antisemitism and white supremacy, don't even ask. Nazis have been banned here before, I cannot find the issue, but it's discussed somewhere and someone pointed to the French law if I remember correctly.

**Comment by nagybarnabas** [comment]
@jorgesumle The definition of "hate speech" is very ambiguous and is usually defined by the political elite. I'm not talking about antisemitism or white supremacy but even that you would have to define. How about anti-feminism, questioning history and historians, pointing out the crimes of the medical establishment, horrors of vaccines, cancer industry or abortion, or talking about flat earth?
