### ISSUE TITLE
Wrong german translation of month/months

### ISSUE THREAD

**Issue by qbi** [liberapay/liberapay.com#1384]
Liberapay shows the history of a user account and writes
> AccountX joined n months ago.

The german translation reads:
> AccountX ist vor n Monate beigetreten.

This should be _Monate**n**_ as in _AccountX ist von n Monaten beigetreten_.

https://github.com/liberapay/liberapay.com/blob/a6224617a7f7252e7f069e5af76ff4c2ad8e80ba/i18n/core/de.po#L2294

**Comment by Changaco** [comment]
I see, the German translation of "{n} months" can be either "{n} Monate" or "{n} Monaten" depending on the context.

```python
>>> website.locales['de'].format_timedelta(timedelta(weeks=-30))
'7 Monate'
>>> website.locales['de'].format_timedelta(timedelta(weeks=-30), add_direction=True)
'vor 7 Monaten'
```

**Comment by Changaco** [comment]
Same for Russian:

```python
>>> website.locales['ru'].format_timedelta(timedelta(weeks=-1))
'1 неделя'
>>> website.locales['ru'].format_timedelta(timedelta(weeks=-1), add_direction=True)
'1 неделю назад'
```
