### ISSUE TITLE
Ledger page doesn't explain `pending` status

### ISSUE THREAD

**Issue by LiamDawe** [liberapay/liberapay.com#1391]
I am curious what happens with pending payments? Had one listed as pending since the 16th, while another that same day went though.

**Comment by Changaco** [comment]
SEPA Direct Debits stay in the `pending` state for 5 days before being processed, whereas card payments are authorized and transitioned to `succeeded` immediately.

**Comment by Changaco** [comment]
Related issue: #1273.

**Comment by LiamDawe** [comment]
Ah thanks, yeah that needs mentioning.

**Comment by LiamDawe** [comment]
Now the related issue is solved, I assume there's no blocker on this now?
