### ISSUE TITLE
Show to users that they can cancel a donation at any time

### ISSUE THREAD

**Issue by RomainLalande** [liberapay/liberapay.com#140]
Bonjour,
Lorsque l'on a déjà une somme en réserve, la rétribution d'un projet ne demande pas de validation lorsque l'on clique sur "Donate", peut-être qu'un pop-up ou une page de confirmation permettrait d'éviter de financer par erreur.

Je ne sais pas si c'était volontaire alors dans le doute :-)

**Comment by Changaco** [comment]
Le don peut être stoppé à tout moment en remettant le montant à zéro, soit sur la page de don du bénéficiaire soit via https://liberapay.com/about/me/giving/, demander à l'utilisateur de les confirmer me semble donc peu utile. Par contre un bouton pour stopper le don ou un texte qui explique qu'il suffit de remettre le montant à zéro pourraient être pertinents.
