### ISSUE TITLE
Support actual recurring payments

### ISSUE THREAD

**Issue by davidak** [liberapay/liberapay.com#1400]
For sustainable financing of a project it is crucial to get recurring donations, since you have recurring costs!

As a donator, i also want to donate once a month since i get salary once a month, so i can predict it easily. Not like with the current system where i randomly get an e-mail to pay a high amount.

![screenshot from 2019-01-23 00-51-30](https://user-images.githubusercontent.com/91113/51767011-6d4a7180-20dc-11e9-9e9d-f21486e45f47.png)

It only makes sense here to pay a big amount at once right now to avoid high fees!

Small donations are not possible. That was one of the main features i liked about the old system since the balance of my bank account was negative, but i still wanted to show the projects, that i'm there to support them, even with a small amount, that might get bigger in the future, when i have more money again.

![screenshot from 2019-01-23 00-47-41](https://user-images.githubusercontent.com/91113/51767496-dd0d2c00-20dd-11e9-87cc-fbd33dc30b8d.png)

It don't makes sense to pay for 12 years support when i want to higher the amount in half a year!

So it's actually a one time payment. The current presentation and communication is confusing to users, like mentioned here https://github.com/liberapay/liberapay.com/issues/1205.

A project can just use PayPal to do that.

**What are your plans to support recurring donations in the future?**

Let me explain what recurring donations means for me: Money is transferred once a month (or week) from my bank account to the projects i want to support. (one-to-many transfer)

Not like it was before, not as it is now. (https://github.com/liberapay/liberapay.com/issues/1171) That's all not optimal.

I'm happy you survived the Mangopay Crisis and hope you are able to implement a perfect system in the future!

**Comment by Changaco** [comment]
> (one-to-many transfer)

This will soon be supported for donations to European users through Stripe, and someday for all donations through Stripe (I asked them, they're working on lifting the "same region" restriction).

**Comment by woj-tek** [comment]
>> (one-to-many transfer)
> This will soon be supported for donations to European users through Stripe

Could you shed some more light on this? Any relevant issue to follow (couldn't find one). It just struck me that recently when I wanted to donate my payments I was informed that actual payment would be split into two charges.

Basically it would be awesome to have recurring payments and, if they happen on same month, charge the card for a group of donations only once (to lower the fees impact).

**Comment by Changaco** [comment]
> Could you shed some more light on this?

One-to-many transfers to European Stripe accounts are now completely implemented (#1436, #1472, #1557).

**Comment by woj-tek** [comment]
I just made a donation to a couple of projects (3) and got a warning that due to _something something_ (sorry, can't remember the exact wording) they payment will be switched to 2 separate charges.

(I'm European and paid using Polish card, but I'm currently not in Europe, if that makes any difference)

**Comment by Changaco** [comment]
It doesn't matter whether you're European or not, the payments can only be grouped if the donation *recipients* have European Stripe accounts.

**Comment by davidak** [comment]
>and someday for all donations through Stripe (I asked them, they're working on lifting the "same region" restriction).

i asked about the status, for another project. here is their response

> > do you still have this "same region" restriction for one-to-many payments? what is the status? When can we expect it to be solved?
>
> Unfortunately **the restriction about the same region is still activated**, the platform and the connected account must be in the same country, I've checked the information and **we don't have a estimate date to lift this restriction** so far.
