### ISSUE TITLE
Can't connect to stripe

### ISSUE THREAD

**Issue by nagybarnabas** [liberapay/liberapay.com#1413]
See: https://cl.ly/13caf113a524

**Comment by Changaco** [comment]
This bug is now fixed.

**Comment by nagybarnabas** [comment]
Thank you! By the way, I sent an email to liberapay, days ago and no response. I was asking if they do censorship like Patreon or not?

**Comment by mattbk** [comment]
@nagybarnabas see the response to https://github.com/liberapay/liberapay.com/issues/1383.
