### ISSUE TITLE
CORS issues for language-specific subdomains.

### ISSUE THREAD

**Issue by dasj19** [liberapay/liberapay.com#1420]
Hi, I noticed that Firefox is unable to show the font glyphs on language specific domains like:
https://en.liberapay.com/ or any other language subdomain.
CORS does not allow the browser to load resources from liberapay.com.

![screen-dump-2019-01-31](https://user-images.githubusercontent.com/7589338/52057778-39e96600-2566-11e9-8795-3610c295c7b0.png)

**Comment by Changaco** [comment]
It's not a CORS issue, it's a side effect of Cloudflare's "Under Attack Mode".

**Comment by dasj19** [comment]
@Changaco okay... but Firefox reports it as CORS... 
Anyway... is there a nice way to fix it?

**Comment by Changaco** [comment]
Yes, but we would have to start paying Cloudflare $5/month to get extra Page Rules.

**Comment by Changaco** [comment]
I've collapsed two Page Rules into one and used the 3rd slot to fix this issue.
