### ISSUE TITLE
Press kit for creators?

### ISSUE THREAD

**Issue by unfa** [liberapay/liberapay.com#1425]
I'd like to promote my Liberapay profile on YouTube - I couldn't find an official "press kit" or "brand guidelines" - I think it's a good thing to develop this to help popularize Liberapay.

I have downloaded the Liberapay logo in SVG from the main page, though it'd be good to have this explicitly available somewhere in a ZIP. I'm a graphic designer so  I can handles this myself, but others might not be so lucky, and might need a PNG, JPG version etc...

What do you think?

**Comment by Changaco** [comment]
Yes, we're still missing a `/logos` page like <https://github.com/logos>.
