### ISSUE TITLE
Is it fine for me to promise and send gifts to my patrons?

### ISSUE THREAD

**Issue by unfa** [liberapay/liberapay.com#1428]
I'm new to Liberapay - setting it up as an alternative to Patreon.
As I am giving some rewards to my Patreon supporters, I'd also want to do the same for Liberapay ones aswell. So I have a question:

Am I allowed to offer gifts to supporters on Liberapay?

**Comment by Changaco** [comment]
No, rewards are currently forbidden by [the Terms of Service](https://liberapay.com/about/legal#terms).

**Comment by unfa** [comment]
Ok. I wasn't sure by reading the terms if it's prohibited, or just not facilitated.
May I ask what is the motivation behind that?
Could there be an option for this in the future?

**Comment by unfa** [comment]
Ok, I get this.

> The user agrees not to use the service for financial transactions that are not donations, notably those linked to the execution of a contract or a promise of recompense.

May I ask for the reasons behind this decision?

Is it fine for me to state publicly something along he lines of:
"If you support me on Liberapay, contact me via e-mail and you might receive a gift"

**Comment by Changaco** [comment]
Liberapay's initial mission was to facilitate donations, not to be a generic payment processor, so naturally our Terms of Service only allow donations. See <https://github.com/liberapay/liberapay.org/issues/23> and <https://github.com/liberapay/liberapay.org/issues/12> for possible evolutions of our mission and terms in the future.

Moreover, taxes are a barrier. Donations are generally considered to be outside the scope of VAT, but processing payments for services could put Liberapay in the position of having to collect VAT from patrons on behalf of creators, [like Patreon does](https://patreon.zendesk.com/hc/en-us/articles/205259549-How-does-VAT-work-on-Patreon-).
