### ISSUE TITLE
Donation renewal reminders aren't sent to users lacking a verified email address

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#1433]
This wouldn't be a problem if users confirmed their email addresses, but a lot of them don't: as of now we have 6054 active accounts with no verified email address, versus 8402 with at least one verified email. Once a user has missed the original verification email we don't do anything to help them rectify the problem.

A quick DB query suggests that we currently have 66 donors who need to renew their donations but haven't been notified by email. (SQL: `select count(*) from participants p where p.status = 'active' and p.email is null and p.is_suspended is not true and exists (select 1 from notifications n where n.participant = p.id and n.event = 'donate_reminder' and n.email_sent is false);`)

This issue is related to #61, because reducing the risk of spam is the reason why we don't send emails when the address isn't verified.

**Comment by mattbk** [comment]
> Once a user has missed the original verification email we don't do anything to help them rectify the problem.

If #61 is fixed (enabling a blacklist), I see no reason to not send maybe three separate emails asking for verification. This would be on par with other websites in my experience.

When an account it set up, is it very obvious that if you don't verify your email address, you won't receive emails, including notifications to renew donations? Could the email verification requirement be built in earlier?

**Comment by Changaco** [comment]
> When an account it set up, is it very obvious that if you don't verify your email address, you won't receive emails, including notifications to renew donations?

No, we don't mention the email verification process at all. Moreover the email we send doesn't mention what happens if the address isn't confirmed.
