### ISSUE TITLE
Clarify text on /donate when no payment methods are set

### ISSUE THREAD

**Issue by mattbk** [liberapay/liberapay.com#1438]
![image](https://user-images.githubusercontent.com/3729038/52503005-e0a6b580-2ba9-11e9-89a7-b72bf11e83bb.png)

(button is from #1366 in progress)

Next page:

![image](https://user-images.githubusercontent.com/3729038/52503174-5f9bee00-2baa-11e9-88b2-7dedc82dd3f0.png)

If no payment methods are set up for the tippee, submitting a donation here is halfway between pledging (which you do if the Liberapay account doesn't exist) and donating (which happens when you can actually send money). I think displaying this information would ease confusion, even after the addition of #1366.

Could we call these pledges, too? Or would that be too confusing?

**Comment by trebmuh** [comment]
What about graying out the page, and only keeping the explanation ("your donation to nikidoz... ...to receive money") ungrayed, then offering the user a "pledging" link?

**Comment by mattbk** [comment]
The current pledging system is only for external accounts that don't have a Liberapay account attached to them. I would be fine with using the same word for this on the front end, as long as we can distinguish between them when handling support.

I do agree that something visual should happen rather than just changing the wording.

The target page after you click the button should be different, too. Right now it dead-ends:

![image](https://user-images.githubusercontent.com/3729038/52508479-7f3b1280-2bba-11e9-96b4-c42dca684745.png)

But even if you pledge (which is further from actually giving money than giving money to someone who can't receive it), you end up at your own /giving page instead of a dead end.

**Comment by Changaco** [comment]
> Could we call these pledges, too?

Yes, but we need to treat them like pledges, which at the very least means sending proper notifications when payment becomes possible. I haven't gotten around to that yet. We may also want to move them to the Pledges section in the donor's Giving page, and possibly to the Unclaimed Donations page where the other pledges are listed.

**Comment by Changaco** [comment]
Oh, we also need to send notifications to the pledgees saying that they're missing out on donations. I actually have a local branch for this that I haven't pushed yet.

**Comment by Changaco** [comment]
Looks like we forgot to close this after merging #1366.
