### ISSUE TITLE
Not able to use bank account to transfer money

### ISSUE THREAD

**Issue by tusch001** [liberapay/liberapay.com#1466]
Hi, 

I wanted to put money in my account, 
on https://liberapay.com/~ACCOUNT NUMBER/giving/pay
I clicked on the right icon for money transfer (European accounts). 
On the next page (https://liberapay.com/~ACCOUNT NUMBER/giving/pay/stripe/?beneficiary=XXXXXX&method=sdd) I can enter my name, but the next field for IBAN is not accessible. I tried to deactivate noscript and allow all cookies, no change. 

Browser Firefox 65.0.2 on Windows 10

What I'm missing?

**Comment by Changaco** [comment]
The IBAN element is a hosted by Stripe, it can be difficult to enable when using browser extensions like NoScript or uMatrix, but if you whitelist the `stripe.com` and `stripe.network` domains and reload the page, then it should work.

**Comment by tusch001** [comment]
Thanks for the help. 
In fact my antivirus program thought it was a cross scripting attack. Whitelisted it.
