### ISSUE TITLE
400 & 404 pages : contact link have bad url (in french) (C to B) acout to about

### ISSUE THREAD

**Issue by sudwebdesign** [liberapay/liberapay.com#1468]
i found bug in 404 & 400 pages in link to contact (in french) https://liberapay.com/acout/contact ::: aBout
::: LOG ::: URL: https://liberapay.com/acout/contact
Referer: b'https://liberapay.com/sudwebdesign/edit/currencies'
Response code: 404
Response message: '' 
AND 1ST ERROR 
::: LOG ::: URL: https://liberapay.com/sudwebdesign/edit/currencies
Referer: b'https://liberapay.com/sudwebdesign/edit/currencies'
Response code: 400
Response message: 'Les paramètres demandés sont incohérents.'

**Comment by Changaco** [comment]
@sudwebdesign Thanks for the report.
