### ISSUE TITLE
Impossible to connect + no "forgot password" button

### ISSUE THREAD

**Issue by myriamboure** [liberapay/liberapay.com#147]
I tried to connect to my account this morning but it's not working, the login page just ignore my request, I got not error message, and there is no button "forgot password" (maybe I do a mistake but I don't know!). I can't connect ;-)

**Comment by Changaco** [comment]
Indeed we don't have a password reset procedure yet, and indeed our login form doesn't have error messages. I'll try to get this done today.

**Comment by Changaco** [comment]
Implementing password reset took me longer than expected (because I went down the rabbit hole of reposting form data), but it's pretty much done now and will be deployed tomorrow at the latest.

**Comment by myriamboure** [comment]
Thanks a lot @Changaco ! Kudos :-)

**Comment by Changaco** [comment]
Okay, password reset should be fully functional now. Let me know if it solves your problem @myriamboure. :-)
