### ISSUE TITLE
Requetss access to GitHub private repos?

### ISSUE THREAD

**Issue by greghendershott** [liberapay/liberapay.com#1483]
Hi. I'm a brand-new user. I have a question I didn't see in the FAQ or when I searched issues here.

I was going to connect my GitHub account and saw this:

> Liberapay by liberapay
> wants to access your greghendershott account
> 
> Organizations and teams
> Read-only access
>
> This application will be able to read your organization and team membership and private Projects.

I almost clicked OK, but noticed "**private** Projects". I stopped. I don't want to do that.

Is this as-intended?

**Comment by Changaco** [comment]
Hello @greghendershott. Liberapay doesn't need access to private repositories, but by asking GitHub for access to organizations we apparently get access to lists of private repositories. I don't think we actually get access to the repositories themselves though. Anyway, now that we've added support for incremental permissions we should be able to stop asking for read access to organizations by default.

**Comment by Changaco** [comment]
After testing, it looks like we don't actually need the `read:org` permission at all.

**Comment by Changaco** [comment]
The fix has been deployed.

**Comment by greghendershott** [comment]
I just tried it and it works perfectly. Thank you!

p.s. I was so sad to hear about Notre Dame today. :frowning_face:
