### ISSUE TITLE
Use the "preferred currency" option on /<team>/donate when the donor isn't logged in

### ISSUE THREAD

**Issue by alexgleason** [liberapay/liberapay.com#1494]
When donating to my team ([`/voadi/donate`](https://liberapay.com/voadi/donate)) from a logged-out browser, the currency is in euros:

![Screenshot from 2019-05-03 12 36 03](https://user-images.githubusercontent.com/3639540/57152333-3225a180-6da1-11e9-993d-476e7a6c6392.png)

**This is a big problem for me.** My donors are based in the US, and this GUI is a barrier of entry.

It is true you can change the currency, like so:

![Screenshot from 2019-05-03 12 38 49](https://user-images.githubusercontent.com/3639540/57152417-7c0e8780-6da1-11e9-8c96-974bd9852692.png)

But this has problems:

* It's hard to find.
* You have to reload the entire page. This is the part where I imagine people say "eh, whatever" and close the tab without donating.

## My suggestion

The team can choose a "preferred currency." If a user is logged out, just use the team's preferred currency. It's this setting:

![Screenshot from 2019-05-03 12 43 20](https://user-images.githubusercontent.com/3639540/57152309-1f12d180-6da1-11e9-9e61-3971ff822647.png)

This allows teams to have some control over the default currency shown for their donations page. The behavior for logged-in users stays the same (it takes the user's currency preference).

Thank you!

**Comment by Changaco** [comment]
The currency is (supposed to be) influenced by the visitor's location (country detected by Cloudflare based on the IP address), so a donor in the US should get the page in USD.

**Comment by alexgleason** [comment]
My IP address says I'm in: New York, United States (10118). I see euros. Sounds like location detection isn't working.

I like your solution. I think it would still be good to fall back to preferred currency if it fails. And it seems like it's failing quietly too, so maybe it should fail loudly (eg send you an email notification)?

**Comment by Changaco** [comment]
Both the country detection and the mapping of countries to currencies were broken. They're both fixed now and I've added regression tests for both. Moreover, the donation form will now fall back to the recipient's main currency if the visitor's currency can't be determined.

**Comment by alexgleason** [comment]
Amazing, thanks so much for taking care of this!!
