### ISSUE TITLE
Going back to default language after saving the translation of "presentation" in some other language 

### ISSUE THREAD

**Issue by EdaNano** [liberapay/liberapay.com#1514]
When I write a translated version of the "presentation" in a given language (in my example it was english) and that I click on save, I am automatically sent to to the project presentation in the default language of my liberapay account (in my case it was french). So one can think that the translated version failed to save, and is lost forever, which is not the case, if one chooses again the presentation in the language version that was just ment to be saved it is indeed saved, but why after saving getting back to the default language?

**Comment by mattbk** [comment]
I can confirm that this is the behavior. It looks like a bug.

**Comment by Changaco** [comment]
Thank you @EdaNano, this bug is now fixed.
