### ISSUE TITLE
Packages do not match the hashes from the requirements file

### ISSUE THREAD

**Issue by 1Jesper1** [liberapay/liberapay.com#1515]

**Comment by mattbk** [comment]
Is your issue related to https://github.com/liberapay/liberapay.com/issues/1457?

**Comment by 1Jesper1** [comment]
Yes, @mattbk

**Comment by mattbk** [comment]
Do you have any more details to add for your specific case?

**Comment by 1Jesper1** [comment]
Just using the docker compose setup from the master branch.

**Comment by techtonik** [comment]
#1568 fixes that.
