### ISSUE TITLE
Confirmation e-mail isn't generated correctly.

### ISSUE THREAD

**Issue by vertexclique** [liberapay/liberapay.com#1538]
I've just opened an account and can't validate or add any connections neither Paypal nor Stripe because generated email doesn't contain correct slug.

<img width="834" alt="Screenshot 2019-07-27 at 21 07 25" src="https://user-images.githubusercontent.com/578559/61998593-93b09000-b0b2-11e9-9590-3ac840db70d7.png">

**Comment by Changaco** [comment]
Confirmed. It's a regression from #1530. It only affects the initial email sent during account creation.
