### ISSUE TITLE
Remove "powered by Mangopay" from Website

### ISSUE THREAD

**Issue by MathiasRenner** [liberapay/liberapay.com#1558]
On the page to withdraw money from your wallet, it says "powered by Mangopay" at the bottom of the page: https://liberapay.com/[USER]/wallet/payout

Source code is here:
https://github.com/liberapay/liberapay.com/blob/master/www/%25username/wallet/payout/%25back_to.spt

Can this link to Mangopay be deleted since Stripe is there? It seems that there is a bunch of functions from Mangopay included here though.

**Comment by Changaco** [comment]
The presence of the Mangopay link and logo is not a mistake, direct withdrawals from wallets are still powered by Mangopay, like they've always been.

> In my case, for example, I have something like $0.93 left in a wallet but the minimum withdrawal amount is greater than that.

The solution for that is to donate the leftover funds to Liberapay via <https://liberapay.com/about/me/wallet/empty>.

Someday I'll work on emptying all wallets, one way or another, then I'll finally be able to start cleaning up Liberapay's source code by removing all the Mangopay stuff.

**Comment by MathiasRenner** [comment]
Thank you all to clarify this! Closing this issue...
