### ISSUE TITLE
Goal text isn't right when a user is above the goal already

### ISSUE THREAD

**Issue by mattbk** [liberapay/liberapay.com#1561]
![image](https://user-images.githubusercontent.com/3729038/64051817-19a47880-cb42-11e9-8de2-e5e5bcc77588.png)

https://liberapay.com/BallotBoxScot/donate

**Comment by biskwikman** [comment]
Hi, I'm interested in solving this and have gotten liberapay set up locally on my machine. Does anyone know where I might find the code that does controls this? Maybe in templates? Not used to working on apps this large.

**Comment by Changaco** [comment]
@biskwikman You can derive the file path from the URL: `/BallotBoxScot/donate` → `www/%username/donate.spt`.

(A generic search of the Git repository would also allow you to find the file: `git grep "they need your help"`.)

**Comment by biskwikman** [comment]
Thanks for the help, @Changaco . I have another question. How do I go about making it so a user I create is read as "receiving" by the system? I've tried pledging money from another account I make, but it doesn't seem to change to "receiving". I'm trying to recreate the issue mattbk has shown so I can see if my changes work. 

The picture below shows that even though the account I'm logged in as is donating to user "foo", they aren't shown to be receiving any donations, it still says "Be the first to contribute!"
![Screenshot from 2019-09-04 20-06-01](https://user-images.githubusercontent.com/17582234/64246210-bf475580-cf4f-11e9-8e83-5984a0e1376e.png)

**Comment by Changaco** [comment]
Only funded donations are included in the `receiving` amount, so the recipient has to have connected a payment account and the donor has to have completed the payment process. (Of course payments don't actually move any money in the development environment.)

Alternatively you can simply modify the simplate temporarily to simulate what you want, for example by adding the line `participant.set_attributes(receiving=Money('5.00', 'EUR'))`.

**Comment by biskwikman** [comment]
Thanks again @Changaco. I think I've basically got the issue solved. I currently have the following wording:

`name` currently recieves `receiving` per week, they have met their funding goal (`goal` per week). You can still help them out by contributing." Does anyone have any suggested changes to the wording? I've tried to just follow a similar format to the wording when the user hasn't met their funding goal. I've attached a screenshot of what it looks like in action.
![image](https://user-images.githubusercontent.com/17582234/64342732-7e723e00-d02e-11e9-878e-322a9e7305b2.png)

**Comment by trebmuh** [comment]
(_recieves -> receives_)

LGTM

**Comment by Changaco** [comment]
It looks fine to me. Here's a variation to consider:

> {username} currently receives {money_amount} per week. They have already reached their funding goal ({goal_amount} per week), but your donation would still help them.

**Comment by biskwikman** [comment]
Just created the PR above. Please let me know if I need to change anything. This is my first time contributing to something that's not my own repo.

**Comment by Changaco** [comment]
> This is my first time contributing to something that's not my own repo.

Congrats! :tada:

**Comment by mattbk** [comment]
Thanks @biskwikman!
