### ISSUE TITLE
botocore dependency needs to be updated

### ISSUE THREAD

**Issue by techtonik** [liberapay/liberapay.com#1566]
Installing base requirements gives this warning:
```
requests 2.21.0 has requirement urllib3<1.25,>=1.21.1, but you'll have urllib3 1.25.1 which is incompatible.
botocore 1.12.85 has requirement urllib3<1.25,>=1.20; python_version >= "3.4", but you'll have urllib3 1.25.1 which is incompatible.
```
Looks like `botocore` is really outdated - https://github.com/boto/botocore/blob/develop/CHANGELOG.rst

I am not sending this as a pull request, because I don't get how hashed in https://github.com/liberapay/liberapay.com/blob/master/requirements_base.txt are generated.

**Comment by mattbk** [comment]
Does this help? https://github.com/liberapay/liberapay.com/pull/1467#issuecomment-472118404

**Comment by techtonik** [comment]
@mattbk helped ALOT. =) Also added comment at the top for other contributors.

**Comment by techtonik** [comment]
PyPI doesn't update `boto3` dependencies - https://pypi.org/pypi/boto3/json and `hashin` can not process them. Something is wrong with either PyPI or `boto3` release process.

**Comment by techtonik** [comment]
Spend time to fill the issue with `boto3` - https://github.com/boto/boto3/issues/2111 - AWS should have resources to handle this, unlike me.

**Comment by Changaco** [comment]
@techtonik There's nothing wrong with the `boto3` packages, `botocore` is listed as a dependency in those packages.

**Comment by techtonik** [comment]
@Changaco if `botocore` was listed as a dependency, then `hashin` would detect it:
```
$ hashin -r requirements_base.txt boto3 -v -d
https://pypi.org/pypi/boto3/json
* Latest version for boto3 is 1.9.220
...
```
But there is nothing:
```
$ curl -s https://pypi.org/pypi/boto3/1.9.220/json | jq . | grep botocore
$
$ curl -s https://pypi.org/pypi/boto3/json | jq . | grep botocore
$ 
```

**Comment by techtonik** [comment]
Compare https://libraries.io/pypi/celery/4.4.0rc3/tree and https://libraries.io/pypi/boto3/1.9.134/tree

**Comment by Changaco** [comment]
@techtonik `hashin` doesn't look at dependencies at all, it's a simple tool that only downloads the packages you tell it to, computes hashes, and puts those in the requirement file.

**Comment by techtonik** [comment]
Then how does it know that `botocore` needs to be indented?

**Comment by Changaco** [comment]
It doesn't, the indentation is manual. As a matter of fact `hashin` doesn't even handle indentation properly.
