### ISSUE TITLE
[Bug] Broken Widget

### ISSUE THREAD

**Issue by MrTeeXD** [liberapay/liberapay.com#1596]
I don't know if I am implementing this widget wrong or it is broken but I cannot seem to get it on my Website.

Screenshot of the Widget in Question : 
![waterfox_x38ggF6TlK](https://user-images.githubusercontent.com/37266538/66706216-5ca45f00-ed30-11e9-8ca6-421705e1c766.png)

Screenshot of me trying to add it : 
![OsTAwOxpet](https://user-images.githubusercontent.com/37266538/66706261-a42aeb00-ed30-11e9-81d2-8561d739ce45.png)

**Comment by Changaco** [comment]
@MrTeeXD Unlike the simple button and shields, the "receiving" widget requires JavaScript.
