### ISSUE TITLE
Tempo

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#16]
Should Liberapay be weekly like Gratipay or should we switch to monthly?

**Comment by mattbk** [comment]
I like Gratipay because it's weekly.  In my mind, small amounts of money + fast tempo go together.

**Comment by Changaco** [comment]
The time has come to reopen this discussion.

A weekly tempo:

- means processing ~433% more money transfers and email notifications than with a monthly rhythm, so it hinders scalability (#908)
- is awkward to many people and makes the UI more complex, so it probably hinders adoption a bit

In order to switch to monthly we'd have to:

- decide on which day of the month payday would run, then update `create_payday_issue` accordingly
- modify the amounts of all existing donations (rounding down)
- update the standard donation amounts (#975)
- change the weekly graphs (e.g. the ones in <https://liberapay.com/about/stats>)
- make lots of other small changes (`git grep week`)

Opinions?

**Comment by Changaco** [comment]
Please vote on this in <https://github.com/liberapay/salon/issues/206>.
