### ISSUE TITLE
impossible to link to my mastodon account on hostux.social

### ISSUE THREAD

**Issue by fallen** [liberapay/liberapay.com#1602]
Your request has been rejected by our software. Please contact us if you need assistance.

'hostux.social ' is not a valid domain name.

If you decide to contact us please include the following debugging information in your message:

URL: https://liberapay.com/on/mastodon/redirect
Method: POST
Referer: b'https://liberapay.com/on/mastodon/redirect'
Response code: 400
Response message: "'hostux.social ' is not a valid domain name."

**Comment by Changaco** [comment]
Your account identifier was rejected because you accidentally put a space at the end. I've added whitespace removal in #1601 to avoid this issue in the future.

**Comment by jonnius** [comment]
I just stumbled upon this, too. Doesn't seem to be fixed yet on the production server.

**Comment by Changaco** [comment]
@jonnius This issue was fixed more than 2 years ago. Please post the debugging information from the error page, or send it via email to support@liberapay.com.

**Comment by jonnius** [comment]
[Example](https://liberapay.com/on/mastodon/@digitalcourage@digitalcourage.social%20/)

Debugging information:
```
URL: https://liberapay.com/on/mastodon/@digitalcourage@digitalcourage.social /
Method: GET
Referer: None
User-Agent: b'Mozilla/5.0 (X11; Linux x86_64; rv:97.0) Gecko/20100101 Firefox/97.0'
Time: 2022-02-10 11:20:56.335022+00:00
Response code: 404
Response message: "'digitalcourage.social ' ist kein gültiger Domainname."
Error location: models/account_elsewhere.py:368
User: <Participant #28075 'Jonius'>
Locale: de
Website version: 651
```
