### ISSUE TITLE
Are fully automated recurring payments possible?

### ISSUE THREAD

**Issue by MesoTRZ** [liberapay/liberapay.com#1616]
Hello,

I signed up for LP a month ago. A few people pledged a monthly amount and were charged the first month. But they weren't charged this month (2nd month) despite pledging a monthly amount.

I have contacted one of them and he said that he simply got an email reminding him to donate. Others have asked for a recurring donation system that is fully automated because they forget to donate manually or check their emails.

**Does LP simply work by reminding people to donate each month? so it's not fully-automated?**

**Comment by Changaco** [comment]
Hello,

Automatic debits aren't supported yet, I'm still working on implementing that feature (#483).

The recommended behavior is to pay for multiple months at a time. That usually results in lower percentages of payment processing fees.

**Comment by Changaco** [comment]
Automated payments are now possible. See https://medium.com/liberapay-blog/the-fourth-year-of-liberapay-bbb8563cfac8 for more information.
