### ISSUE TITLE
Account Avatar Errors

### ISSUE THREAD

**Issue by MrTeeXD** [liberapay/liberapay.com#1624]
So, when I try to get the Profile Pic from my Twitter, GitLab, GitHub, Mastodon, Twitch and Google, LiberaPay throws an Error saying that It is unable to fetch the Profile Pics from the Sites. Libravatar is having a fit so now my Profile Pic is blank. (P.S, my Twitter, Mastodon, GitLab, GitHub, Twitch and Google are connected)
![brave_Kld5GeE8Iy](https://user-images.githubusercontent.com/37266538/70000930-b53fed80-1564-11ea-9c01-f4074d4471fe.png)

**Comment by Changaco** [comment]
Probably a network error. I guess the 3 seconds timeout is too low.

**Comment by Changaco** [comment]
@MrTeeXD Please try again.

**Comment by MrTeeXD** [comment]
Failed, it still cannot get an avatar from my Twitter and for my connected accounts.

**Comment by MrTeeXD** [comment]
Ok, this si weird, I had to reconnect my Twitter and it worked. This needs to be fixed. Keep this issue open

**Comment by dchmelik** [comment]
Mine seems to say it's going to add it then doesn't (maybe because one colour?)

**Comment by stemy2** [comment]
I have the same problem when using libravatar as avatar source.
