### ISSUE TITLE
Not importing my public repos from GitLab

### ISSUE THREAD

**Issue by gloomytrousers** [liberapay/liberapay.com#1627]
I've linked my Liberapay account (https://liberapay.com/gloomytrousers) to my GitLab one (https://gitlab.com/gloomytrousers), which has 3 public repositories. However, Liberapay seems unable to import them (under Profile -> Repositories) - it I click the "GitLab" button, it just tells me
> A list of 0 repositories has been imported from your GitLab account, 0 minutes ago.
> No repositories found.

It's not a big problem personally (I doubt my boring repos are worth donating to) but it's not working as it should be.

**Comment by mattbk** [comment]
I am seeing the same thing with my linked GitLab account.

**Comment by rubdos** [comment]
Same on my liberapay account: https://liberapay.com/rubdos/ Is this because I also have private repositories lingering around?

**Comment by aggsol** [comment]
I found that Liberapay is only requests the `read_user` scop. I suspect the `read_repository` is required to list repositories.

**Comment by rakshazi** [comment]
Same issue here liberapay.com/rakshazi gitlab.com/rakshazi

**Comment by Changaco** [comment]
This bug is now fixed.

**Comment by gloomytrousers** [comment]
Confirmed now working. Thanks!
