### ISSUE TITLE
Broken Markdown Support

### ISSUE THREAD

**Issue by MrTeeXD** [liberapay/liberapay.com#1633]
So, I tried to utilise the Markdown support and well, it does not work. Here's a screenshot of Markdown used in the Statement area :
![brave_TIUpKN6MkG](https://user-images.githubusercontent.com/37266538/70658840-7f3af180-1c67-11ea-96ba-7dc2cb645db6.png)
And here is the Preview with Markdown
![brave_YbfRDsOt2b](https://user-images.githubusercontent.com/37266538/70658867-88c45980-1c67-11ea-878b-4197136d0a38.png)

**Comment by trebmuh** [comment]
`<h1>` and `</h1>` aren't markdown, they are HTML code.
Markdown is:
`# title 1`
`## title 2`
`### title 3`

**Comment by MrTeeXD** [comment]
Oops, I am stupid. Closing this issue
