### ISSUE TITLE
Cookies !

### ISSUE THREAD

**Issue by ValKphotos** [liberapay/liberapay.com#1634]
J'aimerai joindre mon compte liberapay et mon nouveau compte GitHub sans être obligée d'accepter d'ouvrir la porte des cookies : est-ce possible ? 
Merci !

**Comment by ValKphotos** [comment]
_

> URL: https://liberapay.com/on/github/associate?code=ea81738380237671cecc&state=yrXhrOyhbvjlFhsQreFoRfwh2mkm7S
> Method: GET
> Referer: None
> Response code: 400
> Response message: 'Missing cookie'

_

**Comment by Changaco** [comment]
La connexion d'un compte externe à un compte Liberapay nécessite un cookie temporaire, il n'est pas possible de faire autrement.
