### ISSUE TITLE
IBAN field is a div, not input field

### ISSUE THREAD

**Issue by Quix0r** [liberapay/liberapay.com#1637]
Hi, I have just confirmed my email address yet still I cannot enter my IBAN. I like to donate to a youtube-proxy website that runs without ads.

**Comment by Quix0r** [comment]
So I have to unblock `stripe.com` and `stripe.network` in `ublockOrigin`.

**Comment by Quix0r** [comment]
I cannot unblock in due to XSS/ClearClick protection by NoScript.

**Comment by Changaco** [comment]
NoScript's XSS warning is a false positive, you have to allow the request and whitelist the two Stripe domains.

**Comment by Quix0r** [comment]
Still I found it not really right, that an `<input>` tag is being loaded through JavaScript (I guess). Hmm, not so happy about it.
