### ISSUE TITLE
Stripe requests blocked by browser extensions

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#1640]
We used to detect third-party requests being blocked by a browser extension during payments, however this was “lost” when we moved from Mangopay to Stripe. The lack of any in-page error message is confusing for the user, e.g. #1637.

To fix this issue, [`js/stripe.js`](https://github.com/liberapay/liberapay.com/blob/master/js/stripe.js) needs to be modified to somehow detect the failure to load the Stripe resources and insert a warning message for the user into the page.

**Comment by Quix0r** [comment]
Or avoid it at all.
