### ISSUE TITLE
Better UI for deleting notifications and marking them as read

### ISSUE THREAD

**Issue by waldyrious** [liberapay/liberapay.com#1643]
Currently when I open the notifications page I see a button at the top saying "Mark all notifications as read", and each notification has an "X" in the top right, that deletes it if clicked. I clicked on a notification's "X" thinking it would mark it as read, and ended up deleting the notification instead. I think the UI for both features could be improved to avoid similar errors and just to make things clearer overall.

Regarding the "mark as read" feature, it should be possible to mark individual notifications as read from the main notifications page. One way to achieve this is to add a separate icon next to the "X" (say, a checkmark).

As for deleting notifications, IMO that should be better protected against mistakes (including misclicks!). For example:
- It should be clearer what the "X" will do, especially since it's a destructive action. This could be done by adding a tooltip.
- The X could me marked red instead of grey (or turn red on hover)
- There could be a confirmation dialog saying that the action is irreversible
- Even better, the action should be reversible, e.g. instead of disappearing outright, a deleted notification could be replaced with a notice explaining what happened and including a link to undo that action.

**Comment by Calinou** [comment]
Is deleting notifications useful in the first place, considering you can mark them as read? Maybe very old notifications could be hidden if they're read.

**Comment by Changaco** [comment]
I've already started working on hiding notifications instead of deleting them immediately, because for some types of notifications we check whether we've sent one like it recently, so by allowing the user to delete a notification we risk them receiving the exact same notification again, which is obviously confusing and problematic.
