### ISSUE TITLE
ledget/wallet missing consistency?

### ISSUE THREAD

**Issue by trebmuh** [liberapay/liberapay.com#1647]
![wallet-2018](https://user-images.githubusercontent.com/8705846/72017974-172bfb00-3267-11ea-9e1f-133dfd9e1264.png)
This 2018 wallet page displays the awareness about the wallet page note.

The 2019 and 2020 ones don't:
![wallet-2019](https://user-images.githubusercontent.com/8705846/72017977-172bfb00-3267-11ea-9f02-43758168b397.png)
![wallet-2020](https://user-images.githubusercontent.com/8705846/72017978-17c49180-3267-11ea-8623-c89e6427ba3e.png)

Wondering if it would be a good idea to have the same note on those too.

**Comment by Changaco** [comment]
This was done on purpose, since there isn't supposed to be any significant wallet activity after 2018.
