### ISSUE TITLE
Duplicate payment scheduled and executed automatically despite preexisting pending debit

### ISSUE THREAD

**Issue by tuxayo** [liberapay/liberapay.com#1731]
handle: tuxayo
permission to examine my account data: given

![Screenshot_2020-04-09_05-55-23](https://user-images.githubusercontent.com/2678215/78856349-d2ab2980-7a26-11ea-9d9f-4c2c00946763.png)

The huge planed payment in the past of 168€ seems to be a whole year of the fundings.
It was already renewed yesterday with a ~45 € debit initialed to cover ~3months.
I was many months late in the renewal.

Is the result on the screenshot expected?
It mostly about display and confusion. It's clear to me that even with automated payments enabled since yesterday, no huge debit will be made.

**Comment by tuxayo** [comment]
The timing is perfect, after posting this message.I got and email telling me that a 168€ debit is planed.

Liberapay notification id: 87635

If stopping this could cause significant fees for Liberapay, we can let it pass. Which would mean that not automated payment will be triggered before more than a year right?

**Comment by Changaco** [comment]
I see the problem: when you turned on automatic renewals, a new payment was scheduled, even though there was already a pending debit. Clearly the scheduler needs to be modified to check for pending payments, I just have to figure out the implementation details.

Stripe doesn't support cancelling SEPA direct debits, however once the payment has been settled I will be able to refund it.

**Comment by tuxayo** [comment]
Thanks for fixing the title ^^"

**Comment by tuxayo** [comment]
> Clearly the scheduler needs to be modified to check for pending payments, I just have to figure out the implementation details.

It's based on a one year period it seems. Is it based on my manual payments?

**Comment by tuxayo** [comment]
> Stripe doesn't support cancelling SEPA direct debits, however once the payment has been settled I will be able to refund it.

If the scheduler uses a one year period, then it won't change much, you can leave as it is. As long as Liberapay keeps track for this: 3 months + 1 year worth payments will be done.

**Comment by Changaco** [comment]
For each donation, the scheduler uses the amount of the previous successful payment. When multiple donations are grouped, those amounts are simply summed.

**Comment by tuxayo** [comment]
> when you turned on automatic renewals, a new payment was scheduled

Note in case that helps, automatic renewals turned on many hours before this issue was open and the screenshot taken.

**Comment by tuxayo** [comment]
> For each donation, the scheduler uses the amount of the previous successful payment. When multiple donations are grouped, those amounts are simply summed.

ok, I'll try in the future to disable automatic renewal of my "EUR debit cluster" (if that's a good way to name it) to make one manual payment for 3 months and then switch back to automated.

I hope it don't cause chaos with this ^^"

Or maybe I hope so! Bugs are better be found by people reporting them before they hit "innocent people" ^^

**Comment by tuxayo** [comment]
At 5:05 UTC+02:00 I got an email like (rough translation)
> [reminder that 168 € will be debited on the 14 february]


Should I open an issue about the date being wrong?

**Comment by Changaco** [comment]
> Should I open an issue about the date being wrong?

No, #1735 fixes that as well.

**Comment by Changaco** [comment]
@tuxayo I'm seeing a second €168 debit initiated today. I'm not sure yet why that happened and whether #1735 fixes that bug as well or not.

**Comment by Changaco** [comment]
I've initiated the refund for the first €168 debit.

**Comment by Changaco** [comment]
… and the refund for the second €168 debit.

**Comment by Changaco** [comment]
I found another donor who has a duplicate automatic charge. I've initiated a refund for that €12 debit as well.

**Comment by Changaco** [comment]
I think #2004 finally fixed the scheduling problem, and #2011 added a check to prevent the execution of a scheduled renewal when there is a pending payment, so this issue can finally be closed.
