### ISSUE TITLE
libravatar not connecting

### ISSUE THREAD

**Issue by Philippgr06** [liberapay/liberapay.com#1740]
Hello,

I just tried to connect a (newly created libravatar) account to liberapay and it does not work. I am not entirely sure if this is an inssue with libravatar or liberapay. I don't see how to verify that libravatar service is indeed working (that the uploaded image can be used anywhere). 

Are there any issues with this at the moment?

Thanks

**Comment by Changaco** [comment]
The problem doesn't seem to be on our side.

You can use [Libravatar's check tool](https://www.libravatar.org/tools/check/) to look up the avatar for your email address.

If you've set up your account correctly, then [your Libravatar profile](https://www.libravatar.org/accounts/profile/) should look something like this:

![Screenshot of my Libravatar profile page](https://user-images.githubusercontent.com/1581590/79241126-eb766d80-7e72-11ea-8b6b-7d4d40e3100c.png)

**Comment by Philippgr06** [comment]
your photo enabled me to realise that I have to add an email address even though my account already has an email address... thank you.
