### ISSUE TITLE
Bad Request error when changing email address

### ISSUE THREAD

**Issue by BlackWinnerYoshi** [liberapay/liberapay.com#1753]
I have tried to change my email address on Liberapay to _liberapay@blackwinneryoshi.anonaddy.com_ and it gave me this error:

> URL: https://liberapay.com/BlackWinnerYoshi/emails
> Method: POST
> Referer: b'https://liberapay.com/BlackWinnerYoshi/emails'
> Response code: 400
> Response message: "Missing key: 'resend'"

How do I fix the problem?

**Comment by Changaco** [comment]
That's a bug in our code, sorry. Please try again, I've applied a temporary patch.
