### ISSUE TITLE
Connecting GitHub organization fails when membership is private

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#1757]
A private member of a GitHub organization can't connect it to a Liberapay account, because we stopped asking for the `read:org` permission in #1484. The error page shown to the user, for example <https://liberapay.com/on/github/liberapay/failure.html?error=CantReadMembership>, hasn't been updated accordingly.

**Comment by kaiyou** [comment]
I can confirm setting the Github team membership to public fixes the issue. Thank you very much for investigating this!
