### ISSUE TITLE
CTRL+click should open in a new tab

### ISSUE THREAD

**Issue by thibaultmol** [liberapay/liberapay.com#1765]
Hi,

I was going to trough all the top organizations and picking some out that I wanted to support,
So I was trying to CTRL + click on them to open each one in a new tab, but it ust loads it in the name tab which was annoying
https://liberapay.com/explore/organizations 

Cheers,
Thibault

**Comment by jorgesumle** [comment]
I can reproduce it on Firefox when JavaScript is enabled. Until we fix it, you can right click and "open link in new tab".

**Comment by thibaultmol** [comment]
Yeah, forgot to mention i was on Chrome beta on a Chromebook xd
And doing a click with 3 fingers also seems to work as a workaround
