### ISSUE TITLE
Allow custom amount from GET parameter in donation form

### ISSUE THREAD

**Issue by Siltaar** [liberapay/liberapay.com#1790]
Bonjour, j'avais envie de proposer aux utilisateurs de Meta-Press.es de faire un don d'un centime par résultat trouvé lors d'une recherche (enfin, de résultats effectivement rappatriés).

Du coup, je regardais la page : https://liberapay.com/Meta-Press.es/donate et je rêvais qu'il soit possible d'ajouter un paramètre à l'URL pour pré-remplir le champs Custom amount…

J'aurais alors fait un lien du genre : 
- https://liberapay.com/Meta-Press.es/donate?amount=3.14

Pour proposer un don personnalisé de 3,14€ 

C'est amusant comme idée non ?

**Comment by trebmuh** [comment]
For the non-French readers:

----

Hello, I wanted to propose to Meta-Press.es users to donate one cent per result found during a search (well, results actually returned).

So, I was looking at the page: https://liberapay.com/Meta-Press.es/donate and I dreamed that it would be possible to add a parameter to the URL to pre-fill the Custom amount field...

Then I would have made a connection like this:

- https://liberapay.com/Meta-Press.es/donate?amount=3.14

To propose a personalized donation of 3,14€.

It's a fun idea, isn't it?

**Comment by Changaco** [comment]
This is now supported. However, an amount by itself is ambiguous, so you have to specify the currency too, e.g. https://liberapay.com/Meta-Press.es/donate?amount=3.14&currency=EUR

**Comment by Changaco** [comment]
The amount is assumed to be weekly unless another period is specified. The other `period` values are `monthly` and `yearly`. For example: https://liberapay.com/Meta-Press.es/donate?amount=3.14&currency=EUR&period=monthly

**Comment by Siltaar** [comment]
Well, I'll have to divide the amounts by 1000 instead of 100…

**Comment by trebmuh** [comment]
@Changaco what would be the best place to document this? [The FAQ page](https://liberapay.com/about/faq) maybe?
