### ISSUE TITLE
Inconsistent language for receipts

### ISSUE THREAD

**Issue by tuxayo** [liberapay/liberapay.com#1793]
I had them in a language that was not the one I need to show them to the tax administration (if I need to someday) so I changed my Liberapay and browser requested language to french but part of receipts are still in english.

examples:
https://fr.liberapay.com/tuxayo/receipts/direct/2260 => english
https://fr.liberapay.com/tuxayo/receipts/direct/2259 => french

**Comment by Changaco** [comment]
Receipt translations are all-or-nothing. If any word can't be translated, then the whole page is reverted to English.

The French translation is complete, but the word "PayPal" isn't in it because it's not marked for translation, so receipts for donations through PayPal always fail the translation.
