### ISSUE TITLE
Implement k-anonymity for password-based sign up.

### ISSUE THREAD

**Issue by EdOverflow** [liberapay/liberapay.com#1795]
It would be nice to cross-check passwords in breaches during the sign-up and password-reset process. This is in similar vein to #1001: the goal being to ensure good password hygiene.

Resources:

- https://haveibeenpwned.com/API/v2#PwnedPasswords
- https://en.wikipedia.org/wiki/K-anonymity#Hash_Based_k-Anonymity

**Comment by Changaco** [comment]
Duplicate of #986.

**Comment by EdOverflow** [comment]
![](https://media.giphy.com/media/Ra1bmpxpsppNC/giphy.gif)
