### ISSUE TITLE
Twitter avatars are blocked by Firefox's tracking protection

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#1797]
We should probably add a warning about that in https://liberapay.com/about/me/edit/avatar

**Comment by Urahara** [comment]
What about using some referrer hide? Like https://nullrefer.com/?

**Comment by prcmt** [comment]
Or fetch avatars from [Nitter](https://nitter.net/)? Not sure how they'd feel about that though.

**Comment by Changaco** [comment]
Using Nitter could be a good temporary solution. The Liberapay org can start donating to https://liberapay.com/zedeus in return.
