### ISSUE TITLE
Custom donation edit field overides previous donation selection.

### ISSUE THREAD

**Issue by rkingett** [liberapay/liberapay.com#1826]
Using [NVDA, a free screen reader
](http://www.ninite.com/nvda/) When a user clicks, donate, they are taken to the amount page where you select the amount and duration.

Screen reader users navigate by keyboard exclusively, so this impacts sighted keyboard users as well.

When navigating via keyboard, the second that, other, edit box is focused on, that radio button gets selected, even if you previously chose another radio button.

The ideal solution would be that edit field does not change your previous selection. Keyboard users will select, other, if they want to input a custom amount.

**Comment by Changaco** [comment]
I can't reproduce this problem using keyboard navigation in Firefox and Chromium.

The donation form is designed to only select the "Custom" option automatically if the user clicks on it, or inputs something in the amount box, or selects one of the three period options; it's not designed to automatically select "Custom" when the amount input gets the focus.

**Comment by rkingett** [comment]
I'm a screen reader user primarily, so am unsure of how to reproduce this without downloading NVDA.

But after I select a radio button, and enter focus mode, moving between the radio buttons with up and down arrows, when I hit tab to go to the next set of radio buttons, the edit box gets focused. When that happens, the radio button, other, is selected, even though I didn't enter anything into the edit box. I just tabbed there, and tabbed away from it.

**Comment by Changaco** [comment]
@rkingett I've deployed some changes, let me know if they didn't fix the problem.
