### ISSUE TITLE
Making the Liberapay site visually attractive

### ISSUE THREAD

**Issue by Calinou** [liberapay/liberapay.com#183]
Currently, the Liberapay site does not have much identity. It uses the default Bootstrap 3 theming, which is quite bland. Upgrading to Bootstrap 4 (which will be released possibly this year) will make it look a bit more "current", but it still won't give the project much identity.
## What could be improved
- Images/gradients 
  - Primarily as "jumbotron" background, to give the site a more visual feel. Of course, the image shouldn't be too heavy in file size.
- Fonts
  - Font families, sizes, rendering
- Colors
  - To give the site more identity: needs a color palette first. This brings us the question, "what would be the color(s) of Liberapay?"
- Animations and transitions
  -  Some subtle animations make for a better user experience, telling the user where to go more clearly

I could work on this if desired. I have some HTML/CSS experience, having worked on sites like [minetest.net](http://www.minetest.net/) or [godotengine.org](http://godotengine.org/).

For future reference, here's a screenshot of the current website:

![Liberapay.com screenshot](https://lut.im/nvoUrqKSkv/BlWOYK5FFknL78NY.png)

**Comment by Changaco** [comment]
Hey @Calinou, welcome. :-)

I agree with all your improvement ideas:

- Yes, Liberapay would be better with some kind of background illustration to put on the homepage and on our twitter/facebook/etc accounts. I like [Snowdrift](https://snowdrift.coop/)'s animated drawing, but Liberapay is more generic and I'm not sure how to explain it with a drawing. The comic at the top of [this blog post](https://medium.com/@nayafia/what-success-really-looks-like-in-open-source-2dd1facaf91c) is also a nice illustration of the primary problem Liberapay is trying to solve. Another possibility is images of people happily working in shared spaces or outside in a sunny day, evoking team work and freedom, though that's all a bit stereotypical.
- Yes, a less-widely-used font could be useful. I'll probably only agree to switch to a free one though.
- Yes, we need a colour palette, unfortunately I still have no idea. Feel free to make propositions.
- I'm fine with adding some animations/transitions, I hadn't thought of that.

Although I don't think insufficient visual identity is Liberapay's biggest problem right now, help on all this is indeed desired, so feel free to contribute. ;-)

**Comment by Changaco** [comment]
Screenshot of Snowdrift's homepage illustration, FTR:

![snowdrift-2016-02-24-homepage-illustration](https://cloud.githubusercontent.com/assets/1581590/13282181/06cbed18-dae8-11e5-8727-1e0fa76079fd.png)

**Comment by Changaco** [comment]
And the aforementioned comic:

![comic](https://d262ilb51hltx0.cloudfront.net/max/800/1*Q_8HbGbbfEmAjwPqB8D60A.png)

**Comment by Changaco** [comment]
Also FTR, this is what Liberapay looked like before #154:

![liberapay-v1](https://cloud.githubusercontent.com/assets/1581590/8159037/42b52fb2-1363-11e5-9b63-068244d53251.png)

**Comment by Changaco** [comment]
@Calinou If you decide to contribute let me know, I'll add you to the GitHub org so you can work in branches here instead of in a fork.

**Comment by Calinou** [comment]
Also I've noticed a small usability issue in the registration process on the website. There is no password confirmation field (which is fine), but there's no way to display the password (eg. by holding a checkbox) to make sure you typed it right.

**Comment by MartinDelille** [comment]
This studio distribute logo refused by its clients: http://www.logodust.com/

**Comment by Changaco** [comment]
Open source fonts showcase: http://open-foundry.com/

**Comment by pgno** [comment]
Hello, 

Just find this issue as i had already started to think about contributing to the Liberapay UI. Don't know if some work has already been done but i can share a few ideas about logo, font and widget.
All is really simple : 
- font for heading is Ubuntu, font for text is Open sans
- logo is just the letter "lp" in Ubuntu Bold Italic font
- tried 2 colors. The "upper" one is my favorite but i've noticed latter that it could be too close from tipeee ? So there's an alternative.

Let me know if you find any kind of interest to this work. It's not really fancy (i'm no graphic designer) but it's a bit more 'in the trend". It could be easily applied to the current website without many changes in the stylesheet (i've made a few tests).
![widget_lp](https://cloud.githubusercontent.com/assets/18536610/14910637/86289cc0-0def-11e6-885a-cc3c693c284d.jpg)

**Comment by Changaco** [comment]
@pgno That's great, thanks! :-)

The first color does look a lot like Tipeee, and the second one isn't very eye-catching, so a third option would be nice.

As always pull requests are very welcome.

> - logo is just the letter "lp" in Ubuntu Bold Italic font

Then we need to look at the [Ubuntu Font License](http://font.ubuntu.com/licence/).

**Comment by Calinou** [comment]
From that page:
> The Ubuntu Font Family is presently distributed under the Ubuntu Font Licence. This means you can use the font in much the same way as you would use any other font (open or proprietary). The open means that in the long run, the font can continue to be expanded, because the raw source code (design files) for the font itself are available to those who are interested.

> You are most welcome to use the Ubuntu Font Family, in your documents, graphic designs, **logos**, or company stationary. We'd like as many people as possible to have a better quality reading experience everyday.

**Comment by Changaco** [comment]
Yes, after reading the license I concur that we can use the font in a logo.

**Comment by Changaco** [comment]
Leftover TODO item from #330:

- [ ] customize Bootstrap's colors https://getbootstrap.com/customize/

**Comment by Changaco** [comment]
Screenshot of the homepage FTR:

![liberapay-2016-05-21-homepage](https://cloud.githubusercontent.com/assets/1581590/15449019/56dead76-1f72-11e6-8332-4ffd6c03b8c0.png)

**Comment by MartinDelille** [comment]
I'll be happy to try some color scheme with the new brand color. Basically, it seems we need to add a config.json file, but I don't understand well how bootstrap is used.

I understood that we need to serve the config.json file at the root of the bootstrap root, am I right?

**Comment by Changaco** [comment]
Simply adding a `config.json` won't do anything, it's just a file that can be used to download a custom build of Bootstrap.

**Comment by Changaco** [comment]
FTR, a screenshot of the top of the homepage (taken yesterday):

![liberapay-2017-02-02-homepage-1024x900](https://cloud.githubusercontent.com/assets/1581590/22591320/472a52b4-ea14-11e6-8c78-1b5caf9ef52c.png)

**Comment by Changaco** [comment]
Closing in favor of #734.
