### ISSUE TITLE
Headpats as payment method

### ISSUE THREAD

**Issue by koyuawsmbrtn** [liberapay/liberapay.com#1831]
I don't know, would be fun to have

**Comment by trebmuh** [comment]
What's Headpats?
Link please.

**Comment by koyuawsmbrtn** [comment]
> What's Headpats?
> Link please.

https://youtu.be/gjIHwil0cqk

**Comment by trebmuh** [comment]
I there something to understand? If so, I don't get it.

**Comment by koyuawsmbrtn** [comment]
> I there something to understand? If so, I don't get it.

Well headpats are a great payment method. Better than money ;)

**Comment by trebmuh** [comment]
In which place of the world are you able to pay a rent with headpats?

**Comment by koyuawsmbrtn** [comment]
> In which place of the world are you able to pay a rent with headpats?

That depends on your landlord

**Comment by trebmuh** [comment]
Liberapay is a serious project whose aim is to enable those who create commons to be able to make a living out of it.I think you're saying more and more nonsense in this thread, it doesn't serve the liberapay project, so I'm going to stop this pseudo-conversation here.
