### ISSUE TITLE
Donating with PayPal: Cannot add note 

### ISSUE THREAD

**Issue by CanIGetaPR** [liberapay/liberapay.com#1838]
It can be useful for donators to add a note alongside their donation, such as to communicate who they are.

**Comment by rkingett** [comment]
Agreed. This would be useful.

**Comment by revi** [comment]
> such as to communicate who they are

Our original implementation was originally built arount anonymous donation platform (and it was until we were kicked out of previous payment processor), so while we are stuck on PayPal (because for example Stripe isn't available in my domicile) I don't think we want to enable such.

**Comment by Changaco** [comment]
Like @revi said, donations are supposed to be anonymous. Unfortunately, donations through PayPal currently aren't anonymous: recipients see the names and email addresses of donors.

The existing issue about lifting anonymity is #271.
