### ISSUE TITLE
The payment failed.

### ISSUE THREAD

**Issue by davidak** [liberapay/liberapay.com#1841]
I have initiated 2 direct debits yesterday and wanted to do one more today to renew donations, but got an error. I retried again with same result.

> The payment failed. Error message: “An unknown error occurred (request ID: req_I4Y7dUq3l2LZpu)”

Am i limited to 2 sepa payments at a time or is there a problem with my account?

Why do i have to make 7 separate payments in the first place? I thought Stripe supports combined payments. It's not very transparent what's going on.

**Comment by Changaco** [comment]
The error message is from Stripe. I sent them an email about this problem 3 weeks ago, but they still haven't fixed it.

The bug is specific to SEPA direct debits and can be avoided by paying with a card or through PayPal.

> Why do i have to make 7 separate payments in the first place? I thought Stripe supports combined payments.

Stripe only allows us to combine payments to creators in Europe.

**Comment by Changaco** [comment]
Message from Stripe support:

> Hi there,
>
> I want to follow up here to provide an update that this issue is on the team's radar and that they will be updating the error code and message to better illustrate the problem as you noted.

In other words, SEPA direct debits still won't work for payments to Canadian creators, but the error message will be restored, so our software should once again be able to recognize it and ask the donor to use of a different payment method.
