### ISSUE TITLE
Migrate away from Mandrill

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#187]
http://blog.mandrill.com/important-changes-to-mandrill.html

> Going forward, all Mandrill users will be required to have a paid monthly MailChimp account

I was fine with using Mandrill for free to be able to launch Liberapay faster by not spending time on figuring out another solution, but I won't pay for MailChimp account.

**Comment by Changaco** [comment]
The easiest solution would be to move to [Mailgun](http://www.mailgun.com/), which offers 10,000 free emails per month.

The second solution is to send emails through my personal server like we already do for the support@ address. I'm leaning towards this.

The third solution is to build our own open source service to replace the proprietary solutions. Obviously that would be great but it's more work and I've already embarked on a journey to fix Aspen this year in addition to working on Liberapay, so I don't have much spare time.

**Comment by yepher** [comment]
You can consider SparkPost too. They allow 100,000 email/month for free.

Here is the Mandrill migration to SparkPost [guide](https://www.sparkpost.com/mandrill-migration-guide) and this Slack channel is available if you need help with the migration 
    http://slack.sparkpost.com

**Comment by revi** [comment]
Just beware it's a week and more left before the change goes to the world.

**Comment by Changaco** [comment]
Thanks for the reminder @revi, Mandrill has been sending us reminders via email too. I plan to get this done before next week's payday.

**Comment by Changaco** [comment]
I've found several possible libraries to handle the SMTP stuff for us, here are the three I deem best for our use case, ordered from simplest to most complex:

- [MailShake: Dramatically simplify sending email from your python app.](https://github.com/jpscaletti/MailShake)
- [python-emails: Modern python library for emails](https://github.com/lavr/python-emails)
- [marrow.mailer: A highly efficient and modular mail delivery framework for Python 2.6+ and 3.1+, formerly TurboMail.](https://github.com/marrow/mailer)

**Comment by Changaco** [comment]
I've set up DKIM, it seems to be working (sent a test message to a gmail address).

**Comment by Changaco** [comment]
Done. Should we send an email to our users via Mandrill warning them that our future messages may end up in their spam folder?

**Comment by Changaco** [comment]
https://twitter.com/liberapaye/status/722662836372004864

> We have migrated away from @mandrillapp. If an email from us fails to arrive in your inbox, check your spam folder.

**Comment by Changaco** [comment]
We have a bounce:

> [redacted]@live.fr: 550 SC-001 (BAY004-MC5F10) Unfortunately, messages from 5.135.153.125 weren't sent. Please contact your Internet service provider since part of their network is on our block list. You can also refer your provider to http://mail.live.com/mail/troubleshooting.aspx#errors.

So it's Microsoft's fault that the email infrastructure has been centralized.

**Comment by Changaco** [comment]
https://twitter.com/Changaco/status/722712691773718528

> Email, an important part of the Internet, is broken. You probably don't know about it, and nobody seems to care, not even the @ietf.

**Comment by Changaco** [comment]
Okay, so, what shall we do?

**Comment by Changaco** [comment]
:disappointed: For the time being I've piped our outgoing emails through Mailgun.
