### ISSUE TITLE
no visable way of deleting a team

### ISSUE THREAD

**Issue by harcesz** [liberapay/liberapay.com#1874]
Created a team, decided it doesn't solve my need, but it's unclear how to delete it and release the username. Leaving the team (only member), seems to just lock it.

**Comment by Changaco** [comment]
What you wanted to do isn't implemented yet (relevant issue: #1692). I can delete the team for you if you give me its name.

**Comment by harcesz** [comment]
Missed the notice, account (groups) name is "szmer", thanks!

What I was really aiming to do, was creating a way for a project to get money, without exposing particular people who are in the group. I can imagine it sounds dodgy, but there are be legitimate reasons for that. Also, not always there's a simple way the money might be divided. In this case everything goes towards hosting, and possibly financing external developers, and is processed by a single person, so an "externally anonymous" account should solve it.

**Comment by Changaco** [comment]
I've deleted the "szmer" team.

**Comment by harcesz** [comment]
tanks!
