### ISSUE TITLE
Add Payoneer

### ISSUE THREAD

**Issue by MrTeeXD** [liberapay/liberapay.com#1896]
I really wish I could connect my Payoneer to Liberapay and I want to explain why: Unfortunately at the moment for me since I am a resident in South Africa and Paypal for some reason does not support my bank which is a bit of a shame. I recently come across Payoneer and when I first created a account, I was able to link my Bank with no issues whatsoever and I am able to withdraw funds directly to my bank. By adding Payoneer to Liberapay, you allow me to be able to transfer funds from Liberapay directly to my bank.

**Comment by trebmuh** [comment]
See #1280 and #1368.

**Comment by MrTeeXD** [comment]
Closing as its a duplicate
