### ISSUE TITLE
Problème pour ajouter mon compte paypal : déjà utilisé par une autre compte utilisateur, pourtant fermé

### ISSUE THREAD

**Issue by mekkagodzilla** [liberapay/liberapay.com#1902]
Bonjour,
Sur mon compte liberapay actif : 5746
Je n'arrive pas à ajouter mon compte paypal. On me dit qu'il est déjà utilisé sur un autre compte liberapay, or il me semble avoir fermé mon autre compte potentiel, dont l'email était philippe.lemaire@protonmail.com

de même, dans le compte que je souhaite conserver, le 5746, je ne peux ajouter mon email philippe.lemaire@protonmail.com.

Je soupçonne qu'une solution simple serait de complètement supprimer mon autre compte, inactif, dont le login est actuellement philippe.lemaire@protonmail.com. J'ai fermé le compte, mais ça semble insuffisant.

Merci pour votre aide.

**Comment by Changaco** [comment]
J'ai modifié l'adresse email du compte fermé, ça devrait te permettre de l'ajouter au compte actif.

> Je soupçonne qu'une solution simple serait de complètement supprimer mon autre compte

La suppression totale d'un compte qui a été actif dans le passé n'est pas (encore) possible.
