### ISSUE TITLE
i can't get code from my email

### ISSUE THREAD

**Issue by zmtzawqlp** [liberapay/liberapay.com#1904]
i can't get code from zmtzawqlp@live.com,

**Comment by Changaco** [comment]
The email address you mentioned is no longer connected to any Liberapay account, most likely because you removed it after adding another one.

**Comment by zmtzawqlp** [comment]
I removed it because I can’t get any info even liberapay tell me  has sent email.

And I can’t add zmtzawqlp@live.com<mailto:zmtzawqlp@live.com> back now.

Can you please help me

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Charly C.<mailto:notifications@github.com>
发送时间: 2020年10月29日 16:38
收件人: liberapay/liberapay.com<mailto:liberapay.com@noreply.github.com>
抄送: zmtzawqlp<mailto:zmtzawqlp@live.com>; Author<mailto:author@noreply.github.com>
主题: Re: [liberapay/liberapay.com] i can't get code from my email (#1904)


The email address you mentioned is no longer connected to any Liberapay account, most likely because you removed it after adding another one.

―

**Comment by zmtzawqlp** [comment]
i add zmtzawqlp@live.com into liberapay today, but i can't get any confirm info

**Comment by Changaco** [comment]
As far as I can tell the confirmation emails have been sent and should be in your inbox. Have you checked the spam folder?

**Comment by zmtzawqlp** [comment]
thanks, i found it in spam folder
