### ISSUE TITLE
Modify income widgets to show the funding goal

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#191]
Currently we have widgets to show how much you receive on Liberapay, but they don't show the amount you're aiming for.

**Comment by Bat41** [comment]
How do you think it should be presented? Something like "I receive €1.00/€10.00" or with a complete sentence like "I receive €1.00 and my goal is €10.00."?

**Comment by Changaco** [comment]
Here's the best I could come up with in a few minutes:

![screenshot_20171107_212939](https://user-images.githubusercontent.com/1581590/32516180-c40490ce-c402-11e7-98c4-c8546b9d96bc.png)
