### ISSUE TITLE
Add details to Stripe payments

### ISSUE THREAD

**Issue by LiamDawe** [liberapay/liberapay.com#1911]
Hi, currently all payments done via Stripe are just blank apart from the money amount. Stripe have extra fields you (as the service) can fill out, to note that it's coming from Liberapay. Can you please make the payouts more descriptive. It's becoming a bit of a nuisance manually adding details to each Stripe payment from Liberapay to ensure things are easy to match up between things.

**Comment by Changaco** [comment]
On our side we can set two relevant attributes on charges and transfers: `description` and `metadata`. However I'm not sure what you can see on your side.

**Comment by Changaco** [comment]
When I look on the recipient's side, I see a special `Charge` object with an empty `metadata` dictionary. In other words, the `metadata` set by Liberapay isn't visible to the recipient.

However, the object does contain data on its “source”, so you can identify payments as coming from Liberapay if you use Stripe's API.

```json
{
  …
  "source": {
    "application_icon": "https://s3.amazonaws.com/stripe-uploads/acct_1ChyayFk4eGpfLOCapplication-icon-icon_v2_black.75.png",
    "application_logo": "https://s3.amazonaws.com/stripe-uploads/acct_1ChyayFk4eGpfLOCapplication-logo-icon_v2_yellow_r.100.png",
    "application_name": "Liberapay",
    "application_url": "https://liberapay.com/",
    "id": "acct_1ChyayFk4eGpfLOC",
    "object": "account"
  },
  …
}
```

**Comment by LiamDawe** [comment]
Here's some examples.

A payment from Liberapay is basically blank: https://imgur.com/4v38AW7

From a different site that does donations: https://imgur.com/i7iFDeO

For any details users allow to show, it should be noted. At the very least it should note it's from Liberapay.

**Comment by Changaco** [comment]
The BuyMeACoffee example is a different payment type that lets you see who the donor is. It's basically the same thing as you processing the payment from the donor directly on your website. Liberapay donations are supposed to be anonymous, so we do things differently.

**Comment by LiamDawe** [comment]
I'm not asking you to give full donor info, I'm asking you to do more than nothing that's currently shown. At the very least note clearly it's from Liberapay with any other possible info. Right now it's just blank, which is my point.

**Comment by Changaco** [comment]
We're going to try (see #1912), but I can't guarantee that it'll work. The payment object you see on your side isn't the one that Liberapay creates and sees, it's a different one created automatically and opaquely by Stripe.

**Comment by LiamDawe** [comment]
Great, will update when I see anything and come back another time to report.

**Comment by Changaco** [comment]
The change is now deployed. I'll be able to see if it worked as soon as my own Stripe account receives a new payment through Liberapay.

**Comment by Changaco** [comment]
The descriptions added on Liberapay's side haven't solve the problem, they aren't visible on the recipient's side.

We're going to have to modify the payment on the recipient's side instead. This solution only came to me a few minutes ago, but this time I'm confident that it will solve the problem, because I've tested it manually.

@LiamDawe If you have something to say about what you would like to see in the payment's `description` and `metadata` attributes, now's the time to say it.

**Comment by LiamDawe** [comment]
Mainly just make it clear the payment is from Liberapay :+1:

**Comment by Changaco** [comment]
The new code is now deployed, and descriptions have been added to all preexisting payments.
