### ISSUE TITLE
Noscript issue

### ISSUE THREAD

**Issue by micah** [liberapay/liberapay.com#1925]
We have received reports that but on the liberapay.com site you get a XSS warning (from the Firefox Extension NoScript:

![Screenshot__NoScript_XSS-Warning](https://user-images.githubusercontent.com/2832/101640729-c4376680-3a28-11eb-88f3-6040ab594451.png)

This happens whenever one presses the <Save>-button:

![Screenshot__liberapay_add_creditcard](https://user-images.githubusercontent.com/2832/101640870-f6e15f00-3a28-11eb-916f-a4fc6019a3d8.png)

Stripe.com is expected to clear the transaction for liberapay, but it deters people from finishing the transaction.

**Comment by Changaco** [comment]
This isn't exactly a Liberapay or Stripe issue, the real problem is NoScript's simplistic XSS detector. That said, I've found a way to tweak Liberapay's code to avoid triggering the XSS alert. The change is in #1930 and will be deployed tomorrow.

**Comment by micah** [comment]
Excellent, thanks Charly!

**Comment by Changaco** [comment]
The change is now deployed.

**Comment by 992939** [comment]
Allawe1998@gmail.com
