### ISSUE TITLE
Please expand information about reversed transactions

### ISSUE THREAD

**Issue by DuncanLithgow** [liberapay/liberapay.com#1927]
I have a payment set up by bank transfer with my IBAN number. It has been refused/reversed several times. My bank does not recognize that they have received a request for funds transfer. Is it possible to add more information to the notification so I can copy/paste it to my bank?

**Comment by Changaco** [comment]
In the notification that was sent to you when the payment was initiated, you can find a link to the SEPA mandate that you "signed". That mandate contains information that your bank should be able to use to figure out what happened, including our SEPA creditor identifier and the mandate's identifier.

**Comment by DuncanLithgow** [comment]
I have a few suggestions in line with the original idea of this RFE:

I think a lot of people have no idea what a 'SEPA mandate' is or indeed what SEPA is. My bank manager had apparently not heard of it (!). Mandate is not a very commonly used word. 'Agreement' would maybe be better. My bank also has no system in place to advice a customer when they refuse the initial funds transfer request in the absense of an agrrement with SEPA. 

In the "Your payment of €xx has been disputed" notification I suggest a new new link to the mandate/agreement information suggesting this be sent to the bank.

On the page where I originally set up this bank transfer I don't remember reading that I would need to sign an agreement with my bank to use the SEPA system. If I had read that I would probably not have experienced this confusion and would have known what to tell the bank.

Thanks so much for your work on LiberaPay!

**Comment by Changaco** [comment]
#1946 adds links to the mandate in the dispute notification and in the payment page.

![Screenshot of new warning in payment page. Text: “Some banks silently reject SEPA direct debits. We recommend sending a copy of the mandate to your bank if you're not sure that they won't reject the payment without asking you about it.”](https://user-images.githubusercontent.com/1581590/103437209-f6517800-4c24-11eb-8d90-d25a9649c027.png)

**Comment by DuncanLithgow** [comment]
Great!

"not sure that they won't ... without..." is pretty confusing language.

May I suggest

"... copy of the mandate to your bank if you experience problems."
or
"... copy of the SEPA Agreement to your bank if you experience problems."

**Comment by Changaco** [comment]
The warning is an attempt to avoid rejections by telling the donor to send the mandate immediately on their first payment, it would be pointless if it ended with “if you experience problems”.

**Comment by DuncanLithgow** [comment]
Okay, I suggest still that the wording is pretty confusing. Three negatives in a row is confusing in English, at least that has been my experience teaching English as a second language. Maybe:

"... copy of the mandate to your bank if you're unsure how they handle SEPA direct debits."

**Comment by Changaco** [comment]
New proposed wording:

> Your bank may reject this payment. We recommend sending a copy of the mandate to your bank if you're not sure that it properly handles Euro direct debit instructions.

**Comment by DuncanLithgow** [comment]
Looks good.
