### ISSUE TITLE
Feature Request: Please add feature for showing donor list  (usernames only!) on resp. donnee's page

### ISSUE THREAD

**Issue by steffan77** [liberapay/liberapay.com#1952]
As in the topic:
Feature Request: Please add feature for showing donor list  (usernames only!) on the Liberapay page of the respective recipient.

Reason: 
I've been donating a substantial amount via Liberapay for the last 2 years. Before I renew my donations, I'd like to know that I will be able to see if my donation reaches the intended recipient. 

**The feature I'd like to promote would need to be on the page of each recipient,** like as an example on the page of k9
https://liberapay.com/k9mail/

i.e. what would be needed is a **button besides "view income history" that when clicked on would then show the list of all the usernames of people that are currently making donations to the respective donee /beneficiary**. This is not about breaking anonymity since my real name – hidden behind my username – is only known to me, and to Liberapay of course. 

This could be an opt-in feature for donors who want to be able to check what is happening with their donations, even though I don’t really see any reason for this, since an username does not reveal an identity.

Please understand that it is not about not trusting Liberapay in handling to donations in a correct and fair manner.  Effectively, I have been donating for 2 years already. Still, I don't like the thought that I will be donating into a "black hole", by which I don't want to imply that my donation is sucked up elsewhere, but that my knowledge / transparency about what is happening is zero. 

Also, IMHO, I don’t see that there could be any reason that any receiver of a payment might be averse to show a public list of the usernames of the donors, since the amount of the payments they receive is obviously already publicly known, also see comment by cketti in reply to my post below

https://forum.k9mail.app/t/donations-via-liberapay-how-can-i-know-that-my-donation-reaches-the-intended-recipient/572
_Personally, I wouldn’t mind donors having the option to display their name publicly. However, there should still be the option to make anonymous donations._

I would think that is a great feature which could help promote donations via Liberapay.  Every donor could be sent a hint that he/she can check the amount of his/her donation that is reaching the donee every week. I’d think this adds greatly to “donor satisfaction”.

**Comment by trebmuh** [comment]
related #271

**Comment by Changaco** [comment]
> This is not about breaking anonymity since my real name – hidden behind my username – is only known to me, and to Liberapay of course.

Anonymity doesn't mean hiding only your legal name, it means hiding who you are completely. If we exposed the usernames of the donors, then the donations would be pseudonymous, not anonymous.

> I don’t see that there could be any reason that any receiver of a payment might be averse to show a public list of the usernames of the donors

There are reasons. A public list of usernames like the one you're proposing can be abused by spammers and trolls.

> since the amount of the payments they receive is obviously already publicly known

Creators have the option to hide how much they receive.

**Comment by steffan77** [comment]
> 
> 
> > This is not about breaking anonymity since my real name – hidden behind my username – is only known to me, and to Liberapay of course.
> 
> Anonymity doesn't mean hiding only your legal name, it means hiding who you are completely. If we exposed the usernames of the donors, then the donations would be pseudonymous, not anonymous.
> 
Well, actually the donation are at pseudonymous because Liberapay knows at any given time who has given how much to which creator. So it is already up to Liberapay to keep the secret.

> > I don’t see that there could be any reason that any receiver of a payment might be averse to show a public list of the usernames of the donors
> 
> There are reasons. A public list of usernames like the one you're proposing can be abused by spammers and trolls.
Let's assume my username is "Smallface73", and I use it only on Liberapay. Please tell me how it could be abused?!

> 
> > since the amount of the payments they receive is obviously already publicly known
> 
> Creators have the option to hide how much they receive.
Well, for creators who do not show their income history, there will be no option to show this list.  When checking on this page
https://liberapay.com/explore/teams
, I can see that actually nobody keeps secret the amount they receive.

Now, the list I am proposing is an effective tool for transparancy that only gives more transparency to the respective donor. Since only he/she (and Liberapay, of course) can know the connection between the username and the real name, and the donor can look up in his/her ledger under https://liberapay.com/<<username>>/giving/ how much he donated, and can compare with the username in the list that I'd like to see as a feature, there is perfect transparency to the donor, and nobody else (again except Liberapay, of course). And since the creator /the donee knows how much they receive, the numbers in the list definitely will add up correctly since the donee could complain otherwise.

I can see that this could lead to discussions as to how much the paymentment provider (I don't mean Liberapay here) takes for the service. 

But I'd really like to advocate for implementing this feature

**Comment by trebmuh** [comment]
> Well, actually the donation are pseudonymous because Liberapay knows at any given time who has given how much to which creator. So it is already up to Liberapay to keep the secret.

It looks like you're playing on words here. What @Changaco tried to explain to you is that there are people on LP who doesn't want there contributions to be public. LP has allowed that from day-1. So we need to cater for this.

> Let's assume my username is "Smallface73", and I use it only on Liberapay. Please tell me how it could be abused?!

And let's assume my username is my real name and I've subscribed to Liberapay from day-1. So they can easily check on the web who I am and spam me with what-the-hell-they-want, trolls are good at finding trolling-idea you know.

> When checking on this page https://liberapay.com/explore/teams , I can see that actually nobody keeps secret the amount they receive.

I could well be wrong but my understanding is that people who want to keep how much they receives aren't show on those pages.

----

It looks to me that you're asking for a feature here which would interest you. This is perfectly fine to do so. No issue with that. That said, you should try to understand that there are other point of view from other people and LP want to cater for those too. In this regard, please, make a careful read of #271 which is a good example of how LP could improve, particularly the "opt-in" idea.

**Comment by steffan77** [comment]
Thank you for your answer.
Yes, I did  read the post #271 that you mention. Yes, the "opt-in" idea sounds perfect to me. And, no, none of your other points does really sound  convincing to me.  IMHO, in particular the "opt-in" option literally wipes all your objections away. 

This option is not about being thanked by an creator who receives my donation. I am "thanked" enough by being able to use the excellent software for free. Also note please, it is not about denying that Liberapay should have a fair share of donations as well. I have been donating to Liberapay as well, for that matter.

I have  been making donations to a number of FOSS projects via Liberapay for 2 years now.  So you can see that I trusted in Liberapay to handle my donations. I feel now that I need a little more transparency. So, what I will do is that I will not renew my donations for the time being. I will keep my account at Liberapay, so I will be back and continue donating as soon as this feature becomes available.

**Comment by trebmuh** [comment]
That is unfortunate but it reads that you're not really wanting to talk about ideas but rather that you are demanding something
The discussion ends here for what I'm concerned about.

**Comment by steffan77** [comment]
I **do** want to talk about ideas, e.g. the idea of implementing my proposal as opt-in.  But I get it that you don't link my proposal at all. 

Maybe somebody else has an opinion about implementing a feature, as an opt-in for both donors and donees.
It is about a little bit more transparency, strictly only for the donor.

Anybody??

**Comment by Changaco** [comment]
> So, what I will do is that I will not renew my donations for the time being.

Thank you for showing your true colors, I will now ignore you.

Closing this issue in favor of #271 and #482.
