### ISSUE TITLE
Non-dollar currency format is highly likely incorrect

### ISSUE THREAD

**Issue by Avamander** [liberapay/liberapay.com#1967]
Right now when you visit a profile page `https://liberapay.com/<username>` it displays `<username> receives €<amount> per week from <count> patrons.`

EU guidelines say:

> The euro sign is followed by the amount without space in Dutch, Irish and Maltese. In all other official EU languages the order is reversed; the amount is followed by a hard space and the euro sign.

The current format (€ followed by sum) basically looks wrong for people in 24 EU countries, switching it would make it look wrong in only four. The same approach should also be taken with other currencies-country pairs when relevant. 

Alternatively there should be a configuration option for numeric and currency formats.

**Comment by Changaco** [comment]
The way currency amounts are displayed depends on the language, not on the currency. English has the currency before the amount without any space in-between, Dutch has the same order as English but with a space between the currency and the amount, French has the amount followed by a space followed by the currency, etc. The format for each language is from the [Unicode Common Locale Data Repository](http://cldr.unicode.org/).

**Comment by Avamander** [comment]
@Changaco unless you have translations into every 24 of those languages it's obtuse to force a specific format. 

Also like, fuck the people that speak French in Belgium or any other language minority in a specific country - tying together a language and a format selector is absolutely silly.

**Comment by Avamander** [comment]
@Changaco this deserves more discussion than just "we do it because something says so", it's obviously more nuanced than a blanket one config option can possibly cover.

**Comment by trebmuh** [comment]
I can't see any issue here. Could you please make screenshot of what you see right now, and a mockup-image of what should best be in your opinion?

**Comment by Avamander** [comment]
@trebmuh 

Currently it's "€<amount>" when in a lot of EU countries it would be more correct to use "<amount> €"

**Comment by trebmuh** [comment]
Where ? (screenshot please)

**Comment by Avamander** [comment]
@trebmuh 
Everywhere where currency is displayed I think. E.g. discovery, user profile pages:
![image](https://user-images.githubusercontent.com/5392141/106163343-bb921f80-6191-11eb-8cbd-7189e2931ae2.png)

**Comment by trebmuh** [comment]
As @Changaco told you above, it depends on which language the browser is asking the page to be displayed in.

In English:
![liberapay-en](https://user-images.githubusercontent.com/8705846/106165585-8be01900-618b-11eb-84c3-6dfb1452f7c2.png)

In French:
![liberapay-fr](https://user-images.githubusercontent.com/8705846/106165613-90a4cd00-618b-11eb-8c87-910c41ec45eb.png)

**Comment by Avamander** [comment]
@trebmuh You don't have my native language, probably won't for years, and even if you did, I wouldn't want it.

As I said before, display language stuck to units is obtuse, equivalent being forcing people to "pounds" and "football fields" because they chose English.

**Comment by Changaco** [comment]
I think the way forward is #1073. The implementation of its first 3 steps would allow users who dislike traditional English formatting to switch to “European English”.
