### ISSUE TITLE
Embedded donation button picks geolocated language over browser preference for i18n

### ISSUE THREAD

**Issue by thw0rted** [liberapay/liberapay.com#1974]
I'm not a user, but I was reading a page that embeds a liberapay.com donation button and noticed an issue that I thought was worth reporting.

I'm a native English speaker living in Germany -- I can get by in German, but not very well.  What I noticed was, the [page I was reading](https://k9mail.app/2021/02/14/K-9-Mail-is-looking-for-funding) was in English, but the embedded donation button said "Spenden" ("Donate" in German).  The request to `https://liberapay.com/k9mail/widgets/button.js` includes the header `accept-language: en-US,en;q=0.9,es;q=0.8,de;q=0.7`, showing a preference for English, but the script response uses the German word, apparently server-side rendered.  I can only assume that German was selected based on IP geolocation.

I found #75 which references a library you're using for translation.  I'm not sure if this is configurable -- if it's an artifact of how Weblate is configured for liberapay.com -- or if it's an inherent function of the library that needs to be addressed by them directly.  If so, let me know and I'll file the issue over there instead.

**Comment by Changaco** [comment]
This issue is a duplicate of #360.

**Comment by thw0rted** [comment]
Thanks, I tried to search ("button translation", "button language", etc) but didn't think to look for "widget".  Will close.
