### ISSUE TITLE
Shield.io badges don't show any data

### ISSUE THREAD

**Issue by fschrempf** [liberapay/liberapay.com#1978]
My "gives" badge looks like this:
![Badge](https://img.shields.io/liberapay/gives/frsc.svg?logo=liberapay)

While those of others work fine:
![Badge](https://img.shields.io/liberapay/gives/Changaco.svg?logo=liberapay)

So what's the difference? Is it because all of my donations are on a yearly basis and the data doesn't get processed regularly?

**Comment by Changaco** [comment]
The shields.io server gets the data it needs to generate the badges from `https://liberapay.com/%username/public.json`. It's possible that it received an unexpected response, for example a challenge or error page, and that this bad response is currently cached. If that's the problem, then it should fix itself when the cache entry expires.

**Comment by fschrempf** [comment]
> If that's the problem, then it should fix itself when the cache entry expires.

Ok, thanks! I guess I'll just wait for the cache to expire and see if this resolves the problem.

**Comment by Changaco** [comment]
The badges are still broken, so it doesn't look like caching is the cause. You should open an issue in [the shields repository](https://github.com/badges/shields), because I don't see anything wrong on our side.

**Comment by fschrempf** [comment]
Ok, done: https://github.com/badges/shields/issues/6254

**Comment by Changaco** [comment]
This issue is now fixed.
