### ISSUE TITLE
Stripe partial refunds

### ISSUE THREAD

**Issue by sunknudsen** [liberapay/liberapay.com#1987]
Hey guys,

First, thanks so much for Liberapay.

I noticed that all transactions on Stripe were partially refunded.

Is this normal?

Thanks,

Sun

**Comment by Changaco** [comment]
Yes, it's normal. The "refund" is our way of getting back the Stripe fee. We can't compute the exact fee amount ourselves, so we let Stripe process the payment and then pull back some of the money to cover the fee.

**Comment by sunknudsen** [comment]
@Changaco, thanks for the follow-up!
