### ISSUE TITLE
Incorrect notification after manual donation renewal

### ISSUE THREAD

**Issue by Zykino** [liberapay/liberapay.com#1996]
Hello, the print screen is in french, but basically I clicked on "renew this donations" on a precedent notification, paid with paypal (the maximum proposed to have a year of peace of mind with this gift) and came back to the notifications to this.
So the donation to redo is dimissed and reprogrammed for the same date ?

As of today, it is still in the future so I am not sure how the service will react, but I suppose it will ask me again to pay for a year.
![image](https://user-images.githubusercontent.com/3809938/114720261-2b975700-9d38-11eb-9835-0e6654b66d09.png)

I did not search for similar instances before posting this one.

**Comment by Changaco** [comment]
The notification is clearly wrong, but I'm not sure why.

If you look at https://liberapay.com/Zykino/giving/schedule you can see that the new renewal date is actually April 6, 2022.
