### ISSUE TITLE
Missing information or bug ?

### ISSUE THREAD

**Issue by trebmuh** [liberapay/liberapay.com#2003]
If we look here:

![lp-linuxmao](https://user-images.githubusercontent.com/8705846/115713179-02994680-a376-11eb-9a4a-1faa59549f8c.png)

It seems that the project receives 2 donations.

The "_modifications récentes_" says that 4 donations have been created and there isn't "_donations stopped_" information lines.

So, to my understanding either the first line is wrong and should display "_reçoit 3.38€ par semaine de la part de 4 mécènes_" or some information are missing in the "_modifications récentes_" paragraph.

**Comment by Changaco** [comment]
They were probably unfunded donations. #2038 will hide them.
