### ISSUE TITLE
Missing profile descriptions

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#2013]
We have too many users who receive payments but don't have any profile description. We should probably send them a notification asking them to complete their profile and warning them that an incomplete profile increases the probability of their account being blocked.

**Comment by Urahara** [comment]
The reason of account being block is suspicious activty?

**Comment by Changaco** [comment]
@Urahara Suspicious payments, yes.

**Comment by sjcummins** [comment]
Hi, I am interested in working on this issue if it is still available

**Comment by Changaco** [comment]
Yes, this issue still available.

**Comment by sjcummins** [comment]
Just a few questions--
1. How should we define an empty description? Just an empty string? One that doesn't contain any alphanumeric characters (e.g. a bunch of spaces)?
2. How long should we wait to send the reminder (i.e. x days after the account receives its first payment)?
3. Would having a short description or a full description enough to fulfill the requirement or is both needed?
4. Should the notification be repeated after a certain amount of time if there is still no description? If so what should this period of time be?
5. What should the notification message be?

Thanks in advance for the clarifications

**Comment by Changaco** [comment]
1. We don't need anything complicated, just check whether the description exists.
2. I'm not sure why this notification should be delayed at all, but when in doubt I use 6 hours as the delay.
3. Only the full description should be required.
4. I guess it would be okay to send it every 6 months, but only if there have been new payments received since the previous notification. It would also be okay to send it only once.
5. I don't know what the exact message should be.

**Comment by bearbin** [comment]
The wording of the new notification is rather strong, particularly since it is being sent to users who have had an account and been receiving payments for some time.

The warning about account disablement should be qualified by a statement along the lines of "in the case of suspicious payments", and a link to the moderation policies added.
