### ISSUE TITLE
Time to stop the weekly notifications?

### ISSUE THREAD

**Issue by LiamDawe** [liberapay/liberapay.com#2025]
Let's face it, despite the descriptions, nothing about Liberapay is weekly any more.

The "Your Liberapay income is £22.20 this week" notifications are nowadays just a nuisance, since we get notified by Stripe/PayPal whenever we get a payment now.

Time to remove these notifications? They just don't seem to serve an actual purpose now.

**Comment by Changaco** [comment]
It has always been possible to unsubscribe from the weekly notification in https://liberapay.com/about/me/emails/

I'm going to see if I can finish implementing explicit “Unsubscribe” links in email footers.

**Comment by LiamDawe** [comment]
That only applies to emails, not the in-site notifications which are always shown every week even though they serve no actual purpose now.

**Comment by Changaco** [comment]
You're right that we also need a way to disable in-site notifications.

**Comment by LiamDawe** [comment]
I just don't get why keep them at all though? What purpose do they actually solve now? Would love to know your thoughts on this given that nothing about Liberapay is actually weekly any more.

**Comment by Changaco** [comment]
Without the notification any creator who wants to know about changes in income would have to actively check their Liberapay accounts. If we completely stopped sending the notification, then some users would ask why they're not receiving it anymore, and probably request that we bring it back.

There's no doubt that the current notification is crude and could be replaced with better ones, but sadly I still haven't figured out exactly how.

**Comment by LiamDawe** [comment]
Again though, I disagree on this. You're notified directly by the payment services now, whenever a payment comes in. Liberapay doesn't need a "weekly" notification about payments that aren't even in the last week since it covers all payments. It just makes zero sense as it is, I urge you to rethink it :)

**Comment by trebmuh** [comment]
I disagree with that @LiamDawe . The people who are donating to the projects I'm receiving some money from are thinking "how much I give

**Comment by techtonik** [comment]
> I just don't get why keep them at all though?

To liberate Liberapay from PayPal mafia one day. To cryptospace for example.

**Comment by LiamDawe** [comment]
> I disagree with that @LiamDawe . A relevant part of the people who are donating to the projects I'm receiving some money from are thinking "how much do I give on a weekly basis". And I like to have a view of "how much roughly do I get on a weekly basis".
> The possibility to disable the weekly notifications could help people like you to be fine, with keeping people like me to be fine too.

But you're not getting any of it weekly, it's leftovers from the original mechanics why just don't apply now.

**Comment by LiamDawe** [comment]
> > I just don't get why keep them at all though?
> 
> To liberate Liberapay from PayPal mafia one day. To cryptospace for example.

This is such an idiotic reply I don't even know where to begin. Please stay on topic.

**Comment by trebmuh** [comment]
That isn't a problem for me. I like it this way.

**Comment by ZelphirKaltstahl** [comment]
Life and work for most revolve around weeks, working days and weekend, living from week to week or perhaps 2 weeks and so on. Another unit that is important is the month, as wages mostly paid monthly. So these units are important to see the statistics for. A month to me already seems like quite a long time to plan ahead, so seeing things for week is useful to me.

-> Couldn't we have a dynamic display? A select box, where I can select the duration for which I want to see the numbers? I mean, it should be possible to divide timespans in which donations happen by the number of days and then multiply by the number of days that corresponds to the selected timespan and boom, I have the amount of money I donate or receive in that timespan, with the disclaimer, that the money will not necessarily be received exactly on that day or during that timespan and that this is merely a calculation. Then one could have the notification settings pay attention to the selected timespan and use that as a default or let the user configure their own. If there is no hardcoded timespan making things inflexible, this should be possible.

**Comment by LiamDawe** [comment]
> -> Couldn't we have a dynamic display? A select box, where I can select the duration for which I want to see the numbers? I mean, it should be possible to divide timespans in which donations happen by the number of days and then multiply by the number of days that corresponds to the selected timespan and boom, I have the amount of money I donate or receive in that timespan, with the disclaimer, that the money will not necessarily be received exactly on that day or during that timespan and that this is merely a calculation. Then one could have the notification settings pay attention to the selected timespan and use that as a default or let the user configure their own. If there is no hardcoded timespan making things inflexible, this should be possible.

This seems quite sane, I approve of that approach to be more dynamic, with a clear note that donations aren't actually weekly or monthly shown for both the donators and the creators.

**Comment by trebmuh** [comment]
Related #837

**Comment by techtonik** [comment]
> This is such an idiotic reply I don't even know where to begin. Please stay on topic.

If you don't know where to begin, maybe you don't want to write idiotic replies at all? =) To clarify what you didn't get, I will still help you stay on topic. The notifications that you get from Stripe are a courtesy of Stripe service. Other payment providers may not support this in the future, or have a different format that needs parsing, so it is better to have unified interface from LP.
