### ISSUE TITLE
Payin page is confusing

### ISSUE THREAD

**Issue by mattbk** [liberapay/liberapay.com#203]
If I go to https://liberapay.com/about/me/wallet/payin/, I see "Your donations are funded by your income," but supposedly anyone with a credit card can donate, right? Did I miss something somewhere?

**Comment by Changaco** [comment]
The UI is a little confusing. You have to set up a donation first, then you'll be asked to add money to your account to fund it.

**Comment by mattbk** [comment]
Thanks, that looks like it does work. Maybe a note could be added on the payin page?

Kudos on getting up and running!

**Comment by Changaco** [comment]
Renamed and tagged as Easy. It'd be great if someone else than me took care of this.
