### ISSUE TITLE
Some payments still not giving meta data in Stripe

### ISSUE THREAD

**Issue by LiamDawe** [liberapay/liberapay.com#2034]
Hi, in a previous ticket at my request (thanks again), you added some data to Stripe payments to mention it was from Liberapay.

Some payments however don't note this. It's important for many reasons including taxes, enabling people to quickly match up where funds are actually coming from.

Please ensure all Stripe payments actually note they're from Liberapay. Can give example if needed. If you're able to, the May 16, 2021 transaction on the GamingOnLinux Liberapay account of €11.93 had no info on the payout.

**Comment by Changaco** [comment]
All the existing payments which were missing a description have now been updated.
