### ISSUE TITLE
Cloudflare reports that the server is down

### ISSUE THREAD

**Issue by Panquesito7** [liberapay/liberapay.com#2039]
Since today's morning (for me), Cloudflare has been reporting that the server is down, and I cannot access the website or anything related to Liberapay. Some hours ago, I saw the website was working, but I just tried again, and it's not working.

![image](https://user-images.githubusercontent.com/51391473/121968737-7afa0380-cd38-11eb-9061-5c28c47524a9.png)

Have there been any server-related issues recently?
Thanks for reading, folks. 😄

**Comment by Changaco** [comment]
The website was completely inaccessible between 21:14:09 and 22:50:34 (UTC), and partially inaccessible for some time before that. There was no apparent reason for this incident: the web app and database were working, and it wasn't a network connectivity problem.

For more technical details, see <https://github.com/cloudflare/cloudflared/issues/400>.
