### ISSUE TITLE
Possible to use liberapay with stripe without mobile phone?

### ISSUE THREAD

**Issue by najamelan** [liberapay/liberapay.com#2045]
I try to setup a liberapay account with stripe. However I don't own a mobile phone. It seems that liberapay configures stripe to require a phone number for notifications. Thus when I try to connect libarapay to my stripe account I get a a screen like in the screenshot. According to stripe support that is because liberapay requires the phone number.

![stripe](https://user-images.githubusercontent.com/449589/124397725-21667280-dd01-11eb-8737-f15c3147af04.png)

**Comment by Changaco** [comment]
No, we don't ask Stripe to collect mobile phone numbers.

I suggest that you try creating your Stripe account directly at https://dashboard.stripe.com/register instead of going through Liberapay.

**Comment by najamelan** [comment]
I already have a stripe account. This happens when I try to add it as a payment method in liberapay. I will point their support to this issue.

**Comment by Changaco** [comment]
In that case, I suggest that you try setting up two-step authentication for your Stripe account in <https://dashboard.stripe.com/settings/user> using one of the alternatives to SMS.

**Comment by najamelan** [comment]
AFAICT The only other authentication is a google app, which also requires a mobile phone. The app itself can surely run in a VM, but google always requires a google account with a phone number.

**Comment by Changaco** [comment]
There are open source authenticator apps, you don't need a Google account or any specific hardware. I use [OTPClient](https://github.com/paolostivanin/OTPClient) on Linux.

**Comment by najamelan** [comment]
Ok, great. I have installed OTPClient and I have been able to connect liberapay to stripe.
