### ISSUE TITLE
Drop the hard maximum donation amount

### ISSUE THREAD

**Issue by Wuzzy2** [liberapay/liberapay.com#2055]
I just noticed that in the FAQ it says the maximum amount that one is allowed to donate is $100 per week. The justification is that projects are "less dependent on one donor".

I think this is not OK because this is a hard limit forced on ALL projects.

But IMHO It should be up to the individual projects to decide what the upper limit is (if any). Liberapay should not force that decision upon them.

If there is any other reason for having a hard upper limit (like some law or whatever), the FAQ should clearly say that.

**Comment by Changaco** [comment]
Closing in favour of #1072.
