### ISSUE TITLE
Stat request wants CloudFlare verification

### ISSUE THREAD

**Issue by mpldr** [liberapay/liberapay.com#2061]
Hi, when my server requests https://liberapay.com/mpldr/public.json it gets a Cloudflare challenge. Being a python script without a javascript parser it has a hard time passing this challenge. Is there a known workaround for this, or would it be possible to disable Cloudflare for these stat endpoints?

**Comment by Changaco** [comment]
We sometimes get so much junk traffic that I configure Cloudflare to challenge all requests coming from a specific hosting provider's network. I have now added your server's IP address to the list of explicitly allowed sources.

**Comment by mpldr** [comment]
Thank you very much
