### ISSUE TITLE
user reports fraud

### ISSUE THREAD

**Issue by iamthecountry** [liberapay/liberapay.com#2065]
I have paying you through Liberapay. The last payment, I believe it was on Aug 10th or so, went through fine, but was immediately followed by two scam charges that my credit card declined.  One of them was from ExoticIndia. I only use that card for making this quarterly payment to you so I knew it was bogus.  The Credit Company has canceled my card and is issuing a new one.

I wanted to let you know in case it is happening to others, and I suppose I need to report this to Liberapay in case they don't know they have a breach.

**Comment by Changaco** [comment]
This report doesn't contain enough information. I need the ID or email address of your Liberapay account in order to look into what happened. You can email this information to support@liberapay.com instead of posting it here.
