### ISSUE TITLE
Unable to input custom amount on mobile

### ISSUE THREAD

**Issue by sevku** [liberapay/liberapay.com#2066]
Sorry for the bad title, I'm not sure how to put the problem in words.

So I tried to donate a custom amount to a project, but I'm unable to because liberapay doesn't recognize the number format 3.50 as valid. I'd have to type in 3,50, but I'm unable to do so on my mobile phone due to localization. Where I live, 3,50 is 3.50.

**Comment by Changaco** [comment]
In which language are you viewing the Liberapay website? Can you copy the exact error message you see when you input 3.50?

**Comment by sevku** [comment]
> In which language are you viewing the Liberapay website? Can you copy the exact error message you see when you input 3.50?

![image](https://user-images.githubusercontent.com/23403917/131995573-44b7cb79-2100-4a42-91d9-fce389cb7e75.png)
![image](https://user-images.githubusercontent.com/23403917/131995586-1bd3a807-29cc-4724-a53f-897a89633768.png)

**Comment by sevku** [comment]
Language is DE-CH

**Comment by Changaco** [comment]
This issue will soon be fixed. In the meantime, you can avoid it by using the English version of the donation form: https://en.liberapay.com/ubports-foundation/donate

**Comment by sevku** [comment]
Did you fix this that fast? or has this been in preparation for longer than my report?

**Comment by Changaco** [comment]
Language variants were already a known problem that I had put some thought into, as can be seen in #1073. However the actual fix is entirely new and took me a few hours to figure out. It's deployed now.
