### ISSUE TITLE
Privacy at payment service provider Stripe

### ISSUE THREAD

**Issue by Lukas2112** [liberapay/liberapay.com#2074]
I seem to remember reading a post on liberapay.com some time ago that said that the payment service provider Stripe is constantly working on becoming more privacy-friendly in terms of transmission. 

Unfortunately, I can no longer find the relevant passage on the page. :/ Is there an update on this?

**Comment by Changaco** [comment]
I don't remember ever writing anything like “Stripe is constantly working on becoming more privacy-friendly”, and I'm not aware of specific efforts by Stripe to improve privacy.

The first discussion about Stripe and privacy was #1268.
