### ISSUE TITLE
Integration Ğ1 payment method

### ISSUE THREAD

**Issue by juanro49** [liberapay/liberapay.com#2079]
Hi, as a suggestion, you could think about incorporating the free Ğ1 currency for donations.

Payment method name --> Ğ1 (June in francais, Juna in Spanish)

Payment method website --> Francais: https://monnaie-libre.fr/, Spanish: https://moneda-libre.org/descubrir/utilizar
Cesium api documentation --> https://cesium.duniter.io/api/#/app/home

More info in https://fr.wikipedia.org/wiki/%C4%9E1 and https://es.wikipedia.org/wiki/%C4%9E1

**Comment by Changaco** [comment]
Duplicate of #567.
