### ISSUE TITLE
Patrons page incorrectly claims that I'm not a member of any team

### ISSUE THREAD

**Issue by trebmuh** [liberapay/liberapay.com#2100]
I have been looking at this new feature (#2088) this morning and I've been surprised after activating the functionality to get this display: 
![liberapay-mecenes-equipe-erreur](https://user-images.githubusercontent.com/8705846/145674456-37e84f52-fa97-4e8f-b575-46d95f7272b8.png)

The part which surprised me is the _"Teams -> You are not a member of any team"_, because this account is a member of 3 teams.

Hence, I thought something was broken. After thinking about it, maybe this is because there is currently no donator who have activated the "public" system, then they can't be displayed here. Am I right thinking so @Changaco ? If so, I would suggest the possibility in such a case to have a sentence on the following line: "You're member of X team(s), but there is actually not any donor who is making a **public** donation. When a donor will make its donation to be **public**, then it'll be displayed here.".

**Comment by Changaco** [comment]
Hmm, no, it's just a very stupid bug. I'll fix it soon.

**Comment by trebmuh** [comment]
OK :+1:

**Comment by trebmuh** [comment]
nice :+1:
