### ISSUE TITLE
Can't see the patrons from a team I'm belong to

### ISSUE THREAD

**Issue by trebmuh** [liberapay/liberapay.com#2102]
Now that #2100 is fixed, I can see this when enabling the new functionality:

![liberapay-patrons-display-bug](https://user-images.githubusercontent.com/8705846/145708100-cb26faa6-303c-498a-9f4d-bf6e28be6b13.png)

That said, if I'm clicking on the "View the patrons of LibraZiK" button, I'm getting this error:

![liberapay-patrons-display-bug-2](https://user-images.githubusercontent.com/8705846/145708116-6574382d-99a6-46bd-8e6c-979fce4f2a79.png)

Am I missing any step?

**Comment by Changaco** [comment]
More stupid bugs. Thanks for testing and reporting. I've made temporary fixes directly on the server, I'll deploy properly later.

**Comment by trebmuh** [comment]
Seems to work flawlessly now.
Congratz for this new feature and those quick fixes.
