### ISSUE TITLE
"Log In or Create Account" disappeared

### ISSUE THREAD

**Issue by trebmuh** [liberapay/liberapay.com#2108]
The "Log In or Create Account" button seems to have disappeared from most pages: 

![LP-1](https://user-images.githubusercontent.com/8705846/147742156-51ac77e4-d6f9-4d0d-aecb-25104aa41458.png)

To log in, I need to manually input "sign-in" to the URL address:

![LP-2](https://user-images.githubusercontent.com/8705846/147742165-1ff241f7-1a2e-4eb1-bcb4-566ce7e3a116.png)

**Comment by Changaco** [comment]
Oops. That's a regression from #1899. I've temporarily fixed it directly on the server.

**Comment by trebmuh** [comment]
I've just checked and it works as expected now.
I'll let you close this thread when fixed in the code here.
