### ISSUE TITLE
Reporting a sexual predator

### ISSUE THREAD

**Issue by Skift02** [liberapay/liberapay.com#2111]
The user named Sappho ζ,, AKA Hypno Sappho,, that you have on your platform has admitted to being a zoophile (sexual attention to animals) and a MAP (Minor Attracted Person) or a person who has an attraction to those under legal age of consent. Due to this she had been band from both Twitter and Instagram. I am asking you to please take a look at the many video reports of her as well as her profiles on the media that she hasn't been banned from and remove her from your platform. She is know to groom minors into her sexual fetishes and should not be allowed to do so using online platforms.

**Comment by jorgesumle** [comment]
> The organization may close the user's account if it considers that they have violated this contract, or a contract with a partner of the organization, or any applicable law.

I cannot find a user named like that on Liberapay (I guess you mean [Sapphaos](https://liberapay.com/Sapphaos/)?). If that user finances such illegal activities with Liberapay, we can ban that user, but I didn't see anything illegal there (or on the linked accounts, only read a few Mastodon posts though) and nobody is giving money to that user anyways.

If you can prove that that user is trying to finance illegal activities or violating any law, we can close the user's account. Maybe it's better that you send that information to us privately (click on the email button from [our contact page](https://liberapay.com/about/contact)).
