### ISSUE TITLE
Team income table doesn't say when payday is

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#2119]
From <https://nerdculture.de/@ij/107688101193614453>:

> would it be possible to have the dates of Last/Next Paydays being listed on /$user/receiving or mention the dates somewhere als on the page?

![Screenshot of the headers of a team income table](https://user-images.githubusercontent.com/1581590/151201480-28d5b3b9-91d5-4923-9309-c629cc939232.png)

**Comment by biskwikman** [comment]
I'll start working on this.

**Comment by biskwikman** [comment]
@Changaco I'm looking at team-members.html, which I think is where this table is produced. Could you tell me what templating language this is using (is it Pando?) and where I can find the data for when the paydays occur?

**Comment by Changaco** [comment]
@biskwikman The templates are [Jinja](https://jinja.palletsprojects.com/en/3.1.x/templates/). (This is mentioned in the README along with other things that new developers need to know.)

**Comment by biskwikman** [comment]
@Changaco so I think what needs to be done is to add either the most recent `ts_start` or `ts_end` time from the `paydays` database table into the table header which already has `Last Payday`, and then add the date of the upcoming Wednesday into the table header which already has `Next Payday` in `team-members.html`

If this is correct, how would I go about making a database query to `paydays`? From what I can tell, it needs to be done in `www/%username/recieving/index.html.spt` Is that correct?

**Comment by biskwikman** [comment]
I just made a PR in #2157

**Comment by biskwikman** [comment]
@Changaco Is it alright with you if I close this issue?

**Comment by biskwikman** [comment]
@Changaco I see. I wasn't aware of that feature.
