### ISSUE TITLE
Simplified Chinese

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#2126]
This issue is about adding a Simplified Chinese translation, automatically generated from the Traditional Chinese translation. Background: <https://github.com/liberapay/salon/issues/127>.

- [x] create the translation file for Simplified Chinese (`touch i18n/core/zh_Hans.po && make i18n_update`)
- [x] add [OpenCC](https://pypi.org/project/OpenCC/) to `requirements_base.txt` (see the README for instructions)
- [x] create a `cli/convert-chinese.py` script which reads the two Chinese translation files and completes each one with the translations from the other, using OpenCC to convert them
- [x] add a call to the new script in the `i18n_update` target in the `Makefile`

**Comment by biskwikman** [comment]
Hello, I'm having a try at this, but I'm a little confused about the `i18n_update` command.
I created a new branch and then ran `touch i18n/core/zh_Hans.po && make i18n_update`. I then got this message:
`Please go to https://hosted.weblate.org/projects/liberapay/#repository and click the Commit button if there are uncommitted changes, then press Enter to continue...`

I'm not really sure what the website does but I went to it and I it doesn't seem like I should be using it when making a PR so I just pressed enter in the terminal. Then I got this output.

```bash
git fetch weblate
git checkout -q master
There are uncommitted changes in the i18n/ directory.
make: *** [Makefile:140: _i18n_pull] Error 1
```

Then I get this output, which seems to indicate that it has switched back to the master branch.

```bash
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	i18n/core/zh_Hans.po

nothing added to commit but untracked files present (use "git add" to track)
```

Was there some sort of error here?

**Comment by Changaco** [comment]
`make i18n_update` was the wrong command, sorry. The appropriate one is `make _i18n_extract`.

**Comment by biskwikman** [comment]
Great. I think that bit is working now. 

I have another question. I might be misunderstanding, but if `Zh_Hant.po` already exists, shouldn't the opencc python script just convert convert one way? From the traditional to the simplified chinese?

**Comment by Changaco** [comment]
No. The conversion should go both ways so that the two translations always stay at the same level of completion in the future.

**Comment by biskwikman** [comment]
oh, this makes sense.

**Comment by biskwikman** [comment]
Ok, have the python script working.

```python
import opencc
from babel.messages.pofile import read_po, write_po


# Converts traditional to simplified
t2s_converter = opencc.OpenCC('t2s.json')
# Converts simplified to traditional
s2t_converter = opencc.OpenCC('s2t.json')

# Create path variables
t_path = '../i18n/core/zh_Hant.po'
s_path = '../i18n/core/zh_Hans.po'

# Open Traditional Chinese po file and create babel catalog
with open(t_path, 'rb') as pot:
    t_catalog = read_po(pot, locale='zh_Hant')

# Open Simplified Chinese po file and create babel catalog
with open(s_path, 'rb') as pot:
    s_catalog = read_po(pot, locale='zh_Hans')

# If message string is in t_catalog and not s_catalog, convert and insert into s_catalog
for s_message in s_catalog:
    if not s_message.string:
        for t_message in t_catalog:
            if t_message.id == s_message.id:
                s_message.string = t2s_converter.convert(t_message.string)

# Write result to zh_Hans.po
with open(s_path, 'wb') as pot:
    write_po(pot, s_catalog, width=0)    

# If message string is in s_catalog and not t_catalog, convert and insert into t_catalog
for t_message in t_catalog:
    if not t_message.string:
        for s_message in s_catalog:
            if s_message.id == t_message.id:
                t_message.string = s2t_converter.convert(s_message.string) 

# Write result to zh_Hant.po
with open(t_path, 'wb') as pot:
    write_po(pot, t_catalog, width=0)  
```

 I'm having trouble understanding what should be put in the makefile. Is `@PYTHONPATH=. $(env_bin)/python cli/convert-chinese.py` correct?

**Comment by Changaco** [comment]
Yes, that looks correct.

**Comment by biskwikman** [comment]
Before I open a PR I'd just like to check something. It looks like the `i18n_extract` removed the message id "Dashboard" and the corresponding message string from all of the po files. I'm not sure if this is expected behavior or not.

**Comment by Changaco** [comment]
I had forgotten about that problem, but it's not something you need to worry about.

**Comment by biskwikman** [comment]
Ok I've made the PR #2131

**Comment by yfdyh000** [comment]
What is the progress of the submission (#2131)? I am a native speaker and a longtime translator of Chinese Simplified. I noticed that some of the generated translations were not good (containing erroneous meanings) or non-native. About 50% of translated messages are available, 35% are non-native, and 15% are problematic.

For two-way conversions to fill in the gaps, the quality is questionable, they should definitely be 'fuzzy'. If it were simple word-to-word conversion, the big problems might be little. I don't know why this quality is not high.

**Comment by Changaco** [comment]
@biskwikman No. I'm almost done completing the work you did on this, I should be able to merge it soon.

**Comment by yfdyh000** [comment]
> @yfdyh000 I'm not sure of the status. But thanks for pointing out that the quality is not very good. I don't have any knowledge of Chinese so I couldn't tell. Is the result understandable or is it completely wrong?

As mentioned above, it includes many non-standard statements in Chinese Simplified, as well as some incomprehensible translations.

For example, the "badge" is converted to "徽章" & "征章", the "征章" which are incomprehensible.

Some errors derived from Chinese Traditional translations, such as the understanding is incorrect for "We may give your username to someone else if they ask for it, but not for at least a year after you close your account (unless we determine that you've been infringing a trademark).", the current translation says "We may give your username to someone else for accounts that have been closed for more than one year, unless trademark issues are involved.".
