### ISSUE TITLE
default to currency of the receiver

### ISSUE THREAD

**Issue by andrewharvey** [liberapay/liberapay.com#2129]
Being in Australia it seems the currency was automatically set to AUD however doing so falsely implies that I'm making a local payment, and now I discover my credit card has charged me an international transaction fee because this was not a local payment.

This should be made more clear that the payers credit card provider may charge an international transaction fee even when using a payers local currency.

In the future I'd opt to make a payment in the payees preferred currency so I can pay the exact amount they will receive and use a different international card which avoids these bank fees.

**Comment by Changaco** [comment]
Thank you for your feedback. We already have an issue about warning donors of international payments (#1537), so I'm closing this one.
