### ISSUE TITLE
Nearly all the Stripe transactions are partially refunded

### ISSUE THREAD

**Issue by unfa** [liberapay/liberapay.com#2132]
Hey - It's strange but or every donation I receive via Liberapay and Stripe I get "partially refunded" with like 0.5 EUR sent back. It seems automatic, do you know what that is?

![image](https://user-images.githubusercontent.com/491704/155983926-e4805d4d-6645-4cdf-a13c-6c705ddebec1.png)

**Comment by Changaco** [comment]
The partial refunds are how Liberapay recovers Stripe's fee on single-recipient payments.

**Comment by Changaco** [comment]
Closing as a duplicate of #1987.

**Comment by unfa** [comment]
I see. Is that a... loophole?

**Comment by Changaco** [comment]
More of a workaround than a loophole.

**Comment by LiamDawe** [comment]
Sorry to drag this up but is this actually documented anywhere be Liberapay?
