### ISSUE TITLE
Extraneous currency signs input by users aren't ignored

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#2134]
When a donor inputs `$10.00` or `10,00€` in a form, the amount is considered invalid and an error message is returned. It would be better to ignore the currency sign if it matches the expected currency.

**Comment by biskwikman** [comment]
@Changaco I'm interested in doing this. Could you point me to the relevant file that deals with the donation field?

**Comment by Changaco** [comment]
@biskwikman The `parse_money_amount` method in `liberapay/i18n/base.py`.

**Comment by biskwikman** [comment]
@Changaco I just made a PR (#2150 ) which I seems to fix this issue.
