### ISSUE TITLE
Bug in Removing a Movie & Inaccurate Total Movie Count 

### ISSUE THREAD

**Issue by AnthraxBeethrax** [liberapay/liberapay.com#2143]
There seems to be a bug when removing a movie from the list. If I continuously press refresh after clicking the 'remove from Flickchart', it keeps on subtracting the movie count, and it results to inaccurate total movie count. I don't know if there is a different issue regarding the total movie count, but there also seems to be bug in it also, because it doesn't correctly add the total count. I have 285 total movie count but it only says 280 movies, what happened to the remaining 5?

Attach below is the pdf file for proof.
[Remove_A_Movie_Bug_&_Total_Movie_Count_Inaccurate.pdf](https://github.com/liberapay/liberapay.com/files/8461160/Remove_A_Movie_Bug_._Total_Movie_Count_Inaccurate.pdf)

**Comment by Changaco** [comment]
This is the issue tracker for Liberapay, not Flickchart.
