### ISSUE TITLE
Reason for closing account

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#2144]
We might get some useful feedback from people who close their Liberapay accounts if we add an optional text input to ask them why.

Implementation requirements:

- [x] Giving feedback doesn't prevent the deletion of the account, i.e. it's stored in a new table which doesn't have a foreign key constraint on the `participants` table.
- [x] The feedback is limited in length.
- [x] The feedback is displayed in the `/admin/users` page.
- [x] The feedback is displayed in the `/~/admin` page.
- [x] The feedback is automatically deleted after some time (a year?) if the account has been deleted or reopened.

**Comment by biskwikman** [comment]
Should the text of the feedback be stored in the database?

**Comment by Changaco** [comment]
Yes. I've added an implementation checklist to the issue description.

**Comment by biskwikman** [comment]
@Changaco 
I'm trying to figure out how to add a new table. According to the readme, any changes should be put in `sql/branch.sql`. Becuase there is no `branch.sql` file I'm unsure how to go about this. Should I copy the entire contents of `sql/schema.sql` into a new `branch.sql` file, and then edit the `branch.sql` file? 

Also, to see the changes in the database, is running `make schema` sufficient?

**Comment by Changaco** [comment]
@biskwikman The content of the `sql/branch.sql` file automatically ends up in [the `sql/migrations.sql` file](https://github.com/liberapay/liberapay.com/blob/master/sql/migrations.sql), so that file is a convenient way to see the history, but you can also [look at the commit history](https://github.com/liberapay/liberapay.com/commits/master/sql/branch.sql) and [search for the file's name in the code](https://github.com/liberapay/liberapay.com/search?q=branch.sql) to fully understand how it works.

`make schema` recreates the schema from scratch, deleting all data in the process. To check that your `branch.sql` is correct, you can use `make test-schema`. To apply the changes to the database used by your local instance, you can use `psql liberapay -f sql/branch.sql`.

**Comment by biskwikman** [comment]
@Changaco I'm making some progress on this. One thing I keep running into that I don't understand is that the `Participant` class seems to have a lot of properties that I can't seem to find the definitions of. Things like `id`, and particularly `db`. Do you know where I can see where these are defined?

**Comment by Changaco** [comment]
@biskwikman Most of the attributes, including `id`, correspond to the columns of the `participants` database table, which you can see in the `sql/schema.sql` file. The `db` attribute is a convenience reference to the database object (see [the postgres.py docs](https://postgres-py.readthedocs.io/en/latest/)).

**Comment by jfoclpf** [comment]
Can't close my account, WHY?

**Comment by jfoclpf** [comment]
Everytime I try to close the accoount, it requests my credentials which I give, and then it come to home page. Why???
