### ISSUE TITLE
Cannot turn off donations

### ISSUE THREAD

**Issue by LiamDawe** [liberapay/liberapay.com#2179]
Hi, trying to turn off people donating.

When I select this:

> I'm here as a patron, and politely decline to receive gifts. 

I get this error:

> `goal` value -1 is less than 0

> URL: https://liberapay.com/gamingonlinux/edit/goal
> Method: POST
> Referer: b'https://liberapay.com/gamingonlinux/edit/goal'
> User-Agent: b'Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0'
> Time: 2022-09-14 17:02:23.453765+00:00
> Response code: 400
> Response message: '`goal` value -1 is less than 0'
> Error location: utils/__init__.py:470
> User: <Participant #19938 'gamingonlinux'>
> Locale: en_GB
> Website version: 672

**Comment by LiamDawe** [comment]
Can you ping me here when it's actually live on site?

**Comment by Changaco** [comment]
It's live now.
