### ISSUE TITLE
Paypal issue

### ISSUE THREAD

**Issue by Benianus3D** [liberapay/liberapay.com#2187]
Hi,
Why PayPal made accounts permanently limited because of Liberapay transactions, I've got this problem two-time consecutively
and I'm obliged to open another account each time.
I hope this problem will be resolved

**Comment by Changaco** [comment]
There's nothing Liberapay can do about this. You have to work out the problem with PayPal.

**Comment by Changaco** [comment]
No, we don't know why PayPal restricts your accounts. You have to ask PayPal.

**Comment by Benianus3D** [comment]
But this problem happens after I received a donation across Liberapay.
I received a donation across gumroad and I didn't have the same problem
