### ISSUE TITLE
Email verification not mandatory

### ISSUE THREAD

**Issue by almereyda** [liberapay/liberapay.com#221]
I have just signed up and didn't need to verify my email address before being able to log in.

This sounds like another nice spamming option as with #61, but this time its your database.

**Comment by almereyda** [comment]
I see, that's not mandatory and just trying to make it easier for people?

https://liberapay.com/almereyda/emails/

**Comment by Changaco** [comment]
Welcome, @almereyda :-)

The fact that we don't require validating the email address immediately is due to both historical reasons and the wish to make the sign-up process less annoying for the user.
