### ISSUE TITLE
Patrons page doesn't mention the lack of support for secret donations through PayPal

### ISSUE THREAD

**Issue by bjorn3** [liberapay/liberapay.com#2219]
I just clicked the option to explictly not show who my patrons are in the settings. On the settings page it shows "You've chosen not to see who your patrons are." However on the donation page it shows "This donation won't be secret, you will appear in bjorn3's private list of patrons." Which of those two statements is true?

**Comment by Changaco** [comment]
Both statements are true, but the first one is incomplete. Secret donations are only possible if a Stripe account is connected in https://liberapay.com/about/me/payment

**Comment by bjorn3** [comment]
Right, I do get emails from paypal with the email address and name of the person donating. In any case the message on the donation page before I chose an option is incorrect then. That one did talk about donations being secret due to me not having chosen anything.

**Comment by Changaco** [comment]
> In any case the message on the donation page before I chose an option is incorrect then. That one did talk about donations being secret due to me not having chosen anything.

This bug is now fixed.
