### ISSUE TITLE
A new model of funding through sponsor pools

### ISSUE THREAD

**Issue by priyanshujoshi1** [liberapay/liberapay.com#2221]
https://colinhacks.com/essays/a-new-funding-model-for-open-source-software
check the above link it includes an innovative model of using a personal pool for users where they can put money and the money will be distributed to the projects they have chosen within a time period mentioned by the users,  though the above model is supposed to fund open source, this model has the potential to increase donation amount, make it easy for the users to provide donations, make a fixed stable expected donation amount; like a salary for the projects. i personally want Libra pay to prosper, it has the potential to be used for any type of project. i personally want Libra pay to prosper hopefully they implement this system as quickly as possible, thank you.
Priyanshu Joshi

**Comment by Changaco** [comment]
Closing in favor of #54.
