### ISSUE TITLE
Cannot pledge to team

### ISSUE THREAD

**Issue by Apacelus** [liberapay/liberapay.com#2229]
When I try pledging to my own team (to test if it works) I get this message in the "giving" page on my account, "Cannot be renewed because the account of the recipient isn't ready to receive new payments."

The receiving page of the team doesnt have any options.

The team name is: Eupnea-Project

**Comment by Apacelus** [comment]
I already set that up. Do all Team members need to set up a payment method for th Team to be able to receive donations

**Comment by Changaco** [comment]
No, one is enough. However, you can't donate to yourself, not even through a team. Moreover, you're actually rejecting all donations with your choice in <https://liberapay.com/Apacelus/edit/goal>, so right now nobody can donate to you or the team.

**Comment by Apacelus** [comment]
I have (temporarily) enabled donations to my personal account and created another account to try donating to the team, but Im still getting the same message

**Comment by Changaco** [comment]
You have to change your take from the team to something other than zero: https://liberapay.com/Eupnea-Project/income/

You can input either `auto` or a specific amount.

**Comment by Apacelus** [comment]
@Changaco a slightly unrelated question, but when someone donates to the Team, can they see any of my paypal accounts info?

**Comment by Changaco** [comment]
PayPal payments always enable the payer and recipient to see each other's names and email addresses. That's why, as mentioned in <https://liberapay.com/about/privacy>, you should use a business PayPal account instead of a personal one if you don't want to leak your personal data.
