### ISSUE TITLE
Unable to bind my Mastodon username

### ISSUE THREAD

**Issue by twoheartliu** [liberapay/liberapay.com#2230]
callback like this:
```
URL: https://liberapay.com/on/mastodon/redirect
Method: POST
Referer: b'https://liberapay.com/on/mastodon/redirect'
User-Agent: b'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36'
Time: 2023-04-01 02:15:33.640751+00:00
Response code: 502
Response message: 'nofan.xyz 真的是一个 Mastodon 的服务器？目前看起来不像。'
Error location: elsewhere/mastodon.py:78
User: <Participant #1817780 'nofan'>
Locale: zh_Hans_CN
Website version: 692
```

> The upstream issue has been fixed. The documentation for the new API endpoint is at https://docs.joinmastodon.org/methods/accounts/#lookup

I tried calling it in Postman and the result was returned normally.

![image](https://user-images.githubusercontent.com/19301712/229261237-0aff8e8c-58e4-47bb-a41d-dbb41f85ac61.png)

Looking forward to your response.

**Comment by Changaco** [comment]
Connecting your account failed because the API request was challenged by Cloudflare instead of being transmitted to the nofan.xyz server. The Cloudflare configuration of nofan.xyz needs to be modified to never challenge API requests.

**Comment by Changaco** [comment]
Closing in favor of #2233.

**Comment by twoheartliu** [comment]
![image](https://user-images.githubusercontent.com/19301712/230536227-c10fa84d-ec29-4bc8-9f7d-7759f5ec7d87.png)

Additionally, when you deselect [Bot Fight Mode], linking to Mastodon will work normally.
