### ISSUE TITLE
Emails incorrectly encoded/decoded

### ISSUE THREAD

**Issue by hermann-san** [liberapay/liberapay.com#2239]
Hi, 
when I receive a confirmation e-mail about a payment, there are some German characters that are not visible. That implies that those e-mails are not localized for German language. Here is an example.
Those are characters like uäöü but also €  Euro
I can still understand the e-mail, but It would be nice if the e-mails  would be localized for German language

```
Hallo,
Die am 17.04.2023 eingeleitete Auszahlung Ã¼ber 5,00Â â‚¬ ist ausgefÃ¼hrt worden.
Vielen Dank fÃ¼r diese Spende!
```

**Comment by Changaco** [comment]
The problem isn't in Liberapay. It looks like the software you're using to read the email is incorrectly decoding it using one of the ISO-8859 standards, when in fact it's supposed to use the UTF-8 standard.

**Comment by hermann-san** [comment]
I'm using Outlook 2019 - standard installation. 
I've tested it just now and there is no problem sending and receiving e-mails with those special characters, in general. 
Also I've check a number of E-mail newsletters and stuff that I receive and those characters display correctly.
I've these issue only with Liberapay (as far as I remember). All Liberapay E-mails since 2020 (about 20 E-mails) are affected
I personally don't have a problem with these minor issues. If you'd like me to check something, just let me know. Else I will just ignore this in the future.

**Comment by Changaco** [comment]
I've found a possible explanation for this issue, and fixed the cause.

@hermann-san To check whether the problem is indeed fixed for you, I suggest that you [log into your account](https://liberapay.com/log-in) via email (by leaving the password field empty).
