### ISSUE TITLE
Account linker doesn't understand user-input profile URLs for single-domain platforms like GitHub

### ISSUE THREAD

**Issue by spirillen** [liberapay/liberapay.com#2251]
There doesn't seem to be a user named https://github.com/spirillen on GitHub.

URL: https://liberapay.com/on/github/associate?code=ad3d52c6fcf8d5ea6913&state=somecode
Method: GET
Referer: None
User-Agent: b'Yep I used a browser'
Time: 2023-06-04 00:00:00.000001+00:00
Response code: 404
Response message: "There doesn't seem to be a user named https://github.com/spirillen on GitHub."
Error location: unknown
User: <Participant #1822611 'spirillen'>
Locale: iso_lang
Website version: 700

**Comment by Changaco** [comment]
You're supposed to input only your username, i.e. `spirillen`, not the URL of your profile.

I will tweak the code to accept profile URLs even for centralized platforms like GitHub.

**Comment by spirillen** [comment]
Ahh ok, maybe add that as a comment below the box while you add it :smile:
