### ISSUE TITLE
Trying to link a Twitter account no longer works

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#2255]
Liberapay isn't allowed to access Twitter's API anymore.

![Screenshot of Twitter's developer portal. Text: “Suspended - This App has violated Twitter Rules and policies. As a result, it can no longer be accessed. For assistance, submit a support ticket.”](https://github.com/liberapay/liberapay.com/assets/1581590/57daf591-cee3-48e4-957b-a30879ceb490)

**Comment by trebmuh** [comment]
What does Liberapay did wrong?

**Comment by jorgesumle** [comment]
> What does Liberapay did wrong?

It was Twitter, they now [charge money to programs that use their API](https://techcrunch.com/2023/02/08/twitter-says-the-basic-tier-of-its-api-will-cost-100-per-month/). A solution would be to scape the site to avoid using their API, like programs like Nitter and Invidious do.

**Comment by Changaco** [comment]
I have deleted the suspended API application and created a new one. This solves the issue for now, but the new application may end up being blocked as well.
