### ISSUE TITLE
Use black on yellow for the logo

### ISSUE THREAD

**Issue by TheEvilSkeleton** [liberapay/liberapay.com#2259]
I'm not visually impaired, but Liberapay's logo has low contrast to the point I need to squint my eyes to see it, due to it being white on (light) yellow:

![](https://avatars.githubusercontent.com/u/12560099?s=200&v=4)

I suggest using black on yellow, to bump contrast and increase legibility:

![liberapay_logo_black-on-yellow](https://github.com/liberapay/liberapay.com/assets/50847364/51707a87-77f2-4511-88b2-0e5a0abde563)

**Comment by Changaco** [comment]
I'm okay with phasing out the white-on-yellow version of the logo in favor of the black-on-yellow if there is consensus.

Does anyone object to this change?

**Comment by trebmuh** [comment]
I'm all good with this as well

**Comment by idotj** [comment]
Any news about this change?
Talking with some devs about Liberapay we saw that due to the logo the international and French accessibility tests failed (WCAG and RGAA). Color contrast is under the min values accepted.
The Yellow - Black version will work.

**Comment by toby3d** [comment]
I apologize, but in hindsight it looks funny:

![image](https://github.com/liberapay/liberapay.com/assets/5412322/1ec26311-904f-41a9-893e-ad0bc644b5cf)
![image](https://github.com/liberapay/liberapay.com/assets/5412322/f35a5b27-a46c-4dfe-b05c-cc2abe4e4d1f)
