### ISSUE TITLE
Allow different Instruments to be associated with differerent recipients

### ISSUE THREAD

**Issue by JohnLines** [liberapay/liberapay.com#2269]
The credit card I use most adds an extra charge for currency conversion, so I tend to use a different card, which does not add an extra fee, for transactions in Euros or other currencies. I have both cards registered in Liberapay, and can switch default card manually before the payment is taken, but it would be a useful feature to be able to associate an Instrument with payments on the Schedule.

**Comment by Changaco** [comment]
I think it would be simpler to add the possibility of specifying which currencies an instrument should be used with, rather than which donation recipients it should be used for.

**Comment by Changaco** [comment]
@JohnLines It's now possible to define a payment instrument as the default for a specific currency. You should see a new `Set as default for {currency_code}` button in https://liberapay.com/about/me/routes/
