### ISSUE TITLE
Encode addresses with base64 in email verification links

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#227]
https://github.com/gratipay/gratipay.com/pull/3965

We should:

- [x] differentiate links in the new and old formats, for example by using another querystring key such as `email64`
- [x] use our `b64{en,de}code_s` functions, because standard base64 isn't querystring-safe (it can have plusses, and equal signs for padding)

**Comment by aandis** [comment]
Closed in https://github.com/liberapay/liberapay.com/pull/241.
