### ISSUE TITLE
"patreon has no true competitors" article

### ISSUE THREAD

**Issue by lahwran** [liberapay/liberapay.com#2280]
Hey! thought y'all should see this article, "patreon has no true competitors" - I'm going around and sending it to all patreon competitors I can find. Hopefully it either gives you an opportunity to say "hey wait, we can do all those things!" to the author, or can inspire feature development! https://siderea.dreamwidth.org/1824441.html

AI generated overview (not a replacement for the article, which is quite detailed, just an overview to motivate why I'm linking it/why I think it's worth reading):

- Patreon has no true competitors because other platforms fail to understand Patreon's key features and value propositions for creators, such as supporting pseudonyms and confidential identities.
- An important Patreon feature is the "by-work" funding model where patrons pledge per creation rather than monthly, without commitments on output from creators.
- Effective creator-patron platforms must keep creator identities like wallet names confidential.
- Patreon's audience relationship management system and API have room for improvement to better serve creators.
- Payment processing fees have historically posed a challenge for micropayments online, which Patreon addressed through bundling small pledges.
- Patreon's underlying operations handling multiple funding models and variations are immensely complicated.
- Competitors could outperform Patreon by focusing on simplicity through a minimal viable product that addresses core needs.
- Patreon's technology choices have not always prioritized accessibility and inclusiveness.
- Supporting the basic patronage model alone presents significant challenges.
- There is opportunity for a platform that improves upon Patreon's weaknesses while capturing the essence of what makes it valuable to creators.

Hopefully this is of use. If not, close away.

**Comment by awebeer256** [comment]
Is there any interest in adding "by-work" funding? The article's author is pretty adamant that it's *extremely* important.

**Comment by Changaco** [comment]
@awebeer256 See #839.

**Comment by awebeer256** [comment]
@Changaco Thanks. So it looks like there's some interest, but the feature is probably not going to be landing soon.
