### ISSUE TITLE
Proposal: Allow users to set up a payment rotation, paying a different project each month

### ISSUE THREAD

**Issue by Fell** [liberapay/liberapay.com#2298]
### Background
Let's say I am willing to give 10€ per month to my 10 favourite projects or creators. 

### Problem
Splitting that up into 10 individual payments of 1€ would waste a lot in fees.

### Proposed solution
Payment rotations. Instead of paying 10€ per month and splitting it across all my projects, I pay 10€ to a different project each month.

### Simple implementation
There are multiple ways this could be implemented. The simplest way would be to allow users to set a **custom start date** for a yearly payment. This way, I could set up something like:

Every January, I pay 10€ to X
Every February, I pay 10€ to Y
Every March, I pay 10€ to Z

### Complex implementation
It could also be somewhat more sophisticated, where Liberapay offers to automatically manage your rotation. You basically just enter which project you want to support and how much you want to spend. The system could create a rotation that automatically updates when new projects are added, like this:

| Month | Project paid |
| ------- | - |
| January | X |
| March | Y |
| February | X |
| April | Y |
| (New project added:) | (Z)
| May | Z |
| June | X |
| July | Y |
| August | Z |
| September | X |
| October | Y |

What do you think?

**Comment by Changaco** [comment]
Thank you for taking the time to submit a proposal, but there already was a ticket for these specific improvements (#2109), so I'm closing this one as a duplicate.
