### ISSUE TITLE
Virtual Debit Card of Airtel Payments Bank is not supported.

### ISSUE THREAD

**Issue by AV971978** [liberapay/liberapay.com#2313]
I tried to donate, but payment rejected by the software. Here is the actual message:

Payment Required

Your request has been rejected by our software. Please contact us if you need assistance.

Error message:

The payment processor Stripe returned an error: “Your card does not support this type of purchase. (request ID: req_AE5WrjYQmvo3D0)”.

If you decide to contact us please include the following debugging information in your message:

URL: https://liberapay.com/akkcvyas/giving/pay/stripe/?beneficiary=3&method=card Method: POST Referer: b'https://liberapay.com/akkcvyas/giving/pay/stripe/?beneficiary=3&method=card' User-Agent: b'Mozilla/5.0 (Linux; Android 5.1.1; SM-J200G) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.74 Mobile Safari/537.36' Time: 2024-01-27 17:49:34.142992+00:00 Response code: 402 Response message: 'The payment processor Stripe returned an error: “Your card does not support this type of purchase. (request ID: req_AE5WrjYQmvo3D0)”.' Error location: stripe/%payin_id.spt:107 User: <Participant #1844953 'akkcvyas'> Locale: en_US Website version: 725

**Comment by Changaco** [comment]
The payment attempt was rejected by your bank. Only they can tell you why.

I will look into changing the error page to make it less confusing.
