### ISSUE TITLE
make env errors out

### ISSUE THREAD

**Issue by aandis** [liberapay/liberapay.com#232]
```bash

"/usr/bin/python2.7" -c "import virtualenv" || pip install virtualenv
"/usr/bin/python2.7" -m virtualenv --no-download ./env/
Usage: virtualenv.py [OPTIONS] DEST_DIR

virtualenv.py: error: no such option: --no-download
make: *** [env] Error 2
```

**Comment by Changaco** [comment]
Hmm. What version of virtualenv is it?

**Comment by Changaco** [comment]
Here's what I have:

```
% python2 -m virtualenv --version
15.0.0
```

**Comment by Changaco** [comment]
Looking at [virtualenv's changelog](https://virtualenv.pypa.io/en/latest/changes.html) it seems `--no-download` was added in version 14.0.0 two months ago.

**Comment by Changaco** [comment]
And I added it to the `Makefile` two weeks ago in #210.

**Comment by aandis** [comment]
Mine's pretty old. `1.11.4` to be precise. Probably because I don't use them (yet) in independent projects. Why rely on the system's virtual env anyway? Isn't it better to have a [shipped version](https://github.com/gratipay/gratipay.com/blob/master/Makefile#L7) with the codebase and [use](https://github.com/gratipay/gratipay.com/blob/master/Makefile#L21) it for ease of setup?

**Comment by Changaco** [comment]
Vendoring dependencies is a questionable practice that has its own drawbacks (waste of space, etc). ;-)

**Comment by aandis** [comment]
@Changaco I got `make env` to gracefully finish after updating `virtualenv`. :tada: 
We can probably close this and merge #233 only by updating [readme](https://github.com/liberapay/liberapay.com#installation) to specify the needed `virtualenv` version.

**Comment by aandis** [comment]
> We can probably close

I actually get stuck on `make run` now.

```bash
PYTHONPATH=. env/bin/honcho run -e defaults.env,local.env env/bin/python liberapay/models/__init__.py
Traceback (most recent call last):
  File "liberapay/models/__init__.py", line 178, in <module>
    from liberapay import wireup
  File "liberapay.com/liberapay/wireup.py", line 21, in <module>
    import liberapay.billing.payday
  File "liberapay.com/liberapay/billing/payday.py", line 12, in <module>
    from liberapay.billing.exchanges import transfer
  File "liberapay.com/liberapay/billing/exchanges.py", line 27, in <module>
    from liberapay.models.participant import Participant
  File "liberapay.com/liberapay/models/participant.py", line 5, in <module>
    from hashlib import pbkdf2_hmac, md5
ImportError: cannot import name pbkdf2_hmac
make: *** [db-migrations] Error 1
```

**Comment by aandis** [comment]
From http://stackoverflow.com/questions/26770275/hashlib-pbkdf2-hmac-not-found-on-aws-centos-instance

> The pbkdf2_hmac was only just added to hashlib in Python 2.7.8 as part of PEP 466.

**Comment by Changaco** [comment]
Then I guess 2.7.8 is the lowest version we support, it's actually what we're using in production. I've added a commit to #233 that adds the python version requirement to the README.

**Comment by aandis** [comment]
Hm. I prefer not to mess with the python bundled with my OS (which is `2.7.6`). So I installed 2.7.8 separately, and then `$(python) -m virtualenv -p ./python2.7.8/bin/python2.7 --no-download ./env/` in `make env`. 
Local setup done! :tada:
