### ISSUE TITLE
Permit donors to have their name public but their donation amount private

### ISSUE THREAD

**Issue by lpil** [liberapay/liberapay.com#2331]
Hello!

Some donors have requested that their name is shown, but the amount they have donated is not, similar to how GitHub Sponsors works.

Is there a way to do this?

Thank you,
Louis

**Comment by Changaco** [comment]
Users can hide the amounts of all their donations by activating the first privacy option in <https://liberapay.com/about/me/edit/privacy>. It currently isn't possible to only hide the amounts of specific donations.
