### ISSUE TITLE
liberapay is not OpenSource

### ISSUE THREAD

**Issue by miltuss** [liberapay/liberapay.com#2333]
Good morning.  How is liberapay OpenSource?
liberapay is a proprietary, centralized company, using a centralized bank and a centralized website.  There's nothing open-source about this project from what I've seen!

In this project there is nothing different than with helloasso or others

**Comment by jorgesumle** [comment]
> iberapay is a proprietary, centralized company, using a centralized bank and a centralized website. There's nothing open-source about this project from what I've seen!

The payment providers (Paypal and Stripe) are proprietary and centralized. The source code of Liberapay (which is a donation platform intended for recurrent payments) is open source. You're right that this project is not fully free software, it's partially free/open source.

If you want to donate money only using open source, I recommend that you use some cryptocurrency. Maybe take a look at (Monero](https://www.getmonero.org/).

**Comment by Changaco** [comment]
You should read the actual [Open Source Definition](https://opensource.org/osd). Hint: there's nothing in it about decentralization.
