### ISSUE TITLE
Difficulty renewing donation in no longer accepted currency

### ISSUE THREAD

**Issue by dchmelik** [liberapay/liberapay.com#2338]
I can't renew any donations because some people/organizations I pledged to can't currently receive them, but trying to renew to those who can goes to an error page that others can't, and stops there.

**Comment by Changaco** [comment]
I see the problem. You have one donation up for renewal, but the recipient no longer accepts the currency you had chosen, so you have to modify the donation before renewing it, but the generic payment page (https://liberapay.com/about/me/giving/pay) isn't showing this donation at all.

While I work on a patch, you can overcome the problem by clicking on the “Modify” button of the renewable donation in your “Giving” page (https://liberapay.com/about/me/giving).
