### ISSUE TITLE
b64decode_s with unicode crashes.

### ISSUE THREAD

**Issue by aandis** [liberapay/liberapay.com#235]
Was working on https://github.com/gratipay/gratipay.com/pull/3965 when I ran into this.
According to http://stackoverflow.com/a/2230623/2643846

> b64decode quite explicitly can only take bytes (a string), not unicode.

Steps to reproduce - 

1. `b64encode_s('TheEnter?prise')` => `VGhlRW50ZXI_cHJpc2U~`
2. `b64decode_s('VGhlRW50ZXI_cHJpc2U~')` => `TypeError: character mapping must return integer, None or unicode` (deep down in the stack trace)

**Comment by Changaco** [comment]
You're not really supposed to pass a `unicode` object, base64 data is ASCII and should be `bytes`. I see two possible solutions: automatically encode, as you're proposing in #236, or raise a `TypeError` if the input object isn't an instance of `bytes`.

**Comment by aandis** [comment]
> You're not really supposed to pass a unicode object

Isn't `'VGhlRW50ZXI_cHJpc2U~'` an `str` object? A quick `type('VGhlRW50ZXI_cHJpc2U~')` gives `<type 'str'>`. Something else I am missing here?

**Comment by Changaco** [comment]
> Isn't `'VGhlRW50ZXI_cHJpc2U~'` an `str` object?

It depends. [test_utils.py](https://github.com/aandis/liberapay.com/blob/70/tests/py/test_utils.py#L1) uses `from __future__ import unicode_literals`, so in that file `''` is `u''` and its python2 type is `unicode`, not `str`.
