### ISSUE TITLE
Create a legal structure

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#24]
*This thread is in french.*

Y a-t-il des français prêts à participer à la création d'une structure légale pour Liberapay ?

Ping @MartinDelille @SimonSarazin @pscoffoni @ManUtopiK

Les étapes de création d'une association: http://vosdroits.service-public.fr/associations/F3109.xhtml

**Comment by pscoffoni** [comment]
Hello,
Je vois que tu ne lâches pas l'affaire. Bravo ! Il y a effectivement du boulot, la rédaction des statuts entre autre... En toute honnêteté je peux suivre, relire, mais je ne pourrais pas être moteur. Veux-tu que je fasse un peu de relais autour du projet pour voir si il y a moyens d'attirer des contributeurs ?

**Comment by Changaco** [comment]
Je ne cherche pas forcément quelqu'un qui soit "moteur", simplement une ou plusieurs personnes pour faire partie de l'association, parce qu'il faut être au moins deux pour pouvoir la créer.

Tu peux faire un appel à contribution si tu penses que ça vaut le coup. Outre le côté légal il manque encore un logo, des traductions, et des fonctionnalités pour le site lui-même. Le README explique [comment contribuer](https://github.com/liberapay/liberapay.com/#readme) (en anglais).

**Comment by Changaco** [comment]
J'ai rédigé des statuts et un règlement intérieur, je vous invite à les lire et à les commenter (ici de préférence plutôt que sur le pad, pour la postérité) : http://pad.changaco.oy.lc/p/VTiihhPZzf

**Comment by Changaco** [comment]
Tout le monde s'en fout ? Ou vous êtes tous occupés ?

**Comment by Changaco** [comment]
Okay, it's time to move forward. I've created a separate [liberapay.org repository](https://github.com/liberapay/liberapay.org) for all discussions and decisions concerning the legal entity behind liberapay.com. Please subscribe to it if you want to be involved, and review [the pull request that contains the proposed bylaws and rules of procedure](https://github.com/liberapay/liberapay.org/pull/1) (I have translated them into English).

**Comment by Changaco** [comment]
If nobody steps up to be a co-founder then I'll have to start Liberapay as a one-person business instead of a non-profit organization.

*Si personne ne se manifeste pour être cofondateur je vais devoir lancer Liberapay en tant qu'autoentrepreneur plutôt qu'en association à but non lucratif.*

**Comment by pscoffoni** [comment]
Salut je pousse un article sur mon blog ce wekk-end pour essayer d'attirer des volontaires. Peut pas faire mieux dans l'immédiat à titre personnel.

**Comment by Changaco** [comment]
Merci. Si tu as des questions sur le projet n'hésite pas.

*And that goes everyone: if you have questions about the Liberapay project, don't hesitate to ask.*

**Comment by Changaco** [comment]
https://twitter.com/Changaco/status/674592533289312257

**Comment by Changaco** [comment]
Bonne nouvelle : un membre de l'association [Khaganat](http://khaganat.net/) m'a contacté via IRC suite à [mon dernier appel sur Diaspora*](https://framasphere.org/posts/1316974) et a offert son aide pour la création de l'association Liberapay. Pour le moment la discussion est en français dans le canal #liberapay du réseau Freenode.

*Good news: a member of the [Khaganat](http://khaganat.net/) organization contacted me via IRC after [my last post on Diaspora*](https://framasphere.org/posts/1316974) and offered their help in creating the Liberapay organization. For now the discussion is happening in french in the #liberapay chan of the Freenode network.*
