### ISSUE TITLE
Sign-up process is not able to skip a bad MX or multiple MX entries for an e-mail site

### ISSUE THREAD

**Issue by JeeeK** [liberapay/liberapay.com#2459]
If registering an e-mail address only the MX with the best (lowest) preference seems only to be used or checked and if this MX is not reachable the sign-up process stalls with the error "Unser Versuch, eine Verbindung mit dem E-Mail-Server tuwien.ac.at herzustellen, schlug fehl (Fehlermeldung: „timed out“)." (German). According to a correct MTA behavior the sign-up process should walk through all DNS provided MX entries from the best to the worst preference and try them until a connection could be established.

**Comment by Changaco** [comment]
The algorithm was designed to try up to 3 unresponsive IP addresses one after the other in less than 30 seconds before giving up, but there are a couple of bugs in it. It will be fixed in the coming days.

**Comment by JeeeK** [comment]
Thank you, the registration works know. :)
