### ISSUE TITLE
Donate without account

### ISSUE THREAD

**Issue by sils** [liberapay/liberapay.com#247]
I just had a donee who complaint about him having to register an account. It'd be neat to support those recurring paypal transactions or something like that without account, not sure how that works though.

**Comment by Changaco** [comment]
Yes, from the server logs I've noticed that some people seem to stop at the sign-up form. I've been considering requiring only the email address, making the username and password optional, and I've started on working on it, but it's not a straightforward thing to implement.

However once we do that, the donors will probably complain that we're asking for identity information in the next step, and that I can't work around, so we also need to get better at convincing donors to make the effort.

**Comment by Changaco** [comment]
@sils Good news: we no longer ask donors for a username and password. It's not exactly "donate without account", but it's as close to that as I could get.
