### ISSUE TITLE
Allow sending of messages together with payments

### ISSUE THREAD

**Issue by akarelas** [liberapay/liberapay.com#2493]
In some websites that accept donations I'm pseudonymous and wish to tell the website owner what my username on their website is, or which feature/bug I wish a developer to focus on. 

Of course, the owner should be able to block messages from me, to avoid spam and abuse. But I think the payer needs to know whether he's blocked, so he'll avoid writing long texts that will never be read.

**Comment by Changaco** [comment]
Closing as a duplicate of #771.
