### ISSUE TITLE
Pourriez-vous ajouter d'autres forges Gitlab ?

### ISSUE THREAD

**Issue by mbridon** [liberapay/liberapay.com#2514]
Gitlab est une forge (presque) libre, qui a vocation à être installée à peu près partout. :shrug:

Il serait vraiment super si vous pouviez ajouter d'autres forges publiques Gitlab pour les projets qui ne seraient pas hébergés sur Gitlab.com.

Par exemple, le projet [Cangjie](https://liberapay.com/cangjie) est hébergé sur Gitlab: https://gitlab.freedesktop.org/cangjie/ibus-cangjie

(not knowing whether to record the issue in French or English, I can do whichever you prefer :wink:)

**Comment by Changaco** [comment]
Duplicate of #661.
