### ISSUE TITLE
Users can't choose language of emails

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#252]
`email_lang` is filled automatically but the UI doesn't allow users to modify it.

**Comment by iangilfillan** [comment]
I think this is a fairly important bug to fix. I can't read any emails I receive from Liberapay and have to use Google Translate to make sense of them.

**Comment by Changaco** [comment]
@iangilfillan Yes, this issue is next on my list, sorry about the delay.

**Comment by Changaco** [comment]
@iangilfillan There is now a language selector at the bottom of <https://liberapay.com/about/me/emails/>.

**Comment by iangilfillan** [comment]
Thanks, that's perfect.
