### ISSUE TITLE
Implement 'keep me logged in'

### ISSUE THREAD

**Issue by revi** [liberapay/liberapay.com#261]
I'd like to be kept logged in for a while (ie. 2-4 weeks) so I don't have to log in often.

Maybe we need to implement 2FA first for re-authenticating for sensitive operations.

**Comment by Changaco** [comment]
2FA is not required, we only need to prompt the user to reenter their password before making important changes, such as modifying donation amounts.

**Comment by tuxayo** [comment]
Some keywords to make this issue more easy to find (some of the things I tried before finally finding this)
- logout
- logged out
- disconnected
- disconnect
- session

So from what I understand it's normal to currently have to log in something like once per day?

**Comment by Changaco** [comment]
> So from what I understand it's normal to currently have to log in something like once per day?

Yes.

**Comment by tuxayo** [comment]
Good, at least it's not some strange bug :)

Should the issue be split? There is the session duration topic and the 2FA topic.

**Comment by Changaco** [comment]
The issue for 2FA is #926.
