### ISSUE TITLE
When you add a new OAuth account, avatar resets

### ISSUE THREAD

**Issue by revi** [liberapay/liberapay.com#267]
I've been using GitHub as my avatar source. Since then I added OpenStreetMap, and I suddenly found a weird avatar and found it's forcibly reset to libavatar. It's usually expected that the user set an avatar and thinks it won't be reset unless user explicitly tells to do it, so it's more natural to leave it even when adding new OAuth account.

**Comment by Changaco** [comment]
You're right, there's a bug in `update_avatar()` that leads to `avatar_src` being overridden.

**Comment by Changaco** [comment]
+1 from @c-geek in #280.
