### ISSUE TITLE
Mistakes in translations can lead to 500s (internal server errors)

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#268]
https://sentry.changaco.oy.lc/share/issue/322e3437/

We should catch the exception, log it to sentry, and fall back to english.

**Comment by EliotBerriot** [comment]
I'd like to take a look at this one, but I lack some context. Is there anyway you could share the stack trace of the error ? (I have no access to the sentry)

**Comment by Changaco** [comment]
Everyone has access to the Sentry issues when the link has `/share/` in it. Unfortunately Sentry often fails to display issues that are too old. Maybe upgrading Sentry would show at least an error message.

**Comment by Changaco** [comment]
I can't give you a traceback, I don't think I have one, but basically the line that can trigger an uncaught exception is <https://github.com/liberapay/liberapay.com/blob/144/liberapay/utils/i18n.py#L149>. Because for example `"{1}".format(0)` raises `IndexError: tuple index out of range`. The solution is to wrap the calls to `i_format()` in `get_text()` and others.

**Comment by Changaco** [comment]
Note that since this issue was opened our PO files and Weblate project configuration were modified to properly treat messages as `python-brace-format` instead of `python-format` (see #403), and the `pytest-i18n-browse` Makefile target was created (see #404). All that has added protections against bad translations reaching production.

**Comment by Changaco** [comment]
https://sentry.io/share/issue/cd44bc9622494ea3a1c41f0e68b3fce7/
