### ISSUE TITLE
Anonymity prevents thanking sponsors

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#271]
Even if we explicitly allowed users to thank their sponsors (https://github.com/liberapay/liberapay.org/issues/12) they couldn't do it because donations are anonymous. We need to implement a way for donors to reveal their identity if they and their donees want to.

**Comment by Changaco** [comment]
+2 from https://www.peppercarrot.com/en/article418/peppercarrot-is-now-on-liberapay#c0418-1468

**Comment by bitJericho** [comment]
I'd love this feature. With Patreon in the news, now would be the perfect time to implement this feature which is a big pain point for users switching from there.

**Comment by mattbk** [comment]
-1 from me. I think it's a legal bag of worms.

**Comment by gregzaal** [comment]
> legal bag of worms.

Forgive my ignorance, but why? Would an opt-in to be recognised (but default to anonymous) solve this?

**Comment by mattbk** [comment]
Sorry, I posted in the wrong place. Carry on.

**Comment by mattbk** [comment]
Sorry, I posted in the wrong place.

Although I'm personally in favor of anonymous donations because then donors can't demand things in return for their donations ("I give you $10 a month, make me a sandwhich."), is there any reason not to do this?

**Comment by trebmuh** [comment]
The "pure donation" vision is the main "why" I came first to liberapay.

I've nothing against introducing a "patreon/tipeee/..." business model as long as the "pure donation" thing is kept possible and clear enough (I don't want to have nationstate-taxes coming to me thinking I'm making money of a project).

@Changaco : is LP still on this line?

**Comment by Changaco** [comment]
Yes, pure donations will always be possible on Liberapay.

**Comment by trebmuh** [comment]
Thanks for the clarification @Changaco 👍

**Comment by davidak** [comment]
Could there just be a list of supporters on a users public profile with the last point "and X anonymous supporters"? Maybe hide it by default for simplicity and make it visible by clicking on some button "show supporters".

Also, a user might want to show which projects they support publicly. Like on crowdfunding pages.

**Comment by rugk** [comment]
…or implement an anonymous way to thank sponsors. So sponsored people would have a button "Thank my sponsors", where they can write a message to all sponsors – or maybe only to the new once since their last message or so.

**Comment by ashledombos** [comment]
I support this, I really think donators could choose whether to give anonymously or not (and ideally publicly or not, for example you could provide your user/avatar information to the team, but not display it publicly, and you could hide it both to public and to the team etc…), and ideally they should be able to change it later. 
Furthermore it's not clear that it's forced to be anonymous, I published a text to say donators will be thanked for discovering after all donations are anonymous… At least maybe (temporary?) add a warning telling clearly that donations are anonymous…

**Comment by jurra** [comment]
I support the option of anonimous or visible, both could make sense for different contexts.

**Comment by DansLeRuSH** [comment]
To be honest, that's the evolution I'm waiting for before switching my entire donation management to Liberapay :smiley:

**Comment by DansLeRuSH** [comment]
Hi, any news about this ?

Best regards,
Franck

**Comment by Changaco** [comment]
I finally started working on this yesterday, as it occurred to me that I should probably get this done before trying to create new versions of the donation form (#1584).

This is what I have so far:

![Screenshot of a donation secrecy level selector](https://user-images.githubusercontent.com/1581590/76143041-db00f500-6073-11ea-8d3a-e0b65841e9b9.png)

**Comment by trebmuh** [comment]
Nice!
Could this be like this IF AND ONLY IF the donnee accept each of the 3 steps?

To reformulate, as a donnee I'd like to be forbid my donators to make a private/public donation, because of taxes purpose.

**Comment by Changaco** [comment]
The initial implementation of “non-anonymous” donations is scheduled for deployment on December 9th. A blog post will be published then.

**Comment by Changaco** [comment]
It's a day later than planned, but here's the announcement: https://medium.com/liberapay-blog/lifting-the-veil-of-anonymity-479dadd369be
