### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#278]
In https://github.com/liberapay/liberapay.com/issues/183#issuecomment-215655363 @pgno proposed a new logo:

![logo/widgets proposal](https://cloud.githubusercontent.com/assets/18536610/14910637/86289cc0-0def-11e6-885a-cc3c693c284d.jpg)

Here's how it was made:

> - logo is just the letter "lp" in Ubuntu Bold Italic font

Who's in favour of changing our logo to this new one?

For reference, this is our current logo:

![logo v1](https://raw.githubusercontent.com/liberapay/liberapay.com/82/www/assets/liberapay/icon.200.png)

**Comment by revi** [comment]
+1 for me.

**Comment by Changaco** [comment]
I guess we should do a reverse image search to check that this logo or a similar one isn't already being used by someone else.

**Comment by pgno** [comment]
I've quickly uploaded the logo (with and without brand name) on my site and run a reverse search on https://images.google.com/ and https://www.tineye.com/. It seems to be ok (the use of italic with the word "Pay" obviously remind me PayPal, but it dont fell like it's an issue...).
Here are the two urls to run the tests by yourself or use a different and more accurate search engine
- http://pgno.xyz/wp-content/uploads/2016/04/liberapaylogo.jpg (with brand name)
- http://pgno.xyz/wp-content/uploads/2016/04/liberapaylogo_short.jpg (without brand name)
I agree that i have to look for another color (#183). And if you have any "color allergy" or a favorite color, let me know :-)

**Comment by revi** [comment]
>I guess we should do a reverse image search to check that this logo or a similar one isn't already being used by someone else.

Yeah... Thinking about that, I think [bitpay](https://bitpay.com) may look way too similar to the proposed one.

**Comment by Changaco** [comment]
> Yeah... Thinking about that, I think [bitpay](https://bitpay.com) may look way too similar to the proposed one.

It's a similar style, but not exactly the same font, and not a two-letters logo, so I think we're fine as long as we don't use the same brand color.

**Comment by Changaco** [comment]
> I've quickly uploaded the logo (with and without brand name) on my site and run a reverse search on https://images.google.com/ and https://www.tineye.com/. It seems to be ok

I concur.

> And if you have any "color allergy" or a favorite color, let me know :-)

Reticketed as #281.

**Comment by Changaco** [comment]
BTW, here are logos from some other crowdfunding platforms:

![tipeee](https://pbs.twimg.com/profile_images/456777690112983040/_4qDlHCY_400x400.jpeg)
---
![patreon](https://pbs.twimg.com/profile_images/458690209660416000/bWhe-J8I_400x400.png)
---
![gratipay](https://pbs.twimg.com/profile_images/710419385098366976/fp6x2Ci3_400x400.jpg)
---
![bountysource](https://pbs.twimg.com/profile_images/378800000188347152/b3e8c86ff3a8e3f3c7d735cd79454601_400x400.png)
---
![opencollective](https://pbs.twimg.com/profile_images/718469174675177472/f7YQoBux_400x400.jpg)
---
![snowdrift](https://snowdrift.coop/static/img/logo-big.png?etag=4heUY2_6)
---
![flattr](https://pbs.twimg.com/profile_images/674159121583640577/u2ayaR-T_400x400.png)

**Comment by Changaco** [comment]
@pgno Can you upload the source files of your proposal so I can experiment with other colors for #281?

**Comment by pgno** [comment]
Hello, 

Here is a SVG file with the logo in black. I've also add a test with another font (for the brand name, not the logo) for those who were concerned by the proximity with others brands. The font is Kanit, from Google Font.

[logo_black.zip](https://github.com/liberapay/liberapay.com/files/244037/logo_black.zip)

**Comment by Zatalyz** [comment]
Sweet logo, I like it. Not in pink. Please :)
