### ISSUE TITLE
Handle base64 decode failures

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#28]
In some places we use the `b64decode` function on data we receive from the client. This can result in "500 Internal Server Error" responses when in fact we should return a "400 Bad Request".

This is a small issue, pretty easy to fix, ideal for new contributors.

**Comment by kthurimella** [comment]
Hey @Changaco, is this still an issue? I'd like to contribute and it seems like this could be low hanging fruit for a contribution for me!

**Comment by Changaco** [comment]
Hey @kthurimella, welcome. :-)

Yes, this is still an issue. A `git grep base64` shows that we're still using the `b64decode` function imported straight from the standard `base64` module. What we need is to make a wrapper function that catches exceptions and raises a `Response(400, "invalid base64 input")` instead. The `liberapay.utils` module would be the right place to put it.

**Comment by kthurimella** [comment]
Hey @Changaco I've added a small commit here. I was just wondering if I'm going in the right direction here:

https://github.com/kthurimella/liberapay.com/commit/78e5f612ad176568551336230f994d72d3da7474

Do I have to replace all usages of b64decode (specifically in the spt files)?

**Comment by Changaco** [comment]
You're going in the right direction, but the `b64decode` calls you've replaced are the ones that don't need to be, because it's data from the DB that we've encoded ourselves, not user input. It's the calls in `templates/base.html` and `*.spt` files that need replacing.

Cosmetic note: you can drop the `_wrapper` suffix in the function name. Also please try to respect [coding conventions](https://www.python.org/dev/peps/pep-0008/), notably that imports are split into three groups (standard, third-party, local) and usually ordered alphabetically within those groups.

**Comment by Changaco** [comment]
Ping @kthurimella.

**Comment by Changaco** [comment]
Decode failures have happened in production, it's time to land this. I'm going to cherry-pick @kthurimella's commit into the PR I'm making.
