### ISSUE TITLE
The team logo is changing on its own

### ISSUE THREAD

**Issue by c-geek** [liberapay/liberapay.com#280]
Hey, I'm Duniter's founder.

I've successfully created the Duniter team, then I connected it to GitHub and use GH's logo. That was fine, I started to see the dune.

But then I connected Twitter account and the logo changed back to an auto-logo (libravatar). I've switched back to GH logo, so now it's fine, but I just wanted to report it.

Have a good day!

**Comment by Changaco** [comment]
Yes, sorry about that, it's a known bug: #267. Closing this issue as a duplicate.
