### ISSUE TITLE
Brand color

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#281]
To achieve #183 and complete #278 we need to decide on a brand color.

We've been using some red for our [widgets](https://github.com/liberapay/liberapay.com/blob/82/www/assets/widgets/donate.svg.spt) and on [Twitter](https://twitter.com/liberapaye), but it is relatively close to [Tipeee](https://twitter.com/tipeee_officiel)'s red/pink.

**Comment by pgno** [comment]
Made a few tests... (SVG file in a zip at the end for those who want to play with it)
I can also take a look at this url : http://www.flatuicolorpicker.com/ for some "trendy" flat design colors.
![logo_color](https://cloud.githubusercontent.com/assets/18536610/14941156/433db932-0f92-11e6-9b9e-8fe865abfb14.jpg)
[logo_color.zip](https://github.com/liberapay/liberapay.com/files/244039/logo_color.zip)

**Comment by Changaco** [comment]
I'm leaning towards the top-right one, a yellow/sunny color palette. Opinions?

**Comment by Calinou** [comment]
> I'm leaning towards the top-right one, a yellow/sunny color palette. Opinions?

I'm not against that color, but it looks a tad too bright to me (and thus not very readable on a white background).

**Comment by Changaco** [comment]
I didn't necessarily mean that exact color, though I think it's fine even on a white background. I meant that I'm tempted to go with a yellow/sunny theme for Liberapay. Purple doesn't look right to me for some reason, and the other colors are quite common.

**Comment by Zatalyz** [comment]
Yellow or orange for me. I think it's interesting to evocate gold (with color, graphism), and not traditional money (blue, green, used by banks). I like purple but don't see possible symbolism with pay.

**Comment by Changaco** [comment]
Dark orange is used by Patreon.

I don't want to associate Liberapay to gold or any other color that represents a specific currency.

**Comment by Changaco** [comment]
https://liberapay.com/ is now yellow and has a new logo! Thanks to @pgno!

**Comment by revi** [comment]
Yay! :+1:
