### ISSUE TITLE
Give an option on user profile to refuse search engine

### ISSUE THREAD

**Issue by revi** [liberapay/liberapay.com#283]
For example I don't want search engines crawl my profile for some reasons, but it doesn't appear to be possible to disallow them.

It would be happy to be able to put

```html
<meta name="robots" contents="noindex, nofollow">
```

in the profile's html file when set by users.

(This is just a wishlist and you don't have to put this in a high priority :-p)

**Comment by Changaco** [comment]
We already have that: https://en.liberapay.com/about/me/settings/ → Privacy → "Hide myself from search results".
