### ISSUE TITLE
Tweaking the take throttling algorithm

### ISSUE THREAD

**Issue by SimonSarazin** [liberapay/liberapay.com#287]
We're trying to use liberapay for our catalyst community in Lille, that's why we got 100€ (https://liberapay.com/collectifcatalyst/) by week for our local community. We need people to take this money faster than starting with 1€ (and 2€ / 4 / 8 next week) as people are giving a lot of time now. Is that possible ? Could we get multiple way to distribute money in a team depending on how the project go (for example for a faster project, starting with 1€ is difficult).

**Comment by Changaco** [comment]
For the record, the description of the current system from [/about/teams](https://en.liberapay.com/about/teams#throttling):

> Nominal takes are throttled, they can't be raised higher than a maximum computed based on the nominal takes at the time of the previous payday. This regulation is meant to reduce the risk of abuse by ill-intentioned team members.
>
> The exact limit is the maximum of these three values: the number 1, two times the member's take in the previous payday, 70% of the median take in the previous payday, or if that number is zero, the current income divided by the number of members.

**Comment by Changaco** [comment]
Related issue: #81.

**Comment by MarionRousseaux** [comment]
Hello Changaco, I read your message and I wanted to complete Simon's question. I'm also a member of Catalyst community. As Simon said we have 100 euros per week to split between the persons who contribute to a specific project. The thing is that we want to share this money between us in a defined period. Indeed it's 1,5 month work so we'd like to be able to split and use this money during this period. How can we do that? Could we adapt the system for cases like that? Thank you and see you soon in Lille.

**Comment by Changaco** [comment]
I have an idea on how to improve the take throttling algorithm, but I'm not sure it would work for your case, and more importantly I don't want to work on it right now. Thus I think the best course of action here is for you to tell me how much each member of your team would like to take this week, and I'll enter those amounts directly into the database, bypassing the throttling mechanism.

**Comment by Changaco** [comment]
(Note to self: the idea is to bring the amount of leftover income into the equation.)

**Comment by Changaco** [comment]
(But the problem with the leftover amount is that it depends on income so it can change.)

**Comment by Changaco** [comment]
@SimonSarazin @MarionRousseaux @pgno If you want me to change your takes for this week's payday then I need an answer this morning.

**Comment by Changaco** [comment]
In the absence of a reply I've opted to boost the two existing takes to €16, which means that other members will be able to take up to €11 after payday.

**Comment by Changaco** [comment]
For the record, how I did it:

```
% rhc ssh
[…]
> cd $OPENSHIFT_REPO_DIR && PYTHONPATH=. python -i liberapay/main.py
>>> changaco = Participant.from_username('Changaco')
>>> pgno = Participant.from_username('pgno')
>>> simons = Participant.from_username('simons')
>>> team = Participant.from_username('collectifcatalyst')
>>> team.set_take_for(pgno, '16.00', changaco, check_max=False); team.set_take_for(simons, '16.00', changaco, check_max=False)
Decimal('16.00')
Decimal('16.00')
```

**Comment by Changaco** [comment]
I've upped @MarionRousseaux's take to 16 by request of @SimonSarazin in IRC.

**Comment by Changaco** [comment]
The proposal of Gratipay's founder for their new 2.0 take-what-you-want system: https://github.com/gratipay/gratipay.com/issues/3994#issuecomment-217340995. It doesn't have the throttling issue that the Catalyst team ran into on Liberapay, as their proposed system is fully proportional, but the downside is that actual take amounts would not stable, they'd go up and down as income changes.

**Comment by whit537** [comment]
> the downside is that actual take amounts would not be stable, they'd go up and down as income changes.

Don't they already go up and down as income changes?

**Comment by whit537** [comment]
Sorry, seeing [this](https://liberapay.com/about/teams) now:

> Nominal takes also act as maximums: the actual takes are never higher than the nominal ones, even if additional income is available.

**Comment by KindlyFire** [comment]
It would be nice to have the leftover money shared equally between every member of the team that takes more then 0€. 

That way, people taking nothing won't get anything (what they want), but people taking will get some more.

**Comment by Changaco** [comment]
Distributing the leftover every week would lead to a decrease in income for established members when new people join the team and start taking money. That's contrary to our goal of a stable income, plus I think it could create resentment and deter teams from adding new members.

However, I think @whit537's idea of a "bonus" (https://github.com/gratipay/gratipay.com/issues/3994#issuecomment-217419201) is interesting. It could be monthly or quarterly, and maybe limited to a percentage of the money the member has taken from the team during that time, like 10%.

Another possibility is to use the leftover to fund one-time team takes (#81).
