### ISSUE TITLE
Receipts kinda suck

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#289]
Our receipts are inherited from Gratipay, they currently look like this:

![liberapay-2016-05-02-receipt](https://cloud.githubusercontent.com/assets/1581590/14954605/0453da02-1074-11e6-8ca3-37f13e883211.png)

I think we can do better.
- [x] I see no reason for the receipts to be this small, they could just as well be in a standard size like A4.
- [x] Make it very clear that they are only receipts, not bills/invoices.
- [x] Mention that the payment is for recurrent donations.
- [x] Add Liberapay's logo.

**Comment by subkrish** [comment]
@Changaco 
Few things, Where does the logo need to go? And about making it clear about being receipts and not bills and the mention of recurrent donations, does it go at the bottom?

**Comment by Changaco** [comment]
@subkrish I don't really know, for this kind of issue you just have to try things and see what looks best.

**Comment by Changaco** [comment]
WIP screenshot:

![screenshot of a (fake) receipt](https://user-images.githubusercontent.com/1581590/34649431-7a38642a-f3af-11e7-9c54-40ee9f5a7cbf.png)

Feedback welcome.

**Comment by rohitpaulk** [comment]
Is the 'reception' used when talking about payments? I think it's more common to say 'We confirm the receipt of ...' that 'We confirm the reception of ...'.

**Comment by rohitpaulk** [comment]
https://forum.wordreference.com/threads/receipt-reception.1026869/

**Comment by rohitpaulk** [comment]
Also, a bit of spacing could help...

**Before**:

![34649431-7a38642a-f3af-11e7-9c54-40ee9f5a7cbf](https://user-images.githubusercontent.com/3893573/34649783-7fb62816-f3db-11e7-9745-5973226b73da.png)

**After**:

![liberapayspacing](https://user-images.githubusercontent.com/3893573/34649778-6aef9cc8-f3db-11e7-8569-1ca09486f43b.png)

**Comment by Changaco** [comment]
Second draft, with the changes suggested by @rohitpaulk, and other tweaks:

![screenshot of a (fake) receipt, version 2](https://user-images.githubusercontent.com/1581590/34652046-5c6a7cec-f3d9-11e7-9866-77a611294811.png)

**Comment by Changaco** [comment]
Remaining TODO:

- [ ] prevent showing receipts that are partially translated, fall back to English instead
