### ISSUE TITLE
4xx error pages aren't user-friendly

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#290]
We should add a message on 4xx pages explaining to the user that it looks like the error came from their side, and that if they believe the problem is actually on our side they should open an issue here on github or send us an email.

**Comment by subkrish** [comment]
@Changaco '4xx errors' are not checked in `liberapay.com/error.spt`. So they must be checked for first and then shown the appropriate user-friendly message just like the '500 error', right?

**Comment by Changaco** [comment]
@subkrish If you're talking about <https://github.com/liberapay/liberapay.com/blob/223/error.spt#L20-L21>, then no, that's just a fallback message for critical errors. What needs to be modified here is the HTML template. The change could be as simple as adding a paragraph after `<pre>{{ err }}</pre>` when `code == 400`.

**Comment by kindlyfire** [comment]
I'm trying to do this as my first issue. I got a message added to the 404 page (underneath the `<pre>`), but what should that message contain ? Also, should the "Not Found" and the `<pre>` be hidden on 404, as they're unneeded ?

For the message, i'm thinking something along the lines of: The page you requested could not be found. This is probably not our fault. If you think it is, [open an issue](https://github.com/liberapay/liberapay.com/issues) or send us a email.

**Comment by Changaco** [comment]
I think we need two different messages, one for 404s and a more generic one for all other 4xx errors. The `<pre>` can be hidden for 404s if it's empty (it usually is).

Also, we should include debugging info in the page and ask the user to copy it into their report. Ideally the error page would contain a button instead, allowing the user to report the issue with a single click, but that's more complicated to implement.
