### ISSUE TITLE
HSTS header

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#299]
We do have an HSTS header, but it's added by CloudFlare, we should set it directly in the app.

**Comment by Changaco** [comment]
From <https://mastodon.rocks/@miwilc/1621335>:

> @.Liberapay you website doesn't support the HSTS "preload" header, need to look into this, since you're a payment platform.
>
> ![](https://mastodon.rocks/media/GCIbAThCPnwVpCmA8q8)

**Comment by Changaco** [comment]
I've enabled `preload` in Cloudflare.

**Comment by Changaco** [comment]
And submitted liberapay.com for inclusion in the HSTS preload list.

![hstspreload-2017-08-30](https://user-images.githubusercontent.com/1581590/29888757-4a0315be-8dc2-11e7-9d5a-c3cd3bc81d78.png)

**Comment by jplatte** [comment]
Seems like there was a regression. Currently, liberapay.com is not eligible for HSTS preloading: https://hstspreload.org/?domain=liberapay.com
