### ISSUE TITLE
Problème d'alimentation du portefeuille

### ISSUE THREAD

**Issue by MichelBernandMantel** [liberapay/liberapay.com#304]
Bonjour,
A chaque tentative de paiement ,voici le message qui s'affiche 
Token processing error (Error code: 001599)
la case "se rappeler du numéro" n'est pas cochée (facultatif ?)
Merci

**Comment by Changaco** [comment]
Bonjour, le code d'erreur semble indiquer un problème au niveau de l'opérateur de paiement Payline. La case "se rappeler du numéro" n'a pas d'impact à ce niveau. Le problème pourrait venir de votre navigateur, mais ça semble peu probable. Malheureusement il n'y a pas grand chose que je puisse faire, s'il s'agit bien d'un bug chez l'opérateur de paiement il sera probablement corrigé rapidement. Je vous invite donc à réessayer plus tard, demain ou lundi par exemple.

**Comment by Changaco** [comment]
(For the record: the [error codes](https://docs.mangopay.com/api-references/error-codes/) reference says that 001599 means "Getting the token from Payline failed", looking at [the code](https://github.com/liberapay/liberapay.com/blob/86/js/mangopay.js#L109-L169) confirms it; the [MangoPay status page](http://status.mangopay.com/) shows all green; googling "status payline" leads to [Payline Gateway Status](https://support.paylinedata.com/support/solutions/articles/4000050501-payline-gateway-status) which links to [this status board](http://status.transactiongateway.com/) that is also all green right now.)

**Comment by Changaco** [comment]
We've had successful payments today, so this issue was either transient or specific to a minority of users. I'm removing the Critical label.

**Comment by MichelBernandMantel** [comment]
Bonjour,

Je viens de faire deux nouveaux essais avec une carte visa et une carte
master card et toujours le meme message de blocage
oken processing error (Error code: 001599)

que faire
?
Merci
Michel Bernand-Mantel
33 6 2040 8000

2016-05-08 15:09 GMT+02:00 Changaco <notifications@github.com>:

**Comment by Changaco** [comment]
J'ai modifié le code, le message d'erreur devrait désormais contenir des informations supplémentaires. Pouvez-vous réessayer une fois de plus ?

Par ailleurs, quel navigateur utilisez-vous ? Avez-vous essayé avec un autre ?

**Comment by MichelBernandMantel** [comment]
Bonsoir,
Merci, j'utilise Firefox. Pas essayé avec autre navigateur. Je réessaye
demain. Je pense que le champ nom du titulaire de la carte doit être
souvent obligatoire pour certaines banques françaises.
Cdlt
MBM

**Comment by MichelBernandMantel** [comment]
Bonjour ,

Nouvelle tentative :(
voici le nouveau message

Token processing error (Error code: 001599) (Debug info:
{"status":0,"responseText":""})

comme je le craignais il semble manquer le champ nom du titulaire de la
carte

Cordialement

MBM
33 6 2040 8000

**Comment by Changaco** [comment]
Non, l'erreur ne vient pas du prestataire de paiement mais de votre navigateur ou de votre réseau, le code `0` indiquant que la requête n'a soit pas pu être effectuée soit a été bloquée. Je vous conseille donc d'essayer depuis un réseau non-filtré avec un navigateur à jour dans sa configuration par défaut et sans extensions.

Je vais modifier le code pour afficher un meilleur message d'erreur dans ce cas là.

P.S. Le nom figurant sur la carte n'est pas demandé par notre opérateur de paiement, ce n'est pas nous qui avons oublié de le mettre dans le formulaire.

**Comment by MichelBernandMantel** [comment]
Merci,
J'effectue des paiements en ligne chaque jour avec de multiples opérateurs
et je ne rencontre jamais aucun problème
Je vais tester via google chrome et suspendre ma protection antivirus pour
voir.....

**Comment by Changaco** [comment]
On utilise une technique particulière pour l'envoie des données sensibles directement à l'opérateur de paiement. Dans la plupart des cas elle permet une très bonne expérience utilisateur, mais parfois elle pose problème.

**Comment by Changaco** [comment]
(Good answer about the zero status code of XMLHttpRequest: <http://stackoverflow.com/a/14507670/2729778>.)

**Comment by MichelBernandMantel** [comment]
A chaque paiement nouveau, j'ai un pop up de La Banque Postale qui m'envoie
un code de validation du paiement et là ce n'est pas le cas !!
par contre j ai reçu un message comme quoi le don hebdomadaire à LSC est
bien validé (pj)

**Comment by Changaco** [comment]
Le code de validation (3DSecure) n'est activé automatiquement que pour les transactions supérieures à 100€.

**Comment by MichelBernandMantel** [comment]
Bonjour,
Merci
Je versais une avance de six mois soit 130€,
Je vais reduire la somme au dessous de 100€ et réessayer.
Cdlt
Mbm
