### ISSUE TITLE
Local payment methods

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#311]
MangoPay currently supports a dozen [PayIn payment methods](https://docs.mangopay.com/endpoints/v2.01/payins#e264_the-payin-object), including local ones such as iDEAL (Netherlands) and Giropay (Germany). We should probably integrate those into Liberapay in addition to bank wires (#45) and SEPA direct debits (#57).

**Comment by jelv** [comment]
For Europe (stats from https://www.adyen.com/payment-methods) Giropay (DE, 16%) and iDeal (NL, 80%) are good options. Maybe add the Cartes Bancaires logo for extra trust to.

**Comment by madduck** [comment]
Please also consider receiving recurring bank transfers (#649)

**Comment by Changaco** [comment]
Closing in favor of #1356.
