### ISSUE TITLE
Closed account & password

### ISSUE THREAD

**Issue by qsypoq** [liberapay/liberapay.com#315]
After closing your account your still can do a password reset, then with the mail's link you can go to the website, connected as the closed account.
You can do nothing (all account's pages as "The account as been closed") but you are connected.

**Comment by Changaco** [comment]
Indeed, thanks for reporting the issue. :-)

I see two possible ways to fix this: disable password resets for closed accounts, or reopen the account when the user logs in via email.

**Comment by qsypoq** [comment]
I think the 2nd option is better, like this we can reopen accounts while keeping the same name :)
