### ISSUE TITLE
Workers sometimes crash when they try to use SSL on an outgoing HTTP or SMTP connection

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#317]
[sentry#55](https://sentry.changaco.oy.lc/share/issue/322e3535/)

**Comment by Changaco** [comment]
I'm not sure what we can do about this. The worker is apparently receiving SIGABRT, and so gunicorn makes it exit.

**Comment by Changaco** [comment]
We could work around the problem by switching back to using an HTTP API, but the advantage of SMTP is that it's standard so we can change our email provider easily.

If I had the time I'd write an RFC for a standard email transport protocol on top of HTTP…

**Comment by KindlyFire** [comment]
You could use HTTP and make a class that both uses the HTTP API and renders the appropriate email. If you later change providers, there will be only one class to change.

**Comment by Changaco** [comment]
Yeah, abstraction could make it slightly easier to switch to another provider, but we'd still need to modify the code.

I would prefer to find a real solution, and I'd like to understand why the process is receiving SIGABRT.

**Comment by Changaco** [comment]
[sentry#74](https://sentry.changaco.oy.lc/share/issue/322e3734/) tells us that this is not related to SMTP since it also affects HTTP. Moreover, it seems that this happens when the remote host is unresponsive.

**Comment by Changaco** [comment]
In the log I notice that the abort signal was received after approximately 30 seconds, that's [gunicorn's default timeout](http://docs.gunicorn.org/en/stable/settings.html#timeout), which means that the abort signal is probably coming from there.

**Comment by Changaco** [comment]
This issue has resurfaced this week with timeouts on MangoPay requests due to http://status.mangopay.com/incidents/15kmj8b06sf0 and an SMTP timeout just now when a user tried to sign up. We need to put proper timeouts on external connections and show an appropriate error message instead of a generic 500 page that makes it look like the problem is a bug in Liberapay.

**Comment by Changaco** [comment]
> We need to put proper timeouts on external connections

It looks like there's no easy way to do that. We can set a default socket timeout but [it's often ignored](http://stackoverflow.com/questions/8464391/what-should-i-do-if-socket-setdefaulttimeout-is-not-working). For HTTP we use [requests](http://docs.python-requests.org/en/master/) (directly and indirectly), it has no default timeout and no way to set one globally nor on a Session.

**Comment by Changaco** [comment]
The next version of the `mangopay` module will have timeouts: <https://github.com/Mangopay/mangopay2-python-sdk/pull/84>.
