### ISSUE TITLE
Running payday requires SSH access to the server

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#319]
It should be easy for people other than me to run payday, we can accomplish that by integrating it into the webapp. Advantages: it'll make Liberapay more resilient (https://github.com/liberapay/salon/issues/32); it'll save time and prevent mistakes.
- [x] modify payday to self-check that it's running on a Wednesday
- [x] modify payday to refuse running more than once a week
- [x] modify payday to prevent concurrency (use a postgres lock like in the cron module)
- [x] implement running payday from the web
  - [x] in a separate process
  - [x] by admins only
- [x] modify stuff so that payday doesn't compile and clean the web assets (https://github.com/liberapay/liberapay.com/issues/312#issuecomment-219212043)

**Comment by Changaco** [comment]
I completely forgot to integrate the creation of a DB backup before starting, and the display of the `paydays` tables at the end. (See https://github.com/liberapay/salon/issues/44 for an example.)

**Comment by Changaco** [comment]
But a DB backup isn't very useful when you don't have the power to restore it. We could add support for that in the app, but if the DB was badly damaged the app wouldn't work. But why would payday badly damage the DB, and is a backup really a solution to that? In fact, is there any case in which restoring the before-payday backup is the right solution? Has Gittip/Gratipay ever had to do that? I don't remember it happening. Ping @whit537.

**Comment by Changaco** [comment]
Related issue: https://github.com/gratipay/gratipay.com/issues/3132

**Comment by whit537** [comment]
> But why would payday badly damage the DB, and is a backup really a solution to that? In fact, is there any case in which restoring the before-payday backup is the right solution? Has Gittip/Gratipay ever had to do that? I don't remember it happening.

We've definitely had to repair the db after running payday, but I don't recall ever restoring from a backup as part of that. It's possible that, short of actually restoring the backup, we used the backup to verify something or other as part of repairing the db.

https://github.com/gratipay/gratipay.com/issues/3132 was non-payday-related, of course.

**Comment by Changaco** [comment]
Thanks for the reply. :-) So, my premise was wrong: DB backups made before payday aren't for restoration, they're about having a snapshot of the state just before payday, especially `participants.balance` because we don't directly log changes to that (maybe we should? we already have the `balances_at` table).

**Comment by whit537** [comment]
:-)

**Comment by Changaco** [comment]
Closing again since I no longer take a backup before payday (I just check the size of the nightly backup). We don't log every change to balances yet, but it'll probably come in the next batch of accounting-related schema changes.

**Comment by Changaco** [comment]
Reopening because with the migration to AWS EB (#553) the server's local filesystem is now ephemeral storage, so log files need to be downloaded immediately, and that requires SSH access.
