### ISSUE TITLE
More clarity about the amount levied

### ISSUE THREAD

**Issue by MaiaDereva** [liberapay/liberapay.com#344]
Indicate on the donation page that the total sum is taken over 60 weeks. It would avoid surprises for users that don't know Liberapay and contribute for the first time.

**Comment by Changaco** [comment]
Agreed, we need to explain better how Liberapay works at every step (homepage, donation page, payment page, etc). Related issue: #270.

**Comment by Changaco** [comment]
Changes have been implemented to clarify how Liberapay works. Please open a new issue if you find pages that are still insufficiently clear.
