### ISSUE TITLE
Improve Postgresql configuration

### ISSUE THREAD

**Issue by MartinDelille** [liberapay/liberapay.com#347]
As I said on the IRC, I'm always struggling when it comes to configure `postgresql`. If someone has a good documentation for noobs like me, I'll link it to the home page. I also think the documentation is not very pertinent regarding to my configuration (`postgresql` install via [Homebrew](http://brew.sh/) / OSX) and I'll be happy to improve it :-)

**Comment by Changaco** [comment]
I would like to avoid adding OS-specific instructions to the README. We should modify the first command (`sudo -u postgres createuser --superuser $USER`) to be more generic (`sudo` may not be installed, the user may not be called `postgres`, the `$USER` variable may not be set). We should also add links to the official postgresql documentation: https://www.postgresql.org/download/ and https://www.postgresql.org/docs/9.4/static/index.html.

Previous discussion: https://github.com/liberapay/salon/issues/7#issuecomment-181056154.

**Comment by Changaco** [comment]
For comparison, take a look at [Gratipay's README](https://github.com/gratipay/gratipay.com/blob/1967/README.md).

**Comment by MartinDelille** [comment]
Thanks I forgot we had this previous discussion! I will try to improve the doc in a more generic way which is totally fine for me!
