### ISSUE TITLE
Markdown ?

### ISSUE THREAD

**Issue by MaiaDereva** [liberapay/liberapay.com#357]
I try to use markdown (p, h2, li) in my profile but nothing happens...

**Comment by Changaco** [comment]
`<p>` is HTML. Markdown is a different and lighter format. `<h2>Title</h2>` → `## Title`, `<li>list item</li>` → `- list item`, etc. See [Markdown Basics](https://daringfireball.net/projects/markdown/basics) for more.

**Comment by MaiaDereva** [comment]
Thank you Changaco, I tried HTML because the stars didn't work for the list but now it's ok.

**Comment by Changaco** [comment]
:-)

Asterisks (`*`) also work for lists, but there has to be a blank line before the start of the list.
