### ISSUE TITLE
Widget i18n is skewed by bad HTTP caching

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#360]
CloudFlare only respects `Accept-Encoding` in the `Vary` header ([What headers can I vary the cache on?](https://support.cloudflare.com/hc/en-us/articles/217343117-What-headers-can-I-vary-the-cache-on-)), we use [`Accept-Language`](https://github.com/liberapay/liberapay.com/blob/109/www/%25username/widgets/button.js.spt#L12).

**Comment by Changaco** [comment]
[Introducing Cloudflare Workers: Run JavaScript Service Workers at the Edge](https://blog.cloudflare.com/introducing-cloudflare-workers/)

**Comment by Changaco** [comment]
An alternative solution to using Cloudflare Workers could be to send all the translations to the browser and use JavaScript to pick one of them based on [NavigatorLanguage](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorLanguage). It would be cheaper but less efficient.

**Comment by Avamander** [comment]
This is kinda annoying, maybe it should indeed be done client-side.

**Comment by CaptainMorgan12** [comment]
![Screenshot from 2023-10-16 11-48-34](https://github.com/liberapay/liberapay.com/assets/80182265/8bfcb798-cf02-42e7-bc96-cb0b4b9e0277)
that doesn't look right next to the paypal widget

**Comment by Changaco** [comment]
I've fixed this issue by adding a (no-)caching rule to Cloudflare. This solution doesn't scale, but the current rate of requests for widgets seems to be low enough for the webapp and database to handle without any caching.

**Comment by Changaco** [comment]
Ten years later, [Cloudflare has finally added support for the `Vary` header](https://blog.cloudflare.com/vary-support/). I've modified the cache rule for widgets to use this new feature.
