### ISSUE TITLE
Space on sign-in

### ISSUE THREAD

**Issue by JulienLecaille** [liberapay/liberapay.com#365]
Trying to create a username with a space in it cause an erroneous HTML page return.

A warning is needed to not submit a username with wrong caracters in it

![space](https://cloud.githubusercontent.com/assets/19620144/16272193/1f4547be-389d-11e6-8906-01b42212e8d2.JPG)

**Comment by JulienLecaille** [comment]
Same issue as https://github.com/liberapay/liberapay.com/issues/363

**Comment by Changaco** [comment]
Also same as #362.

**Comment by Changaco** [comment]
I can replicate in production, but not locally, so it has something to do with the server.

**Comment by Changaco** [comment]
Scratch that, I can replicate locally, but since there is no proxy in the middle to mess things up the problem isn't apparent.

The bug is that somehow the erroneous username ends up… where the HTTP status code is supposed to be!

```
% curl -v "http://localhost:8339/sign-in?back_to=/" \
     -H 'Cookie: csrf_token=...' \
     --data 'csrf_token=...&form.repost=false&sign-in.username=foo+bar&sign-in.email=foobar%40example.net&sign-in.password=xxxxxxxx&sign-in.kind=individual&sign-in.terms=agree'
*   Trying ::1...
* connect to ::1 port 8339 failed: Connexion refusée
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8339 (#0)
> POST /sign-in?back_to=/ HTTP/1.1
> Host: localhost:8339
> User-Agent: curl/7.49.1
> Accept: */*
> Cookie: csrf_token=...
> Content-Length: 203
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 203 out of 203 bytes
* HTTP 1.0, assume close after body
< HTTP/1.1 foo bar
< Server: gunicorn/19.6.0
< Date: Thu, 23 Jun 2016 11:59:30 GMT
< Connection: close
< Transfer-Encoding: chunked
< Set-Cookie: csrf_token=...; Domain=.localhost; expires=Thu, 30 Jun 2016 11:59:30 GMT; Path=/
< X-Frame-Options: SAMEORIGIN
< Content-Type: text/html; charset=UTF-8
< Cache-Control: no-cache
< 
<!DOCTYPE html>
<html lang="en">
...
    <div id="main">
        <div class="container">
<h1>400</h1>            <div id="subnav"></div>
        <p>Bad Request</p>
        <pre>The username &#39;foo bar&#39; contains invalid characters.</pre>
        </div>
    </div>
...
```

**Comment by Changaco** [comment]
The traceback in https://github.com/liberapay/liberapay.com/issues/362#issuecomment-227715679 tells us that the bug is in aspen, not gunicorn.

**Comment by Changaco** [comment]
I found the bug! Origin: ed89f67e32ef780d32dad695529c5ac77a9c0880.

**Comment by Changaco** [comment]
Problem fixed \o/
