### ISSUE TITLE
Unable to send IBAN information by mail

### ISSUE THREAD

**Issue by MartinDelille** [liberapay/liberapay.com#377]
I decided to add money via IBAN transfert. When I got to this address: https://liberapay.com/martindelille/wallet/payin/bankwire/?exchange_id=XXX&payin_id=XXXXXX, there is a button proposing me to send me the information by email.

When clicking on it I have the following error message (not translated into french):

    Looks like you've found a bug! Sorry for the inconvenience, we'll get it fixed ASAP!

**Comment by Changaco** [comment]
Seems to be a transient network connectivity issue, just try again.

**Comment by MartinDelille** [comment]
After several tried it worked! Maybe the error message could be updated and translated?

**Comment by MartinDelille** [comment]
What do we need to make this string translatable with weblate? https://github.com/liberapay/liberapay.com/blob/55d63f8b8c009f688e4189308a42fc619dd9b7b8/error.spt#L23

**Comment by Changaco** [comment]
No, it can't be translated, it's the last error message we show when everything fails miserably, i18n is not available at that point.

**Comment by MartinDelille** [comment]
Ok

**Comment by Changaco** [comment]
Oh wait, I was thinking of that one: https://github.com/liberapay/liberapay.com/blob/master/liberapay/main.py#L82

The one you saw is already supposed to be translated.

**Comment by Changaco** [comment]
We need to add `error.spt` to the list of files we extract messages from: https://github.com/liberapay/liberapay.com/blob/master/Makefile#L75
