### ISSUE TITLE
[Weblate] Translation - "Engage" page

### ISSUE THREAD

**Issue by AmauryVanEspen** [liberapay/liberapay.com#385]
Hi !

Thank you for your amazing engagement and work,

I've just sent you an email with translation for the following page =>
https://hosted.weblate.org/engage/liberapay/

Would it be possible to translate it also and let users see this page in foreign langage ?

Thank you for your kind collaboration

Amaury

**Comment by Changaco** [comment]
Hey Amaury :-)

That page is part of the Weblate app, not Liberapay, so if you want to modify its Hungarian translation, then this is where you should submit it: https://hosted.weblate.org/translate/weblate/master/hu/?checksum=0bb609d63e9455ffe92772f56d2a6328

**Comment by AmauryVanEspen** [comment]
Hi Charly,

Thank you for your kind advice,
I let know my friend about her work of translation that I've sent you by
email.
I will let her know about :
https://hosted.weblate.org/projects/weblate/master/hu/

Moreover, would you be kind to "transfer" the email I've sent you to the
Weblate Team about the translation of the page ?

Thank you for your kind collaboration

Amaury
