### ISSUE TITLE
[Translation] Transifex

### ISSUE THREAD

**Issue by AmauryVanEspen** [liberapay/liberapay.com#386]
Good morning,

have you ever heard about Transifex ?
It is a "free for open source project" translation plateforme,

May you know "Assemblée des Communs de Lille" which has just open a Team to support translation of Commons projects and Thrid Party Community

Let us know and contact us (as well as Julien Lecaille) to register a project and get support.

Best

Amaury

**Comment by Changaco** [comment]
Yes, I know about Transifex, I prefer Weblate because it's open source and [it has a Liberapay team](https://liberapay.com/Weblate/).

**Comment by AmauryVanEspen** [comment]
Thank you Charly for your answer =)

Hope we could help

Amaury

**Comment by comradekingu** [comment]
@AmauryVanEspen Transifex is neither gratis for open source projects, nor is it actually one.
