### ISSUE TITLE
It's not clear that Liberapay is legal

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#391]
In the blog post *[Liberapay, dons open-source](http://alias.codiferes.net/wordpress/index.php/liberapay-dons-open-source/)* there's a paragraph doubting Liberapay's legal status, pointing to [Snowdrift.coop's wiki](https://snowdrift.coop/p/snowdrift/w/en/othercrowdfunding) as the source of the doubt. We should clear that up:

- [x] post a comment under the blog post clarifying the situation
- [x] state on liberapay.com that the service complies with EU financial regulations
- [x] ask the snowdrift folks to drop the FUD about Liberapay from their wiki page

**Comment by Changaco** [comment]
I've posted a comment under the blog post ([link](http://alias.codiferes.net/wordpress/index.php/liberapay-dons-open-source/#comment-26753)) and asked about modifying the snowdrift wiki in their IRC channel ([logs](http://ircbrowse.net/day/snowdrift/2016/08/06?id=77355&timestamp=1470474178#t1470474178)).

**Comment by Changaco** [comment]
The [Snowdrift wiki page](https://wiki.snowdrift.coop/market-research/other-crowdfunding#subscription) has been modified, hopefully it'll help prevent future misunderstandings.

**Comment by MartinDelille** [comment]
Maybe adding an item to the [FAQ](https://liberapay.com/about/faq)?

**Comment by Changaco** [comment]
> Maybe adding an item to the [FAQ](https://liberapay.com/about/faq)?

and/or https://liberapay.com/about/legal and/or https://liberapay.com/about/money

As always, Pull Requests are welcome. ;-)
