### ISSUE TITLE
error when creating a new community

### ISSUE THREAD

**Issue by mcl1234** [liberapay/liberapay.com#394]
hi,

I got an error when I created a new community

https://ipfs.pics/ipfs/QmVFjvtagu2iwVYYP335z3iPoymrfZFYKjNKtyR7A2ibBf

but it is registered after

**Comment by Changaco** [comment]
Thanks for reporting the problem.

The public technical details are in [sentry#64](https://sentry.changaco.oy.lc/share/issue/322e3634/). It's a stupid bug, easy to fix, it should have been taken care of two months ago.

**Comment by Changaco** [comment]
Should be fixed now.
