### ISSUE TITLE
After deleting an account it's impossible to open another with the same e-mail address

### ISSUE THREAD

**Issue by matunixe** [liberapay/liberapay.com#406]
Hello,

I tried to re-open an account for my project but I can't because it says the e-mail address is still used. So I tried to recover the password, I received the proper e-mail with the link but then I faced a 400 error : <code>This login link is expired or invalid.</code>

I really can't change the e-mail, what can I do?
Thanks in advance.

**Comment by Changaco** [comment]
Hi,

Resetting the password currently doesn't work on closed accounts (#315).

Is https://liberapay.com/le-kale/ the account you're trying to reopen? If so I can do it for you, and after that doing another password reset should work.

**Comment by matunixe** [comment]
Hello,

Yeah, that's the account we need. Please re-open it. :)
Thanks for your quick answer.

**Comment by Changaco** [comment]
The account is now reopened.

**Comment by matunixe** [comment]
Many thanks!
