### ISSUE TITLE
Old notifications show current balance

### ISSUE THREAD

**Issue by JulienLecaille** [liberapay/liberapay.com#409]
En reprenant les notifications sur : https://liberapay.com/JulienLecaille/notifications

Ca fait des choses incohérentes (car le solde restant sur le compte est corrigé rétrospectivement sur les messages)

![bugliberapay](https://cloud.githubusercontent.com/assets/19620144/18448953/67bd551a-792d-11e6-9816-c2f6856a7f10.JPG)

**Comment by Changaco** [comment]
Thanks for reporting the problem, I was already aware of it but apparently I didn't create an issue for it.

This is a low-priority bug, easy to fix.

**Comment by Changaco** [comment]
It's time to fix this bug. I'll do it in the next few days if nobody else does it first.
