### ISSUE TITLE
Internal Server Error when create community

### ISSUE THREAD

**Issue by Zatalyz** [liberapay/liberapay.com#410]
I have more "Internal Server Error" about community. 

first, when I create a community (here "Jeux_vidéos", with "french" language), i'm redirected on https://liberapay.com/for/new but this page is only with "Internal Server Error".

But, community is created ; I can see it when I search. 

I join it, and again : "Internal Server Error" when I join. Again, despite error, I have join this community.

So : it's work, but it display a terrifying error :-D

**Comment by Changaco** [comment]
Should be fixed now, thanks for reporting the problem. :-)
