### ISSUE TITLE
Ugly message when clickink "Give" button

### ISSUE THREAD

**Issue by MaiaDereva** [liberapay/liberapay.com#414]
If I'm not logged-in and I click on the "Give" button, an ugly message appears!
![message-liberapay](https://cloud.githubusercontent.com/assets/17183356/19004854/205331ac-8758-11e6-9a9f-d417eca1b2ab.jpg)

Isn't it possible to go directly to the login page instead of this message?

**Comment by Changaco** [comment]
Thanks for reporting the problem, it's fixed now.
