### ISSUE TITLE
Closing account fails when a final-gift recipient has no mangopay account

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#425]
Sentry: https://sentry.changaco.oy.lc/share/issue/322e3938/

User report: https://twitter.com/fuolpit/status/791660972670853120

**Comment by Angristan** [comment]
Thanks for creating an issue. What's a mangopay account and what's its purpose ?

**Comment by Changaco** [comment]
MangoPay is our payment processor, we create an account there for every user when they fill the identity form, but team accounts (e.g. <https://liberapay.com/Liberapay/>) never have a MangoPay account because they represent an informal collective that has no legal entity.

**Comment by Changaco** [comment]
@Angristan You should be able to close your account now.

**Comment by Angristan** [comment]
Great work ! I should test it but I changed my mind 😆

**Comment by Angristan** [comment]
Same error !
![screenshot_02-11-2016_b 109qhmiz](https://cloud.githubusercontent.com/assets/11699655/19926092/ff04e11c-a0f2-11e6-8aa7-2df702886f82.png)

**Comment by Changaco** [comment]
New issue: #430.

Although an error was returned, the final gifts were successful and there is no money left in your wallet, so you should be able to close your account by retrying one more time.

Thanks for helping us debug.

**Comment by Angristan** [comment]
You're right, my account is now closed. Thanks !

**Comment by Changaco** [comment]
You're welcome, though of course I'm saddened to see you leave.

**Comment by Angristan** [comment]
It's a personnal decision, I will continue to promote Liberapay whenever I can. Keep up the good work ;)
