### ISSUE TITLE
Investigate uphold.com

### ISSUE THREAD

**Issue by webmaven** [liberapay/liberapay.com#44]
I'm not sure if this will help you at all with Liberapay, but https://uphold.com/en/developer/api recently came up in discussion on a Gratipay ticket, and I thought you might find it useful.

**Comment by Changaco** [comment]
Definitely something to keep an eye on, thanks. At present they look less advantageous than MangoPay (notably because of higher fees). Their edge seems to be currency conversion, but support for multiple currencies is not a priority for Liberapay.

**Comment by webmaven** [comment]
What currency is Liberapay going to use?

**Comment by Changaco** [comment]
The euro.

**Comment by Changaco** [comment]
Closing. If there's something more to say about Uphold let's start a thread in [the salon](https://github.com/liberapay/salon) instead of here.

**Comment by Changaco** [comment]
Very relevant: https://github.com/gratipay/gratipay.com/issues/3870#issuecomment-187718272 O.O
