### ISSUE TITLE
Implement payin by bank wire

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#45]
It's not as convenient as credit cards but [the fee is only 0.5% instead of 1.8% + €0.18](https://www.mangopay.com/pricing/pricing-worldwide/).

**Comment by juliencarnot** [comment]
Sorry if this is a stupid question, I haven't researched the issue, but have you considered offering to wire money directly from my bank account to liberapay's account by publishing an IBAN and asking users to reference a key in the description field of the transfer, to reconcile the transfer with a user account and credit its wallet? Might be a good option for a 0% fee (at least for a lot of French/European contributors), even if that means going through the transfer interface of their own bank account and might induce some delay before crediting the wallet. Thanks for your time and great project anyways!

**Comment by Changaco** [comment]
We can't legally hold our users' money in our own bank account, that's why go through Mangopay. A zero fee option would be nice, but I think 0.5% is low enough, don't you? :-)

**Comment by juliencarnot** [comment]
Ok, got it! Nothing beats the "Power of Free", but 0.5% will be nice ! ;-)

**Comment by Changaco** [comment]
This will be done soon, see #316 for details.

**Comment by Changaco** [comment]
Deployed! Anyone wants to test it? @juliencarnot?

![liberapay-2016-05-16-payin-live](https://cloud.githubusercontent.com/assets/1581590/15284485/be62cbb4-1b51-11e6-8bb2-2c22517aa9e0.png)

**Comment by juliencarnot** [comment]
Sure! I checked this morning and did not find it but I can see it now! Will let you know how it went for me!

**Comment by juliencarnot** [comment]
Went through the process without any problem, but a few remarks:
* first screen: "bank wire to a Euro account" should be "bank wire from a Euro account"
* second screen: 
 * for each amount option, a different fee is listed, and none equates the 0.585% fee "advertised" on top of the dropdown list, and the fee is higher for €13.09 than for €9.81. A bit confusing. Might be a typo?
   * €2.03 (1.48% fee included)
    * €3.28 (0.91% fee included)
    * €6.55 (0.76% fee included)
    * €9.81 (0.61% fee included)
    * €13.09 (0.69% fee included)
  * What if I want to put more than 13.09 € in my wallet?     
My bank will usually take a working day to complete the wire transfer, so I'll let you know tomorrow if my wallet is still "empty".

Maybe it could be a bit clearer on what I should expect next (notification/e-mail once my transfer is received and matched with my LiberaPay account?) and on what I should do if nothing happens within this usual delay. I do see the pending payment in the Wallet page though.

Thanks again for this feature, great job!

**Comment by Changaco** [comment]
> first screen: "bank wire to a Euro account" should be "bank wire from a Euro account"

Why? We don't care where the money comes from, we're just telling the user where they'll have to send it and in which currency.

> for each amount option, a different fee is listed, and none equates the 0.585% fee "advertised" on top of the dropdown list, and the fee is higher for €13.09 than for €9.81. A bit confusing.

I know, we're rounding the fee twice and it's throwing things off. I may have a solution but I still have to check it against real data to make sure it's correct (we don't want to end up owing money to MangoPay again).

> What if I want to put more than 13.09 € in my wallet?

One step at a time. Eventually we'll add the possibility to transfer an arbitrary amount, but first let's test the feature and take care of #251.

> Maybe it could be a bit clearer on what I should expect next (notification/e-mail once my transfer is received and matched with my LiberaPay account?) and on what I should do if nothing happens within this usual delay.

You're right, we should tell users that they'll receive an email when the payment succeeds or fails (unless they've disabled those notifications in their email settings).

**Comment by juliencarnot** [comment]
Fair enough, it was just my euro-centered user feeling regarding the first message. For the other points, I understand perfectly and again, kudos for rolling this out!

**Comment by Changaco** [comment]
I've just deployed #323 and reticketed the other issues as #325 and #326.

**Comment by Changaco** [comment]
@juliencarnot's money has arrived, our first bank wire payin is a success! :-)

**Comment by juliencarnot** [comment]
\o/

**Comment by juliencarnot** [comment]
just a glitch: the receipt link leads to a 404 page, both in notification tray and e-mail.

**Comment by Changaco** [comment]
Oh, yeah, I didn't put the `.html` suffix. /o\

Email and notifications are the same, so it's normal that they're both affected. The link on the wallet page is correct.

**Comment by Changaco** [comment]
Fix in #328.
