### ISSUE TITLE
duplicated notifications

### ISSUE THREAD

**Issue by maxlath** [liberapay/liberapay.com#452]
what I get at https://liberapay.com/maxlath/notifications:

![libranotifs](https://cloud.githubusercontent.com/assets/1596934/20812943/d030a4a6-b813-11e6-9191-d73048cc3186.png)

Could that be that one notification got duplicated many times or that previous notifications got updated to the latest state? Either way, its confusing ^^

**Comment by Changaco** [comment]
Income notifications show the current balance, it's a known bug: #409. Sorry.

**Comment by maxlath** [comment]
np, thank you for Liberapay! :)
