### ISSUE TITLE
Flattr

### ISSUE THREAD

**Issue by AmauryVanEspen** [liberapay/liberapay.com#454]
I'm discovering Flattr initiative and i would like to understand the difference with Liberapay,
maybe there is some technical, legal or philosophy gap between the services. Otherwise, is there a project to cross-fertilize or cooperation with others micro-give community ?

https://flattr.com/

**Comment by Changaco** [comment]
Differences between Liberapay and other platforms are briefly [explained in our FAQ](https://liberapay.com/about/faq#differences), which contains a link to [Snowdrift's giant list of crowdfunding / fundraising services](https://wiki.snowdrift.coop/market-research/other-crowdfunding) for more details.

Flattr is an old proprietary service, it's mostly dead in the water and currently trying to make a comeback with [Flattr Plus](https://flattrplus.com/).

Flattr allows donors to automatically split a constant budget, we're planning to add a similar feature to Liberapay: #54.
