### ISSUE TITLE
Server version disclosure instead of 404 page

### ISSUE THREAD

**Issue by EdOverflow** [liberapay/liberapay.com#470]
[https://liberapay.com/%2f..](https://liberapay.com/%2f..) returns to following:

![liberapay_version](https://cloud.githubusercontent.com/assets/18099289/21482675/8771a2ca-cb77-11e6-84d7-560004d88f28.PNG)

**Comment by Changaco** [comment]
This is an upstream issue, unfortunately the platform we're using is deprecated so I'm not sure we can get it fixed.

**Comment by EdOverflow** [comment]
OK, in that case would you like me to close this issue?

**Comment by Changaco** [comment]
Nah, I don't mind leaving this open, it'll act as one more reminder that we need better hosting (for now I'm waiting for the next version of OpenShift Online to become available for production use).

**Comment by Changaco** [comment]
This was fixed when we migrated to AWS EB (#553).
