### ISSUE TITLE
Automatic renewal of donations

### ISSUE THREAD

**Issue by SimonSarazin** [liberapay/liberapay.com#483]
I think a lot of people forget to fill their account once the don't get any more money in Liberapay.

Is it possible to fill automatically our account once there is no more money, as it was with Gratipay (i'm not sure is this issue is already created ?)

**Comment by Changaco** [comment]
The existing issue is #331, see my answer there. ;-)

**Comment by Changaco** [comment]
Now that we've implemented direct debits (#57) we will be able to fully automate the payments of any donor who has a bank account in the [Single Euro Payments Area](https://en.wikipedia.org/wiki/Single_Euro_Payments_Area).

We'll need to add a way for donors to configure the payment amounts and frequency. This will probably lead us to #54.

**Comment by Changaco** [comment]
+1 from https://www.reddit.com/r/SolusProject/comments/6z1fc7/have_you_heard_of_considered_liberapay_for_solus/dmrzgau/

**Comment by jelv** [comment]
I use SEPA automatic fill up for [Blendle](https://blendle.com), online reader for newspapers and magazines. When my account gets below 1 euro its filled with 10 euro. Because SEPA is without fees this would be great for Liberapay to!

**Comment by Changaco** [comment]
SEPA direct debits are not free, the fee is €0.59 per payment.

**Comment by Changaco** [comment]
+1 from [Doesn't Liberapay defeat the whole purpose of the recurring donations?! ⋅ /r/liberapay](https://www.reddit.com/r/liberapay/comments/8539x4/doesnt_liberapay_defeat_the_whole_purpose_of_the/)

**Comment by Changaco** [comment]
![Screenshot of a selector for the "renewal mode" of a donation. It gives three options: automatic renewal, manual renewal, or no renewal.](https://user-images.githubusercontent.com/1581590/50724264-f0366880-10ea-11e9-80d3-937e36d8372a.png)

**Comment by tuxayo** [comment]
Great! :D
It that only for SEPA direct debits ?

**Comment by mattbk** [comment]
@Changaco, what PR is your screenshot from?

**Comment by Changaco** [comment]
@mattbk There isn't a PR yet, I haven't finished the work.

**Comment by davidak** [comment]
Any update here?

I would question if onetime donations should be supported at all. It's not the core concept of the service. Users could stop contributing after one month like some do on Patreon to get the perks.

**Comment by Changaco** [comment]
I'm still not finished implementing this, but I've made some progress and it should be ready in the next few months.

> I would question if onetime donations should be supported at all.

Not supporting one-off donations makes Liberapay less stable for creators, as some donors set up recurrent donations that they have no intention of renewing.

**Comment by Changaco** [comment]
This is finally done. See https://medium.com/liberapay-blog/the-fourth-year-of-liberapay-bbb8563cfac8 for more information.

**Comment by trebmuh** [comment]
:+1:
