### ISSUE TITLE
`javascript:` links shouldn't be allowed anywhere

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#493]
Background: <https://github.com/liberapay/liberapay.com/pull/488>.

Filtering them client-side by adding a few lines of code to `js/10-base.js` seems like the simplest and least expensive solution to me. It's basically implementing a small part of CSP ourselves.

**Comment by EdOverflow** [comment]
You might want to take a look at https://github.com/cure53/DOMPurify.

**Comment by Framartin** [comment]
Be careful if you filter links manually. There are a lot of tricks like : 

* `javascript&#58alert&#40;1&#41;`
* `JaVaScRiPt:alert(0)`
* ` javascript:alert(0)` (with a space at the beginning)
* `data:text/html;base64,PHNjcmlwdD5hbGVydCgnWFNTJyk8L3NjcmlwdD4K`
* `vbscript:alert`

Another solution is to force links to start by `http(s):` or `ftp(s):`.

**Comment by EdOverflow** [comment]
And by "forcing", it should really automatically prefix them with `http(s)://`.

**Comment by Changaco** [comment]
Closing because I don't think trying to improve security for obsolete browsers that don't support CSP is worth the cost.

**Comment by EdOverflow** [comment]
Personally, I don't think relying on our CSP is a good idea and we should really consider implementing a basic whitelist similar to how MathJax and KaTeX does it. <sup>[[1]](https://katex.org/docs/options.html#docsNav)</sup>

**Comment by Framartin** [comment]
I agree with @EdOverflow . CSP is a mitigation technique and shouldn't be seen as a security fix. 
As said on the [Mozilla Wiki](https://wiki.mozilla.org/Security/CSP/Design_Considerations):
> It helps mitigate and detect types of attacks such as XSS and data injection. CSP is not intended to be a main line of defense, but rather one of the many layers of security that can be employed to help secure a web site.
I think that this issue should be re-opened as it doesn't only affect old browser.
