### ISSUE TITLE
add support for xmpp: uri in markdown syntax

### ISSUE THREAD

**Issue by goffi-contrib** [liberapay/liberapay.com#500]
When adding and XMPP uri in the following form:
`[sat@chat.jabberfr.org](xmpp:sat@chat.jabberfr.org?join)`
the uri syntax is shown raw instead of linking to the room as expected.

**Comment by Changaco** [comment]
Okay, so here's the Markdown situation:

We're currently using Misaka 1.0.2, an obsolete version based on the abandoned Sundown lib.

We have two possibilities:

- upgrade [Misaka](http://misaka.61924.nl/) to 2.0.0
- switch to [Mistune](http://mistune.readthedocs.io/en/latest/)

According to [this benchmark] Mistune is around 20 times slower than Misaka, but it's pure python so there are no dependency issues, and it allows customizing the lexer in addition to the renderer (we don't need that feature right now though).

In both cases we need a Renderer subclass to sanitize links. We've been using the `HTML_SAFELINK` flag of Misaka 1, but Misaka 2 and Mistune don't have this feature built-in, and anyway we need to have sufficient control over the filter to allow XMPP links and close this issue.

**Comment by Changaco** [comment]
I tried upgrading Misaka first and it worked so I went with that. See #502.

**Comment by goffi-contrib** [comment]
That was quick, thanks :)
