### ISSUE TITLE
Title tool tip not translated on one specific checkbox

### ISSUE THREAD

**Issue by bnjbvr** [liberapay/liberapay.com#508]
Hi there, and thank you for doing liberapay.

When going to the settings section for the first time, then the Identity tab, the user needs to check a [box](https://github.com/liberapay/liberapay.com/blob/master/templates/identity-form.html#L79-L80) meaning that they agree to the terms of services of MangoPay. When using a translated version of this page (say, the French localized one), the tool tip displayed when hovering over this particular checkbox is not translated (to French).

The page I'm talking about is there: https://fr.liberapay.com/{username}/identity
Please let me know if you need more details, and keep up the good work 👍

**Comment by Changaco** [comment]
Hi. Interesting bug. The tooltip doesn't come from Liberapay, it's from your browser. This is a bug in Firefox. I've tested Chromium and Opera, they properly translate their tooltips.

**Comment by bnjbvr** [comment]
Ha, in this case this is not as interesting, since my browser is using English as its default locale. So I guess we can close in this case; thanks for looking at it, though!

**Comment by Changaco** [comment]
Doh, you're right, my Firefox is also in English, that's why it's showing the tooltip in that language instead of the page's language.
