### ISSUE TITLE
Cannot edit community with "+" in name

### ISSUE THREAD

**Issue by aggsol** [liberapay/liberapay.com#527]
I tried to edit the "C++" community. When I pressed the edit button I created a new community named "edit". Expected behaviour: Able to edit text of a community. Also switching languages for the community description text is not working. I expect to have a blank field or the old description in the respective language. Maybe that is a different bug?

**Comment by Changaco** [comment]
It's just a bad link, the "Edit" button has `href="edit"` when it should be `href="/for/{{ community.name }}/edit"`.

The language switcher is working fine for me.

**Comment by Changaco** [comment]
FTR, we used to redirect requests like `/for/C++` to `/for/C++/`, that's why `href="edit"` worked before but is half broken now.
