### ISSUE TITLE
Facebook link broken

### ISSUE THREAD

**Issue by revi** [liberapay/liberapay.com#536]
[My profile](https://liberapay.com/revi/) has a link to FaceBook ([this](https://www.facebook.com/profile.php?id=1828376324056378)) but clicking the link produces 'not available' error.

I guess this is because I have a custom [username](https://fb.com/hym411) set, so the `profile.php?id=` doesn't work.

For the record, I once deleted the facebook integration and then re-added the credentials, no luck. (The username has been set since 2013 or 2014 so it's unlikely username was updated after joining liberapay.)

**Comment by Changaco** [comment]
We've received an email saying that links to Facebook profiles are broken once again:

> Hi!
>
> The linking to Facebook acounts at Liberapay does not work anymore.
> Links are being created but they just lead to error messages at
> Facebook:
> 
> "Sorry, this content isn't available right now
> The link you followed may have expired, or the page may only be
> visible to an audience you're not in."
> 
> At least that's what I see on my account: […]
> 
> It seems that Facebook has shut off this functionality:
> 
> https://developers.facebook.com/blog/post/2018/04/19/facebook-login-changes-address-abuse/

**Comment by Changaco** [comment]
Related issue: #664.
