### ISSUE TITLE
Welcome email should not reference the account number

### ISSUE THREAD

**Issue by iangilfillan** [liberapay/liberapay.com#538]
The email I received after signing up says "We've received a request to connect XXX to the ~YYY account on Liberapay. Sound familiar?"

It doesn't sound familiar as it's a new account, and the "YYY" account number means nothing to me as I've just signed up. The email should be more along the lines of the familiar "Welcome to liberapy etc. etc. If this is not you, please ignore etc."

**Comment by Changaco** [comment]
Agreed, some email templates are legacies that aren't worded appropriately with regards to how Liberapay works now.

**Comment by hugoroger** [comment]
I agree. It's kind of hard to decide if you are all new to the whole scenario. I think a guided tour approach to show some options and possibilities can be rather encouraging.

**Comment by Changaco** [comment]
+1 in an email to support

**Comment by Changaco** [comment]
Pull Request to fix this issue: #551. For accounts that have just been created the new message is:

> A Liberapay account was created on {datetime} with the email address {addr}. Was it you?

@iangilfillan @hugoroger Opinions?
