### ISSUE TITLE
Usability issues

### ISSUE THREAD

**Issue by iangilfillan** [liberapay/liberapay.com#539]
As a new user, I can probably notice usability issues that the established team don't, having used it for so long. I will use this issue as a container to add various usability issues as I come across them.
1) On signing up, it is off-putting to be asked to decide between a personal and  business/nonprofit account. What does this mean? What if I haven't yet decided, or could be either? Does it affect the ability to earn income, give donations? From a usability perspective, if this distinction is critical, it should be added later rather than discourage users at the moment of signup
2) #538

**Comment by Changaco** [comment]
The "kind" of an account is an important piece of information that we use in multiple places. I suppose it would be possible to delay setting it, but I think rewording the form to be friendlier could suffice.

**Comment by Changaco** [comment]
#645 fixes this.
