### ISSUE TITLE
Migration to AWS

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#553]
I'm going to use this issue to log my attempt to migrate Liberapay to AWS. See #177 for background.

**Comment by Changaco** [comment]
I've installed https://github.com/aws/aws-cli on my machine (`pacman -S aws-cli`).

**Comment by Changaco** [comment]
I've also [installed the Elastic Beanstalk CLI](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb-cli3-install.html).

**Comment by Changaco** [comment]
I've created an AWS account for Liberapay, it required: accepting the [AWS Customer Agreement](https://aws.amazon.com/agreement/), a postal address, a credit card number, a phone number (you receive a call and input a 4-digit code), and finally choosing a support plan.

**Comment by Changaco** [comment]
Okay, I have the Liberapay app running on AWS, with an empty DB. The steps to get to that were:

- create an access key in the [IAM console](https://console.aws.amazon.com/iam/home)
- create the "liberapay.com" application: `eb init`
- create the "production" environment: `eb create`
- add [.ebextensions](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/ebextensions.html) to:
    - install `postgresql95-devel` (for `psycopg2`) and `libffi-devel` (for `misaka`)
    - install our python dependencies with an up-to-date version of `pip`
- set the `WSGIPath` to `liberapay/main.py` via `eb config`, and add an `application = website` alias in that file
- import the environment variables from OpenShift: `rhc env list | xargs -d '\n' eb setenv`
- adjust the environment variables: drop `GUNIORN_OPTS`, create `DATABASE_URL`
- implement variable interpolation for `DATABASE_URL` in `liberapay/wireup.py`
- run `psql <sql/recreate-schema.sql` and `psql <sql/app-conf-defaults.sql` via `eb ssh`

**Comment by Changaco** [comment]
I've been familiarizing myself with AWS, here are some notes:

- DB encryption isn't available for micro instances, so we won't have it for now
- Elastic Beanstalk seems to use S3 a lot for its internal workings, eating our free tier allotment of S3 requests (here's a forum thread about it: [S3 used for Elastic Beanstalk without explicit user consent](https://forums.aws.amazon.com/thread.jspa?threadID=239773))
- S3 doesn't keep logs of requests by default, and they're only "best effort" if you turn them on (meaning that log messages can be dropped)
- tailing the logs can be accomplished with `eb ssh -c 'tail -f /var/log/httpd/{error,access}_log'`
- the default log format is of course different from the custom one we've been using on OpenShift, I'm going to change it
- we could replace Apache with nginx and/or gunicorn ([like this](http://blog.code-mine.com/2015/11/04/changing-apache-to-nginx-with-php-fpm-on-elastic-beanstalk-amazon-web-services/)), but I don't feel like doing it right now

**Comment by Changaco** [comment]
Now the hard part: switch over from OpenShift to AWS without causing any significant downtime or data loss. Here's my plan:

- restore a DB backup on AWS, check that "everything" is working
- put the OpenShift app in read-only mode
- back up the DB from OpenShift, then restore it on AWS
- point CloudFlare to AWS
- celebrate

Later:

- shred the logs and data files on OpenShift

**Comment by hugoroger** [comment]
Are you able to completely run and host Liberapay on AWS for free? Or which plan are you on?

**Comment by Changaco** [comment]
@hugoroger In theory we can run for free for a year, see https://aws.amazon.com/free/ for details.

**Comment by Changaco** [comment]
Before switching over to AWS I needed to enable TLS. There's no builtin support for that on single instances, so I switched back to using a load balancer with only one instance behind. I used Amazon's certificate manager to get a new free one for `liberapay.com,*.liberapay.com`. It sends an email to the domain owner for verification. Then I enabled HTTPS on the load balancer with the new certificate, and opened the port in the firewall.

**Comment by Changaco** [comment]
The migration is done! \o/ 💃 🎆

**Comment by Changaco** [comment]
Post-migration notes:

- tailing the logs through SSH doesn't really work - even when there is only one instance - because the connection dies pretty fast (often less than an hour), so the logs have to go through CloudWatch and get pulled from there with [awslogs](https://github.com/jorgebastida/awslogs), but of course the number of free CloudWatch API calls is limited
- AWS EB has two deployment modes, neither fits our needs well:
  - the default mode is a zip archive upload, that's somewhat slow because it means sending the contents of the whole repo every time
  - the other is based on [CodeCommit](https://aws.amazon.com/codecommit/), it's faster, but [CodeCommit doesn't support git-lfs](https://forums.aws.amazon.com/thread.jspa?messageID=744178) so we can't use it on its own
- the "Application Healthcheck URL" setting doesn't work, I had to modify the app to route the requests based on the `User-Agent`
- the health check requests bloat the access log, so I added a rule to filter them
- I hadn't used Apache's httpd in many years, I can now confirm that it still sucks
- eventually we may want to create a [Custom Platform for Elastic Beanstalk](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/custom-platforms.html) to move beyond the shortcomings of the official ones
- by default old application versions are kept indefinitely until the limit is reached, which is pretty stupid, so I've modified the [Application Version Lifecycle Settings](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/applications-lifecycle.html) to keep only the last 20 versions and delete the rest (including the archives in S3)

**Comment by Changaco** [comment]
All the data has been shredded on OpenShift.

**Comment by Changaco** [comment]
I've set postgresql's `log_min_duration_statement` setting to `500` in production. That means queries taking more than 0.5 seconds are logged, so we can optimize them someday.

**Comment by Changaco** [comment]
Something I forgot to mention: I chose PostgreSQL 9.6 when setting up our DB on AWS. Previously we were running 9.4 on OpenShift, and I was holding back postgres upgrades on my laptop.

**Comment by aggsol** [comment]
Do we have a dedicated Postgresql topic? Any queries coming up slow?

**Comment by Changaco** [comment]
@aggsol No and no. Liberapay is relatively well optimized (I'm familiar with SQL performance tuning, I contributed a lot to the optimization of Gittip 3 years ago).
