### ISSUE TITLE
birthday will be saved one day early

### ISSUE THREAD

**Issue by dapor2000** [liberapay/liberapay.com#554]
when i want to save 1981-09-05, after refresh its 1981-09-04
when i input 1981-09-06 its saves correctly 1981-09-05 
(google chrome Version 57.0.2987.98)

strange....

**Comment by Changaco** [comment]
Confirmed, my birthday is displayed one day early. Looks like a bug in the new version of the mangopay library we've switched to recently.

**Comment by Changaco** [comment]
I've submitted a fix upstream: <https://github.com/Mangopay/mangopay2-python-sdk/pull/101>.

**Comment by dapor2000** [comment]
THX

**Comment by Changaco** [comment]
@dapor2000 This is fixed now, my birthday is displayed correctly. Thanks for having reported the bug.
