### ISSUE TITLE
Design of the donation form

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#569]
This issue is for the upcoming overhaul of the donation form.

**Comment by Changaco** [comment]
Here's a current screenshot of a donation form (<https://liberapay.com/Liberapay/donate>):

![spectacle h23369](https://cloud.githubusercontent.com/assets/1581590/25043110/cc98a3de-211d-11e7-8540-b534d6f8cd9b.png)

**Comment by Changaco** [comment]
Here's a first prototype for the new version, based on the same design as #566:

![spectacle s23369](https://cloud.githubusercontent.com/assets/1581590/25043209/7ce44ca2-211e-11e7-8ab4-1357206823ba.png)

**Comment by Changaco** [comment]
If you have ideas or suggestions please comment.

**Comment by trebmuh** [comment]
Adding something between 5€ per week and 100€ would make sense I guess. 20 or 25 maybe?

**Comment by Changaco** [comment]
I'm not planning to modify the suggested amounts, but here's some data on popular ones:

```
> select amount, count(*) from current_tips where amount > 0 group by amount having count(*) > 2 order by amount; 
 amount | count 
--------+-------
   0.01 |   283
   0.02 |    18
   0.03 |     8
   0.05 |    29
   0.10 |    44
   0.12 |     6
   0.15 |     5
   0.20 |     9
   0.24 |    46
   0.25 |   122
   0.29 |     5
   0.30 |     7
   0.35 |     3
   0.40 |     3
   0.47 |    13
   0.50 |    47
   0.70 |     6
   0.93 |     5
   0.97 |     4
   1.00 |   133
   1.16 |    20
   1.93 |     4
   2.00 |    31
   2.31 |     9
   2.50 |     4
   3.00 |     9
   4.62 |     4
   5.00 |    36
   5.77 |     4
  10.00 |    11
  15.00 |     4
  20.00 |     4
  25.00 |     4
 100.00 |     9
(34 rows)
```

**Comment by hugoroger** [comment]
Indeed interesting data. I think you've mentioned before but can people change the currency to display currency values in their own currency while still being billed in pounds?

**Comment by Changaco** [comment]
Second prototype, with a single cell for custom amounts:

![spectacle m26666](https://cloud.githubusercontent.com/assets/1581590/26579944/51a2d8b0-4536-11e7-9696-5ef836d132fa.png)

**Comment by Changaco** [comment]
@hugoroger We don't support any kind of currency conversion.

**Comment by Changaco** [comment]
When pledging:

![liberapay-2017-05-31-pledge-changaco-twitter](https://cloud.githubusercontent.com/assets/1581590/26630845/ce4dfebc-4608-11e7-809c-b4c9ee9bd5cc.png)

**Comment by Changaco** [comment]
Solution: full-width button!

![spectacle m16390](https://cloud.githubusercontent.com/assets/1581590/26632066/65a2707c-460e-11e7-8012-2dd9373c1cc9.png)

**Comment by jorgesumle** [comment]
> What do you like about the current donation form?

I liked its simplicity... However, now I've thought than some people might want to see the monthly amount and come to prefer the last one with the big donate button.

**Comment by Changaco** [comment]
Here's what I'm thinking of putting below the Donate button:

![spectacle l23279](https://cloud.githubusercontent.com/assets/1581590/26637994/4adbea62-4621-11e7-9c8c-cf3908e74aa7.png)

---

The first section is only shown if the user has connected at least one elsewhere account. In the future we could add other kinds of verifications in there.

**Comment by Changaco** [comment]
When a donation is already set up:

![spectacle lh1277](https://cloud.githubusercontent.com/assets/1581590/26676607/b0d76790-46c8-11e7-96e3-674b2c163bbc.png)
