### ISSUE TITLE
Implement payin by direct debit

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#57]
Looks like MangoPay is working on it: http://www.crowdfundinsider.com/2015/12/78787-mangopay-gocardless-form-partnership-for-improved-collection-of-payments/

**Comment by Changaco** [comment]
MangoPay has [released a new version of its API](https://docs.mangopay.com/release-snake/) with support for direct debits, so this ticket is no longer blocked.

**Comment by Changaco** [comment]
The [pricing page](https://www.mangopay.com/pricing/pricing-worldwide/) indicates that the fee is €0.80 per direct debit. That would make it more advantageous than the 0.5% of bank wires (#45) for amounts greater than €160.

**Comment by Changaco** [comment]
MangoPay has activated the direct debits feature for our accounts (sandbox and production), I'm continuing my work.

**Comment by Changaco** [comment]
Direct debit support is now deployed! To try it: https://liberapay.com/about/me/wallet/payin/direct-debit/

**Comment by madduck** [comment]
Hey, I've been busy, but wanted to say thanks for turning this around so quickly, and thanks to MangoPay too. I've now set up recurring donations to Liberapay…
