### ISSUE TITLE
Email field is case sensitive.

### ISSUE THREAD

**Issue by Technowix** [liberapay/liberapay.com#570]
Hello, I just tried to log into my account, and It seem that putting an caps inside one letter is actually considered as another email (on phone, the first letter is a lot of time caps'ed so it's silly to prevent it)
I think this should not be case sensitive, since emails aren't case sensitive in general :)

Steps to reproduce : 
 - Register
 - Log out
 - Try to log-in using different caps inside the email field from the one you registered.

**Comment by Changaco** [comment]
Strictly speaking the first part of an email address is case-sensitive, however in practice doing a case-insensitive lookup should be fine.
