### ISSUE TITLE
Error installing liberapay.com (make env)

### ISSUE THREAD

**Issue by jorgesumle** [liberapay/liberapay.com#576]
I'm trying to install it following the installation instructions from the README. However, I got an error when I executed `make env`. It seems to be a problem with the pip installation of misaka.

I'm also warned about my version of Python being to old. But I have Python 2.7.12 which is greater than `python ≥ 2.7.8`, which is what the README says.

Below the complete error:
<pre><samp>$ make env 
"/usr/bin/python2.7" -m ensurepip --user || make --no-print-directory _warning
ensurepip is disabled in Debian/Ubuntu for the system python.

Python modules For the system python are usually handled by dpkg and apt-get.

    apt-get install python-<module name>

Install the python-pip package to use pip itself.  Using pip together
with the system python might have unexpected results for any system installed
module, so use it on your own risk, or make sure to only use it in virtual
environments.

-e 
Warning: you're using an old version of python, you really should upgrade!

"/usr/bin/python2.7" -m pip --disable-pip-version-check install --user "virtualenv>=15.0.0"
Collecting virtualenv>=15.0.0
  Using cached virtualenv-15.1.0-py2.py3-none-any.whl
Installing collected packages: virtualenv
Successfully installed virtualenv-15.1.0
"/usr/bin/python2.7" -m virtualenv --no-download ./env/
New python executable in /home/jorge/Repos/liberapay.com/env/bin/python2.7
Also creating executable in /home/jorge/Repos/liberapay.com/env/bin/python
Installing setuptools, pip, wheel...done.
env/bin/pip --disable-pip-version-check install --require-hashes $(for f in requirements_*.txt; do echo "-r $f"; done)
Collecting python-mimeparse==1.6.0 (from -r requirements_base.txt (line 1))
  Using cached python_mimeparse-1.6.0-py2.py3-none-any.whl
Collecting first==2.0.1 (from -r requirements_base.txt (line 4))
  Using cached first-2.0.1-py2.py3-none-any.whl
Collecting dependency_injection==1.1.0 (from -r requirements_base.txt (line 7))
  Using cached dependency_injection-1.1.0.tar.gz
Collecting algorithm==1.2.0 (from -r requirements_base.txt (line 9))
  Using cached algorithm-1.2.0.tar.gz
Collecting filesystem_tree==1.1.2 (from -r requirements_base.txt (line 12))
  Using cached filesystem_tree-1.1.2.tar.gz
Collecting aspen==1.0rc1 (from -r requirements_base.txt (line 14))
  Using cached aspen-1.0rc1.zip
Collecting pando==0.44 (from -r requirements_base.txt (line 19))
  Using cached pando-0.44-py2.py3-none-any.whl
Collecting MarkupSafe==0.23 (from -r requirements_base.txt (line 25))
  Using cached MarkupSafe-0.23.tar.gz
Collecting Jinja2==2.8 (from -r requirements_base.txt (line 27))
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Collecting aspen-jinja2==0.5 (from -r requirements_base.txt (line 30))
  Using cached aspen_jinja2-0.5-py2.py3-none-any.whl
Collecting psycopg2==2.6.1 (from -r requirements_base.txt (line 34))
  Using cached psycopg2-2.6.1.tar.gz
Collecting postgres==2.2.1 (from -r requirements_base.txt (line 38))
  Downloading postgres-2.2.1.tar.gz
Collecting simplejson==3.8.1 (from -r requirements_base.txt (line 41))
  Downloading simplejson-3.8.1.tar.gz (76kB)
    100% |████████████████████████████████| 81kB 1.2MB/s 
Collecting certifi==0.0.8 (from -r requirements_base.txt (line 44))
  Downloading certifi-0.0.8.tar.gz (118kB)
    100% |████████████████████████████████| 122kB 2.1MB/s 
Collecting pyasn1==0.1.3 (from -r requirements_base.txt (line 46))
  Downloading pyasn1-0.1.3.tar.gz (54kB)
    100% |████████████████████████████████| 61kB 4.6MB/s 
Collecting chardet==1.0.1 (from -r requirements_base.txt (line 49))
  Downloading chardet-1.0.1.tar.gz (156kB)
    100% |████████████████████████████████| 163kB 2.3MB/s 
Collecting oauthlib==1.0.3 (from -r requirements_base.txt (line 51))
  Downloading oauthlib-1.0.3.tar.gz (109kB)
    100% |████████████████████████████████| 112kB 3.2MB/s 
Collecting requests==2.6.0 (from -r requirements_base.txt (line 53))
  Downloading requests-2.6.0-py2.py3-none-any.whl (469kB)
    100% |████████████████████████████████| 471kB 2.1MB/s 
Collecting requests-oauthlib==0.6.1 (from -r requirements_base.txt (line 56))
  Downloading requests_oauthlib-0.6.1-py2.py3-none-any.whl
Collecting xmltodict==0.8.4 (from -r requirements_base.txt (line 59))
  Downloading xmltodict-0.8.4.tar.gz
Collecting blinker==1.4 (from -r requirements_base.txt (line 62))
  Downloading blinker-1.4.tar.gz (111kB)
    100% |████████████████████████████████| 112kB 3.4MB/s 
Collecting mangopaysdk==3.0.6 (from -r requirements_base.txt (line 64))
  Downloading mangopaysdk-3.0.6.tar.gz (61kB)
    100% |████████████████████████████████| 61kB 4.5MB/s 
Collecting contextlib2==0.4.0 (from -r requirements_base.txt (line 67))
  Downloading contextlib2-0.4.0.tar.gz
Collecting raven==5.25.0 (from -r requirements_base.txt (line 69))
  Downloading raven-5.25.0-py2.py3-none-any.whl (269kB)
    100% |████████████████████████████████| 276kB 2.7MB/s 
Collecting six==1.8.0 (from -r requirements_base.txt (line 73))
  Downloading six-1.8.0-py2.py3-none-any.whl
Collecting libsass==0.11.1 (from -r requirements_base.txt (line 76))
  Downloading libsass-0.11.1-cp27-cp27mu-manylinux1_x86_64.whl (7.1MB)
    100% |████████████████████████████████| 7.1MB 253kB/s 
Collecting environment==1.0.0 (from -r requirements_base.txt (line 83))
  Downloading environment-1.0.0.tar.gz
Collecting html2text==2016.4.2 (from -r requirements_base.txt (line 86))
  Downloading html2text-2016.4.2.tar.gz (45kB)
    100% |████████████████████████████████| 51kB 5.4MB/s 
Collecting MailShake==0.12.1 (from -r requirements_base.txt (line 88))
  Downloading MailShake-0.12.1.tar.gz
Collecting pytz==2015.7 (from -r requirements_base.txt (line 91))
  Downloading pytz-2015.7-py2.py3-none-any.whl (476kB)
    100% |████████████████████████████████| 481kB 2.3MB/s 
Collecting Babel==2.3.4 (from -r requirements_base.txt (line 97))
  Downloading Babel-2.3.4-py2.py3-none-any.whl (7.1MB)
    100% |████████████████████████████████| 7.1MB 261kB/s 
Collecting misaka==2.0.0 (from -r requirements_base.txt (line 101))
  Downloading misaka-2.0.0.tar.gz (121kB)
    100% |████████████████████████████████| 122kB 3.3MB/s 
    Complete output from command python setup.py egg_info:
    c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
    compilation terminated.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-8b8QFZ/misaka/setup.py", line 68, in <module>
        cffi_modules=['build_ffi.py:ffi'],
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/jorge/Repos/liberapay.com/env/local/lib/python2.7/site-packages/setuptools/dist.py", line 315, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/home/jorge/Repos/liberapay.com/env/local/lib/python2.7/site-packages/setuptools/dist.py", line 361, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/jorge/Repos/liberapay.com/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 850, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/home/jorge/Repos/liberapay.com/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1122, in best_match
        return self.obtain(req, installer)
      File "/home/jorge/Repos/liberapay.com/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1134, in obtain
        return installer(requirement)
      File "/home/jorge/Repos/liberapay.com/env/local/lib/python2.7/site-packages/setuptools/dist.py", line 429, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/jorge/Repos/liberapay.com/env/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 665, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/home/jorge/Repos/liberapay.com/env/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 695, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/home/jorge/Repos/liberapay.com/env/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 876, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/home/jorge/Repos/liberapay.com/env/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1115, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/home/jorge/Repos/liberapay.com/env/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1103, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-8b8QFZ/misaka/
Makefile:22: recipe for target 'env' failed
make: *** [env] Error 1</samp></pre>

**Comment by Changaco** [comment]
It looks like you need to install the `libffi-dev` package.

**Comment by Changaco** [comment]
Note that since our migration to AWS we're now running on Python 2.7.12 in production instead of 2.7.8.

**Comment by Changaco** [comment]
I've updated the README: 8b23645dd8d6594a57cde451967ea4ce6a7d24bc.

**Comment by revi** [comment]
>postgresql 9.6.1

Travis is testing on 9.4, you may want to fix that :)

**Comment by jorgesumle** [comment]
Thanks, @Changaco, after installing the `libffi-dev` package it worked.
