### ISSUE TITLE
PostgreSQL version on Travis doesn't match production

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#577]
https://github.com/liberapay/liberapay.com/issues/576#issuecomment-295393745

**Comment by revi** [comment]
Probably fixed now? Looks like we are testing on [9.6 branch](https://travis-ci.org/liberapay/liberapay.com/jobs/288143821#L91) as of master now.

**Comment by Changaco** [comment]
Indeed, it was fixed in 3061b135f0bdf3a093f15be8f104be9064312bcc.
