### ISSUE TITLE
502 error pages are masked by Cloudflare

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#592]
We use the 502 HTTP error code when communication with another platform (GitHub, Twitter, etc) fails. It seems that, at least for the last few days, Cloudflare has been shadowing our 502 error pages with their own, making it look like our app is malfunctioning when in fact it has returned a proper error page.

Perhaps the time has come for us to migrate away from Cloudflare.

**Comment by revi** [comment]
Customizing 50X errors are [paid feature](https://support.cloudflare.com/hc/en-us/articles/200172706-How-do-I-customize-CloudFlare-error-pages-).

>By default, these error pages mention Cloudflare; however, as a **paying customer** you can customize and brand these error pages.

(emphasis mine)

Leaving Cloudflare means longer connection time for me, though :-p

**Comment by Changaco** [comment]
We don't really want to customize Cloudflare's error pages, we just want Cloudflare to transmit our custom 502 error pages to the client instead of replacing them.

**Comment by Changaco** [comment]
I sent a message to Cloudflare yesterday and it turns out that what I would consider to be a normal behavior is in fact an Entreprise-level "feature": https://support.cloudflare.com/hc/en-us/articles/206777107-What-is-Enable-Origin-Error-Pages-

Two solutions: either we modify our error codes to circumvent Cloudflare's behavior, or we set up our own reverse-proxy and drop Cloudflare.
