### ISSUE TITLE
Pledges confirmation text

### ISSUE THREAD

**Issue by jelv** [liberapay/liberapay.com#597]
When confirming a pledge you get the notification "You are now donating X per week to Y. Thank you!". But your donation only starts when it's activated. My suggestion is to change it to: "You have now pledged donating X per week to Y. Thank you!".

**Comment by subkrish** [comment]
@Changaco I am ready to work on it.

**Comment by Changaco** [comment]
@subkrish Great! Let me know if you need any help. I've sent you an invite to join the org so you can do stuff like assigning an issue to yourself.
