### ISSUE TITLE
Get rid of is_suspicious

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#60]
While writing the Terms of Service (https://github.com/liberapay/liberapay.org/issues/4) it occurred to me that blacklisting users without notifying them and with no time limit is very bad. #58 and #59 are how we should handle fraud.

**Comment by Changaco** [comment]
Anyone up for this? It should be pretty easy: `git grep is_suspicious` and modify or remove the relevant files.

**Comment by MartinDelille** [comment]
I working on this. In order to understand the admin part, how do we access the admin account when using fake data in the local env?

**Comment by Changaco** [comment]
`psql liberapay -c "update participants set is_admin = true where username = '<your-username>'"`

**Comment by Changaco** [comment]
Although if you're talking about `www/dashboard/index.spt`, we can actually remove that completely, along with `admin.js` and `test_is_suspicious.py`.

**Comment by MartinDelille** [comment]
shall I clean the translation file for 'blacklist' ?

**Comment by MartinDelille** [comment]
In fact 'blacklist' is mentioned only in the about page. Shall I remove the reference to 'blacklist' there? Will the translation files be updated if a string has been removed? How? Otherwiwe how do we clean translation?

**Comment by Changaco** [comment]
Don't modify the `.po` files in a PR, it could result in conflicts on Weblate (see 5th item of #75), they're updated automatically when we sync translations (`make i18n_update`).

**Comment by Changaco** [comment]
> Shall I remove the reference to 'blacklist' there?

Yes.
