### ISSUE TITLE
Text on "Adding money" page is not clear enough

### ISSUE THREAD

**Issue by jelv** [liberapay/liberapay.com#605]
Money adding screen is not showing when logged in on /payin page. 

URL: https://liberapay.com/Jelv/wallet/payin
Screenshot: ![schermafbeelding 2017-06-06 om 19 24 09](https://user-images.githubusercontent.com/7106279/26842621-cc8788f2-4aed-11e7-9478-4845f214b0b2.png)
OS: macOS Sierra. Browser: FF and Safari.

**Comment by Changaco** [comment]
The page is working as intended, we don't allow adding money if your income is already ≥ the amount of your outgoing donations, since it would be pointless to add money that is only going to sit in your wallet until you withdraw it back.

Is the displayed message not clear enough?

**Comment by jelv** [comment]
I clicked add money and get the text "Your donations are funded by your income." That is not explicid mentioning that I cannot add more money and why.

**Comment by Changaco** [comment]
Okay. Tagged as Easy (i.e. it's a small issue and you don't need to be familiar with Liberapay's code base to fix it).

**Comment by subkrish** [comment]
@Changaco Is it still about the adding money feature or the text that is shown for not being able to add money? If it is about the text then I think the issue title should be changed.

**Comment by Changaco** [comment]
This issue is only about clarifying the text.

**Comment by subkrish** [comment]
@Changaco Should we change it to -> "Your donations are funded by your income. Adding money is not allowed if your income is already ≥ the amount of your outgoing donation."? Something like this?

**Comment by Changaco** [comment]
My proposal: "We don't allow adding money when your donations are already funded by your income. If this is a problem for you please send an email to support@liberapay.com explaining why."

What do you think @jelv?

**Comment by jelv** [comment]
I like the proposal of @changaco.

**Comment by subkrish** [comment]
@Changaco This update will be made to `/wallet/payin` files and the i18n files, right? I see the message in multiple i18n files.

**Comment by Changaco** [comment]
@subkrish No, you shouldn't modify the files in `i18n/`.
