### ISSUE TITLE
one-time donation

### ISSUE THREAD

**Issue by B4rb3rouss** [liberapay/liberapay.com#613]
It could be nice to make a one-time "big" donation from his wallet to another liberapay user instead of dealing with amounts for a week than changing it back.
A lot of possible users don't subscribe to liberapay because of the "recurrent-only" working of liberapay. 

Just an idea thought :)

**Comment by trebmuh** [comment]
I do agree.

What about allowing the donor to give xxx €, and dispatch these across 12 months to allow to cater for the "stable income" idea of Liberapay for the receiver?

**Comment by Changaco** [comment]
This issue is a duplicate of #415.
