### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by jelv** [liberapay/liberapay.com#614]
In text line 763 there is a small typo: "lefotver" instead of "leftover"

Complete text:
"The limit works like this: you can always increase your take to 1.00 if it was below that, you can double your take compared to the previous week, you can raise your take to claim the team's **lefotver** income, and you can bring your take up to the level of the median take in the previous payday. Whichever of these possibilities results in the highest amount is your maximum take for the week."

i18n

**Comment by Changaco** [comment]
🤦‍

Fixing it now.
