### ISSUE TITLE
Charts on statistics page not up to date

### ISSUE THREAD

**Issue by Maltimore** [liberapay/liberapay.com#618]
I couldn't find an open issue about this although I suspect there must be one? I like the charts on the statistics page, but it seems like they're not being updated.

**Comment by Changaco** [comment]
The charts appear to be working as usual to me. What exactly is troubling you?

**Comment by Maltimore** [comment]
I believe they have been showing the same information since at least two weeks, is that possible?

**Comment by Changaco** [comment]
The only way I can think of right now would be if your browser or a proxy was wrongly caching the JSON data.

Can you provide a screenshot? Here's what I have:

![liberapay-2017-06-22-stats](https://user-images.githubusercontent.com/1581590/27455484-b9eb2052-579d-11e7-9ac8-307454ad6ea7.png)

**Comment by Maltimore** [comment]
Hm maybe I was wrong? I'll check again next week and close this issue for now. Sorry for the inconvenience!
