### ISSUE TITLE
When saving the pinned github repo, the user should have a feedback

### ISSUE THREAD

**Issue by Flaburgan** [liberapay/liberapay.com#622]
When I check the github repo I want to display on my profile (so the https://liberapay.com/Fla/repos/github page), nothing happens when I click save. The repos are correctly pinned on my profile, but I have no feedback everything went well. The page should at least display a message saying the list of pinned repos has been updated, and should eventually redirect to https://liberapay.com/Fla/ or https://liberapay.com/Fla/edit (where we're coming from).

**Comment by Changaco** [comment]
When the changes are saved the message “Your profile has been updated.” is displayed at the bottom of the page.

**Comment by Changaco** [comment]
Navigation was improved in #624. Concerning the lack of feedback I assume that you did in fact get a notification but that you didn't see it, so I'm closing this issue in favour of #625.
