### ISSUE TITLE
Wrong donating value on the profile

### ISSUE THREAD

**Issue by Flaburgan** [liberapay/liberapay.com#623]
My profile indicates "Fla reçoit 0,05 € et donne 1,00 € par semaine." (Fla receives 0,05 and give 1,00 per week). But I receive 1,05 euros and give 6 euros per week.

**Comment by Changaco** [comment]
The values are correct. They're not the amounts that were transferred in the last payday, they're estimates of how much will be transferred next week if nothing changes. Right now your donations are not funded (<https://liberapay.com/Fla/giving>), and the person who has been giving you 1€ per week also needs to top up their account.

**Comment by Flaburgan** [comment]
Yep I saw that my donations were blocked because I'm out of money. Which should arrive soon hopefully, waiting for the transfert to procceed. Closing then.
