### ISSUE TITLE
Can't receive money per creation

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#632]
Liberapay only supports "unconditional" donations. Should we add support for per-deliverable (an episode, a software release, etc) payments?

**Comment by artsyhonker** [comment]
Yes! (But... you already know I think this. I don't know how to do the fancy cross-reference get thing, will see if I can figure it out.)

**Comment by Changaco** [comment]
Ah, see that @jelv? There already was an issue for this before #839, I just forgot about it…

**Comment by Changaco** [comment]
Closing in favor of the new issue which has more details.
