### ISSUE TITLE
libravatar's link is broken

### ISSUE THREAD

**Issue by silberzwiebel** [liberapay/liberapay.com#637]
Hey there,

I've just signed up at libravatar to have an avatar at librapay.
However, the automatically generated link is broken and still links to a default gravatar image.
This is the link:
`https://seccdn.libravatar.org/avatar/1cb1897908c6f20abcbeae2563457657?s=160&default=retro`

Removing the `&default=retro`part resolves properly to my libravatar image:

`https://seccdn.libravatar.org/avatar/1cb1897908c6f20abcbeae2563457657?s=160`

**Comment by Changaco** [comment]
The first link seems to work fine, the default image you're seeing is probably from your browser's cache.

**Comment by silberzwiebel** [comment]
oh, yeah. sorry for the noise ... (could you maybe add a message to clear the cache when setting libravatar for the impatient like me ...?)
