### ISSUE TITLE
Avatar caching is confusing

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#640]
See #637. Two possible solutions:

- add a simple message like @silberzwiebel suggested
- add a "Refresh" button which tweaks the avatar URL to bypass the cache (e.g. by adding a timestamp in the querystring)

**Comment by tchncs** [comment]
I just wanted to add: 
It's no simple browser caching thing. I just set a new gravatar and instead of showing my old photo, it got replaced by a default gravatar for a while.
Using Mastodon for it firstly "worked" (my uMatrix plugin blocked it) but after that it just was a questionmark again.
