### ISSUE TITLE
Invalid (non-consistent) declension of time spans in Russian language

### ISSUE THREAD

**Issue by Skybladev2** [liberapay/liberapay.com#644]
Here is the example: https://ru.liberapay.com/for/Game_Development/

![default](https://user-images.githubusercontent.com/548735/28757289-b88c534a-7587-11e7-81c3-209bc09b32e0.png)

**Comment by Changaco** [comment]
Time delta translations are from [Babel](http://babel.pocoo.org/). Upgrading it to the latest version (2.4.0) might fix the issue.

**Comment by Changaco** [comment]
(Instructions on updating Python dependencies are in the README: <https://github.com/liberapay/liberapay.com/blob/202/README.md#modifying-python-dependencies>.)

**Comment by Changaco** [comment]
I've figured this out, it's the same issue as #1384.
