### ISSUE TITLE
Email notification treated as spam

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#662]
[Carl Chenet reports on Mastodon](https://mastodon.social/@carlchenet/14905706) that the income notification email from today's payday ended up in his spam folder.

We haven't changed anything on our side. DKIM and SPF look okay.

**Comment by chaica** [comment]
Here is the spam cause indicated in the source email:
```
X-VR-SPAMSTATE: SPAM
X-VR-SPAMSCORE: 300
X-VR-SPAMCAUSE: gggruggvucftvghtrhhoucdtuddrfeelkedrkeehgdegudcutefuodetggdotefrodftvfcurfhrohhfihhlvgemucfqggfjpdevjffgvefmvefgnecuuegrihhlohhuthemuceftddtnecuogfuphgrmhfkphculdeftddtmd
X-Ovh-Spam-Status: SPAM
X-Ovh-Spam-Reason: vr: SPAM; dkim: disabled; spf: disabled
X-Ovh-Message-Type: SPAM
X-Spam-Tag: YES
```

**Comment by jorgesumle** [comment]
What is the spam checker of your email provider? Can you exactly what makes up those 300 spam score. I can't see any spam cause there, what does X-VR-SPAMCAUSE means, I just see a bunch of letters which apparently doesn't make much sense.

The message is not detected as spam in my case (using SpamAssassin)

![captura de pantalla_2017-08-09_16-14-58](https://user-images.githubusercontent.com/14212780/29126251-15adbfda-7d1e-11e7-9bd9-e11068778f12.png)

**Comment by chaica** [comment]
OVH is the leading French web hoster. I've no idea what they use.

**Comment by Changaco** [comment]
The antispam software is <https://www.vadesecure.com/>. We can't decode their cause headers ourselves.

**Comment by Schoumi** [comment]
Like @chaica, my mail is hosted by OVH and the only information that say it's a spam is given by him. I have the exact same data.
The cause is a hash, but don't know where to find what reason it is exactly behind this hash.

Since june 21 (I have no record before) to the last week spam status in mail header are:
```
X-VR-SPAMSTATE: OK
X-VR-SPAMSCORE: 0
X-VR-SPAMCAUSE: gggruggvucftvghtrhhoucdtuddrfeeljedrkeelgdduvdeiucetufdoteggodetrfdotffvucfrrhhofhhilhgvmecuqfggjfdpvefjgfevmfevgfenuceurghilhhouhhtmecufedttdenuc
X-Ovh-Spam-Status: OK
X-Ovh-Spam-Reason: vr: OK; dkim: disabled; spf: disabled
X-Ovh-Message-Type: OK
```

Today it's:
```
X-VR-SPAMSTATE: SPAM
X-VR-SPAMSCORE: 300
X-VR-SPAMCAUSE: gggruggvucftvghtrhhoucdtuddrfeelkedrkeehgdegudcutefuodetggdotefrodftvfcurfhrohhfihhlvgemucfqggfjpdevjffgvefmvefgnecuuegrihhlohhuthemuceftddtnecuogfuphgrmhfkphculdeftddtmd
X-Ovh-Spam-Status: SPAM
X-Ovh-Spam-Reason: vr: SPAM; dkim: disabled; spf: disabled
X-Ovh-Message-Type: SPAM
X-Spam-Tag: YES
```

**Comment by Changaco** [comment]
(They're not hashes. Hashes are always the same length and change a lot when the underlying data is slightly modified.)

**Comment by Schoumi** [comment]
(I haven't verify the length and only believe what i've read in my little research on this site https://help.dreamhost.com/hc/en-us/articles/215686647-Technical-details-on-how-Anti-spam-filters-work)

**Comment by B4rb3rouss** [comment]
If they configured correctly their webmail, movin this "fake spam" to a folder like "INBOX" should mark it as legitimate.

    X-Ovh-Spam-Reason: vr: SPAM; dkim: disabled; spf: disabled

They don't seem to read dkim or spf, but they are here as spamassassin can tell on my server : 

    X-Spam-Status: No, score=0.0 required=5.0 tests=DKIM_SIGNED,DKIM_VALID,
        HTML_MESSAGE,RCVD_IN_DNSWL_NONE autolearn=ham autolearn_force=no version=3.4.1
Received: from so254-22.mailgun.net (so254-22.mailgun.net [198.61.254.22])
        by ledzep.yeuxdelibad.net (OpenSMTPD) with ESMTPS id 538d7a71 (TLSv1.2:ECDHE-RSA-CHACHA20-POLY1305:256:NO)
        for <thuban@yeuxdelibad.net>;
        Wed, 9 Aug 2017 13:16:30 +0200 (CEST)
DKIM-Signature: a=rsa-sha256; v=1; c=relaxed/relaxed; d=mg.liberapay.com; q=dns/txt;
        s=smtp; t=1502277387; h=Message-ID: Date: To: From: Subject:
        MIME-Version: Content-Type: Sender;
        bh=dGd3OSLzylPKLkBDMH8JVb3Uo2o4+YC5OzHJgCceOxg=; b=N9dWUnqzITm0eEIvo/OyXWbrkuydvPujlIrGUvHB6J4TEEjBqjymWIPUuQVHUg8fWd3RGZE5
        /Ny46QIQu4BuleKrvkExbcZ/P5hwJ2tsNMtidBAaU4Ne4D05FSZnzzP6feusQ6Wmr3hXLSYb
        1xmm8x42Inx0PyPkqeA90QyGfK0=
DomainKey-Signature: a=rsa-sha1; c=nofws; d=mg.liberapay.com; s=smtp;
        q=dns; h=Sender: Content-Type: MIME-Version: Subject: From: To: Date:
        Message-ID;
        b=pyw1pXEFWJbc4Dx86FdSU96JVcH1gRZwYqrbkDaroZWXu4dRKutIENvEXf9IKItkSSEj1j
        /aVHpw9Z6g7JfUVPWUK8RkMrbfpIDKSX2v0v2Dab3WbBgJDCl3dZM39nV32o9xe2bnP69X5p
        +yGMAKqXzGSw3jHTPjMNQAUUUOO18=
Sender: support=liberapay.com@mg.liberapay.com

This is more an issue concerning OVH I think.

**Comment by Schoumi** [comment]
```
Received-SPF: Pass (sender SPF authorized) identity=mailfrom; client-ip=198.61.254.22; helo=so254-22.mailgun.net; envelope-from=bounce+4a66c0.ea41fd-contact=domaine.tld@mg.liberapay.com; receiver=contact@domain.tld 
Received: from so254-22.mailgun.net (so254-22.mailgun.net [198.61.254.22])
	by in14.mail.ovh.net (Postfix) with ESMTPS id D498666F
	for <contact@domain.tld>; Wed,  9 Aug 2017 13:15:21 +0200 (CEST)
DKIM-Signature: a=rsa-sha256; v=1; c=relaxed/relaxed; d=mg.liberapay.com; q=dns/txt;
 s=smtp; t=1502277315; h=Message-ID: Date: To: From: Subject:
 MIME-Version: Content-Type: Sender;
 bh=mVLmfYw0gUWwMkPBQF5iVZAjC1rUDY0datDxUrRNakQ=; b=PNa4KjpAgaWW+41M03UMpECkqN3eot2sArshMGRkC4zyRTp3/zeXLzqEYE4n7od2WVvmD03Y
 mXs3vsDAD8uDjkE6RIcZtLXjXRssHh7iFWp7ePkry28Ljed2ItJGxh/b9wHPVt5DQVEZdO01
 7FWGSR+aYV4IGZpUf/wZI7lzWgw=
DomainKey-Signature: a=rsa-sha1; c=nofws; d=mg.liberapay.com; s=smtp;
 q=dns; h=Sender: Content-Type: MIME-Version: Subject: From: To: Date:
 Message-ID;
 b=scAlRuuD8xSoZlJrVoiGScZAVHaxbzQdkkgSK6Q0V8qORdYST1lonKhc0BNhNPfJhsBviI
 5SOYUdyRcqxVQi0Pks1ryZ56fRJahV8Ma9UseaB+U5xwjOuRcELtGLhGdupGL8J7uXVdg1NG
 jmtGPZZMdAMlrcOqC15b5GNSkwjnM=
Sender: support=liberapay.com@mg.liberapay.com
```

The mail is in my inbox. It's just flag as spam and the object is change to [SPAM] original mail object. No more than that.
I've open a ticket on OVH support to identify the cause and to try to correct the problem if it's due to a configuration on OVH e-mail.

**Comment by chaica** [comment]
I hope I'm wrong here but if you're not a gold customer don't expect anything, especially a real investigation, from their support. You should try social networks to get an insider pushing your case.

**Comment by Schoumi** [comment]
I have an answer about the email, and they say they remove the email from their spamlist. 

Today it's not flag as spam. Will see if it come again as spam in some weeks.

**Comment by beebopfr** [comment]
You can decode the SPAMCAUSE header here : http://beebop.fr/spamcause-decode.html
