### ISSUE TITLE
make known the address of Crédit Mutuel Arkéa

### ISSUE THREAD

**Issue by grahamperrin** [liberapay/liberapay.com#677]
In IRC: 

![2017-08-26 09 40 14 liberapay mangopay sa](https://user-images.githubusercontent.com/192271/29740301-2dbe4e20-8a4b-11e7-803f-76fd766e43f5.png)

> … my (Halifax) banking form requires the address, in France, of CREDIT MUTUEL ARKEA
> 
> I'll try the address from http://www.arkea.com/banque/assurance/credit/mutuel/ecb_5052/en/contact

Changaco in IRC: 

> … I just checked: the name and address of the receiving bank aren't provided by mangopay when we initiate a payment, that's why it's not in the information we show/send you

**Comment by Changaco** [comment]
Closing as obsolete since we no longer process payments through Mangopay.
