### ISSUE TITLE
Card payments with saved number lead to confusing failures

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#681]
We allow users to save their card number so they don't have to input it again next time, however this is currently resulting in payment failures with a confusingly generic error message (`009499: Bank technical error`). What this apparently means is that the payer's bank is refusing the transaction because the [card's verification number](https://en.wikipedia.org/wiki/Card_security_code) is missing. Why is it missing? Because payment processors are not allowed to store it.

MangoPay is working on a solution to this problem. In the meantime we should either stop saving card numbers, or ask the user to re-input their card data when we get 009499 error code.

**Comment by jankeromnes** [comment]
Note: I've had a similar issue in #888 but with the error message `001599: Token processing error`. Retrying with freshly input card details worked.

👍 for asking for verification numbers again, or simply disabling saved cards for now.
