### ISSUE TITLE
Orphaned Bevry team and balupton account

### ISSUE THREAD

**Issue by balupton** [liberapay/liberapay.com#692]
Hi there,

It seems I have an active account that I can access at:
https://liberapay.com/balupton/

However I went to create a team for my organisation called Bevry, but was alerted that it already exists on Liberapay:
https://liberapay.com/Bevry/

It also seems that it is attached to an account that represents me, but is not me:
https://liberapay.com/~3787/

What I would like is:
- that account that seems to be me, but I do not have access to, be deleted
- have the Bevry team be associated to my active account

**Comment by Changaco** [comment]
Done.

```python
>>> Participant.from_username('Bevry').add_member(Participant.from_id(3792))
>>> Participant.from_id(3787).close(None)
```
