### ISSUE TITLE
Incomplete translation warning

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#712]
It's not good that we display partially translated pages to users, but what's worse is that we don't display a warning about the translation being incomplete.

**Comment by trebmuh** [comment]
@Changaco nice one. what about putting a link to the place (weblate) when the translation happen? Something like: "If you would be willing to help Liberapay with translating the missing parts into $LANG complete, please be welcome!" (with "be welcome" being the link to the place).
