### ISSUE TITLE
Blacklisted countries

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#729]
Mangopay now has a public list of [countries from which payments are blocked](https://mangopay.desk.com/customer/en/portal/articles/2299163-black-listed-countries), as well as a list of [payout rules per country](https://mangopay.desk.com/customer/en/portal/articles/2723231-which-are-the-rules-applied-for-pay-outs-black-listed-countries-). We should add links to those lists, or better yet integrate them into our app.

Context: https://github.com/liberapay/salon/issues/164#issuecomment-335142176

**Comment by Changaco** [comment]
Got an email from someone in Panama.

**Comment by Changaco** [comment]
https://mastodon.gamedev.place/@xananax/99344622821195035

**Comment by Changaco** [comment]
Got an email from a donor in Lebanon.

**Comment by Changaco** [comment]
Mangopay's list of payout rules per country is no longer available. :frowning_face:

**Comment by revi** [comment]
And looks like your ‘blacklsted countries’ link is actually ‘whitelisted countries’ list as of now.

**Comment by blinkenlight** [comment]
Well, I do understand you have very little recourse but frankly, this sucks. I have no idea what Mangopay's problem can conceivably be with an EU-member like Romania but thanks to their "_you can pay from anywhere in the world (as long as it's on this here list)_" I now know not to even try signing up for Liberapay. The saddest thing is the poor artist I would have tried supporting is even less at fault than I might possibly be...

**Comment by Changaco** [comment]
@blinkenlight You should definitely try, it's the only way to know for sure what works and what doesn't.

**Comment by Changaco** [comment]
Got an email from someone in Guatemala.

**Comment by Changaco** [comment]
Closing as obsolete now that we're no longer processing payments through Mangopay.

**Comment by mtremr** [comment]
> Mangopay's list of payout rules per country is no longer available. ☹️
https://docs.mangopay.com/guides/users/country-restrictions
