### ISSUE TITLE
[EU grant] alternative funding mechanism for non-author fee based open access publishing

### ISSUE THREAD

**Issue by jibe-b** [liberapay/liberapay.com#733]
How about Liberapay teaming up with an OpenAccess publishing service to provide a liberapay-style way of funding scientific publishing?

https://www.openaire.eu/second-call-for-proposals-for-alternative-funding-mechanism-for-non-author-fee-based-open-access-publishing

cc @bozana @sloria

**Comment by Changaco** [comment]
Hi,

We're pretty busy right now, so I'm not sure we can help, but can you elaborate on what you're proposing?

**Comment by jibe-b** [comment]
This is merely prospective: publication of scientific articles is associated with a bit of work and server maintenance costs, so money is and will always be in the scientific publishing process.

But as you may know, there is a fracture between monopolistic publishers and universities which are ok to allocate some money for publications but not so much.

Here could be where Liberapay comes into play: offering the opportunity for researchers themselves, to attribute fundings to publishers, either the mainstream ones, or even better, the preprint services and ethical and innovative journals (those who don't try to profit too much and have a real scientific activity), in the end, up to the individual.

The funding that could be attributed could be either their own money, or the fraction budget of the university library. 

This is somehow related in my mind with https://www.euroscientist.com/self-organised-scientific-crowds-remedy-research-bureaucracy/ cc

as well as https://enspiral.com cc @phillcoxon

**Comment by jibe-b** [comment]
cc @julienhering

**Comment by jorgesumle** [comment]
The deadline has finished, so I'm closing this issue.
