### ISSUE TITLE
Unclear wording in Widgets page

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#737]
See <https://github.com/liberapay/liberapay.com/commit/4f17550925da1a97ec713835aa9f1b27f45d2c38#commitcomment-24140861>.

**Comment by trebmuh** [comment]
Is that full review of the widget page suggested or was it only this string which needed to be changed?

**Comment by Changaco** [comment]
The second sentence `"Or, if you'd like to include a \"giving\" widget, you can use this:"` should also be modified in a similar way.

**Comment by trebmuh** [comment]
Done.
