### ISSUE TITLE
Virtual wallet for teams

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#753]
How donations to teams work is a little confusing. Aside from explaining it better (#752), we could also modify them to be closer to personal donations, and in the process make team accounts seem more "real".

The idea is to implement a "virtual" wallet for teams. During payday, when the team has a leftover, the money would "go into" the team's virtual wallet. The funds wouldn't actually move, they would still stay in the donors' wallets, but they would be tagged in our database as being reserved for future use by the team's members.

This approach would allow a collective to "accumulate" money without having to create a legal entity or join an existing one (fiscal sponsorship).

Thoughts?

**Comment by Changaco** [comment]
Related issue: #81.

**Comment by mattbk** [comment]
Does this have any legal implications? Does a team need to be a legal entity to have funds held in its wallet, rather than passing them through to the team members?

> Teams are for peer-to-peer donations, they can't be used by a legal entity to distribute donations to its members. https://liberapay.com/about/teams

**Comment by Changaco** [comment]
> Does a team need to be a legal entity to have funds held in its wallet, rather than passing them through to the team members?

Yes, a wallet has to have a single legal owner.

**Comment by Changaco** [comment]
It has just occurred to me that implementing this could also solve our payday scaling issue, because if we can do virtual transfers for teams we can do them for everyone, and then we can only do real transfers when a user actually wants to withdraw the money, thus greatly reducing the number of transfers on the Mangopay side and shifting them from being "all at once" during payday to being more spread out.

One downside is that legally speaking a donor could end up sending money to someone they didn't intend to fund, because Alice gave to Bob but he redistributed money to Carl so in the end Alice gives to Carl.

Another downside is that the wallet balances on the Mangopay side wouldn't match the new virtual balances on our side, so if we mess up the virtual balances we won't be able to look at the Mangopay balances to help us figure out what went wrong. We should make sure we have proper DB checks on our side to help us detect errors in virtual balances.

I wonder if this is a good solution or if we would be better off working on providing umbrella organizations for teams so they can have real wallets, and dealing with the payday scaling issue in some other way.

**Comment by chrismarquardt** [comment]
Our current workaround is that one member of the team withdraws all team funds to their wallet weekly and keeps book outside Liberapay. Not ideal, requires more trust and any better solution would be highly appreciated. Thanks for your great work so far!

**Comment by timpritlove** [comment]
I also just ran into this issue because I just expected it to already behave exactly as described in this change request. Which means I have left a lot of money on the table without knowing.

Is this just for teams or is the behaviour for organisations the same?

**Comment by Changaco** [comment]
@timpritlove It's only teams.

**Comment by Changaco** [comment]
This idea is no longer implementable since donors no longer have wallets.
