### ISSUE TITLE
Wording is not clear enough when adding money

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#758]
https://twitter.com/josh_cheek/status/921716393766211584

**Comment by ziyadedher** [comment]
I am interested in this, but I have been looking around trying to find where the error messages are stored and they seem to be in a database somewhere which I cannot find.  Could you lead me in the right direction?

**Comment by Changaco** [comment]
Actually this issue isn't about the error message, it's about the wording of the page before that, which apparently doesn't make it clear that the payment is attempted immediately and in full, as opposed to a weekly charge.
