### ISSUE TITLE
Increase the default nominal take from zero

### ISSUE THREAD

**Issue by mattbk** [liberapay/liberapay.com#765]
For teams that only have one member, it may not make sense to the user to check that their nominal take is set above 0.00, because why look at takes if you're the only one taking? The assumption may be that all donations will come to you automatically.

I suggest that the nominal take be set at some reasonable amount (10? 100?) for the first team member. Then when that team member goes to add a member, a notice could be displayed that shows the takes table and suggests modifying this value.

See, for example, https://liberapay.com/SocialCoop/income/.

(Mistakenly posted this at https://github.com/liberapay/liberapay.org/issues/24 first.)

**Comment by mattbk** [comment]
https://github.com/liberapay/liberapay.com/blob/master/liberapay/models/_mixin_team.py

**Comment by Changaco** [comment]
I would prefer that we work on properly improving [team management](https://github.com/liberapay/liberapay.com/milestone/3) for everyone instead of implementing this small hack for single-member teams.

For example we should improve notifications so that team members are made aware of their teams' leftovers every week.

**Comment by pulkomandy** [comment]
Even when there are multiple users, I'm not sure the default intake should be 0. Maybe it should be (amount received by team / number of members), or (leftover / number of members).

I had a look at some teams and I see that sometimes people don't dare to increase their intake. Maybe they feel their contribution to the team doesn't deserve taking money from it? If there was instead a default amount that shares the money somewhat evenly, they could make the decision to get less than the default, but still take something.
