### ISSUE TITLE
Badge at Shields.io

### ISSUE THREAD

**Issue by mattbk** [liberapay/liberapay.com#775]
I recently updated the one for Gratipay, so this should be simple enough for me to take on. Will look into it.

**Comment by mattbk** [comment]
In progress at https://github.com/badges/shields/pull/1251.

**Comment by mattbk** [comment]
I think it's done, waiting for Shields review.

https://user-images.githubusercontent.com/3729038/32533766-ebf45f0a-c417-11e7-8fb8-55d7ec029c41.png

**Comment by mattbk** [comment]
badges/shields#1251 has been merged, waiting for deploy.

**Comment by Changaco** [comment]
!m @mattbk

**Comment by mattbk** [comment]
From https://github.com/badges/shields/issues/1545, looks like this was deployed in late February. Sorry about that. :grimacing: 

<img width="829" alt="screen shot 2018-04-03 at 8 41 02 pm" src="https://user-images.githubusercontent.com/3729038/38284169-7df86c90-377f-11e8-9870-ba85881a8103.png">

**Comment by Changaco** [comment]
Thanks @mattbk.

> (sorry about that :grimacing:)

It's not your fault. Anyway I've figured out how to configure Cloudflare to cache the JSON files there.
