### ISSUE TITLE
Don't show cancelled tips when migrating from Gratipay -> Liberapay

### ISSUE THREAD

**Issue by rohitpaulk** [liberapay/liberapay.com#776]
All of my cancelled tips are shown in the list, I think they can be ignored for importing (or at least de-emphasized in the list)

![screen shot 2017-11-02 at 11 26 46 pm](https://user-images.githubusercontent.com/3893573/32342098-6aaee168-c025-11e7-9141-e9332def2fac.png)

**Comment by Changaco** [comment]
Agreed, the sentence doesn't make much sense when the amount is zero.
