### ISSUE TITLE
Mention that 'merging' liberapay/third-party accounts is possible when migrating

### ISSUE THREAD

**Issue by rohitpaulk** [liberapay/liberapay.com#777]
When using the Gratipay -> Liberapay migration flow, I saw text that said something along the lines of "We couldn't import your github username 'rohitpaulk', because it is already linked to another account". 

However, I could go to my 'Profile' page and link my github account successfully.

**Comment by Changaco** [comment]
We can do more than mention the possibility, we should be doing the merge automatically when the existing account is a stub.
