### ISSUE TITLE
The contact page isn't clear enough

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#797]
We regularly receive messages which are not addressed to us but to one of our users. The most common type is take-down requests for [archive.is](https://archive.is/) pages. This morning I received one of those in a FedEx package (#785) instead of the usual email.

Clarifying the contact page could potentially save everyone time.

**Comment by mattbk** [comment]
This was an issue at Gratipay as well.

**Comment by trebmuh** [comment]
:+1:

**Comment by Changaco** [comment]
For the record, I doubt the new paragraph will be sufficient to completely fix the problem, but it's better than nothing.
