### ISSUE TITLE
Unclear how currency is set

### ISSUE THREAD

**Issue by mattbk** [liberapay/liberapay.com#813]
I couldn't find a setting, but I assume it's based on nationality? Americans default to $, others default to euro?

Related: Am I right that currencies are kept separate, and that's why I need to pay in with $ to set a new donation? That's what it looks like from /about/stats:

> €29,925.80 + $32.15 is escrowed within Liberapay.

**Comment by Changaco** [comment]
This is part of #182. I know it's confusing, but it's because multi-currency support is not finished yet. There was a deadline so I had to push a half-baked feature into production.

> Americans default to $, others default to euro?

No, right now the only way to get a USD account is to migrate from Gratipay.

> Related: Am I right that currencies are kept separate, and that's why I need to pay in with $ to set a new donation?

Yes.

**Comment by Changaco** [comment]
@mattbk Are we good to close this?
