### ISSUE TITLE
Link "insufficient funds" notice to wallet/payin

### ISSUE THREAD

**Issue by mattbk** [liberapay/liberapay.com#819]
![2017-12-01_11-56-56](https://user-images.githubusercontent.com/3729038/33496201-ee51e36a-d68e-11e7-8090-82e7ce54d6fe.png)

Would make it easier for user to know what exactly to do.

**Comment by Changaco** [comment]
I'm not sure this is necessary, the "Add money" button is just above. See screenshot in <https://github.com/liberapay/liberapay.com/issues/182#issuecomment-343521220> for example.

**Comment by mattbk** [comment]
![iwkad22](https://user-images.githubusercontent.com/3729038/33502789-14379d0a-d6a7-11e7-9323-0305df4bda5a.jpg)
