### ISSUE TITLE
Default wallet/payin does not default to USD for users using that currency

### ISSUE THREAD

**Issue by mattbk** [liberapay/liberapay.com#820]
Note: I'm pretty sure this is only an issue for those users who had accounts merged from Gratipay.

My account uses USD.

From the menu, https://liberapay.com/mattbk/wallet/payin brings me to a EUR page.

From setting a new donation (e.g.,https://liberapay.com/ConEmu/donate), https://liberapay.com/mattbk/wallet/payin?currency=USD brings me correctly to a USD page.

Is the easiest way to allow users to choose the currency on that page?

**Comment by Changaco** [comment]
This is also part of #182. I have a commit for the payin page in my local `currencies-6` branch, it adds separate sections for each currency the user has donations in.
