### ISSUE TITLE
Repeated clicks on "View income history" adds duplicates of the graphs

### ISSUE THREAD

**Issue by aklar** [liberapay/liberapay.com#822]
When you click on the button "View income history" (located on people's profiles in the "History" section) the graphs are revealed. But the button remains active so you can repeat to click on it, adding more and more of the same graphs.

My suggestion would be to either de-activate the button or change it into a "Hide income history" button.

Thanks for all your efforts and evolving this great platform!

**Comment by Changaco** [comment]
I'm pretty sure we used to deactivate the button.

**Comment by ZacharyThomas** [comment]
Picked this up because it seemed straight forward :)
