### ISSUE TITLE
The identity form scares off some people

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#824]
Copy-paste of a profile statement:

> This account was created to prevent someone else from pretending to be [me]. Please visit and donate to [Patreon account]. I would be happy to have a full-fledge Librepay account, but the requirements for proof of identity are too much for the yearly €1,000 income.

**Comment by Changaco** [comment]
Related question: is there someone here who isn't European and has received a significant amount of money in a year via PayPal? What did you have to do to prove your identity?

**Comment by artsyhonker** [comment]
I think even among people in the EU, a lot of people who use PayPal and haven't received that much are unaware of the identity requirements. I certainly was.

**Comment by Changaco** [comment]
The only reason I know about PayPal doing the same thing is because it happened to me back in the day when I received a somewhat significant amount of money from working on Gratipay.

**Comment by Changaco** [comment]
The problem is people don't realize that they're essentially opening a bank account when signing up for PayPal or Liberapay, so they're surprised by the paperwork even though it would probably seem normal to them if they were opening a traditional bank account.

**Comment by artsyhonker** [comment]
Yes -- I wonder if wording like "Just as you need to provide ID for other online accounts like PayPal, if you [receive X/donate Y] we'll need to see [forms of ID] would make it sound less daunting?

**Comment by artsyhonker** [comment]
I know of one person, not sure if it's the same one, who has set up Ko-Fi instead of Liberapay and said it's because they "can't afford a passport", but they will run into the same problem eventually anyway.

**Comment by artsyhonker** [comment]
(Argh, no, I just looked it up and it was another service, not Liberapay. So.)

**Comment by myfreeweb** [comment]
It's not clear to me whether the €1000 limit is about withdrawing money or just receiving to the liberapay account. If I were to set up an account and receive donations only to redistribute them inside of the service, never withdraw, would I still need to worry about this?

**Comment by Changaco** [comment]
It's about all the money received, not just withdrawals.

**Comment by Changaco** [comment]
Closing as obsolete since identity verification is now handled by Stripe and PayPal instead of through Liberapay.

**Comment by Changaco** [comment]
https://octodon.social/@cwebber/100900306465517419

**Comment by Changaco** [comment]
@revi A few months ago I asked Mangopay what they do with KYC documents, they claim that due to financial regulations "user data can only be deleted 5 years after the last use of the user account". Does that answer your question?
