### ISSUE TITLE
More currencies

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#833]
This issue is about the following paragraph from <https://medium.com/liberapay-blog/liberapay-now-supports-us-dollars-f9484e3008f8>:

> Our payment partner currently supports 9 other currencies which could be added to Liberapay: the British pound (GBP), the Canadian dollar (CAD), the Swedish krona (SEK), the Norwegian krone (NOK), the Danish krone (DKK), the Swiss franc (CHF), the South African rand (ZAR), the Polish złoty (PLN), and the Australian dollar (AUD). Please reach out to us if you’re interested in receiving donations in one of these currencies.

**Comment by Changaco** [comment]
We have a first +1 for CAD from <https://mastodon.zombocloud.com/@staticsafe/99134531153221958>.

**Comment by Changaco** [comment]
https://mastodon.art/@awyruu/99134759598579659

> I signed up before I'd finished my morning coffee haha!! I prefer having things in USD (AUD to USD is... kinda bad), & I do know from that USD to AUD does work - or at least it does for me.
>
> I can't program, but I thought I should let you folks know about this. Also, I obviously have interest in AUD support being a thing.

**Comment by Changaco** [comment]
+1 for GBP from https://mastodon.at/@JubalBarca/99135829048118644

**Comment by Kithop** [comment]
+1 for CAD here too! :)

**Comment by artsyhonker** [comment]
I would definitely like GBP!

**Comment by artsyhonker** [comment]
(I mean, the pound is all over the place at the moment, and in some ways it's better for me if my income is in a more stable currency like EUR, but I think my patrons are more likely to get involved if they see £, so.)

**Comment by LiamDawe** [comment]
GBP please! This would incredibly simplify the system for taxes for those of us in the UK. In fact, it would make you my favourite platform and one of very few that would do it.

**Comment by maurokenny** [comment]
Hey, my first comment here. What about cryptocurrencies? E.g. Bitcoin (most famous), Litecoin and Dash (low fees). This would save a lot of money and the system would have a new feature in comparison to the main alternatives. Of course that we need to think about the details, but it would keep the same system idea. It will be a place to send credits (escrow) containing an auto timed basis payment to the content creator.

**Comment by iangilfillan** [comment]
If your payment partner offers this, what is the downside of adding a new currency? Excited to see the South African rand on there, this will ease things for people from here receiving donations.

**Comment by Changaco** [comment]
The downside is additional complexity. For example we currently have a binary choice for currencies: you can either accept all of them or only one; since we only have two currencies all possibilities are actually covered, but as soon as we add more currencies two options won't be enough anymore.

There's also a bit of work to do under the hood because some of our code can only handle two currencies at the moment, we need to make it generic before adding more.

**Comment by maurokenny** [comment]
Hey, my first comment here. What about cryptocurrencies? E.g. Bitcoin (most famous), Litecoin and Dash (low fees). This would save a lot of money and the system could have a new feature in comparison to the main alternatives. Of course that we need to think about the details, but it would keep the actual system idea. It will be a place to send credits (escrow) and then send money to the content creator with an auto timed basis.

**Comment by Changaco** [comment]
Cryptocurrencies are a separate matter, see #364 and #567.

**Comment by sejomagno** [comment]
This one is not in the list, but I just want to say that it would be great to eventually have the Mexican peso (MXN) :smile:

**Comment by yaxu** [comment]
+1 for GBP, well really it doesn't really make sense for me to take donations without wide cross-currency support, as some might take offence if their donation isn't accepted based on where they live.

**Comment by Changaco** [comment]
> if their donation isn't accepted based on where they live.

That is unavoidable (#729). It's also mostly unrelated to the number of currencies supported inside Liberapay.

**Comment by yaxu** [comment]
Righto, I don't fully understand how this works but just a +1 on supporting as many currencies as is easily possible. Thanks for your work on this

**Comment by Changaco** [comment]
+1 for INR from https://mastodon.social/@prashere/99883593355335663

**Comment by fullofcaffeine** [comment]
+1 for MXN

**Comment by fullofcaffeine** [comment]
I'm new to liberpay, just found it out. Happy I did! I don't know much about it yet: how complicated is it to support new currencies? Do you work with any payment gateways in particular? I'm particularly interested in adding supprot for Mexican Peso.

**Comment by Changaco** [comment]
Here is the list of the 31 currencies I'm working on adding:

- Australian Dollar (AUD)
- Bulgarian Lev (BGN)
- Brazilian Real (BRL)
- Canadian Dollar (CAD)
- Swiss Franc (CHF)
- Chinese Yuan (CNY)
- Czech Koruna (CZK)
- Danish Krone (DKK)
- British Pound (GBP)
- Hong Kong Dollar (HKD)
- Croatian Kuna (HRK)
- Hungarian Forint (HUF)
- Indonesian Rupiah (IDR)
- Israeli New Shekel (ILS)
- Indian Rupee (INR)
- Icelandic Króna (ISK)
- Japanese Yen (JPY)
- South Korean Won (KRW)
- Mexican Peso (MXN)
- Malaysian Ringgit (MYR)
- Norwegian Krone (NOK)
- New Zealand Dollar (NZD)
- Philippine Piso (PHP)
- Polish Zloty (PLN)
- Romanian Leu (RON)
- Russian Ruble (RUB)
- Swedish Krona (SEK)
- Singapore Dollar (SGD)
- Thai Baht (THB)
- Turkish Lira (TRY)
- South African Rand (ZAR)

**Comment by Changaco** [comment]
The 31 new currencies are now live. The form to modify the list of currencies you accept is in https://liberapay.com/about/me/edit/currencies

**Comment by Changaco** [comment]
(The new issue for additional currencies is #1288.)

**Comment by Changaco** [comment]
The first payment in one of the 31 new currencies (PLN) has just been successfully processed via PayPal.
