### ISSUE TITLE
Feedback from an author I follow

### ISSUE THREAD

**Issue by traverseda** [liberapay/liberapay.com#838]
An author I follow had this to say about libera pay, not sure what the appropriate feedback mechanism is so I figured I'd dump it in a ticket a-la gratipay.

---

They have a much better 'donate to creators' model than Patreon's, as paying into a wallet and then moving the money internally drastically reduces the fees for all concerned. Unfortunately, they are purely a payment system, they don't have the patron management and publishing platform that Patreon provides, so I can't dump Patreon in their favor -- there's no easy way for me to post the content and control who it goes to.

Believe me, if I had another option aside from Patreon I would use it. Their platform is terrible, but it's also the only game in town. If you or anyone you know have the tuits to build a competitor I'll be your first customer as long as you provide:

 * Ability to publish to any set of tiers, not just "tier #X and up". I want to publish to my $5/month patrons on (e.g.) Monday and then publish the same thing to the $1/month ones on Tuesday without having the $5 people get it again.

 * Ability to schedule publication in advance. I'd like to have a buffer set up that would automatically go out at a specified date/time. Right now my option is "do it manually" or "publish manually and also set the 'make this public in 3 days' checkbox"

 * A decent WYSIWYG editor. Theirs is horrendous.

 * The basics: create a profile, create tiers and associate rewards with them, provide tools for communicating with my patrons, provide an easy way for me to get the money.

**Comment by Changaco** [comment]
Dumping messages in GitHub is fine, although https://github.com/liberapay/salon is more appropriate than the main repo.

Relevant answer: https://mastodon.rocks/@Liberapay/98890540440886249
