### ISSUE TITLE
Add way to follow / bookmark creators without donating (yet)

### ISSUE THREAD

**Issue by voltagex** [liberapay/liberapay.com#841]
I'm trying to collate a list of creators that are on Liberapay as I move away from other platforms. I'm waiting for things to settle down before I add money / start donating, so I'd like a way to bookmark creators.

**Comment by Changaco** [comment]
This issue is a duplicate of #48.

@voltagex If you're not already an active donor on Liberapay then as a temporary workaround you can set up donations and not add any money (so they'll be inactive).

**Comment by voltagex** [comment]
Sorry - obviously my keyword searching was not good enough!
