### ISSUE TITLE
Lacking singular in several translation-strings

### ISSUE THREAD

**Issue by Katharsisdrill** [liberapay/liberapay.com#843]
I am not sure if this is the right place to write - but here goes:

In several translations strings with singular/plural option the singular has strings that look like this:

_<unused singular (hash=e5b7d2c32b1e52c487dbaf69fc0de6a6)>_

Is this an error. Am I to copy it or let the field be empty. I can see that the other translators has done different things...

**Comment by jorgesumle** [comment]
See https://github.com/liberapay/salon/issues/125#issuecomment-329496197

It doesn't matter what you write, it won't be displayed.

**Comment by Katharsisdrill** [comment]
Thanks!
