### ISSUE TITLE
Polish translation - typo

### ISSUE THREAD

**Issue by argus-core** [liberapay/liberapay.com#849]
The translation of "Pledges" on https://liberapay.com/~USERID/giving/ page has a typo. It should be "Darowizny" instead of "Daarowizny".

**Comment by Changaco** [comment]
You can submit a fix for this yourself on Weblate, using the [search feature](https://hosted.weblate.org/projects/liberapay/core/pl/#search) to find [the incorrect translation](https://hosted.weblate.org/translate/liberapay/core/pl/?checksum=&offset=&q=Daarowizny&search=ftx&target=on&type=all&ignored=False&date=&only_user=&exclude_user=).

**Comment by argus-core** [comment]
Done.

**Comment by Changaco** [comment]
Nice! Thanks for contributing @argus-core!
