### ISSUE TITLE
Support monthly and yearly amounts in donation form

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#85]
I'm not sure yet how this should be implemented.

**Comment by Changaco** [comment]
+1 from https://twitter.com/UdoKifferbrehl/status/701047839397433344

**Comment by UdoKifferbrehl** [comment]
+1

**Comment by Changaco** [comment]
We now have basic support for monthly and yearly donation amounts. :tada: In reality all donations are still processed weekly, but now users can input a monthly or yearly donation amount and the server automatically computes the weekly equivalent. You can see what it looks like on <https://liberapay.com/Liberapay/donate> for example.
