### ISSUE TITLE
Is "wallet" really a word we want to use?

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#855]
The word "wallet" refers to a physical object which can be relatively easily lost or stolen. Can the fact that we use this word lead to a conscious or subconscious lack of trust in the security of Liberapay?

**Comment by trebmuh** [comment]
I wouldn't think so. Have you any alternative in mind maybe?

**Comment by Changaco** [comment]
There's "vault", although it may have the opposite problem of sounding paranoid to some people I guess.

We could also try not to use a separate word and just say "Liberapay account" instead.

**Comment by trebmuh** [comment]
There is "purse" also which stands for "porte-monnaie" in French. Maybe that fits better the meaning intended than "vault" (salle des coffres / chambre forte [FR]) or wallet (porte-feuille [FR])?

Still, you can forget your purse that said.

**Comment by artsyhonker** [comment]
I don't think it sounds untrustworthy because the physical object is portable, but I think bitcoin and other blockchain currencies make use of the term, and I'm not sure it's a good idea to be associated with those at the moment.

I think "account" is probably the most neutral.

**Comment by LeifSimmons** [comment]
Why not call it an account? Isn't that what it is?

**Comment by mattbk** [comment]
I have no problem with "wallet," but "account" would probably work just as well. The term "wallet" isn't used that much on the site, but it's an important menu item that needs to be named well enough that people know what it is.

![image](https://user-images.githubusercontent.com/3729038/33847646-daff236a-de70-11e7-84ed-49d5df27ef50.png)

At Gratipay it was "payments" which I thought was confusing.

**Comment by artsyhonker** [comment]
Are there potential disambiguation issues with "account"?

(I'm thinking probably not...)

If so, would "Account balance" work?

**Comment by Changaco** [comment]
The "Wallet" menu item links to a page which used was called "History" back in the day IIRC. "Ledger" would be the technically correct term. The "Add money" and "Withdraw money" items could be moved under "Giving" and "Receiving" respectively.

**Comment by LiamDawe** [comment]
I see nothing wrong with Wallet, everyone knows what it means.

**Comment by LeifSimmons** [comment]
The reasons I suggested "account" are: 
- It is how I view it the wallet.
- I read around here somewhere that users had a hard time understanding why they needed to provide identification on Liberapay, even though they usually don´t have a problem understanding why they need to do it when opening a bank account.

Having that, I think the term "wallet" works just fine and I don't think that it leads to any trust issues.

**Comment by iangilfillan** [comment]
'Account' is preferable, and is already used on the Wallet page ('Account Statement'). It's standard, and well-understood. I don't have a big problem with 'wallet', it's just not as good a term, and it implies something held by the user (even a bitcoin wallet is in possession of the user, as opposed to an account on an exchange).

**Comment by mattbk** [comment]
One reason I like "wallet" is that multiple currencies actually function as a physical wallet, because there is no conversion. In your physical wallet, you can have some cash in USD and some in EUR, but you can't mix them during a transaction. This is essentially the behavior right now.

**Comment by LeifSimmons** [comment]
This multi currency implementation is confusing. If the wallet actually contains multiple accounts, one for each currency, then, then the separate accounts should be shown with it's own total & transactions. The wallet could then be called _"Accounts"_ (plural).

**Comment by miwilc** [comment]
I think "wallet" / "wallets" is just fine and gives the correct meaning.

A different example of this is a BTC wallet.

**Comment by Changaco** [comment]
Closing as obsolete since wallets are going away.
