### ISSUE TITLE
Running a test platform on a non AWS VM.

### ISSUE THREAD

**Issue by nightstryke** [liberapay/liberapay.com#856]
I'm having a problem running this in a VirtualBox VM environment as I cannot use release.sh because it calls for elastic beanstalk which a normal VM would not have that installed and trying to get it in a non-AWS VM seems to be quite the pain in the proverbial rear.

Does anyone have a workaround for this?
Could someone help me out?

**Comment by Changaco** [comment]
`release.sh` isn't meant to be used for local development/testing, it's only for deployment to production.

**Comment by nightstryke** [comment]
@Changaco That's great, but you can't just assume that everyone will want to or can use AWS for their needs. There's too many options out there for reliable hosting, vm, dedicated servers etc.

My question still still stands, how would one use release.sh without elastic beanstalk?

**Comment by Changaco** [comment]
Liberapay isn't designed for self-hosting, you can't deploy it to anything without modifying `release.sh` accordingly.

**Comment by nightstryke** [comment]
@Changaco from what i've seen release just uses 3 or 4 lines with the elastic beanstalk function. How should I go about either rewriting the release.sh or modifying release.sh?
Any suggestions?

**Comment by Changaco** [comment]
No offense, but why would I spend time helping you when I don't even understand what exactly you're trying to do and why you're doing it?

**Comment by nightstryke** [comment]
So that means it'll take too long to explain or it's too complicated and that those representing Liberapay would rather be at the behest of Amazon AWS then letting anyone run or use their software on a Private Dedicated Server or Virtual Machine. I guess that means then it's better to scrap trying to mess with liberapay and move on then. Thanks for your input at least.
