### ISSUE TITLE
The quarantine is unclear

### ISSUE THREAD

**Issue by LiamDawe** [liberapay/liberapay.com#861]
So I just got my first weekly amount from Liberapay. Fully understand funds have to be kept for a month for the stated reasons, however, it doesn't work right.

It says "You have €17.50 in your Liberapay wallet. Out of that, €2.99 is available for withdrawal, the rest is still in quarantine."

Why do I have 2.99 I cam withdraw? It should all be in quarantine I've only been signed up for 1 week.

**Comment by Changaco** [comment]
The quarantine is actually from the moment the money entered the donor's wallet, not yours. Sorry about the confusion. Things will become even harder to explain once #307 is taken care of.

**Comment by LiamDawe** [comment]
Right, this is getting messy.

We need to know when they will clear then, can the date be listed next to the donation in the wallet?

**Comment by Changaco** [comment]
I think we'll need some kind of graphic representation of the "cash bundles" in your account showing how much money will become withdrawable each day.

**Comment by LiamDawe** [comment]
Well it needs something, we need to know when funds enter the account for tax purposes.

In the UK, you're liable as soon as you can withdraw it. So right now, I would need to check every single day which becomes a bit of a nightmare.

**Comment by LiamDawe** [comment]
The main issue is just making it clear when the funds will be available.

**Comment by LeifSimmons** [comment]
@Changaco 
> The quarantine is actually from the moment the money entered the donor's wallet, not yours.
Isn't the quarantine an attempt to safeguard against card fraud? Is it really needed for money transferred to the donors wallet using bank wire or direct debit?

**Comment by Changaco** [comment]
Yes, the quarantine was originally created to provide some protection against card chargebacks (#2). Bank wires cannot technically be pulled back, however I'm not sure if the payer could use a consumer protection law to obtain a refund within 14 days, so a two-weeks quarantine could still make sense. Direct debits can be disputed and "pulled back" just like card payments, although I don't remember if the period is also 13 months.

**Comment by LiamDawe** [comment]
Thinking on this more, is it possible to take a re-look at the time? A month seems to be an overly long time. Wouldn't 14 days cover all bases?

**Comment by Changaco** [comment]
1 month is a short quarantine, the period for card payment disputes is 13 months.

The ticket for a more advanced quarantine system is #307.

**Comment by Changaco** [comment]
Closing as obsolete since there is no quarantine anymore.
