### ISSUE TITLE
Change "Pledges" to "Future Pledges"

### ISSUE THREAD

**Issue by iangilfillan** [liberapay/liberapay.com#864]
Since there are users coming from Patreon, 'pledge' is the term used there for current donations. The content Is not what I expected when visiting the page for the first time.

**Comment by Changaco** [comment]
That does sound better to me.

Other ideas: "unclaimed pledges", "unclaimed donations".

**Comment by mattbk** [comment]
Ooh, I like those more.

**Comment by revi** [comment]
+1 on `Unclaimed`.

**Comment by iangilfillan** [comment]
Agree, 'unclaimed' is better than 'pending' or 'future'

**Comment by trebmuh** [comment]
+1 for "unclaimed"

**Comment by Changaco** [comment]
What about "donation promises"? It doesn't sound "negative" like "unclaimed" does a little (to me at least). It's also basically the same as what we use in French (*promesses de don*).

**Comment by trebmuh** [comment]
even better !

**Comment by miwilc** [comment]
I don't think "donation promises" translates properly into English.

+1 for Unclaimed, it gives the right meaning.

**Comment by iangilfillan** [comment]
I don't think unclaimed sounds negative. Lotteries in the English-speaking world use the term for unclaimed winnings, and there's nothing particularly negative about it - the recipient just needs to appear to claim the money, as is the case here. Agree that "Donation promises" sounds a bit off in English.
