### ISSUE TITLE
Ambiguous text on Organizations/Teams/Individuals pages

### ISSUE THREAD

**Issue by iangilfillan** [liberapay/liberapay.com#867]
The Individuals page starts with "The top 18 individuals on Liberapay are:" (and likewise for Organizations). Are these all the organizations/individuals there are? If not, how can I browse/search more?

The teams page is more definitive, stating "There are 210 teams on Liberapay" and presumably lists them all.

**Comment by mattbk** [comment]
To answer your questions, no, these are not all the organizations/individuals there are.

Searching can be done with the menu item, but direct browsing of individuals and organizations is not possible at the moment. Looking through the [communities](https://liberapay.com/explore/communities) is probably the next best way to browse right now.

IMHO the truncated Explore pages should be pagified and include filters.

**Comment by iangilfillan** [comment]
Agree, in that case the results should be pagified.
