### ISSUE TITLE
Usability - Teams/Individuals/Organizations

### ISSUE THREAD

**Issue by iangilfillan** [liberapay/liberapay.com#869]
Following on from #539, it may be unclear to users what an organization is. Teams has a description and a link, and seems clear, but not organizations.  If a user is setting up an account on behalf of an organization, should they first register an account? If they are not logged in/registered, the signup process appears to be the same no matter which create button they click.

Similarly, when creating an organization account while logged in, the system tells the user that they are already logged in (with a user number, rather than a name), but it's not clear what it's expecting after that.. Which email address? The existing one used for the current account (in which case the system should know it already), or a new one for the organization?

**Comment by Changaco** [comment]
Closing in favor of #1105 and #1107.
