### ISSUE TITLE
Wrong amounts in income notification

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#870]
https://twitter.com/icculus/status/941034084792459267

**Comment by mattbk** [comment]
![image](https://user-images.githubusercontent.com/3729038/33962042-d1a6379e-e015-11e7-909e-d1e34a451281.png)

**Comment by Changaco** [comment]
I'm not sure where the problem is. I'm thinking of avoiding it by showing the exact amounts instead of fuzzy totals (related issue: #851).
