### ISSUE TITLE
Which Cloudflare mode do you use?

### ISSUE THREAD

**Issue by rugk** [liberapay/liberapay.com#876]
I don't like Cloudflare [as they always MI(TM your traffic – by design](https://scotthelme.co.uk/cloudflares-great-new-features-and-why-i-wont-use-them/). But if you use it, I hope you have at least set Cloudflare to "Full SSL (Strict)" as Cloudflare has already been used for MITM traffic [e.g. in India](https://medium.com/@karthikb351/airtel-is-sniffing-and-censoring-cloudflares-traffic-in-india-and-they-don-t-even-know-it-90935f7f6d98#.3ie9791kb).

**Comment by Changaco** [comment]
Yes, we use "Full SSL (Strict)":

![screenshot_20171215_140611](https://user-images.githubusercontent.com/1581590/34043387-1beacdd8-e1a1-11e7-9172-40d31182efb6.png)
