### ISSUE TITLE
[Suggestion] "Tip this person" bookmarklet/webextension

### ISSUE THREAD

**Issue by jibe-b** [liberapay/liberapay.com#877]
As Liperapay is social networks accounts oriented, a webextension (or bookmarklet as a start) could open the pledge page when you are on the social network account of this person and click on it.

Here is a sketch:

```if(location.href.match('https://twitter.com/')){

  location.href=location.href.replace('https://twitter.com/','https://liberapay.com/on/twitter/');

}

if(location.href.match('https://github.com/')){

  location.href=location.href.replace('https://github.com/','https://liberapay.com/on/github/');

}
```

As a bookmarklet:

`javascript:(function(){if(location.href.match('https://twitter.com/')){location.href=location.href.replace('https://twitter.com/','https://liberapay.com/on/twitter/')};if(location.href.match('https://github.com/')){location.href=location.href.replace('https://github.com/','https://liberapay.com/on/github/');}})()`

**Comment by Changaco** [comment]
Maybe @clone1018 or someone else can migrate https://github.com/gratipay/gratipay-everywhere to Liberapay?

**Comment by Bat41** [comment]
I looked at the code of this extension and it seems to be very complicated, while it could fit in a few lines of code. And there is two different versions: one for Chrome, the other for Firefox, when we could only have one thanks to WebExtensions. Maybe staring something new would be simpler?

**Comment by jorgesumle** [comment]
> the other for Firefox

That version doesn't do anything useful. It isn't even published.

> Maybe staring something new would be simpler?

Yes, definitely, but maybe we can reuse some code and ideas. I can create an initial WebExtenssion and we can start working together if you want, @Bat41

**Comment by jorgesumle** [comment]
Most of the code can be reused. I just finished the GitHub version.

![bildschirmfoto vom 2017-12-17 00-20-28](https://user-images.githubusercontent.com/14212780/34075217-1a5bcea2-e2c0-11e7-8085-d924de16143a.png)

**Comment by jorgesumle** [comment]
I just uploaded the code to my GitLab account, hoping that we can transfer it to our inactive GitLab organisation and start working toward https://github.com/liberapay/liberapay.com/issues/46

Here is the temporary URL: https://gitlab.com/jorgesumle/liberapay-everywhere

**Comment by mattbk** [comment]
!m @jorgesumle

**Comment by Changaco** [comment]
@jorgesumle I've added you to the Liberapay group on GitLab (as requested in IRC). Let me know if you need more permissions.

**Comment by Bat41** [comment]
@jorgesumle Oh, I was thinking about something really simpler, like a page action (these buttons that appears at the right of the address bar) that open the wanted Liberapay page. It would result in less code, being less dependent on websites changes (what if GitHub changes the CSS classes they are using?) and being less "intrusive".

**Comment by jorgesumle** [comment]
That doesn't make it much simpler. We should still check for the author name in some way, it's impossible to do that without having some website dependent code. I prefer that too. But it's just a different way to do it. What do you think @jibe-b, @mattbk, @Changaco, and other people?

The source code repository is https://gitlab.com/liberapay/liberapay-everywhere

**Comment by Bat41** [comment]
Most of the time, we can get the user's name only with the URL, which will probably never change. But refactoring some CSS and changing a class name can happen at any time. If we were parsing URLs, we would only need a regex/function per website, all the rest of the code would be shared.

**Comment by jibe-b** [comment]
Url parsing is definitely the simplest thing to do.

**Comment by jorgesumle** [comment]
> Url parsing is definitely the simplest thing to do.

II like the idea of a page action. But the URL parsing alone isn't enough, we would need a blacklist too, which is even more complicated to maintain. For example, for GitHub:

- https://github.com/blog/*
- https://github.com/marketplace/*
- ...

The code that @clone1018 wrote isn't very complicated for me, it even works now after three years. If it doesn't find the HTML elements (in GitHub the both `author` and `pagehead-actions`), it's clear that we're not in a repository page, and it doesn't show anything. We just need to change the code to display the Liberapay button as a page action, instead of modifying the GitHub page to add a button.

**Comment by jorgesumle** [comment]
Please check out the page action version and review the code: https://gitlab.com/liberapay/liberapay-everywhere/merge_requests/1

Here is a demo for non-developers:
![peek 2017-12-18 01-29](https://user-images.githubusercontent.com/14212780/34085804-a3a3435e-e395-11e7-8123-45cf1ac908af.gif)

**Comment by jorgesumle** [comment]
When the main issues ([#1](https://gitlab.com/liberapay/liberapay-everywhere/issues/1), [#2](https://gitlab.com/liberapay/liberapay-everywhere/issues/2)) are solved, we should start adding other platforms. I don't want to build upon buggy code. Anyone can help.

**Comment by jorgesumle** [comment]
I've added a bunch of platforms to the extension. It would be nice if some of you could look at the code and test the extension. After a week, I plan to publish it in the Firefox Addon Repository.

If you want the extension available from the repositories of other browsers, just tell us here.

**Comment by jorgesumle** [comment]
I've added a bunch of platforms to the extension. It would be nice if some of you could look at the code and test the extension. After a week, I plan to publish it in the Firefox Addon Repository.

If you want the extension available from the repositories of other browsers, just tell us here.

**Comment by moriczgergo** [comment]
@jorgesumle Chrome?

**Comment by jorgesumle** [comment]
Sure, we can upload it to Chrome Store too, it's said that WebExtensions can run in Chrome, Firefox and the Edge thing from Microsoft. Can anyone do this task? From my own experience, it's trivial to upload an extension from time to time (at least with Firefox).

I cannot upload it to the Chrome Store, as I don't have a Google account (and don't want to) and I haven't had good experiences with Google as a Tor user.

**Comment by moriczgergo** [comment]
@jorgesumle I can do it. I already paid the one-time extension fee.

**Comment by jorgesumle** [comment]
Great! Thanks a lot @moriczgergo 

We'll ping you when we publish the release.

**Comment by jibe-b** [comment]
Dear @jorgesumle, thanks a lot for having written this extension!

I made a few tests (not exhaustive) and it is really smooth.

The icon is pretty visible in yellow and yet only visible on a little number of website, I like that.

Two things:

- as for gitlab the "user_name lookup" is not available, the icon should remain hidden to avoid deception (temporary blacklist?).
- I suggest ticking [x] in the readme the platforms that are actually supported and leaving the others [ ]

**Comment by jorgesumle** [comment]
@jibe-b, thanks a lot for testing it. There is an [open issue](https://gitlab.com/liberapay/liberapay-everywhere/issues/5) for that (read it for more details). I hope we can fix it soon.

**Comment by jorgesumle** [comment]
I uploaded the extension to the Add-on Developer Hub from Mozilla Firefox. Hopefully, Mozilla will approve it. Here is the data I filled, feel free to ask me to modify it if anything could be improved: (Sadly, I [couldn't add our donation link](https://github.com/liberapay/salon/issues/221), ignore it in the first screenshot, it actually failed and had to remove it).

## Some metadata

![captura de pantalla de 2018-04-05 23-24-18](https://user-images.githubusercontent.com/14212780/38393218-7bd940e0-392a-11e8-82d2-42dc67875450.png)
![captura de pantalla de 2018-04-05 23-26-50](https://user-images.githubusercontent.com/14212780/38393226-81652cc2-392a-11e8-8b64-3578472ebd16.png)
![captura de pantalla de 2018-04-05 23-01-25](https://user-images.githubusercontent.com/14212780/38393249-91291e16-392a-11e8-9b16-bc7e819bd7cb.png)
![captura de pantalla de 2018-04-05 23-06-17](https://user-images.githubusercontent.com/14212780/38393276-a02a74aa-392a-11e8-9068-3d6953835c8c.png)
![captura de pantalla de 2018-04-05 23-06-33](https://user-images.githubusercontent.com/14212780/38393285-a43e5eb2-392a-11e8-86ee-33b051285041.png)

## Featured screenshots

![captura de pantalla de 2018-04-05 23-20-16](https://user-images.githubusercontent.com/14212780/38393194-69f99eec-392a-11e8-8ae3-7315420398d2.png)
![captura de pantalla de 2018-04-05 23-20-30](https://user-images.githubusercontent.com/14212780/38393206-713d33ee-392a-11e8-90c2-91ca7482a56e.png)
![captura de pantalla de 2018-04-05 23-19-02](https://user-images.githubusercontent.com/14212780/38393211-7520301a-392a-11e8-9503-fc5980c7f296.png)

## Let's upload it for other browsers too
 
Ping @moriczgergo. It's the tag 0.1. You should be able to download it easily from https://gitlab.com/liberapay/liberapay-everywhere/tags/0.1

![captura de pantalla de 2018-04-05 23-44-40](https://user-images.githubusercontent.com/14212780/38393551-73ec87a6-392b-11e8-9ae0-64c10087bf2b.png)

**Comment by jorgesumle** [comment]
[Liberapay Everywhere](https://addons.mozilla.org/en-US/firefox/addon/liberapay-everywhere/) has been approved. I'm closing this issue because we already made the extension and a release, and other people can now upload it to other browsers' repositories easily by using our [tags](https://gitlab.com/liberapay/liberapay-everywhere/tags) from the extension repository. I encourage you to continue the discussion about the extension [there](https://gitlab.com/liberapay/liberapay-everywhere/issues) (open a new issue if necessary).

**Comment by Changaco** [comment]
Good work, @jorgesumle!

**Comment by trebmuh** [comment]
super nice @jorgesumle !

**Comment by jibe-b** [comment]
Thanks alot @jorgesumle

**Comment by jorgesumle** [comment]
@moriczgergo any progress with the Google Store upload? I've opened an [issue on GitLab](https://gitlab.com/liberapay/liberapay-everywhere/issues/16), so that we can discuss it and solve issues there.
