### ISSUE TITLE
liberapay.com/security.txt team link redirects to https://liberapay.com/about/security.

### ISSUE THREAD

**Issue by EdOverflow** [liberapay/liberapay.com#887]
By clicking on the _security.txt_ team link located here: https://liberapay.com/security.txt/donate, one is redirected to https://liberapay.com/about/security and not https://liberapay.com/security.txt/.

![image](https://user-images.githubusercontent.com/18099289/34228030-8da651ea-e5cf-11e7-84b0-a454db66a54f.png)

**Comment by trebmuh** [comment]
confirmed

**Comment by mattbk** [comment]
Interesting!

https://liberapay.com/security.txt/ itself works
https://liberapay.com/security.txt <--no trailing slash redirects

So this is a little more than just the link on the donate page.

**Comment by EdOverflow** [comment]
When you remove the trailing slash it treats the `.txt` as a file extension and adds a location header to redirect to `/about/security` as seen below.

```
$ curl -I --silent https://liberapay.com/security.txt | grep "HTTP\|Location"
HTTP/1.1 302 Found
Location: /about/security
```

```
$ curl -I --silent https://liberapay.com/security.txt/ | grep "HTTP\|Location"
HTTP/1.1 200 OK
```

The root cause is located here: https://github.com/liberapay/liberapay.com/blob/8709f4543e78ef148d56bb0009aee1a735fe8fac/www/security.spt.

```
[---]
response.redirect('/about/security')
[---] text/plain
```

**Comment by Changaco** [comment]
Actually the bug is that you were able to claim the "security.txt" username while `security.spt` exists, and it's because our conflict detection mechanism isn't thorough.
