### ISSUE TITLE
Adding Money fails. Error message: 001599: Token processing error

### ISSUE THREAD

**Issue by jankeromnes** [liberapay/liberapay.com#888]
Dear Liberapay,

Thank you for what looks like an amazing service! I am trying to add some USD to my account, using a US Debit Card, in order to make USD donations. (I've already added some EUR via Wire Transfer.)

Adding USD has failed several times (a few times with "bad CSRF token" error). My latest attempt got the following error:

```
The attempt to take $ from your credit card has failed. Error message: 001599: Token processing error
```

Is there any way around this? Please help me add some USD to my account.

**Comment by Changaco** [comment]
Hi,

Can you retry the payment with a freshly input card number? It's possible that the problem you're facing is similar to #681.

**Comment by jankeromnes** [comment]
Aha, thanks @Changaco! Retrying with a the full card details worked. Closing this issue but adding a new error message to #681.
