### ISSUE TITLE
Missing description for `final-gift` transfers

### ISSUE THREAD

**Issue by jelv** [liberapay/liberapay.com#889]
**Edit**: It's an missing label for final-gift transfer. It was just an coincidence that it happened on the day of my deposit.

Ive added 50 dollar with bank wire to my account. Ive used the SHA setting (shared costs) from my bank. The payin showed up with an extra line +0,14 without an description. On the last day my 1,50 pay was increased to 1,64. I guess this was this extra 0,14.

Did I set the bank wire right or do you have to choose a different option for the costs? What is this 0,14? I don't think it should be added on the payday but as an deposit or something else.

Screenshots:
![Screenshot from payday](https://user-images.githubusercontent.com/7106279/34248917-ffd9890e-e637-11e7-9a0e-780cc6082efa.png)
![Screenshot from my bank wire settings](https://user-images.githubusercontent.com/7106279/34248918-fff1282a-e637-11e7-92f5-f3e3fa7e18d5.png)
Shared costs (SHA)
Costs for me (OUR)
Costs for other party (BEN)
![Screenshot from my deposit](https://user-images.githubusercontent.com/7106279/34248919-000d44b0-e638-11e7-9790-3fa76e6d383e.png)

**Comment by Changaco** [comment]
The €0.14 transfer is not related to the bank wire, it's a "final gift" (one-time donation from someone closing their account). Apparently we're missing a description for these transfers.

**Comment by jelv** [comment]
That explains it and should be on the payday for the team. Thanks!
