### ISSUE TITLE
Checking "Hide total receiving from others" on team results in error

### ISSUE THREAD

**Issue by mattbk** [liberapay/liberapay.com#893]
![image](https://user-images.githubusercontent.com/3729038/34309357-3b1de052-e717-11e7-9fe5-7b322868bcbd.png)

Reported at https://gitter.im/liberapay/salon?at=5a3d512203838b2f2a280e2b. I can confirm this happens with my own teams as well.

**Comment by Changaco** [comment]
Hiding the income of a team is not allowed. In fact the whole privacy section is inadequate for teams, it used to be in the Settings page and hidden for team accounts.
