### ISSUE TITLE
Improve statistic graphs labels

### ISSUE THREAD

**Issue by julia-r** [liberapay/liberapay.com#906]
There are numbers below the graphs, in this screenshot 85 and 99, but I don't know what they mean. It says "Weeks", so I guess it is the number of the weekly payout since the service started? Maybe the actual dates would be more helpful here?

![liberapay-graphs](https://user-images.githubusercontent.com/5902553/34486018-f21462a4-efcd-11e7-99f7-6eecf58a3fa9.PNG)

**Comment by julia-r** [comment]
This seems to be fixed now. Nice!

**Comment by Changaco** [comment]
(This was fixed by #1316.)

**Comment by trebmuh** [comment]
Nice. :+1:
