### ISSUE TITLE
Setting up payment method not working

### ISSUE THREAD

**Issue by yaxu** [liberapay/liberapay.com#912]
I'm making a liberapay profile:
  https://liberapay.com/yaxu/

Someone tried setting up a donation but got this error message:
`deposit — error message: 400 {"Message":"One or several required parameters are missing or incorrect. An incorrect resource ID also raises this kind of error.","Type":"param_error","Id":"4e4ef7ed-e306-4631-a611-52a3994d9e48#1514997880","Date":1514997881.0,"errors":{"MandateId":"This mandate only supports GBP payments"}}`

I have my a/c set up to accept donations from all currencies, and they were paying from a GBP a/c.

**Comment by Changaco** [comment]
We don't support GBP yet (#833), and unfortunately euro direct debits only work inside the eurozone (your donor should have seen a message telling them that) (#853).

**Comment by yaxu** [comment]
Thanks for the explanation. I don't think they had that message, actually one received an email implying that the payment was successfully set up

**Comment by Changaco** [comment]
Emails about direct debits are sent by our payment processors, we have no control over them. In fact we can't even see them.

**Comment by Changaco** [comment]
#913 is my attempt to improve our user interface and error messages to avoid confusing UK donors in the future.
