### ISSUE TITLE
ponctual donation / one-off donation

### ISSUE THREAD

**Issue by trebmuh** [liberapay/liberapay.com#915]
An idea just pop up in my brain hence sharing it here.

Re: allowing one-off donation, we could maybe allow one giver to choose something like "I want to give 1€ for 20 weeks to project/member X", then:

- from the user point of view: he gives 20€ (and doesn't have to cancel his donation after 20 weeks)
- from the member point of view: he receives 20 times 1€ (which helps to smooth donations across time)
- from the LP great and wonderful idea of helping donations to be recurrent: we're still in line with helping to sustain and smoothing donations across time

Thought?

**Comment by Changaco** [comment]
Please post in #415 instead of as a new issue.

**Comment by trebmuh** [comment]
Ah s**t! I've search with the one-off and punctual keyword! Thanks for the pointer.
