### ISSUE TITLE
Idea: A fixed amount and automatic splitting

### ISSUE THREAD

**Issue by Phyks** [liberapay/liberapay.com#923]
Hi,

I recently came across Liberapay and the service looks really great! I had a particular use case in mind, which does not seem to be feasible at the moment, not sure whether this could be something interesting for others as well?

For about a year now, my donation scheme has been to give a fixed amount (something like 10€ / month) each month, to a different team/project/organization providing a service or an app I use. But these are single shots and not really long-term support and then, I came across liberapay which is more long-term oriented. So I thought I could somehow "star" projects I am using / would like to support, and fix a given amount I want to donate per month and let Liberapay handle the splitting.

So, I was thinking there could be an option "I want to support this project" (without amount) for every team/project, and somewhere in the settings we could set a given amount per month, and Liberapay would split automatically to the projects (so that if I want to give 10 € / month and I star 10 projects, each will receive 1€ / month).

Not sure whether this might be an interesting option?

Thanks for all the work in Liberapay!

**Comment by Changaco** [comment]
Hi,

Your idea is very close to #54, except that you're proposing only equal splits whereas #54 includes the possibility of having multiple donation levels.

**Comment by Phyks** [comment]
Indeed, sorry for the duplicate, it did not showed up in my search :/

Let's continue the discussion over there :)
