### ISSUE TITLE
New languages fy and et don't work

### ISSUE THREAD

**Issue by jelv** [liberapay/liberapay.com#927]
The new languages [fy](https://fy.liberapay.com/) and [et](https://et.liberapay.com/) don't seem to work. It doesn't load any page on those subdomains.

**Comment by Changaco** [comment]
These subdomains haven't been added in Cloudflare yet.

**Comment by jelv** [comment]
Alright. The pages are currently linked in the languages list so the links are visible for the visitors.
![Uploading Screenshot_3.png…]()

**Comment by trebmuh** [comment]
@jelv your screenshot link is corrupted.

**Comment by jelv** [comment]
@trebmuh fixed the screenshot
