### ISSUE TITLE
CSP blocks inline styles of notifications

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#936]
In #924 I replaced all inline styles except those of notifications. The problem is that we don't only send those inline styles in HTML emails, they also end up in the user's notifications page.

**Comment by Changaco** [comment]
The quick fix is to allow inline styles for the notifications page.

The proper fix would be to stop using inline styles in notification templates, and use a library to compile to inline styling when sending emails.

**Comment by EdOverflow** [comment]
The CSP also blocks the "Donation button" widget's fill from loading (https://liberapay.com/%username/widgets/). 

```
Content Security Policy: 
The page’s settings blocked the loading of a resource at self (“default-src”).
```

```html
<a class="liberapay-btn" href="https://liberapay.com/EdOverflow/donate">
    <svg viewBox="0 0 80 80" height="16" width="16">
   <g transform="translate(-78.37-208.06)" fill="#1a171b">
   ...
   <span>Donate</span>
</a>
```

![image](https://user-images.githubusercontent.com/18099289/35289487-c75c1a66-0067-11e8-96fd-3283d560c882.png)
