### ISSUE TITLE
Prevent users from creating usernames with extensions in them.

### ISSUE THREAD

**Issue by EdOverflow** [liberapay/liberapay.com#938]
I have claimed ownership of liberapay.com on https://keybase.io/edoverflow by creating a user with `keybase.txt` as the username and playing the verification snippet in the user's statement as you can see below (https://liberapay.com/keybase.txt):

![image](https://user-images.githubusercontent.com/18099289/35120564-d26274aa-fc98-11e7-884f-b972fdc44efe.png)

![image](https://user-images.githubusercontent.com/18099289/35120581-e233b146-fc98-11e7-826d-40d54a46601c.png)

In order to fix this issue we should disallow usernames containing file extensions in them.

**Comment by EdOverflow** [comment]
I also managed to claim ownership of liberapay.org:

![image](https://user-images.githubusercontent.com/18099289/35158882-c1adf30a-fd38-11e7-93b8-57a814762e69.png)

**Comment by Changaco** [comment]
I suggest rejecting names ending with any of: `.txt`, `.html`, `.htm`, `.json`, `.xml`.

**Comment by Changaco** [comment]
#948 has been deployed, and the existing accounts with infringing names have been closed:

```python
>>> l = website.db.all("SELECT p FROM participants WHERE username ~ '\.(txt|html?|json|xml)' and username <> 'security.txt'")
>>> [(p.id, p.username) for p in l]
[(29897L, u'crossdomain.xml'), (29899L, u'sign-in.html'), (29902L, u'migrate.html'), (30293L, u't.html'), (29741L, u'keybase.txt'), (29862L, u'Changaco.txt')]
>>> [p.close(None) for p in l]                                                                                                 
[None, None, None, None, None, None]
>>> [website.db.one("UPDATE participants SET username = '~' || id::text WHERE id = %s RETURNING id", (p.id,)) for p in l]
[29897L, 29899L, 29902L, 30293L, 29741L, 29862L]
>>> l = website.db.all("SELECT p FROM participants p WHERE username ~ '\.(txt|html?|json|xml)' and username <> 'security.txt'")
>>> len(l)                                                                                                                     
0
```
