### ISSUE TITLE
were given -> was given

### ISSUE THREAD

**Issue by iangilfillan** [liberapay/liberapay.com#950]
In the notifications, the message reads:
"€x.xx were given to you personally."
In English, it should read:
"€x.xx was given to you personally."

**Comment by Changaco** [comment]
Source? I tried to search for a grammar rule about this but I couldn't find one.

**Comment by iangilfillan** [comment]
See https://english.stackexchange.com/questions/71266/are-monetary-values-plural which says 
"Plural if you're thinking of the $x as x individual dollars, singular if you're thinking of the sum of money as a whole." The latter applies here, so as a singular, the correct term in the passive is "was", for example "One dog was given..." vs "Two dogs were given".

**Comment by bearbin** [comment]
I don't have a strong opinion here either way, but is the money being given here not a collection of individual donations? So 'were' would be more appropriate in that sense.

**Comment by iangilfillan** [comment]
In this instance, it's a single total being given to you. The breakdown into individual donations is not listed in that line.
