### ISSUE TITLE
Resizing images

### ISSUE THREAD

**Issue by Jehan** [liberapay/liberapay.com#966]
It would be nice if images could be resized (even though if just in styling, not asking you to actually resize the images, hence hosting them). :-)

**Comment by Changaco** [comment]
Do you mean automatic resizing to fit the parent box, or specific pixel sizes?

**Comment by Jehan** [comment]
Yeah I just mean fitting the parent box. Or more accurately so that in the end, the whole page fits the screen so that people don't have to scroll *horizontally* depending on the image and their display resolution.

P.S.: of course, when I said not "actual resizing" of the image (which means caching the scaled version), ideally that would be even better. Even I sometimes go to the quickest/laziest and would appreciate to be able to upload a big image without having to worry about the file size. But that's another matter and even with actual image scaling, we would still need screen fitting.

**Comment by Changaco** [comment]
I thought we had an appropriate `max-width: 100%` for images inside profile statements, but we don't. I must have messed it up somehow.
