### ISSUE TITLE
Language localized in their own languages

### ISSUE THREAD

**Issue by Jehan** [liberapay/liberapay.com#967]
Currently languages are written in the current localization. For instance, if the page is in English, you would get "French" in the list. But that is a little annoying when you don't speak a language, because then how to find your preferred language in the list?

In a language list, a language must always be self-translated, therefore you will want to see "français" in this list, whatever the lang actually displayed in the rest of the page.

**Comment by jorgesumle** [comment]
> Currently languages are written in the current localization

No they aren't, at least not in the navigation bar. If you mean the language selector from the profile, I don't see nothing wrong with that. Why would you want to (select and) write a statement in a language you don't understand? If you can please specify a bit more what do you refer to, it would be better.

**Comment by Jehan** [comment]
> No they aren't, at least not in the navigation bar.

I'm not sure what you are refering at, I don't see any language list in the navigation bar here (I tried every item in the nav bar just now to be sure). :-)

Personally I simply meant the list of language for a project description. Here is the screenshot for our project for instance (which has English, French and Korean; I would expect to see the list: English, français, 한국어):
![screenshot from 2018-02-01 01-21-06](https://user-images.githubusercontent.com/794997/35654824-3095c47c-06ef-11e8-9d18-db0eb3446d15.png)

> Why would you want to (select and) write a statement in a language you don't understand?

I'm not sure what you mean about writing in a language that you don't understand (this seems to be like impossible by definition). But I can answer about how would you arrive on the localization you don't understand, there are many possibilities for this: maybe you just followed a link which was directing to a specific lang (ko.liberapay.com/…); maybe you followed the generic link, but being in a foreign country, the language detection gave you the localization for this country; maybe the computer you are in right now is set for this language (company computer, friend's, whatever…) even though not your favorite lang; maybe you speak/read this other language and have your computer set on purpose for it, yet you still prefer to read in some other language sometimes…

Also why would you want to get each language self-translated? Simply to be able to find yours easily. If I look for the French language, I will find it a lot easier if I see "français" in the list, rather than "프랑스어".
And this, even more if I happen to not speak Korean and came into the Korean version by mistake. 
Then it's quite hard to know which is which language (and even simply to be sure this is the language list at all, except by trial and error). :-P

As an example, here is the language list selection for GIMP (it's a known example, I am the one who made the languages self-translated there ;p):
![screenshot from 2018-01-31 22-57-01](https://user-images.githubusercontent.com/794997/35655152-a8f6b9f2-06f0-11e8-8e43-9ceec43feae7.png)

**Comment by Jehan** [comment]
I see you rolled out the patch to the live website. It works well, thanks!

Also the icon was a good idea to spot the language list in case you don't speak the currently displayed language. 🙂
