### ISSUE TITLE
Currency exchange rate between EUR and USD are mixed up

### ISSUE THREAD

**Issue by jpdeplaix** [liberapay/liberapay.com#978]
If I give euros to an account using dollar as main currency, the currency rate gets mixed up somewhere.
For instance if I give 5€, on the creator's page it only displays 4.05$ instead of 6.18$.

Current exchange rate:
* 5 EUR to USD: 6.18$
* 5 USD to EUR: 4.05€

**Comment by Changaco** [comment]
I already knew about this bug, but thanks for creating an issue. Fixing this is next on my list.
