### ISSUE TITLE
Human readable N=X

### ISSUE THREAD

**Issue by jelv** [liberapay/liberapay.com#985]
On the giving page the Donations, Pledges and Recently Cancelled topic have N=X in there title. For non-programmers and non-technical people this may look a bit weird. My suggestion is to change it to just X. So:

Donations (N=8) -> Donations (8)
Pledges (N=8) -> Pledges (8)
Recently Cancelled (N=8) -> Recently Cancelled (8)

**Comment by Kaligule** [comment]
This seems to be the line in question: https://github.com/liberapay/liberapay.com/blob/97444c2ca1b0297a31dfe4e72b77485bcae40430/www/%25username/giving/index.html.spt#L107
