### ISSUE TITLE
Password check

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#986]
When a user inputs a password we should check if it's in the "pwned passwords" database: [I've Just Launched "Pwned Passwords" V2 With Half a Billion Passwords for Download](https://www.troyhunt.com/ive-just-launched-pwned-passwords-version-2/).

**Comment by umang-malik** [comment]
I would like to try this. What shall I do after checking if it exists in the database? Maybe set a threshold value for the rarity of the password?

**Comment by Changaco** [comment]
Hey @umang-malik, welcome.

Given that Liberapay is a service that handles money we should show a warning no matter what the password count is. However the wording of the warning could vary based on the password count, and maybe the password's "strength" too.

We need to take into account that there can be false positives (hash collisions). For example, if looking up the hash of a complex password returns a high leak count, then it may be a hash collision with a weak password.

**Comment by umang-malik** [comment]
@Changaco, please review #988. I believe that taking hash collisions into considerations while setting a new password is unneecessary. The thresholds have been decided by checking various passwords.
