### ISSUE TITLE
Address Verification System

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#994]
[AVS | MANGOPAY API Docs](https://docs.mangopay.com/guide/avs)

> Address Verification System is an anti-fraud tool used in the UK, US and Australia for online payment by Visa, Mastercard and Amex.
>
> The system compares the billing address entered by the user for the purchase and the address of the credit card registered at his bank. Depending on multiple checks between these two addresses, a "score" is provided by the acquiring bank. We are now providing you this AVS result as an indicator. In other words, we won’t act over a bad scoring. You are therefore responsible for implementing rules on the scoring.

**Comment by braderhart** [comment]
I was put on hold by JP Morgan Chase for over 30 minutes and lied to numerous times, until they finally fixed it again. Whoever you payment vendor is raises serious flags in American banking systems.

**Comment by braderhart** [comment]
Which is strange because some of the countries that MANGOPAY blocks are semi-progressive and appear to be blocked for simply not agreeing with the American capitalistic business model.

**Comment by Changaco** [comment]
Closing as obsolete since Mangopay kicked us out.
